import type { ProviderAdmissionPolicy } from '../definitions/providerAdmissionPolicy';

const API_KEY_FIELD = {
  id: 'api_key',
  kind: 'secret',
  required: true,
  label: 'API Key',
} as const;

const CHATGPT_AUTHORIZATION_FIELD = {
  id: 'authorization',
  kind: 'oauth',
  required: true,
  label: '使用 ChatGPT 登录',
} as const;

const KIMI_CODE_MODELS = [
  {
    id: 'k3',
    display_name: 'Kimi K3',
    release_status: 'active',
    context_window_tokens: 1_048_576,
    max_input_tokens: 1_048_576,
    max_output_tokens: 131_072,
    capabilities: { image_input: true, tool_call: true, reasoning: true },
    family: 'kimi-k3',
  },
  {
    id: 'k3-256k',
    display_name: 'Kimi K3 256K',
    release_status: 'active',
    context_window_tokens: 262_144,
    max_input_tokens: 262_144,
    max_output_tokens: 131_072,
    capabilities: { image_input: true, tool_call: true, reasoning: true },
    family: 'kimi-k3',
  },
  {
    id: 'kimi-for-coding',
    display_name: 'Kimi K2.7 Code',
    release_status: 'active',
    context_window_tokens: 262_144,
    max_input_tokens: 262_144,
    max_output_tokens: 262_144,
    capabilities: { image_input: true, tool_call: true, reasoning: true },
    family: 'kimi-k2',
  },
  {
    id: 'kimi-for-coding-highspeed',
    display_name: 'Kimi K2.7 Code HighSpeed',
    release_status: 'active',
    context_window_tokens: 262_144,
    max_input_tokens: 262_144,
    max_output_tokens: 262_144,
    capabilities: { image_input: true, tool_call: true, reasoning: true },
    family: 'kimi-k2',
  },
] as const;

const GLM_CODING_PLAN_MODELS = [
  {
    id: 'glm-5.3',
    display_name: 'GLM-5.3',
    release_status: 'active',
    context_window_tokens: 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 131_072,
    capabilities: { image_input: false, tool_call: true, reasoning: true },
    family: 'glm',
  },
  {
    id: 'glm-5.3-flash',
    display_name: 'GLM-5.3-Flash',
    release_status: 'active',
    context_window_tokens: 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 131_072,
    capabilities: { image_input: true, tool_call: true, reasoning: true },
    family: 'glm',
  },
] as const;

/**
 * models.dev 负责模型事实，Linnya policy 负责产品身份和已验收的 runtime route。
 * 不能依据上游 npm 字段把正式厂商降级到通用 compatible package。
 */
export const PROVIDER_ADMISSION_POLICIES: readonly ProviderAdmissionPolicy[] = [
  {
    source_provider_id: 'openai',
    provider_definition_id: 'openai',
    provider_connection_definition_id: 'openai-api',
    display_name: 'OpenAI',
    connection_display_name: 'OpenAI API',
    connection_description: '按量计费，使用 OpenAI Platform API Key',
    connection_badge: 'API',
    setup_help_url: 'https://platform.openai.com/api-keys',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'openai',
      default_base_url: 'https://api.openai.com/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openai_responses',
      supported_route_profile_ids: ['openai_responses', 'openai_chat'],
    },
  },
  {
    provider_definition_id: 'openai',
    provider_connection_definition_id: 'openai-chatgpt-subscription',
    display_name: 'OpenAI',
    connection_display_name: 'ChatGPT 订阅',
    connection_description: '使用 ChatGPT 订阅额度，通过浏览器登录',
    connection_badge: '订阅',
    setup_help_url: 'https://learn.chatgpt.com/docs/auth',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [CHATGPT_AUTHORIZATION_FIELD],
    model_discovery: 'account_catalog',
    runtime_binding: {
      endpoint_id: 'chatgpt',
      default_base_url: 'https://chatgpt.com/backend-api/codex',
      auth_profile: 'bearer',
      default_route_profile_id: 'chatgpt_codex_responses',
      supported_route_profile_ids: ['chatgpt_codex_responses'],
    },
    source_catalog_observation: {
      package_name: '@ai-sdk/openai@4.0.50',
      api_url: 'https://chatgpt.com/backend-api',
    },
  },
  {
    source_provider_id: 'opencode-go',
    provider_definition_id: 'opencode-go',
    display_name: 'OpenCode Go',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'opencode-go',
      default_base_url: 'https://opencode.ai/zen/go/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openai_compatible_chat',
      supported_route_profile_ids: [
        'openai_compatible_chat',
        'openai_responses',
        'anthropic_messages',
      ],
      model_route_bindings: [
        {
          model_id: 'grok-4.6',
          base_url: 'https://opencode.ai/zen/go/v1',
          route_profile_id: 'openai_responses',
        },
        {
          model_id: 'gpt-5.6-luna',
          base_url: 'https://opencode.ai/zen/go/v1',
          route_profile_id: 'openai_responses',
        },
        {
          model_id: 'muse-spark-1.2-contributor',
          base_url: 'https://opencode.ai/zen/go/v1',
          route_profile_id: 'openai_responses',
        },
        ...[
          'minimax-m3',
          'minimax-m2.7',
          'qwen3.8-max',
          'qwen3.7-max',
          'qwen3.7-plus',
          'qwen3.6-plus',
        ].map(modelId => ({
          model_id: modelId,
          // @ai-sdk/anthropic 将 /messages 追加到 baseURL；Go 的 baseURL 必须保留 /v1。
          base_url: 'https://opencode.ai/zen/go/v1',
          route_profile_id: 'anthropic_messages' as const,
        })),
      ],
    },
  },
  {
    source_provider_id: 'anthropic',
    provider_definition_id: 'anthropic',
    display_name: 'Anthropic',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'anthropic',
      default_base_url: 'https://api.anthropic.com/v1',
      auth_profile: 'api_key',
      default_route_profile_id: 'anthropic_messages',
      supported_route_profile_ids: ['anthropic_messages'],
    },
  },
  {
    source_provider_id: 'google',
    provider_definition_id: 'google',
    display_name: 'Google Gemini',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'google',
      default_base_url: 'https://generativelanguage.googleapis.com/v1beta',
      auth_profile: 'api_key',
      default_route_profile_id: 'google_generative_ai',
      supported_route_profile_ids: ['google_generative_ai'],
    },
  },
  {
    source_provider_id: 'deepseek',
    provider_definition_id: 'deepseek',
    display_name: 'DeepSeek',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'deepseek',
      default_base_url: 'https://api.deepseek.com',
      auth_profile: 'bearer',
      default_route_profile_id: 'deepseek_chat',
      supported_route_profile_ids: ['deepseek_chat'],
    },
  },
  {
    source_provider_id: 'moonshotai',
    provider_definition_id: 'moonshot',
    provider_connection_definition_id: 'moonshot-api-global',
    display_name: 'Kimi（月之暗面）',
    connection_display_name: 'Moonshot API（国际站）',
    connection_description: '国际站开放平台按量 API，使用普通 API Key',
    connection_badge: 'API',
    setup_help_url: 'https://platform.moonshot.ai/console/api-keys',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'moonshotai',
      default_base_url: 'https://api.moonshot.ai/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'moonshot_chat',
      supported_route_profile_ids: ['moonshot_chat'],
    },
  },
  {
    source_provider_id: 'moonshotai',
    provider_definition_id: 'moonshot',
    provider_connection_definition_id: 'moonshot-api-cn',
    display_name: 'Kimi（月之暗面）',
    connection_display_name: 'Kimi 开放平台 API（中国站）',
    connection_description: '中国站开放平台按量 API，使用普通 API Key',
    connection_badge: 'API',
    setup_help_url: 'https://platform.moonshot.cn/console/api-keys',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'moonshotai-cn',
      default_base_url: 'https://api.moonshot.cn/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'moonshot_chat',
      supported_route_profile_ids: ['moonshot_chat'],
    },
  },
  {
    provider_definition_id: 'moonshot',
    provider_connection_definition_id: 'kimi-code',
    display_name: 'Kimi（月之暗面）',
    connection_display_name: 'Kimi Code',
    connection_description: '使用 Kimi 会员额度与会员专属 API Key',
    connection_badge: '会员',
    setup_help_url: 'https://www.kimi.com/code/docs/',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    bundled_models: KIMI_CODE_MODELS,
    runtime_binding: {
      endpoint_id: 'kimi-code',
      default_base_url: 'https://api.kimi.com/coding/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'moonshot_chat',
      supported_route_profile_ids: ['moonshot_chat'],
    },
    source_catalog_observation: {
      package_name: '@ai-sdk/moonshotai@3.0.41',
      api_url: 'https://api.kimi.com/coding/v1',
    },
  },
  {
    source_provider_id: 'alibaba',
    provider_definition_id: 'alibaba',
    display_name: 'Alibaba / Qwen',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'alibaba',
      default_base_url: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'alibaba_chat',
      supported_route_profile_ids: ['alibaba_chat'],
    },
  },
  {
    source_provider_id: 'minimax',
    provider_definition_id: 'minimax',
    display_name: 'MiniMax',
    kind: 'direct',
    release_status: 'stable',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    runtime_binding: {
      endpoint_id: 'minimax',
      default_base_url: 'https://api.minimax.io/anthropic/v1',
      auth_profile: 'api_key',
      default_route_profile_id: 'minimax_chat',
      supported_route_profile_ids: ['minimax_chat'],
    },
  },
  {
    source_provider_id: 'mistral',
    provider_definition_id: 'mistral',
    display_name: 'Mistral AI',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'mistral',
      default_base_url: 'https://api.mistral.ai/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'mistral_chat',
      supported_route_profile_ids: ['mistral_chat'],
    },
  },
  {
    source_provider_id: 'xai',
    provider_definition_id: 'xai',
    display_name: 'xAI',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'xai',
      default_base_url: 'https://api.x.ai/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'xai_responses',
      supported_route_profile_ids: ['xai_responses'],
    },
  },
  {
    source_provider_id: 'groq',
    provider_definition_id: 'groq',
    display_name: 'Groq',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'groq',
      default_base_url: 'https://api.groq.com/openai/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'groq_chat',
      supported_route_profile_ids: ['groq_chat'],
    },
  },
  {
    source_provider_id: 'cerebras',
    provider_definition_id: 'cerebras',
    display_name: 'Cerebras',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'cerebras',
      default_base_url: 'https://api.cerebras.ai/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'cerebras_chat',
      supported_route_profile_ids: ['cerebras_chat'],
    },
  },
  {
    source_provider_id: 'openrouter',
    provider_definition_id: 'openrouter',
    display_name: 'OpenRouter',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'openrouter',
      default_base_url: 'https://openrouter.ai/api/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openrouter_chat',
      supported_route_profile_ids: ['openrouter_chat'],
    },
  },
  {
    source_provider_id: 'fireworks-ai',
    provider_definition_id: 'fireworks',
    display_name: 'Fireworks AI',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'fireworks',
      default_base_url: 'https://api.fireworks.ai/inference/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'fireworks_chat',
      supported_route_profile_ids: ['fireworks_chat'],
    },
  },
  {
    source_provider_id: 'togetherai',
    provider_definition_id: 'togetherai',
    display_name: 'Together AI',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'togetherai',
      default_base_url: 'https://api.together.xyz/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'togetherai_chat',
      supported_route_profile_ids: ['togetherai_chat'],
    },
  },
  {
    source_provider_id: 'deepinfra',
    provider_definition_id: 'deepinfra',
    display_name: 'DeepInfra',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'deepinfra',
      // 官方 package 会在该根地址后追加 /openai/chat/completions。
      default_base_url: 'https://api.deepinfra.com/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'deepinfra_chat',
      supported_route_profile_ids: ['deepinfra_chat'],
    },
  },
  {
    source_provider_id: 'cohere',
    provider_definition_id: 'cohere',
    display_name: 'Cohere',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'cohere',
      default_base_url: 'https://api.cohere.com/v2',
      auth_profile: 'bearer',
      default_route_profile_id: 'cohere_chat',
      supported_route_profile_ids: ['cohere_chat'],
    },
  },
  {
    source_provider_id: 'siliconflow',
    provider_definition_id: 'siliconflow',
    display_name: 'SiliconFlow',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'siliconflow',
      default_base_url: 'https://api.siliconflow.com/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openai_compatible_chat',
      supported_route_profile_ids: ['openai_compatible_chat'],
    },
  },
  {
    source_provider_id: 'siliconflow-cn',
    provider_definition_id: 'siliconflow-cn',
    display_name: 'SiliconFlow (China)',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'siliconflow-cn',
      default_base_url: 'https://api.siliconflow.cn/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openai_compatible_chat',
      supported_route_profile_ids: ['openai_compatible_chat'],
    },
  },
  {
    source_provider_id: 'zai',
    provider_definition_id: 'zai',
    provider_connection_definition_id: 'zai-api-global',
    display_name: '智谱 AI（GLM）',
    connection_display_name: 'Z.AI API（国际站）',
    connection_description: '国际站开放平台按量 API，使用普通 API Key',
    connection_badge: 'API',
    setup_help_url: 'https://z.ai/manage-apikey/apikey-list',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'zai',
      default_base_url: 'https://api.z.ai/api/paas/v4',
      auth_profile: 'bearer',
      default_route_profile_id: 'zai_chat',
      supported_route_profile_ids: ['zai_chat'],
    },
  },
  {
    source_provider_id: 'zai',
    provider_definition_id: 'zai',
    provider_connection_definition_id: 'zhipu-api-cn',
    display_name: '智谱 AI（GLM）',
    connection_display_name: '智谱开放平台 API（中国站）',
    connection_description: '中国站开放平台按量 API，使用普通 API Key',
    connection_badge: 'API',
    setup_help_url: 'https://open.bigmodel.cn/usercenter/proj-mgmt/apikeys',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'zhipu-cn',
      default_base_url: 'https://open.bigmodel.cn/api/paas/v4',
      auth_profile: 'bearer',
      default_route_profile_id: 'zai_chat',
      supported_route_profile_ids: ['zai_chat'],
    },
  },
  {
    provider_definition_id: 'zai',
    provider_connection_definition_id: 'glm-coding-plan',
    display_name: '智谱 AI（GLM）',
    connection_display_name: 'GLM Coding Plan',
    connection_description: '使用 Coding Plan 套餐额度与套餐专属 API Key',
    connection_badge: 'Coding Plan',
    setup_help_url: 'https://docs.bigmodel.cn/cn/coding-plan/quick-start',
    kind: 'direct',
    release_status: 'hidden',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    bundled_models: GLM_CODING_PLAN_MODELS,
    runtime_binding: {
      endpoint_id: 'glm-coding-plan',
      default_base_url: 'https://open.bigmodel.cn/api/coding/paas/v4',
      auth_profile: 'bearer',
      default_route_profile_id: 'zai_chat',
      supported_route_profile_ids: ['zai_chat'],
    },
    source_catalog_observation: {
      package_name: '@ai-sdk/zai@3.0.1',
      api_url: 'https://open.bigmodel.cn/api/coding/paas/v4',
    },
  },
  {
    source_provider_id: 'nvidia',
    provider_definition_id: 'nvidia',
    display_name: 'NVIDIA NIM',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'nvidia',
      default_base_url: 'https://integrate.api.nvidia.com/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openai_compatible_chat',
      supported_route_profile_ids: ['openai_compatible_chat'],
    },
  },
  {
    source_provider_id: 'modelscope',
    provider_definition_id: 'modelscope',
    display_name: 'ModelScope',
    kind: 'direct',
    release_status: 'preview',
    setup_fields: [API_KEY_FIELD],
    model_discovery: 'bundled',
    model_admission: { requires_tool_call: true },
    runtime_binding: {
      endpoint_id: 'modelscope',
      default_base_url: 'https://api-inference.modelscope.cn/v1',
      auth_profile: 'bearer',
      default_route_profile_id: 'openai_compatible_chat',
      supported_route_profile_ids: ['openai_compatible_chat'],
    },
  },
  {
    provider_definition_id: 'linnya-cloud',
    display_name: 'Linnya Cloud',
    kind: 'cloud',
    release_status: 'stable',
    setup_fields: [],
    model_discovery: 'cloud_catalog',
  },
  {
    provider_definition_id: 'ollama',
    display_name: 'Ollama',
    kind: 'local_runtime',
    release_status: 'preview',
    setup_fields: [
      {
        id: 'service_url',
        kind: 'url',
        required: true,
        label: '服务地址',
        default_value: 'http://127.0.0.1:11434',
      },
    ],
    model_discovery: 'local_runtime',
  },
];
