export {
  SLIDES_ACTIVE_DOCUMENT_TYPE,
  SLIDES_DOCUMENT_TYPE,
  SLIDES_FILE_EXTENSION,
  SLIDES_FILE_EXTENSIONS,
  SLIDES_OWNED_TABLES,
  SLIDES_PLUGIN_ID,
  SLIDES_PLUGIN_META,
  SLIDES_PLUGIN_VERSION,
} from './pluginMeta';
export {
  SLIDES_AGENT_ID,
  SlidesPromptKeys,
} from './agentIdentity';
export type { SlidesPromptKey } from './agentIdentity';

export {
  SLIDES_IPC,
  SLIDES_IPC_CHANNELS,
  SLIDES_PUSH_CHANNELS,
  SLIDES_PUSH_EVENTS,
  SLIDES_TEMPLATE_IMPORT_MAX_BYTES,
} from './ipc';
export type {
  BrushArtworkArcMark,
  BrushArtworkBrush,
  BrushArtworkEllipseMark,
  BrushArtworkField,
  BrushArtworkFill,
  BrushArtworkFlowLineMark,
  BrushArtworkHatch,
  BrushArtworkIntent,
  BrushArtworkLayer,
  BrushArtworkLineMark,
  BrushArtworkMark,
  BrushArtworkMassFill,
  BrushArtworkPixelSize,
  BrushArtworkPoint,
  BrushArtworkPolygonMark,
  BrushArtworkPosition,
  BrushArtworkQuality,
  BrushArtworkRectMark,
  BrushArtworkRenderErrorCode,
  BrushArtworkRenderRequest,
  BrushArtworkRenderResult,
  BrushArtworkSplineMark,
  BrushArtworkSourceRef,
  BrushArtworkStroke,
  BrushArtworkWashFill,
  BrushArtworkWatercolorFill,
} from './brushArtwork';
export {
  BRUSH_ARTWORK_BRUSHES,
  BRUSH_ARTWORK_FIELDS,
  BRUSH_ARTWORK_LIMITS,
  BRUSH_ARTWORK_QUALITIES,
  createBrushArtworkRenderFailure,
  normalizeBrushArtworkIntent,
  normalizeBrushArtworkSourceRef,
  parseBrushArtworkRenderRequest,
  parseBrushArtworkRenderResult,
  resolveBrushArtworkPixelSize,
  SLIDES_BRUSH_WORKER_CANCEL_CHANNEL,
  SLIDES_BRUSH_WORKER_ID,
  SLIDES_BRUSH_WORKER_PROTOCOL_VERSION,
  SLIDES_BRUSH_WORKER_READY_CHANNEL,
  SLIDES_BRUSH_WORKER_REQUEST_CHANNEL,
  SLIDES_BRUSH_WORKER_RESPONSE_CHANNEL,
  createBrushArtworkWorkerCancelPayload,
  createBrushArtworkWorkerReadyPayload,
  createBrushArtworkWorkerRequestPayload,
  createBrushArtworkWorkerResponsePayload,
  extractBrushArtworkRequestId,
  parseBrushArtworkWorkerCancelPayload,
  parseBrushArtworkWorkerReadyPayload,
  parseBrushArtworkWorkerRequestPayload,
  parseBrushArtworkWorkerResponsePayload,
} from './brushArtwork';
export type {
  BrushArtworkWorkerBridge,
  BrushArtworkWorkerCancelPayload,
  BrushArtworkWorkerReadyPayload,
  BrushArtworkWorkerRequestPayload,
  BrushArtworkWorkerResponsePayload,
} from './brushArtwork';
export type {
  OperationResult,
  SlidesIpcChannel,
  SlidesPushChannel,
} from './ipc';
export type {
  SlidesDocumentBuildState,
  SlidesDraftStatus,
  SlidesSourceOrigin,
  SlideSourceSpan,
  SlidesSourceSliceOutput,
  SlidesSourceSlicesInput,
  SlidesSourceSlicesOutput,
  SlidesSourceSliceTargetInput,
} from './documentSource';
export { buildSlideSourceSpanLocusKey } from './documentSource';
export type {
  GeneratedLayoutBox,
  GeneratedLayoutComputedRatios,
  GeneratedLayoutConstraintEvidence,
  GeneratedLayoutConstraintNode,
  GeneratedLayoutDeclaredConstraints,
  GeneratedLayoutSourceSpan,
  GeneratedParentLayoutConstraintFacts,
} from './generatedLayoutConstraints';
export { isGeneratedLayoutConstraintEvidence } from './generatedLayoutConstraints';
export {
  isMathFormulaSource,
  isMathFormulaErrorCode,
  MathFormulaError,
  MATH_FORMULA_ERROR_CODES,
  MATH_FORMULA_PROFILE_VERSION,
  normalizeMathFormulaSource,
} from './mathFormula';
export type {
  MathFormulaAlign,
  MathFormulaAuthoringInput,
  MathFormulaErrorCode,
  MathFormulaMetrics,
  MathFormulaRenderProjection,
  MathFormulaSource,
  MathFormulaSourceResult,
} from './mathFormula';
export type {
  TextFontFaceFingerprint,
  TextFontResolutionKind,
  TextFontScript,
} from './textFontIdentity';
export {
  DEFAULT_SVG_GRAPHIC_ADMISSION_POLICY,
  SVG_GRAPHIC_ADMISSION_FAILURE_CODES,
  SvgGraphicAdmissionError,
} from './svgGraphic';
export type {
  SvgGraphicAccessibility,
  SvgGraphicAdmissionFailureCode,
  SvgGraphicAdmissionPolicy,
  SvgGraphicAdmissionReport,
  SvgGraphicAuthoringSource,
  SvgGraphicElementSpec,
  SvgGraphicFeatureFacts,
  SvgGraphicFit,
  SvgGraphicMetrics,
  SvgGraphicOwnedAssetRef,
  SvgGraphicResolvedAsset,
  SvgGraphicViewBox,
} from './svgGraphic';
export {
  SlideMarkerIndex,
  SlideMarkerIndexError,
} from './documentSource';
export type {
  SlideMarkerIndexErrorCode,
  SlideSourceRange,
} from './documentSource';
export type {
  SlideBox,
} from './deckSpec';
export {
  DEFAULT_SHAPE_GEOMETRY,
  MAX_SHAPE_PATH_COMMANDS,
  MAX_SHAPE_POLYGON_POINTS,
  PRESET_SHAPE_NAMES,
  ShapeGeometryError,
  isPresetShapeName,
  parseShapeGeometrySpec,
  resolvePresetShapePath,
  resolveShapeGeometry,
  serializeShapePath,
  shapePathToPointArray,
} from './shapeGeometry';
export type {
  ParallelogramGeometrySpec,
  PathGeometrySpec,
  PolygonGeometrySpec,
  PresetShapeGeometrySpec,
  PresetShapeName,
  RegularPolygonGeometrySpec,
  ResolvedPathShapeGeometry,
  ResolvedPresetShapeGeometry,
  ResolvedShapeGeometry,
  ShapeGeometrySpec,
  ShapePathCommand,
  ShapePoint,
  ShapeViewBox,
  TrapezoidGeometrySpec,
} from './shapeGeometry';
export type {
  CanonicalDeck,
  CanonicalElement,
  CanonicalPatchMeta,
  CanonicalRole,
  CanonicalSlide,
  CanonicalTextParagraph,
  CanonicalTextRun,
  CanonicalVisualHints,
} from './canonicalDeck';
export type {
  DeckPreview,
  PreviewElement,
  PreviewSlide,
  PreviewWarning,
  PreviewWarningCode,
} from './deckPreview';
export {
  DEFAULT_PRESENTATION_EXPORT_CHART_MODE,
  DEFAULT_PRESENTATION_EXPORT_IMAGE_WIDTH,
  PRESENTATION_EXPORT_FORMATS,
  PRESENTATION_EXPORT_ARTIFACTS,
  PRESENTATION_EXPORT_IMAGE_WIDTHS,
  buildPresentationExportFileName,
  parsePresentationImageExportProgress,
  parsePresentationExportRequest,
} from './presentationExport';
export type {
  PresentationExportChartMode,
  PresentationExportFormat,
  PresentationExportImageWidth,
  PresentationImageExportProgress,
  PresentationExportRequest,
  PresentationExportResult,
} from './presentationExport';
export {
  PptInspectToolArgsSchema,
  PptInspectToolDataSchema,
  PptInspectToolMessageResultSchema,
  PptInspectToolResultSchema,
} from './pptInspectToolContract';
export type {
  PptInspectToolArgs,
  PptInspectToolData,
  PptInspectToolMessageResult,
  PptInspectToolResult,
} from './pptInspectToolContract';
export {
  isContainerNode,
  isFlexComposeInput,
  isLeafNode,
} from './flexComposeContract';
export type {
  AbsolutePositionBox,
  ContainerDecoration,
  EdgeInsets,
  FlexComposeInput,
  FlexProps,
  LayoutBorderInput,
  LayoutChartConfig,
  LayoutChartDataLike,
  LayoutChartLegendPosition,
  LayoutChartNode,
  LayoutChartPresetName,
  LayoutChartSeriesInput,
  LayoutChartType,
  LayoutContainerNode,
  LayoutDisplayValue,
  LayoutGradient,
  LayoutGradientStop,
  LayoutHStackNode,
  LayoutImageConfig,
  LayoutBrushArtworkConfig,
  LayoutImageNode,
  LayoutImageSourceInput,
  LayoutImageSourceRef,
  LayoutImageVisualShadowInput,
  LayoutFormulaConfig,
  LayoutFormulaNode,
  LayoutLinearGradient,
  LayoutLeafNode,
  LayoutNode,
  LayoutRadialGradient,
  LayoutShapeConfig,
  LayoutShapeFillInput,
  LayoutShapeNode,
  LayoutShapeStroke,
  LayoutSvgGraphicConfig,
  LayoutSvgGraphicNode,
  LayoutSvgGraphicSourceInput,
  LayoutSlideBackground,
  LayoutSlideConfig,
  LayoutSlideNode,
  LayoutSourceMetadata,
  LayoutSpacerConfig,
  LayoutSpacerNode,
  LayoutTableCellInput,
  LayoutTableCellValue,
  LayoutTableConfig,
  LayoutTableDataLike,
  LayoutTableNode,
  LayoutTextAlign,
  LayoutTextConfig,
  LayoutTextLineSpacingInput,
  LayoutTextNode,
  LayoutTextRun,
  LayoutPlainTextRun,
  LayoutFormulaTextRun,
  LayoutTextStyleInput,
  LayoutThemeInput,
  LayoutVerticalAlign,
  LayoutViewConfig,
  LayoutViewNode,
  LayoutVStackNode,
} from './flexComposeContract';
export type {
  PresentationSourceKind,
} from './documentSource';
export type {
  PresentationInspectionFeedbackOptions,
  PresentationInspectionRequest,
  PresentationInspectionSelection,
  PresentationInspectionSnapshot,
} from './presentationInspection';
export type {
  MasterInfo,
  PresentationInfo,
  SlideElementChartInfo,
  SlideElementInfo,
  SlideElementImportFidelity,
  SlideElementParagraphInfo,
  SlideElementShapeVisual,
  SlideElementSvgGraphicInfo,
  SlideElementTableCellTextInfo,
  SlideElementTableInfo,
  SlideElementTextBodyInfo,
  SlideElementTextRunInfo,
  SlideElementTextStyleInfo,
  SlideInfo,
  ThemeInfo,
} from './presentationInfo';
export {
  findSlideElement,
  flattenSlideElements,
  visitSlideElements,
} from './presentationInfo';
export {
  isDataUri,
  isExternalUrl,
  normalizeAssetRef,
} from './deckSpec';
export type {
  AssetRef,
} from './deckSpec';
export {
  DEFAULT_THEME_CHART_PALETTE,
  deriveChartPaletteFromThemeColors,
  resolveThemeChartPalette,
} from './visual';
export type {
  ThemeChartPalette,
  ThemeChartPaletteLike,
  ThemeChartSpec,
} from './visual';
export type {
  ThemeSpec,
} from './visual';
export type {
  TemplateSpec,
  TemplateSummary,
} from './templateSpec';
export type {
  CustomSlideLayout,
  RenderSlideSizeInches,
  SlideLayout,
  SlideLayoutNormalizationResult,
  SlideLayoutPreset,
  SlideSizeBoxInches,
  SlideSizeEmu,
  SlideSizeInches,
} from './deckSpec';
export {
  DEFAULT_SLIDE_LAYOUT,
  EMU_PER_INCH,
  createPptxCustomLayoutName,
  createSlideLayoutKey,
  isSlideLayout,
  normalizeSlideLayout,
  requireNormalizedSlideLayout,
  resolveSlideSizeBoxInches,
  resolveSlideSizeInches,
  SLIDE_LAYOUT_MAX_INCHES,
  SLIDE_LAYOUT_MIN_INCHES,
  SLIDE_SIZES_INCHES,
  toSlideSizeEmu,
  toRenderSlideSize,
  toSlideSizeBox,
} from './deckSpec';
export {
  CHART_DEFAULT_LABEL_FONT_SIZE_PT,
  TABLE_DEFAULT_BACKGROUND_FILL,
  TABLE_DEFAULT_CELL_PADDING,
  TABLE_DEFAULT_HEADER_FILL,
  resolveTableCellLayouts,
} from './renderModel';
export type { TableCellLayout } from './renderModel';
export {
  BULLET_HANGING_INDENT_INCHES,
  DEFAULT_TEXT_AUTOFIT_POLICY,
  DEFAULT_TEXT_LINE_BREAK_POLICY,
  DEFAULT_TEXT_LINE_SPACING,
  DEFAULT_TEXT_LINE_SPACING_MULTIPLE,
  DEFAULT_TEXT_OVERFLOW_POLICY,
  DEFAULT_TEXT_VERTICAL_ALIGN,
  DEFAULT_TEXT_WRAP_POLICY,
  NORM_AUTOFIT_FONT_SCALE_CANDIDATES,
  NORM_AUTOFIT_LINE_SPACING_REDUCTION_FACTOR,
  PPTX_DEFAULT_TEXT_INSET,
  TITLE_TEXTBOX_MIN_AUTOFIT_SCALE,
  resolveTextLayoutContract,
  resolveTextLayoutContractFromNode,
  breakParagraphIntoLines,
  layoutParagraph,
  layoutTextNode,
  measureLineMetrics,
  resolveTextLayoutFontScaleCandidates,
  segmentClusters,
  createMultipleTextLineSpacing,
  isTextLineSpacing,
  normalizeLegacyTextLineSpacing,
  parseTextLineSpacingInput,
  resizeTextBoxForAutoFit,
  summarizeSlideTextLayoutProvenance,
} from './textLayout';
export type {
  BrokenLine,
  LayoutParagraphOptions,
  LayoutParagraphResult,
  RenderLineSlice,
  InlineBoxLineSlice,
  RenderInlineLineSlice,
  RenderTextLine,
  FontLineMetrics,
  FontMetricsProvider,
  ResolveTextLayoutContractInput,
  RunAdvanceProvider,
  RunAdvanceMeasureResult,
  RunMeasureStyle,
  SlideTextLayoutProvenance,
  TextAutoFitPolicy,
  TextBoxInsets,
  TextFontResolutionContract,
  TextLayoutContract,
  TextLayoutInput,
  TextLayoutAttentionNodeProvenance,
  TextLayoutFontProvenance,
  TextLayoutProfile,
  TextLayoutResult,
  TextLineBreakPolicy,
  TextLineMetrics,
  TextLineSpacing,
  TextLineSpacingResolution,
  TextCluster,
  TextRunStyleResolver,
  TextWrapPolicy,
} from './textLayout';
export type {
  ChartRenderNode,
  ChartPptxHints,
  EditableOperation,
  EditableTarget,
  GroupRenderNode,
  ImageRenderNode,
  PresentationRenderModel,
  RelayoutCapability,
  RenderAssetRef,
  RenderBox,
  RenderBullet,
  RenderCapabilities,
  RenderChartAxes,
  RenderChartAxis,
  RenderChartDataLabels,
  RenderChartGridlines,
  RenderChartLabelStyle,
  RenderChartLegend,
  RenderChartSeries,
  RenderChartType,
  RenderFill,
  RenderGradientFill,
  RenderLineSpacing,
  RenderNode,
  RenderNodeBase,
  RenderNodeKind,
  RenderNoneFill,
  RenderPadding,
  RenderParagraph,
  RenderShadow,
  RenderSlideSize,
  RenderSolidFill,
  RenderSourceSpan,
  RenderStroke,
  RenderTableCell,
  RenderTableCellBorders,
  RenderTextRun,
  RenderFormulaRun,
  RenderInlineRun,
  ShapeRenderNode,
  SvgGraphicRenderNode,
  SlideBackgroundGradientModel,
  SlideBackgroundModel,
  SlideDiagnosticsSummary,
  SlideReferencePreview,
  SlideRenderModel,
  TablePptxHints,
  TableRenderNode,
  TextRenderNode,
} from './renderModel';
export {
  findRenderNode,
  flattenRenderNodes,
  visitRenderNodes,
} from './renderModel';
export type {
  RenderNodeVisitContext,
} from './renderModel';
export {
  SLIDE_RASTER_FORMAT,
  SLIDES_RASTER_WORKER_ID,
  SLIDES_RASTER_WORKER_PROTOCOL_VERSION,
  SLIDES_RASTER_WORKER_READY_CHANNEL,
  SLIDES_RASTER_WORKER_REQUEST_CHANNEL,
  SLIDES_RASTER_WORKER_RESPONSE_CHANNEL,
  createAspectRatioSlideRasterProfile,
  createSlideRasterFailure,
  createSlideRasterWorkerReadyPayload,
  createSlideRasterWorkerRequestPayload,
  createSlideRasterWorkerResponsePayload,
  extractSlideRasterRequestId,
  isSlideRasterPixelSizeWithinBudget,
  isSlideRasterSquareEnvelopeWithinBudget,
  parseSlideRasterRequest,
  parseSlideRasterResult,
  parseSlideRasterWorkerReadyPayload,
  parseSlideRasterWorkerRequestPayload,
  parseSlideRasterWorkerResponsePayload,
  resolveSlideRasterPixelSize,
  SLIDES_RASTER_MAX_OUTPUT_PIXELS,
} from './slideRasterization';
export type {
  CreateAspectRatioSlideRasterProfileInput,
  SlideRasterErrorCode,
  SlideRasterFailure,
  SlideRasterFormat,
  SlideRasterPixelSize,
  SlideRasterProfile,
  SlideRasterRequest,
  SlideRasterResult,
  SlideRasterSuccess,
  SlideRasterWorkerBridge,
  SlideRasterWorkerReadyPayload,
  SlideRasterWorkerRequestPayload,
  SlideRasterWorkerResponsePayload,
} from './slideRasterization';
export {
  collectEditableTargetsBySlide,
  PATCHABLE_EDIT_OPERATIONS,
  sanitizeToolEditableTarget,
} from './renderModel';
export type {
  OverlapClassification,
  RelationEdge,
  SpatialAnalysisSummary,
  SpatialBox,
  SpatialNode,
  SpatialNodeKind,
  SpatialSectionSummary,
} from './spatialTypes';
export {
  ALIGNMENT_ACTIONS,
  ARRANGEMENT_PLACEMENTS,
  buildNodeToolCapabilities,
  buildSlideTools,
  ELEMENT_ACTIONS,
} from './toolCapabilities';
export type {
  PresentationToolCapabilityMap,
} from './toolCapabilities';
export type {
  InspectBackgroundSummary,
  InspectPageSummary,
  ReferenceFrameInfo,
  SceneGraphNodeSummary,
  SceneGraphSlideSummary,
  SourceLocationHint,
  ToolArtifactRef,
  ToolBuildStatus,
  ToolCapabilityMap,
  ToolFeedbackPayload,
} from './toolFeedback';
export type {
  SemanticRole,
} from './deckSpec';
export type {
  Box,
  ChartSeries,
  ChartType,
  DeckSpec,
  DeferredPatchOperation,
  FreeformElement,
  FreeformElementBase,
  FreeformGroupElement,
  FreeformImageElement,
  FreeformShapeElement,
  FreeformSvgGraphicElement,
  FreeformFormulaElement,
  FreeformSlideSpec,
  FreeformTextElement,
  FreeformTextRun,
  FreeformFormulaTextRun,
  FreeformInlineRun,
  ImageSourceInput,
  ImageSourceRef,
  ImageVisualOptions,
  ImageVisualShadow,
  PatchOperation,
  PatchSpec,
  PatchTarget,
  ResolvedImageAsset,
  ShapeStyle,
  SlideBackgroundGradient,
  SlideBackgroundGradientStop,
  SlideEntry,
  SourceSpan,
  StructuredElement,
  StructuredSvgGraphicElement,
  StructuredFormulaElement,
  StructuredSlideSpec,
  TableCell,
  TextStyle,
} from './deckSpec';

export type {
  ChartFrame,
  ChartFrameOptions,
  ChartPoint,
  ChartValueRange,
  RadarPoint,
  RenderTextMeasureBox,
  RenderTextMeasureInput,
  RenderTextMeasureLine,
  RenderTextMeasurePadding,
  RenderTextMeasureParagraph,
  RenderTextMeasurePort,
  RenderTextMeasureResult,
  RenderTextMeasureSourceKind,
  RenderTextMeasureStyle,
  SnappedRect,
} from './render-geometry';
export {
  buildCartesianRange,
  buildChartFrame,
  buildClusterBarThickness,
  buildRadarPoints,
  CHART_GAP_WIDTH_RATIO,
  CHART_LABEL_FONT_FAMILY,
  CHART_LABEL_FONT_SIZE,
  isRadialChart,
  pointsToFlatArray,
  resolveChartPalette,
  resolveSeriesType,
  snapRect,
  snapStrokeCenter,
  valueToX,
  valueToY,
} from './render-geometry';
export {
  assertCanonicalHexColor,
  normalizeDeckSpecColors,
  normalizeFillColor,
  normalizeFreeformSlideSpecColors,
  normalizeGradientAngle,
  normalizeGradientColors,
  normalizeGradientPaint,
  normalizeImageShadowColors,
  normalizeOpaqueColor,
  normalizePaint,
  normalizeShapeFillInput,
  normalizeShapeStyleColors,
  normalizeStrokePaint,
  normalizeStructuredSlideSpecColors,
  normalizeTextStyleColors,
  normalizeThemeSpecColors,
  resolvePaintOpacity,
  toPptxHexColor,
} from './visual';

export type {
  GradientPaint,
  GradientStop,
  LinearGradientPaint,
  NoPaint,
  NormalizedPaintPoint,
  NormalizedPaintRadius,
  Paint,
  RadialGradientPaint,
  ShapeFillInput,
  ShapeStrokeStyle,
  SolidPaint,
  StrokePaint,
} from './visual';
