import type { MessageCatalogContribution } from '@app/localization';
import type { EditorMessageKey } from './editorMessages';

export const EDITOR_MESSAGE_FALLBACKS = {
  'editor.common.moreActions': '更多操作',
  'editor.common.unavailableInTable': '表格内不可用',
  'editor.common.unknownError': '未知错误',
  'editor.shortcuts.save.noOpenFile': '无打开的文件，无法保存',
  'editor.shortcuts.save.saving': '正在保存，请稍候...',
  'editor.shortcuts.save.unexpectedError': '保存时发生意外错误，请稍后重试。',
  'editor.menu.headingLevel': '标题级别',
  'editor.menu.bold': '加粗',
  'editor.menu.italic': '斜体',
  'editor.menu.bulletList': '无序列表',
  'editor.menu.orderedList': '有序列表',
  'editor.menu.quoteBlock': '引用块',
  'editor.menu.insertImage': '插入图片',
  'editor.menu.insertTable': '插入表格',
  'editor.menu.insertAudio': '插入录音',
  'editor.menu.debug': '调试',
  'editor.menu.viewLatestProviderOutboundAttempt': '查看最近一次 Provider 请求',
  'editor.menu.heading.level1': '一级标题',
  'editor.menu.heading.level2': '二级标题',
  'editor.menu.heading.level3': '三级标题',
  'editor.menu.heading.level4': '四级标题',
  'editor.menu.heading.level5': '五级标题',
  'editor.menu.heading.level6': '六级标题',
  'editor.menu.error.headingUnavailable': '切换标题功能暂时不可用。',
  'editor.menu.error.quoteUnavailable': '切换引用块功能暂时不可用。',
  'editor.menu.toast.imageInserted': '图片已插入：{fileName}',
  'editor.menu.toast.editorNotReady': '无法插入图片：编辑器未就绪。',
  'editor.menu.toast.imageLoadFailed': '无法加载图片，请确认文件仍可访问。',
  'editor.menu.toast.imageFlowFailed': '插入图片流程出错，请稍后重试。',
  'editor.menu.toast.imageDialogUnavailable': '无法打开图片选择对话框，系统功能未正确初始化。',
  'editor.menu.imageDialog.title': '选择图片',
  'editor.menu.imageDialog.filterName': '图片文件',
  'editor.slash.empty': '没有匹配的结果',
  'editor.slash.group.convertTo': '转换为',
  'editor.slash.group.insert': '插入',
  'editor.slash.group.ai': 'AI',
  'editor.slash.item.heading1': '一级标题',
  'editor.slash.item.heading2': '二级标题',
  'editor.slash.item.bulletList': '无序列表',
  'editor.slash.item.orderedList': '有序列表',
  'editor.slash.item.quoteBlock': '引用块',
  'editor.slash.item.audioBlock': '录音块',
  'editor.slash.item.codeBlock': '代码块',
  'editor.slash.item.latexBlock': 'LaTeX 公式',
  'editor.slash.item.horizontalRule': '水平分割线',
  'editor.slash.item.tableBlock': '表格块',
  'editor.slash.item.imageBlock': '图片块',
  'editor.slash.item.aiWriting': 'AI 写作',
  'editor.slash.item.citation': '引用',
  'editor.slash.toast.imageDialogUnavailable': '无法打开图片选择对话框，系统功能未正确初始化。',
  'editor.slash.toast.imageLoadFailed': '无法加载图片，请确认文件仍可访问。',
  'editor.slash.toast.imageInserted': '图片已插入：{fileName}',
  'editor.slash.toast.imageFlowFailed': '插入图片流程出错，请稍后重试。',
  'editor.slash.imageDialog.title': '选择图片',
  'editor.slash.imageDialog.filterName': '图片文件',
  'editor.findReplace.title': '查找和替换',
  'editor.findReplace.searchPlaceholder': '查找',
  'editor.findReplace.replacePlaceholder': '替换为',
  'editor.findReplace.previous': '上一个',
  'editor.findReplace.next': '下一个',
  'editor.findReplace.replaceCurrent': '替换当前匹配',
  'editor.findReplace.replaceAll': '替换全部匹配',
  'editor.findReplace.matchCase': '区分大小写',
  'editor.findReplace.wholeWord': '全字匹配',
  'editor.findReplace.regex': '正则表达式',
  'editor.findReplace.noMatches': '未找到匹配项',
  'editor.outline.togglePinned': '目录已固定，点击取消固定',
  'editor.outline.togglePreview': '悬停显示目录，点击固定目录',
  'editor.outline.emptyHeading': '空标题',
  'editor.blockMenu.duplicate': '创建副本',
  'editor.blockMenu.color': '颜色',
  'editor.blockMenu.delete': '删除',
  'editor.blockMenu.addAnnotation': '添加批注',
  'editor.blockMenu.createVersion': '创建为新版本',
  'editor.blockMenu.viewHistory': '查看历史版本',
  'editor.blockMenu.color.background': '背景颜色',
  'editor.blockMenu.color.text': '文字颜色',
  'editor.blockMenu.color.clear': '清除颜色',
  'editor.blockMenu.toast.noDocumentForHistory': '未找到当前文档，无法查看历史',
  'editor.blockMenu.toast.noBlockForHistory': '未找到块 ID，无法查看历史',
  'editor.blockMenu.toast.loadedHistoryVersions': '已加载 {count} 个历史版本',
  'editor.blockMenu.toast.loadHistoryFailed': '加载历史版本失败',
  'editor.blockMenu.toast.noDocumentForCreateVersion': '未找到当前文档，无法创建版本',
  'editor.blockMenu.toast.noBlockForCreateVersion': '未找到块 ID，无法创建版本',
  'editor.blockMenu.toast.noBlockTypeForCreateVersion': '未找到块类型，无法创建版本',
  'editor.blockMenu.toast.createVersionFailed': '创建块版本失败',
  'editor.blockMenu.toast.createVersionSuccess': '已为当前块创建版本 v{version}',
  'editor.blockMenu.toast.createVersionException': '创建块版本时出现异常',
  'editor.floatingToolbar.aiReference': 'AI 引用',
  'editor.floatingToolbar.bold': '加粗',
  'editor.floatingToolbar.italic': '斜体',
  'editor.floatingToolbar.strikethrough': '删除线',
  'editor.floatingToolbar.textColor': '文字颜色',
  'editor.floatingToolbar.textHighlight': '文字高亮',
  'editor.floatingToolbar.heading': '标题',
  'editor.floatingToolbar.headingWithLevel': '标题 {level}',
  'editor.floatingToolbar.heading.level1': '一级标题',
  'editor.floatingToolbar.heading.level2': '二级标题',
  'editor.floatingToolbar.heading.level3': '三级标题',
  'editor.floatingToolbar.heading.level4': '四级标题',
  'editor.floatingToolbar.heading.level5': '五级标题',
  'editor.floatingToolbar.heading.level6': '六级标题',
  'editor.floatingToolbar.paragraph': '文本',
  'editor.floatingToolbar.colorPanel': '颜色面板',
  'editor.floatingToolbar.highlightPanel': '高亮面板',
  'editor.floatingToolbar.clearColor': '清除颜色',
  'editor.floatingToolbar.clearHighlight': '清除高亮',
  'editor.floatingToolbar.quoteLabel': '引用内容',
  'editor.floatingToolbar.toast.noSelection': '请先在文档中选中要引用的内容',
  'editor.floatingToolbar.toast.emptySelection': '选中的内容为空，无法作为引用',
  'editor.floatingToolbar.toast.addedReference': '已将当前选区添加到 AI 引用',
  'editor.color.red': '红色',
  'editor.color.crimson': '洋红',
  'editor.color.pink': '粉色',
  'editor.color.purple': '紫色',
  'editor.color.indigo': '靛蓝',
  'editor.color.blue': '蓝色',
  'editor.color.teal': '青色',
  'editor.color.mint': '薄荷',
  'editor.color.green': '绿色',
  'editor.color.lime': '青柠',
  'editor.color.yellow': '黄色',
  'editor.color.orange': '橙色',
  'editor.color.brown': '棕色',
  'editor.color.slate': '石板灰',
  'editor.color.gray': '灰色',
  'editor.color.brightYellow': '亮黄',
  'editor.color.brightPink': '亮粉',
  'editor.color.brightGreen': '亮绿',
  'editor.color.brightOrange': '亮橙',
  'editor.color.brightBlue': '亮蓝',
  'editor.codeBlock.language.select': '选择语言',
  'editor.codeBlock.language.plainText': '纯文本',
  'editor.codeBlock.action.copy': '复制代码',
  'editor.codeBlock.action.copied': '已复制!',
  'editor.imageBlock.action.more': '更多操作',
  'editor.imageBlock.action.preview': '预览图片',
  'editor.imageBlock.action.resize': '调整尺寸',
  'editor.imageBlock.align.left': '左对齐',
  'editor.imageBlock.align.center': '居中对齐',
  'editor.imageBlock.align.right': '右对齐',
  'editor.imageBlock.resize.width': '宽度 (px):',
  'editor.imageBlock.resize.height': '高度 (px):',
  'editor.imageBlock.resize.confirm': '确定',
  'editor.imageBlock.resize.cancel': '取消',
  'editor.imageBlock.property.uploadedAt': '上传于',
  'editor.imageBlock.property.format': '格式',
  'editor.imageBlock.property.dimensions': '尺寸',
  'editor.imageBlock.property.size': '大小',
  'editor.imageBlock.property.panelTitle': '属性',
  'editor.imageBlock.value.unknown': '未知',
  'editor.imageBlock.value.originalSize': '原始尺寸',
  'editor.imageBlock.value.widthOnly': '{width}px (宽)',
  'editor.imageBlock.value.heightOnly': '{height}px (高)',
  'editor.imageBlock.empty': '无图片',
  'editor.imageBlock.missing': '图片已失效或源文件丢失',
  'editor.latexBlock.inline.invalidSource': '无效的 LaTeX 源码',
  'editor.latexBlock.input.placeholder': '输入 LaTeX 公式...\n(Enter 确定, Shift+Enter 换行，Esc 取消)',
  'editor.latexBlock.input.confirm': '确定',
  'editor.latexBlock.input.cancel': '取消',
  'editor.latexBlock.input.invalidFormula': '无效的 LaTeX 公式',
  'editor.latexBlock.placeholder': '添加 LaTeX 公式……',
  'editor.latexBlock.renderError': '渲染错误',
  'editor.latexBlock.symbolCategory.math': '数学',
  'editor.latexBlock.symbolCategory.physics': '物理',
  'editor.latexBlock.symbolCategory.chemistry': '化学',
  'editor.latexBlock.symbolCategory.arrows': '箭头',
  'editor.latexBlock.symbolCategory.greekLetters': '希腊字母',
  'editor.service.loadFileFailed': '加载文件失败，请稍后重试。',
  'editor.conversion.inTable.blockType': '表格内不支持块类型转换',
  'editor.conversion.inTable.listItem': '表格内不支持转换为列表项',
  'editor.conversion.inTable.quoteBlock': '表格内不支持转换为引用块',
  'editor.conversion.inTable.latexBlock': '表格内不支持转换为 LaTeX 块',
  'editor.conversion.inTable.audioBlock': '表格内不支持转换为录音块',
  'editor.command.splitBlock.failed': '块拆分时发生错误',
  'editor.placeholder.baseBlock': '开始输入...',
  'editor.placeholder.baseBlockAi': '输入文字... 按下空格唤起 AI',
  'editor.placeholder.listItem': '列表项...',
  'editor.placeholder.heading': '标题 {level}',
  'editor.placeholder.heading.level1': '一级标题...',
  'editor.placeholder.heading.level2': '二级标题...',
  'editor.placeholder.heading.level3': '三级标题...',
  'editor.placeholder.heading.level4': '四级标题...',
  'editor.placeholder.heading.level5': '五级标题...',
  'editor.placeholder.heading.level6': '六级标题...',
  'editor.placeholder.heading.empty': '标题 {level}...',
  'editor.aiWriting.placeholder': 'AI 写作... (Shift+Enter 换行，按下空格键取消) ',
  'editor.aiWriting.cancel': '取消 (Esc)',
  'editor.aiWriting.submit': '生成 (Enter)',
  'editor.aiWriting.error.streamRequestFailed': 'AI 流式请求失败',
  'editor.aiWriting.error.streamEndedAbnormally': '流异常结束',
  'editor.aiWriting.error.queueProcessingFailed': '处理队列发生未知错误',
  'editor.autocomplete.error.requestFailed': '自动补全请求失败',
  'editor.documentSettings.tabTitle': '文本文档',
  'editor.documentSettings.interface.title': '文本文档界面',
  'editor.documentSettings.interface.menuBar': '显示菜单栏',
  'editor.documentSettings.interface.menuBarDescription': '在文本文档顶部显示格式、插入和调试工具栏。',
  'editor.documentSettings.interface.characterCount': '显示字数统计',
  'editor.documentSettings.interface.currentCharacterCount': '当前字数: {count}',
  'editor.documentSettings.interface.characterCountDescription': '在文本文档右下角显示当前内容的字数。',
  'editor.documentSettings.interface.blockHover': '块悬停交互',
  'editor.documentSettings.interface.blockHoverDescription': '启用后，鼠标悬停在编辑块上时会显示背景高亮。',
  'editor.documentSettings.input.title': '输入体验',
  'editor.documentSettings.input.spellcheck': '拼写检查',
  'editor.documentSettings.input.spellcheckDescription': '启用后，浏览器会对文本文档输入内容进行原生拼写检查。',
  'editor.documentSettings.ai.title': 'AI 交互',
  'editor.documentSettings.ai.description': '控制文本文档里的自动补全行为。',
  'editor.documentSettings.ai.autocomplete': '启用自动补全',
  'editor.documentSettings.ai.intraParagraphCompletion': '段落内补全',
  'editor.documentSettings.ai.intraParagraphCompletionDescription': '允许在段落中间触发自动补全。',
  'editor.documentSettings.ai.triggerDelay': '补全触发延迟',
  'editor.documentSettings.ai.triggerDelayDescription': '停止输入后等待自动补全触发的时间。',
  'editor.documentSettings.ai.triggerFrequency': '补全触发频率',
  'editor.documentSettings.ai.triggerFrequencyDescription': '控制两次自动补全触发之间的时长。',
  'editor.documentSettings.ai.completionLength': '补全长度',
  'editor.documentSettings.ai.completionLengthDescription': '控制自动补全建议的长度。',
  'editor.documentSettings.ai.scale.slowest': '极慢',
  'editor.documentSettings.ai.scale.slower': '较慢',
  'editor.documentSettings.ai.scale.medium': '中等',
  'editor.documentSettings.ai.scale.faster': '较快',
  'editor.documentSettings.ai.scale.fastest': '极快',
  'editor.documentSettings.ai.scale.lowest': '极低',
  'editor.documentSettings.ai.scale.lower': '较低',
  'editor.documentSettings.ai.scale.higher': '较高',
  'editor.documentSettings.ai.scale.highest': '极高',
  'editor.documentSettings.ai.scale.always': '总是',
  'editor.documentSettings.ai.scale.short': '短',
  'editor.documentSettings.ai.scale.long': '长',
  'editor.documentSettings.ai.scale.unknown': '未知',
  'editor.documentSettings.model.title': '模型配置',
  'editor.blockHistory.currentVersion': '当前版本 v{version}',
  'editor.blockHistory.currentVersionUnsaved': '当前版本（未创建版本）',
  'editor.blockHistory.noSelectedVersion': '未选择版本',
  'editor.blockHistory.selectedVersionWithTime': '版本 v{version} ({time})',
  'editor.blockHistory.selectedVersion': '版本 v{version}',
  'editor.blockHistory.more.deleteVersion': '删除版本 v{version}',
  'editor.blockHistory.timeline.applyVersion': '应用版本 v{version}',
  'editor.blockHistory.timeline.exit': '退出',
  'editor.blockHistory.overlay.versionBadge': '历史版本 {version}',
  'editor.blockHistory.overlay.restore': '恢复',
  'editor.blockHistory.overlay.empty': '此版本内容为空',
  'editor.blockHistory.overlay.closePreviewShortcut': '按 Esc 关闭预览',
  'editor.blockHistory.origin.ai': 'AI 生成',
  'editor.blockHistory.origin.manual': '手动编辑',
  'editor.blockHistory.origin.restore': '版本恢复',
  'editor.blockHistory.time.justNow': '刚刚',
  'editor.blockHistory.time.minutesAgo': '{count} 分钟前',
  'editor.blockHistory.applyDialog.title': '应用版本',
  'editor.blockHistory.applyDialog.message': '当前块的内容尚未创建历史版本。\n\n创建版本并应用：先将当前内容保存为新版本，再应用所选版本；\n直接应用所选版本：不保存当前内容，直接应用所选版本（当前改动将丢失）。',
  'editor.blockHistory.applyDialog.confirm': '创建版本并应用',
  'editor.blockHistory.applyDialog.cancel': '直接应用所选版本',
  'editor.blockHistory.deleteDialog.title': '删除版本',
  'editor.blockHistory.deleteDialog.message': '确定要删除这个历史版本吗？此操作无法撤销。',
  'editor.blockHistory.deleteDialog.messageWithVersion': '确定要删除版本 v{version} 吗？此操作无法撤销。',
  'editor.blockHistory.deleteDialog.confirm': '删除',
  'editor.blockHistory.deleteDialog.cancel': '取消',
  'editor.blockVersionHandle.viewHistory': '查看历史版本',
  'editor.blockVersionHandle.singleVersion': '查看历史版本（1 个版本）',
  'editor.blockVersionHandle.multipleVersions': '查看历史版本（{count} 个版本，最新 v{version}）',
  'editor.debugPanel.title': '编辑器调试面板',
  'editor.debugPanel.action.documentStructure': '查看文档结构',
  'editor.debugPanel.action.currentNode': '查看当前节点',
  'editor.debugPanel.action.selectionInfo': '查看选区信息',
  'editor.debugPanel.analyzingDocumentStructure': '正在分析文档结构...',
  'editor.debugPanel.documentStructureLogged': '文档结构已输出到控制台',
  'editor.debugPanel.analyzingCurrentNode': '正在分析当前节点...',
  'editor.debugPanel.currentNodeLogged': '当前节点信息已输出到控制台',
  'editor.providerOutboundDebug.title': 'Provider 请求调试',
  'editor.providerOutboundDebug.overviewTab': '请求概览',
  'editor.providerOutboundDebug.snapshotTab': '安全快照',
  'editor.providerOutboundDebug.loading': '加载中...',
  'editor.providerOutboundDebug.empty': '暂无 Provider 请求快照',
  'editor.providerOutboundDebug.noData': '// 暂无数据',
  'editor.providerOutboundDebug.loadFailed': '加载 Provider 请求快照失败，请查看控制台日志',
  'editor.annotation.toast.creating': '正在创建批注...',
  'editor.annotation.toast.created': '批注创建成功',
  'editor.annotation.error.confirmFailed': '确认批注失败',
  'editor.annotation.error.startFailed': '无法启动批注创建过程',
  'editor.annotation.toast.createFailed': '创建批注失败，请稍后重试。',
  'editor.annotation.author.user': '用户',
  'editor.annotation.status.resolved': '已解决',
  'editor.annotation.action.ai': '调用 AI (Ctrl+Alt+A)',
  'editor.annotation.action.aiAndSave': '调用 AI 并保存 (Ctrl+Alt+A)',
  'editor.annotation.action.aiAndCreate': '调用 AI 并创建 (Ctrl+Alt+A)',
  'editor.annotation.action.edit': '编辑批注',
  'editor.annotation.action.resolve': '标记为已解决',
  'editor.annotation.action.resolveAria': '标记已解决',
  'editor.annotation.action.reopen': '重新打开',
  'editor.annotation.action.delete': '删除批注',
  'editor.annotation.action.cancelEdit': '取消编辑',
  'editor.annotation.action.cancelCreate': '取消创建',
  'editor.annotation.action.save': '保存',
  'editor.annotation.action.create': '创建批注',
  'editor.annotation.placeholder.edit': '编辑批注内容...',
  'editor.annotation.placeholder.create': '输入批注内容...',
  'editor.annotation.time.yesterday': '昨天',
  'editor.audioBlock.status.checkingDevice': '检测录音设备中...',
  'editor.audioBlock.status.microphoneConnected': '麦克风已连接',
  'editor.audioBlock.status.defaultMicrophone': '默认麦克风',
  'editor.audioBlock.status.systemDefaultRecordingDevice': '系统默认录音设备',
  'editor.audioBlock.status.usingMicrophone': '使用 {device}',
  'editor.audioBlock.status.usingDefaultMicrophone': '使用默认麦克风',
  'editor.audioBlock.status.noMicrophone': '未检测到可用麦克风',
  'editor.audioBlock.status.deviceDetectionFailed': '检测录音设备出错，请检查设备或权限。',
  'editor.audioBlock.status.unsupportedDeviceDetection': '浏览器不支持录音设备检测',
  'editor.audioBlock.status.unsupportedRecording': '浏览器不支持录音功能',
  'editor.audioBlock.status.microphoneAccessFailed': '获取麦克风失败，请检查设备或权限。',
  'editor.audioBlock.status.microphonePermissionDenied': '麦克风权限被拒绝，无法录音。',
  'editor.audioBlock.status.microphoneNotFound': '未找到可用的麦克风设备。',
  'editor.audioBlock.status.recording': '正在录音...',
  'editor.audioBlock.status.paused': '录音已暂停。',
  'editor.audioBlock.status.processingAudio': '正在处理音频...',
  'editor.audioBlock.status.ready': '准备就绪',
  'editor.audioBlock.status.savingRecording': '正在保存录音文件...',
  'editor.audioBlock.status.loadingAudio': '正在加载音频...',
  'editor.audioBlock.status.loadingSavedAudio': '正在加载已保存的音频...',
  'editor.audioBlock.status.loadFailed': '加载失败',
  'editor.audioBlock.status.loadFailedWithMessage': '加载音频失败，请确认文件仍可访问。',
  'editor.audioBlock.status.recordingTerminatedNoAudio': '录音已终止，但无有效音频数据。',
  'editor.audioBlock.status.initializationFailed': '无法初始化录音功能。',
  'editor.audioBlock.status.startRecordingFailed': '开始录音失败。',
  'editor.audioBlock.status.pauseRecordingFailed': '暂停录音失败。',
  'editor.audioBlock.status.resumeRecordingFailed': '恢复录音失败。',
  'editor.audioBlock.status.terminateRecordingFailed': '终止录音失败。',
  'editor.audioBlock.status.saveFallback': '保存失败，当前录音仅在本次会话中可用。',
  'editor.audioBlock.status.saveFailedRetryable': '保存失败，当前录音仍在本次会话中，可重试保存。',
  'editor.audioBlock.status.saveFailedNoRuntimeAudio': '保存失败，当前会话中的录音数据已不可用。',
  'editor.audioBlock.status.recordingProcessFailed': '处理录音时出错，请稍后重试。',
  'editor.audioBlock.status.recordingError': '录音出错，请重新开始录音。',
  'editor.audioBlock.status.transcribingAudio': '正在转录音频...',
  'editor.audioBlock.status.transcriptionCompletedGenerated': '转录完成，内容已生成。',
  'editor.audioBlock.status.transcriptionCompletedEmpty': '转录完成，但未返回文本内容。',
  'editor.audioBlock.status.playFailed': '播放失败，请稍后重试。',
  'editor.audioBlock.status.audioError': '音频播放出错，请确认文件仍可访问。',
  'editor.audioBlock.status.maxDuration': '录音最长可达2小时',
  'editor.audioBlock.render.file': '音频文件: {src}',
  'editor.audioBlock.render.readyToRecord': '准备录音...',
  'editor.audioBlock.missing.source': '音频已失效或源文件丢失',
  'editor.audioBlock.missing.temporarySource': '上次录音未成功保存，临时音频已失效',
  'editor.audioBlock.missing.saveFailed': '上次录音未成功保存，当前会话音频已不可用',
  'editor.markdownSerializer.imageAlt': '图片',
  'editor.markdownSerializer.imageDescription': '[图片：{alt}]',
  'editor.markdownSerializer.imageDescriptionWithWidth': '[图片：{alt}，宽度{width}px]',
  'editor.markdownSerializer.imageDescriptionWithHeight': '[图片：{alt}，高度{height}px]',
  'editor.markdownSerializer.imageDescriptionWithSize': '[图片：{alt}，宽度{width}px，高度{height}px]',
  'editor.markdownSerializer.audioFile': '音频文件',
  'editor.markdownSerializer.emptyAudioBlock': '空音频块',
  'editor.audioBlock.action.startRecording': '开始录音',
  'editor.audioBlock.action.retryMicrophone': '重新检测麦克风',
  'editor.audioBlock.action.retrySaveRecording': '重试保存',
  'editor.audioBlock.action.notes': '笔记',
  'editor.audioBlock.action.pause': '暂停',
  'editor.audioBlock.action.resume': '继续',
  'editor.audioBlock.action.finish': '完成',
  'editor.audioBlock.action.transcribing': '转写中...',
  'editor.audioBlock.action.transcribed': '已转写',
  'editor.audioBlock.action.transcriptionFailed': '转录失败',
  'editor.audioBlock.action.transcribe': '转文字',
  'editor.audioBlock.action.transcribeAndCreate': '转录并创建',
  'editor.audioBlock.action.showPanel': '显示内容面板',
  'editor.audioBlock.action.hidePanel': '隐藏内容面板',
  'editor.audioBlock.action.insertTimestamp': '插入时间戳',
  'editor.audioBlock.action.bold': '加粗 (Ctrl+B)',
  'editor.audioBlock.action.italic': '斜体 (Ctrl+I)',
  'editor.audioBlock.action.bulletList': '无序列表',
  'editor.audioBlock.action.heading': '标题',
  'editor.audioBlock.panel.notes': '笔记',
  'editor.audioBlock.panel.transcript': '转录',
  'editor.audioBlock.panel.summary': '纪要',
  'editor.audioBlock.panel.collapse': '收起内容面板',
  'editor.audioBlock.panel.expand': '展开内容面板',
  'editor.audioBlock.create.group': '创建',
  'editor.audioBlock.transcript.copyFullText': '复制全文',
  'editor.audioBlock.transcript.translateTargetLanguage': '翻译目标语言',
  'editor.audioBlock.transcript.translating': '翻译中',
  'editor.audioBlock.transcript.translateTo': '翻译为',
  'editor.audioBlock.transcript.retranslateTo': '重新翻译为',
  'editor.audioBlock.transcript.empty': '暂无转录内容',
  'editor.audioBlock.transcript.placeholder': '暂无转录内容...',
  'editor.audioBlock.transcript.language.english': '英语',
  'editor.audioBlock.transcript.language.japanese': '日语',
  'editor.audioBlock.transcript.language.korean': '韩语',
  'editor.audioBlock.transcript.language.french': '法语',
  'editor.audioBlock.transcript.language.german': '德语',
  'editor.audioBlock.transcript.language.spanish': '西班牙语',
  'editor.audioBlock.content.createdAt': '创建于 {time}',
  'editor.audioBlock.content.editedAt': '编辑于 {time}',
  'editor.audioBlock.content.yesterday': '昨天',
  'editor.audioBlock.notes.placeholder': '在此记录笔记... 输入 @time 快速插入时间戳',
  'editor.audioBlock.summary.placeholder': '在此记录会议纪要... 输入 @time 快速插入时间戳',
  'editor.audioBlock.toast.transcriptionCompleted': '转录完成！',
  'editor.audioBlock.toast.transcriptionFailedRetry': '转录失败，请重试',
  'editor.audioBlock.toast.durationUnknownSeek': '音频时长未知，无法跳转。',
  'editor.audioBlock.toast.durationUnknownDrag': '音频时长未知，无法拖动。',
  'editor.audioBlock.toast.transcriptionInProgress': '转录进行中，请稍候...',
  'editor.audioBlock.toast.transcribingAudio': '正在转录音频，请稍候...',
  'editor.audioBlock.toast.transcriptionFailedWithMessage': '转录失败，请稍后重试。',
  'editor.audioBlock.toast.transcriptionCompletedFilled': '转录完成，内容已填入转录面板。',
  'editor.audioBlock.toast.transcriptionCompletedEmpty': '转录完成，但未返回文本内容。',
  'editor.audioBlock.toast.copied': '已复制到剪贴板',
  'editor.audioBlock.toast.copyFailed': '复制失败',
  'editor.audioBlock.toast.noTranscriptToTranslate': '没有可翻译的转录内容',
  'editor.audioBlock.toast.translatingTo': '正在翻译为{language}...',
  'editor.audioBlock.toast.translationCompleted': '翻译完成！',
  'editor.audioBlock.toast.translationFailed': '翻译失败，请稍后重试。',
  'editor.audioBlock.toast.generatingSummary': '正在生成纪要...',
  'editor.audioBlock.toast.summaryCompleted': '纪要生成完成！',
  'editor.audioBlock.toast.generateFailed': '生成失败，请稍后重试。',
  'editor.audioBlock.toast.operationFailed': '操作失败，请稍后重试。',
  'editor.audioBlock.error.missingBlockId': '缺少 blockId，无法开始转录',
  'editor.audioBlock.error.noRuntime': '无法获取音频块运行时状态',
  'editor.audioBlock.error.transcriptionFailed': '转录失败，请稍后重试。',
  'editor.audioBlock.error.transcriptionNoContent': '转录失败或未返回转录内容',
  'editor.audioBlock.error.noAudioForTranscription': '未找到可用于转录的音频数据',
  'editor.audioBlock.error.audioDataReadFailed': '读取音频数据失败',
  'editor.audioBlock.error.audioDataUrlLoadFailed': '加载音频 Data URL 失败',
  'editor.audioBlock.error.fileTooLarge': '音频文件过大 ({fileSizeMB}MB)，请确保文件小于25MB。',
  'editor.audioBlock.error.apiBaseUrlUnavailable': '无法获取API服务地址。',
  'editor.audioBlock.error.transcriptionErrorParseFailed': '转录失败，无法解析错误信息。',
  'editor.audioBlock.error.transcriptionServiceReturnedError': '转录服务返回了错误。',
  'editor.audioBlock.error.emptyTranscriptForTranslation': '转录内容为空，无法翻译',
  'editor.audioBlock.error.emptyTranscriptForSummary': '转录内容为空，无法生成纪要',
  'editor.audioBlock.error.saveFileFailed': '保存录音文件失败',
  'editor.audioBlock.menu.unknown': '未知',
  'editor.audioBlock.menu.createdAt': '创建于',
  'editor.audioBlock.menu.size': '大小',
  'editor.audioBlock.menu.unsaved': '未保存',
  'editor.audioBlock.menu.format': '格式',
  'editor.audioBlock.menu.storageLocation': '存储位置',
  'editor.audioBlock.menu.openLocation': '点击打开文件所在位置',
  'editor.audioBlock.menu.temporaryFile': '临时文件（未保存）',
  'editor.audioBlock.menu.startTranscription': '开始转录',
  'editor.audioBlock.menu.retranscribe': '重新转录',
  'editor.audioBlock.menu.properties': '属性',
  'editor.tableBlock.toolbar.aiFillTitle': 'AI 批量填充',
  'editor.tableBlock.toolbar.aiFill': 'AI 填充',
  'editor.tableBlock.toolbar.insertTitle': '插入行或列',
  'editor.tableBlock.toolbar.insert': '插入',
  'editor.tableBlock.toolbar.deleteRow': '删除行',
  'editor.tableBlock.toolbar.deleteColumn': '删除列',
  'editor.tableBlock.toolbar.alignTitle': '单元格对齐',
  'editor.tableBlock.toolbar.align': '对齐',
  'editor.tableBlock.toolbar.mergeCellsTitle': '合并单元格',
  'editor.tableBlock.toolbar.merge': '合并',
  'editor.tableBlock.toolbar.splitCellTitle': '拆分单元格',
  'editor.tableBlock.toolbar.split': '拆分',
  'editor.tableBlock.menu.insertRowBefore': '在上方插入行',
  'editor.tableBlock.menu.insertRowAfter': '在下方插入行',
  'editor.tableBlock.menu.insertColumnBefore': '在左侧插入列',
  'editor.tableBlock.menu.insertColumnAfter': '在右侧插入列',
  'editor.tableBlock.menu.aiAnalyze': 'AI分析',
  'editor.tableBlock.menu.alignLeft': '左对齐',
  'editor.tableBlock.menu.alignCenter': '居中对齐',
  'editor.tableBlock.menu.alignRight': '右对齐',
  'editor.tableBlock.menu.jsonFormat': 'JSON格式',
  'editor.tableBlock.menu.csvFormat': 'CSV格式',
  'editor.tableBlock.menu.markdownTable': 'Markdown表格',
  'editor.tableBlock.menu.rawData': '原始数据',
  'editor.tableBlock.context.referenceColumns': '引用列',
  'editor.tableBlock.context.insertReference': '插入引用：{reference}',
  'editor.tableBlock.context.selectionRange': '选区范围',
  'editor.tableBlock.context.selectionRangeTitle': '选区范围：{range}',
  'editor.tableBlock.context.outputColumn': '输出列',
  'editor.tableBlock.size.display': '{rows} × {cols} 表格',
  'editor.tableBlock.size.headerRow': '表头行',
  'editor.tableBlock.alert.selectCellRange': '请先选择表格中的单元格区域',
  'editor.tableBlock.alert.aiFillFailed': '执行 AI 填充时出错，请稍后重试。',
  'editor.tableBlock.alert.aiAnalyzeUnavailable': 'AI分析功能暂未实现',
  'editor.tableBlock.alert.missingSubmitContext': '无法提交AI请求：编辑器或表格信息丢失。',
  'editor.tableBlock.notification.missingTableComponents': '表格功能组件缺失，无法创建表格。',
  'editor.tableBlock.selection.invalidState': '无效的编辑器状态',
  'editor.tableBlock.selection.noValidSelection': '未选择有效的表格区域',
  'editor.tableBlock.selection.emptySelection': '表格选区不包含任何单元格',
  'editor.tableBlock.selection.infoExtractionFailed': '无法提取选区信息或矩形范围',
  'editor.tableBlock.selection.metadataProcessingFailed': '处理选区元数据失败，请稍后重试。',
  'editor.tableBlock.selection.invalidArguments': '无效参数',
  'editor.tableBlock.selection.mapUnavailable': '无法获取表格地图',
  'editor.tableBlock.selection.rectUnavailable': '无法计算选区矩形',
  'editor.tableBlock.selection.notInsideTableCell': '当前不是表格单元格内的选区',
  'editor.tableBlock.selection.formattingFailed': '格式化错误，请稍后重试。',
  'editor.citation.panel.title': '插入引用',
  'editor.citation.panel.tab.knowledgeBase': '知识库',
  'editor.citation.panel.tab.webManual': '网页 / 手动',
  'editor.citation.inlineTrigger.title': '引用',
  'editor.citation.kb.searchScope': '搜索范围',
  'editor.citation.kb.noProjectKnowledgeBases': '当前项目未关联任何知识库',
  'editor.citation.kb.searchPlaceholder': '输入关键词搜索知识库...',
  'editor.citation.kb.search': '搜索',
  'editor.citation.kb.searching': '搜索中...',
  'editor.citation.kb.noResults': '未找到匹配结果',
  'editor.citation.kb.startSearch': '输入关键词开始搜索',
  'editor.citation.kb.page': '第 {page} 页',
  'editor.citation.kb.insert': '插入引用',
  'editor.citation.kb.insertWithCount': '插入引用 ({count})',
  'editor.citation.kb.searchFailed': '知识库搜索失败，请稍后重试。',
  'editor.citation.source.knowledgeBase': '知识库',
  'editor.citation.source.web': '网页',
  'editor.citation.source.manual': '手动',
  'editor.citation.source.fallback': '引用',
  'editor.citation.popover.jumpToSourceTitle': '跳转到来源文档',
  'editor.citation.popover.viewSource': '查看来源',
  'editor.citation.popover.openUrlTitle': '在浏览器中打开',
  'editor.citation.popover.openLink': '打开链接',
  'editor.citation.popover.editTitle': '编辑引用元数据',
  'editor.citation.popover.edit': '编辑引用',
  'editor.citation.form.webSource': '网页引用',
  'editor.citation.form.manualSource': '手动输入',
  'editor.citation.form.title': '标题',
  'editor.citation.form.titlePlaceholder': '文章或资料的标题',
  'editor.citation.form.authors': '作者',
  'editor.citation.form.authorsPlaceholder': '多个作者用逗号分隔',
  'editor.citation.form.authorsHint': '例如：张三, 李四, 王五',
  'editor.citation.form.year': '年份',
  'editor.citation.form.yearDate': '年份/日期',
  'editor.citation.form.yearPlaceholder': '例如：2024',
  'editor.citation.form.yearDatePlaceholder': '例如：2024 或 2024-01-15',
  'editor.citation.form.datePickerPlaceholder': '选择日期',
  'editor.citation.form.container': '出处',
  'editor.citation.form.containerEdit': '期刊/书名',
  'editor.citation.form.containerPlaceholder': '期刊名、书名或网站名',
  'editor.citation.form.url': '链接',
  'editor.citation.form.urlHint': '可选：用于在引用卡片中“打开链接”（若为空则不显示）。',
  'editor.citation.form.snippet': '引用片段',
  'editor.citation.form.snippetPlaceholder': '可选：引用的具体内容片段',
  'editor.citation.form.snippetEditPlaceholder': '引用的原文内容',
  'editor.citation.form.reset': '重置',
  'editor.citation.form.insert': '插入引用',
  'editor.citation.form.cancel': '取消',
  'editor.citation.form.save': '保存',
  'editor.citation.form.error.titleRequired': '标题不能为空',
  'editor.citation.form.error.urlRequired': 'URL 不能为空',
  'editor.citation.form.error.urlInvalid': 'URL 格式不正确',
  'editor.citation.edit.title': '编辑引用',
  'editor.citation.edit.sameSourceNotice': '本文档中共有 {count} 处引用了该来源，保存后将同步更新标题/作者/日期等基础信息（引用片段仅更新当前引用）。',
  'editor.citation.bibliography.title': '参考文献',
  'editor.citation.bibliography.empty': '暂无引用',
  'editor.citation.bibliography.switchToAuthorDate': '切换为作者-年份格式',
  'editor.citation.bibliography.switchToNumeric': '切换为数字编号格式',
  'editor.citation.bibliography.authorDateLabel': '(作者, 年)',
  'editor.citation.author.othersSuffix': '等',
  'editor.citation.fallback.unknownDocument': '未知文档',
  'editor.citation.fallback.searchFailed': '搜索失败',
  'editor.citation.fallback.projectKbLoadFailed': '获取项目关联 KB 失败（未知错误）',
  'editor.revision.action.accept': '接受',
  'editor.revision.action.reject': '拒绝',
  'editor.revision.action.acceptAll': '接受全部',
  'editor.revision.action.rejectAll': '拒绝全部',
  'editor.revision.toolbar.acceptAllTitle': '接受全部修订 (⌘+Enter)',
  'editor.revision.toolbar.rejectAllTitle': '拒绝全部修订 (Esc)',
  'editor.revision.global.pendingTitle': '待处理修订',
  'editor.revision.global.blockCount': '{count} 个块',
  'editor.revision.global.projectionDeferred': '行内预览已暂缓',
  'editor.revision.error.reloadRequired': '修订已在后台完成，但编辑器无法安全加载结果。当前内容已保留，请重新打开文档同步。',
  'editor.revision.indicator.label': '修订',
  'editor.revision.indicator.pending': '待处理',
  'editor.revision.indicator.statsSeparator': '，',
  'editor.revision.indicator.insertStat': '{count} 处新增',
  'editor.revision.indicator.deleteStat': '{count} 处删除',
  'editor.revision.indicator.pendingTitle': '待处理修订',
  'editor.revision.indicator.pendingTitleWithStats': '待处理修订：{stats}',
  'editor.revision.indicator.pendingTitleDeferred': '待处理修订：尚未投影详细差异',
  'editor.revision.indicator.appliedTitle': '已接受修订：{stats}',
  'editor.revision.indicator.discardedTitle': '已拒绝修订：{stats}',
  'editor.revision.mark.acceptInsert': '接受新增内容',
  'editor.revision.mark.acceptDelete': '接受删除（移除此文字）',
  'editor.revision.mark.rejectInsert': '拒绝新增（移除此文字）',
  'editor.revision.mark.rejectDelete': '拒绝删除（保留此文字）',
  'editor.revision.time.yesterday': '昨天',
  'editor.review.agent.logicCheck.name': '逻辑检查',
  'editor.review.agent.structure.name': '结构梳理',
  'editor.review.agent.polish.name': '文本润色',
  'editor.review.setup.title': '审阅当前文档',
  'editor.review.setup.subtitle': '配置审阅角色、背景与目标',
  'editor.review.setup.historyEntry': '已有审阅 ({count})',
  'editor.review.setup.selectedAgents': '已选角色 ({count}/3)',
  'editor.review.setup.knowledgeBadge': '背景知识',
  'editor.review.setup.editAgent': '编辑',
  'editor.review.setup.removeAgent': '移除',
  'editor.review.setup.addAgentPlaceholder': '添加审阅角色...',
  'editor.review.setup.systemAgentsGroup': '系统角色',
  'editor.review.setup.customAgentsGroup': '自定义角色',
  'editor.review.setup.createCustomAgent': '新建自定义角色...',
  'editor.review.setup.backgroundLabel': '审阅背景',
  'editor.review.setup.backgroundPlaceholder': '例如：你是[角色]，你的任务是审查[目标]，请重点关注[关注点]，忽略[忽略项]。',
  'editor.review.setup.goalLabel': '审阅目标',
  'editor.review.setup.goalPlaceholder': '例如：找出逻辑漏洞、梳理结构层次...',
  'editor.review.setup.start': '开始审阅',
  'editor.review.agentCreator.createTitle': '新建审阅角色',
  'editor.review.agentCreator.editTitle': '编辑审阅角色',
  'editor.review.agentCreator.back': '返回',
  'editor.review.agentCreator.nameLabel': '角色名称',
  'editor.review.agentCreator.namePlaceholder': '例如：风控',
  'editor.review.agentCreator.promptLabel': '系统提示词',
  'editor.review.agentCreator.promptPlaceholder': '你是一个专业的审阅助手，请关注...',
  'editor.review.agentCreator.knowledgeLabel': '背景知识',
  'editor.review.agentCreator.knowledgePlaceholder': '在此输入该角色需要的背景知识，最多1500字/词',
  'editor.review.agentCreator.save': '保存',
  'editor.review.processing.title': 'AI 正在阅读文档...',
  'editor.review.processing.preparing': '准备开始审阅...',
  'editor.review.processing.reviewingChunk': '正在审阅第 {current}/{total} 部分...',
  'editor.review.processing.completed': '审阅完成',
  'editor.review.processing.failed': '审阅失败，请稍后重试。',
  'editor.review.dashboard.title': '审阅结果',
  'editor.review.dashboard.newReview': '新审阅',
  'editor.review.dashboard.filterAriaLabel': '审阅角色筛选',
  'editor.review.dashboard.all': '全部',
  'editor.review.dashboard.emptyTitle': '暂无待处理建议',
  'editor.review.dashboard.emptySubtitle': '你可以点击“新审阅”调整维度或补充背景/目标后再试。',
  'editor.review.message.delete': '删除',
  'editor.review.message.yesterday': '昨天',
} as const satisfies Readonly<Record<EditorMessageKey, string>>;

export const EDITOR_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'editor',
  catalogs: {
    'zh-CN': EDITOR_MESSAGE_FALLBACKS,
    'en-US': {
      'editor.common.moreActions': 'More actions',
      'editor.common.unavailableInTable': 'Unavailable in tables',
      'editor.common.unknownError': 'Unknown error',
      'editor.shortcuts.save.noOpenFile': 'No file is open, so nothing can be saved',
      'editor.shortcuts.save.saving': 'Saving. Please wait...',
      'editor.shortcuts.save.unexpectedError': 'Unexpected error while saving. Please try again.',
      'editor.menu.headingLevel': 'Heading level',
      'editor.menu.bold': 'Bold',
      'editor.menu.italic': 'Italic',
      'editor.menu.bulletList': 'Bulleted list',
      'editor.menu.orderedList': 'Numbered list',
      'editor.menu.quoteBlock': 'Quote block',
      'editor.menu.insertImage': 'Insert image',
      'editor.menu.insertTable': 'Insert table',
      'editor.menu.insertAudio': 'Insert recording',
      'editor.menu.debug': 'Debug',
      'editor.menu.viewLatestProviderOutboundAttempt': 'View latest Provider request',
      'editor.menu.heading.level1': 'Heading 1',
      'editor.menu.heading.level2': 'Heading 2',
      'editor.menu.heading.level3': 'Heading 3',
      'editor.menu.heading.level4': 'Heading 4',
      'editor.menu.heading.level5': 'Heading 5',
      'editor.menu.heading.level6': 'Heading 6',
      'editor.menu.error.headingUnavailable': 'Heading switching is temporarily unavailable.',
      'editor.menu.error.quoteUnavailable': 'Quote block switching is temporarily unavailable.',
      'editor.menu.toast.imageInserted': 'Image inserted: {fileName}',
      'editor.menu.toast.editorNotReady': 'Cannot insert image: the editor is not ready.',
      'editor.menu.toast.imageLoadFailed': 'Unable to load the image. Make sure the file is still accessible.',
      'editor.menu.toast.imageFlowFailed': 'Image insertion failed. Please try again.',
      'editor.menu.toast.imageDialogUnavailable': 'Unable to open the image picker. System features are not initialized.',
      'editor.slash.empty': 'No matching results',
      'editor.slash.group.convertTo': 'Convert to',
      'editor.slash.group.insert': 'Insert',
      'editor.slash.group.ai': 'AI',
      'editor.slash.item.heading1': 'Heading 1',
      'editor.slash.item.heading2': 'Heading 2',
      'editor.slash.item.bulletList': 'Bulleted list',
      'editor.slash.item.orderedList': 'Numbered list',
      'editor.slash.item.quoteBlock': 'Quote block',
      'editor.slash.item.audioBlock': 'Audio block',
      'editor.slash.item.codeBlock': 'Code block',
      'editor.slash.item.latexBlock': 'LaTeX formula',
      'editor.slash.item.horizontalRule': 'Horizontal rule',
      'editor.slash.item.tableBlock': 'Table block',
      'editor.slash.item.imageBlock': 'Image block',
      'editor.slash.item.aiWriting': 'AI writing',
      'editor.slash.item.citation': 'Citation',
      'editor.slash.toast.imageDialogUnavailable': 'Unable to open the image picker. System features are not initialized.',
      'editor.slash.toast.imageLoadFailed': 'Unable to load the image. Make sure the file is still accessible.',
      'editor.slash.toast.imageInserted': 'Image inserted: {fileName}',
      'editor.slash.toast.imageFlowFailed': 'Image insertion failed. Please try again.',
      'editor.findReplace.title': 'Find and replace',
      'editor.findReplace.searchPlaceholder': 'Find',
      'editor.findReplace.replacePlaceholder': 'Replace with',
      'editor.findReplace.previous': 'Previous',
      'editor.findReplace.next': 'Next',
      'editor.findReplace.replaceCurrent': 'Replace current match',
      'editor.findReplace.replaceAll': 'Replace all matches',
      'editor.findReplace.matchCase': 'Match case',
      'editor.findReplace.wholeWord': 'Whole word',
      'editor.findReplace.regex': 'Regular expression',
      'editor.findReplace.noMatches': 'No matches found',
      'editor.outline.togglePinned': 'Outline pinned. Click to unpin.',
      'editor.outline.togglePreview': 'Hover to show outline. Click to pin.',
      'editor.outline.emptyHeading': 'Empty heading',
      'editor.blockMenu.duplicate': 'Duplicate',
      'editor.blockMenu.color': 'Color',
      'editor.blockMenu.delete': 'Delete',
      'editor.blockMenu.addAnnotation': 'Add annotation',
      'editor.blockMenu.createVersion': 'Create as new version',
      'editor.blockMenu.viewHistory': 'View version history',
      'editor.blockMenu.color.background': 'Background color',
      'editor.blockMenu.color.text': 'Text color',
      'editor.blockMenu.color.clear': 'Clear color',
      'editor.blockMenu.toast.noDocumentForHistory': 'No current document, so history cannot be opened',
      'editor.blockMenu.toast.noBlockForHistory': 'No block ID found, so history cannot be opened',
      'editor.blockMenu.toast.loadedHistoryVersions': 'Loaded {count} history versions',
      'editor.blockMenu.toast.loadHistoryFailed': 'Failed to load history versions',
      'editor.blockMenu.toast.noDocumentForCreateVersion': 'No current document, so a version cannot be created',
      'editor.blockMenu.toast.noBlockForCreateVersion': 'No block ID found, so a version cannot be created',
      'editor.blockMenu.toast.noBlockTypeForCreateVersion': 'No block type found, so a version cannot be created',
      'editor.blockMenu.toast.createVersionFailed': 'Failed to create block version',
      'editor.blockMenu.toast.createVersionSuccess': 'Created version v{version} for this block',
      'editor.blockMenu.toast.createVersionException': 'An error occurred while creating the block version',
      'editor.floatingToolbar.aiReference': 'AI reference',
      'editor.floatingToolbar.bold': 'Bold',
      'editor.floatingToolbar.italic': 'Italic',
      'editor.floatingToolbar.strikethrough': 'Strikethrough',
      'editor.floatingToolbar.textColor': 'Text color',
      'editor.floatingToolbar.textHighlight': 'Text highlight',
      'editor.floatingToolbar.heading': 'Heading',
      'editor.floatingToolbar.headingWithLevel': 'Heading {level}',
      'editor.floatingToolbar.heading.level1': 'Heading 1',
      'editor.floatingToolbar.heading.level2': 'Heading 2',
      'editor.floatingToolbar.heading.level3': 'Heading 3',
      'editor.floatingToolbar.heading.level4': 'Heading 4',
      'editor.floatingToolbar.heading.level5': 'Heading 5',
      'editor.floatingToolbar.heading.level6': 'Heading 6',
      'editor.floatingToolbar.paragraph': 'Text',
      'editor.floatingToolbar.colorPanel': 'Color panel',
      'editor.floatingToolbar.highlightPanel': 'Highlight panel',
      'editor.floatingToolbar.clearColor': 'Clear color',
      'editor.floatingToolbar.clearHighlight': 'Clear highlight',
      'editor.floatingToolbar.quoteLabel': 'Quoted content',
      'editor.floatingToolbar.toast.noSelection': 'Select text in the document before adding it as a reference',
      'editor.floatingToolbar.toast.emptySelection': 'The selected content is empty and cannot be added as a reference',
      'editor.floatingToolbar.toast.addedReference': 'Current selection added to AI references',
      'editor.color.red': 'Red',
      'editor.color.crimson': 'Crimson',
      'editor.color.pink': 'Pink',
      'editor.color.purple': 'Purple',
      'editor.color.indigo': 'Indigo',
      'editor.color.blue': 'Blue',
      'editor.color.teal': 'Teal',
      'editor.color.mint': 'Mint',
      'editor.color.green': 'Green',
      'editor.color.lime': 'Lime',
      'editor.color.yellow': 'Yellow',
      'editor.color.orange': 'Orange',
      'editor.color.brown': 'Brown',
      'editor.color.slate': 'Slate gray',
      'editor.color.gray': 'Gray',
      'editor.color.brightYellow': 'Bright yellow',
      'editor.color.brightPink': 'Bright pink',
      'editor.color.brightGreen': 'Bright green',
      'editor.color.brightOrange': 'Bright orange',
      'editor.color.brightBlue': 'Bright blue',
      'editor.codeBlock.language.select': 'Select language',
      'editor.codeBlock.language.plainText': 'Plain text',
      'editor.codeBlock.action.copy': 'Copy code',
      'editor.codeBlock.action.copied': 'Copied!',
      'editor.imageBlock.action.more': 'More actions',
      'editor.imageBlock.action.preview': 'Preview image',
      'editor.imageBlock.action.resize': 'Resize image',
      'editor.imageBlock.align.left': 'Align left',
      'editor.imageBlock.align.center': 'Align center',
      'editor.imageBlock.align.right': 'Align right',
      'editor.imageBlock.resize.width': 'Width (px):',
      'editor.imageBlock.resize.height': 'Height (px):',
      'editor.imageBlock.resize.confirm': 'OK',
      'editor.imageBlock.resize.cancel': 'Cancel',
      'editor.imageBlock.property.uploadedAt': 'Uploaded at',
      'editor.imageBlock.property.format': 'Format',
      'editor.imageBlock.property.dimensions': 'Dimensions',
      'editor.imageBlock.property.size': 'Size',
      'editor.imageBlock.property.panelTitle': 'Properties',
      'editor.imageBlock.value.unknown': 'Unknown',
      'editor.imageBlock.value.originalSize': 'Original size',
      'editor.imageBlock.value.widthOnly': '{width}px (width)',
      'editor.imageBlock.value.heightOnly': '{height}px (height)',
      'editor.imageBlock.empty': 'No image',
      'editor.imageBlock.missing': 'Image unavailable or source file missing',
      'editor.latexBlock.inline.invalidSource': 'Invalid LaTeX source',
      'editor.latexBlock.input.placeholder': 'Enter LaTeX formula...\n(Enter to confirm, Shift+Enter for newline, Esc to cancel)',
      'editor.latexBlock.input.confirm': 'OK',
      'editor.latexBlock.input.cancel': 'Cancel',
      'editor.latexBlock.input.invalidFormula': 'Invalid LaTeX formula',
      'editor.latexBlock.placeholder': 'Add LaTeX formula...',
      'editor.latexBlock.renderError': 'Render error',
      'editor.latexBlock.symbolCategory.math': 'Math',
      'editor.latexBlock.symbolCategory.physics': 'Physics',
      'editor.latexBlock.symbolCategory.chemistry': 'Chemistry',
      'editor.latexBlock.symbolCategory.arrows': 'Arrows',
      'editor.latexBlock.symbolCategory.greekLetters': 'Greek letters',
      'editor.service.loadFileFailed': 'Failed to load file. Please try again.',
      'editor.conversion.inTable.blockType': 'Block type conversion is not available inside tables',
      'editor.conversion.inTable.listItem': 'Converting to a list item is not available inside tables',
      'editor.conversion.inTable.quoteBlock': 'Converting to a quote block is not available inside tables',
      'editor.conversion.inTable.latexBlock': 'Converting to a LaTeX block is not available inside tables',
      'editor.conversion.inTable.audioBlock': 'Converting to a recording block is not available inside tables',
      'editor.command.splitBlock.failed': 'An error occurred while splitting the block',
      'editor.placeholder.baseBlock': 'Start typing...',
      'editor.placeholder.baseBlockAi': 'Type text... Press Space to open AI',
      'editor.placeholder.listItem': 'List item...',
      'editor.placeholder.heading': 'Heading {level}',
      'editor.placeholder.heading.level1': 'Heading 1...',
      'editor.placeholder.heading.level2': 'Heading 2...',
      'editor.placeholder.heading.level3': 'Heading 3...',
      'editor.placeholder.heading.level4': 'Heading 4...',
      'editor.placeholder.heading.level5': 'Heading 5...',
      'editor.placeholder.heading.level6': 'Heading 6...',
      'editor.placeholder.heading.empty': 'Heading {level}...',
      'editor.aiWriting.placeholder': 'AI writing... (Shift+Enter for a new line, press Space to cancel) ',
      'editor.aiWriting.cancel': 'Cancel (Esc)',
      'editor.aiWriting.submit': 'Generate (Enter)',
      'editor.aiWriting.error.streamRequestFailed': 'AI streaming request failed',
      'editor.aiWriting.error.streamEndedAbnormally': 'Stream ended abnormally',
      'editor.aiWriting.error.queueProcessingFailed': 'An unknown error occurred while processing the queue',
      'editor.autocomplete.error.requestFailed': 'Autocomplete request failed',
      'editor.documentSettings.tabTitle': 'Text document',
      'editor.documentSettings.interface.title': 'Text Document Interface',
      'editor.documentSettings.interface.menuBar': 'Show menu bar',
      'editor.documentSettings.interface.menuBarDescription': 'Show formatting, insert, and debugging tools at the top of text documents.',
      'editor.documentSettings.interface.characterCount': 'Show character count',
      'editor.documentSettings.interface.currentCharacterCount': 'Current characters: {count}',
      'editor.documentSettings.interface.characterCountDescription': 'Show the current content character count in the lower-right corner of text documents.',
      'editor.documentSettings.interface.blockHover': 'Block hover interaction',
      'editor.documentSettings.interface.blockHoverDescription': 'When enabled, hovering over editor blocks shows a background highlight.',
      'editor.documentSettings.input.title': 'Input Experience',
      'editor.documentSettings.input.spellcheck': 'Spellcheck',
      'editor.documentSettings.input.spellcheckDescription': 'When enabled, the browser uses native spellcheck for text document input.',
      'editor.documentSettings.ai.title': 'AI Interaction',
      'editor.documentSettings.ai.description': 'Control autocomplete behavior in text documents.',
      'editor.documentSettings.ai.autocomplete': 'Enable autocomplete',
      'editor.documentSettings.ai.intraParagraphCompletion': 'In-paragraph completion',
      'editor.documentSettings.ai.intraParagraphCompletionDescription': 'Allow autocomplete to trigger in the middle of a paragraph.',
      'editor.documentSettings.ai.triggerDelay': 'Completion trigger delay',
      'editor.documentSettings.ai.triggerDelayDescription': 'How long to wait after typing stops before autocomplete triggers.',
      'editor.documentSettings.ai.triggerFrequency': 'Completion trigger frequency',
      'editor.documentSettings.ai.triggerFrequencyDescription': 'Control the time between autocomplete triggers.',
      'editor.documentSettings.ai.completionLength': 'Completion length',
      'editor.documentSettings.ai.completionLengthDescription': 'Control the length of autocomplete suggestions.',
      'editor.documentSettings.ai.scale.slowest': 'Slowest',
      'editor.documentSettings.ai.scale.slower': 'Slower',
      'editor.documentSettings.ai.scale.medium': 'Medium',
      'editor.documentSettings.ai.scale.faster': 'Faster',
      'editor.documentSettings.ai.scale.fastest': 'Fastest',
      'editor.documentSettings.ai.scale.lowest': 'Lowest',
      'editor.documentSettings.ai.scale.lower': 'Lower',
      'editor.documentSettings.ai.scale.higher': 'Higher',
      'editor.documentSettings.ai.scale.highest': 'Highest',
      'editor.documentSettings.ai.scale.always': 'Always',
      'editor.documentSettings.ai.scale.short': 'Short',
      'editor.documentSettings.ai.scale.long': 'Long',
      'editor.documentSettings.ai.scale.unknown': 'Unknown',
      'editor.documentSettings.model.title': 'Model settings',
      'editor.blockHistory.currentVersion': 'Current version v{version}',
      'editor.blockHistory.currentVersionUnsaved': 'Current version (not saved as a version)',
      'editor.blockHistory.noSelectedVersion': 'No version selected',
      'editor.blockHistory.selectedVersionWithTime': 'Version v{version} ({time})',
      'editor.blockHistory.selectedVersion': 'Version v{version}',
      'editor.blockHistory.more.deleteVersion': 'Delete version v{version}',
      'editor.blockHistory.timeline.applyVersion': 'Apply version v{version}',
      'editor.blockHistory.timeline.exit': 'Exit',
      'editor.blockHistory.overlay.versionBadge': 'History version {version}',
      'editor.blockHistory.overlay.restore': 'Restore',
      'editor.blockHistory.overlay.empty': 'This version is empty',
      'editor.blockHistory.overlay.closePreviewShortcut': 'Press Esc to close preview',
      'editor.blockHistory.origin.ai': 'AI generated',
      'editor.blockHistory.origin.manual': 'Manual edit',
      'editor.blockHistory.origin.restore': 'Version restore',
      'editor.blockHistory.time.justNow': 'Just now',
      'editor.blockHistory.time.minutesAgo': '{count} minutes ago',
      'editor.blockHistory.applyDialog.title': 'Apply version',
      'editor.blockHistory.applyDialog.message': 'This block has not been saved as a history version yet.\n\nCreate version and apply: save the current content as a new version, then apply the selected version;\nApply selected version directly: do not save current content, and apply the selected version directly (current changes will be lost).',
      'editor.blockHistory.applyDialog.confirm': 'Create version and apply',
      'editor.blockHistory.applyDialog.cancel': 'Apply selected version directly',
      'editor.blockHistory.deleteDialog.title': 'Delete version',
      'editor.blockHistory.deleteDialog.message': 'Delete this history version? This action cannot be undone.',
      'editor.blockHistory.deleteDialog.messageWithVersion': 'Delete version v{version}? This action cannot be undone.',
      'editor.blockHistory.deleteDialog.confirm': 'Delete',
      'editor.blockHistory.deleteDialog.cancel': 'Cancel',
      'editor.blockVersionHandle.viewHistory': 'View version history',
      'editor.blockVersionHandle.singleVersion': 'View version history (1 version)',
      'editor.blockVersionHandle.multipleVersions': 'View version history ({count} versions, latest v{version})',
      'editor.debugPanel.title': 'Editor debug panel',
      'editor.debugPanel.action.documentStructure': 'View document structure',
      'editor.debugPanel.action.currentNode': 'View current node',
      'editor.debugPanel.action.selectionInfo': 'View selection info',
      'editor.debugPanel.analyzingDocumentStructure': 'Analyzing document structure...',
      'editor.debugPanel.documentStructureLogged': 'Document structure logged to the console',
      'editor.debugPanel.analyzingCurrentNode': 'Analyzing current node...',
      'editor.debugPanel.currentNodeLogged': 'Current node info logged to the console',
      'editor.providerOutboundDebug.title': 'Provider outbound debug',
      'editor.providerOutboundDebug.overviewTab': 'Overview',
      'editor.providerOutboundDebug.snapshotTab': 'Safe snapshot',
      'editor.providerOutboundDebug.loading': 'Loading...',
      'editor.providerOutboundDebug.empty': 'No Provider attempt snapshot',
      'editor.providerOutboundDebug.noData': '// No data',
      'editor.providerOutboundDebug.loadFailed': 'Failed to load Provider attempt snapshot. Check the console logs.',
      'editor.annotation.toast.creating': 'Creating annotation...',
      'editor.annotation.toast.created': 'Annotation created',
      'editor.annotation.error.confirmFailed': 'Failed to confirm annotation',
      'editor.annotation.error.startFailed': 'Unable to start annotation creation',
      'editor.annotation.toast.createFailed': 'Failed to create the annotation. Please try again.',
      'editor.annotation.author.user': 'User',
      'editor.annotation.status.resolved': 'Resolved',
      'editor.annotation.action.ai': 'Invoke AI (Ctrl+Alt+A)',
      'editor.annotation.action.aiAndSave': 'Invoke AI and save (Ctrl+Alt+A)',
      'editor.annotation.action.aiAndCreate': 'Invoke AI and create (Ctrl+Alt+A)',
      'editor.annotation.action.edit': 'Edit annotation',
      'editor.annotation.action.resolve': 'Mark as resolved',
      'editor.annotation.action.resolveAria': 'Mark resolved',
      'editor.annotation.action.reopen': 'Reopen',
      'editor.annotation.action.delete': 'Delete annotation',
      'editor.annotation.action.cancelEdit': 'Cancel editing',
      'editor.annotation.action.cancelCreate': 'Cancel creation',
      'editor.annotation.action.save': 'Save',
      'editor.annotation.action.create': 'Create annotation',
      'editor.annotation.placeholder.edit': 'Edit annotation content...',
      'editor.annotation.placeholder.create': 'Enter annotation content...',
      'editor.annotation.time.yesterday': 'Yesterday',
      'editor.audioBlock.status.checkingDevice': 'Checking recording devices...',
      'editor.audioBlock.status.microphoneConnected': 'Microphone connected',
      'editor.audioBlock.status.defaultMicrophone': 'default microphone',
      'editor.audioBlock.status.systemDefaultRecordingDevice': 'System default recording device',
      'editor.audioBlock.status.usingMicrophone': 'Using {device}',
      'editor.audioBlock.status.usingDefaultMicrophone': 'Using default microphone',
      'editor.audioBlock.status.noMicrophone': 'No available microphone detected',
      'editor.audioBlock.status.deviceDetectionFailed': 'Failed to detect recording devices. Check the device or permissions.',
      'editor.audioBlock.status.unsupportedDeviceDetection': 'This browser does not support recording device detection',
      'editor.audioBlock.status.unsupportedRecording': 'This browser does not support recording',
      'editor.audioBlock.status.microphoneAccessFailed': 'Failed to access the microphone. Check the device or permissions.',
      'editor.audioBlock.status.microphonePermissionDenied': 'Microphone permission was denied, so recording cannot start.',
      'editor.audioBlock.status.microphoneNotFound': 'No available microphone device was found.',
      'editor.audioBlock.status.recording': 'Recording...',
      'editor.audioBlock.status.paused': 'Recording paused.',
      'editor.audioBlock.status.processingAudio': 'Processing audio...',
      'editor.audioBlock.status.ready': 'Ready',
      'editor.audioBlock.status.savingRecording': 'Saving recording file...',
      'editor.audioBlock.status.loadingAudio': 'Loading audio...',
      'editor.audioBlock.status.loadingSavedAudio': 'Loading saved audio...',
      'editor.audioBlock.status.loadFailed': 'Load failed',
      'editor.audioBlock.status.loadFailedWithMessage': 'Failed to load audio. Make sure the file is still accessible.',
      'editor.audioBlock.status.recordingTerminatedNoAudio': 'Recording ended, but no valid audio data is available.',
      'editor.audioBlock.status.initializationFailed': 'Unable to initialize recording.',
      'editor.audioBlock.status.startRecordingFailed': 'Failed to start recording.',
      'editor.audioBlock.status.pauseRecordingFailed': 'Failed to pause recording.',
      'editor.audioBlock.status.resumeRecordingFailed': 'Failed to resume recording.',
      'editor.audioBlock.status.terminateRecordingFailed': 'Failed to stop recording.',
      'editor.audioBlock.status.saveFallback': 'Save failed. This recording is only available in the current session.',
      'editor.audioBlock.status.saveFailedRetryable': 'Save failed. This recording is still available in the current session and can be saved again.',
      'editor.audioBlock.status.saveFailedNoRuntimeAudio': 'Save failed, and the recording data from this session is no longer available.',
      'editor.audioBlock.status.recordingProcessFailed': 'Error while processing the recording. Please try again.',
      'editor.audioBlock.status.recordingError': 'Recording failed. Start a new recording and try again.',
      'editor.audioBlock.status.transcribingAudio': 'Transcribing audio...',
      'editor.audioBlock.status.transcriptionCompletedGenerated': 'Transcription complete. Content generated.',
      'editor.audioBlock.status.transcriptionCompletedEmpty': 'Transcription complete, but no text was returned.',
      'editor.audioBlock.status.playFailed': 'Playback failed. Please try again.',
      'editor.audioBlock.status.audioError': 'Audio playback failed. Make sure the file is still accessible.',
      'editor.audioBlock.status.maxDuration': 'Recordings can be up to 2 hours',
      'editor.audioBlock.render.file': 'Audio file: {src}',
      'editor.audioBlock.render.readyToRecord': 'Ready to record...',
      'editor.audioBlock.missing.source': 'Audio is unavailable or the source file is missing',
      'editor.audioBlock.missing.temporarySource': 'The last recording was not saved, and the temporary audio has expired',
      'editor.audioBlock.missing.saveFailed': 'The last recording was not saved, and the session audio is no longer available',
      'editor.markdownSerializer.imageAlt': 'Image',
      'editor.markdownSerializer.imageDescription': '[Image: {alt}]',
      'editor.markdownSerializer.imageDescriptionWithWidth': '[Image: {alt}, width {width}px]',
      'editor.markdownSerializer.imageDescriptionWithHeight': '[Image: {alt}, height {height}px]',
      'editor.markdownSerializer.imageDescriptionWithSize': '[Image: {alt}, width {width}px, height {height}px]',
      'editor.markdownSerializer.audioFile': 'Audio file',
      'editor.markdownSerializer.emptyAudioBlock': 'Empty audio block',
      'editor.audioBlock.action.startRecording': 'Start recording',
      'editor.audioBlock.action.retryMicrophone': 'Check microphone again',
      'editor.audioBlock.action.retrySaveRecording': 'Retry save',
      'editor.audioBlock.action.notes': 'Notes',
      'editor.audioBlock.action.pause': 'Pause',
      'editor.audioBlock.action.resume': 'Resume',
      'editor.audioBlock.action.finish': 'Finish',
      'editor.audioBlock.action.transcribing': 'Transcribing...',
      'editor.audioBlock.action.transcribed': 'Transcribed',
      'editor.audioBlock.action.transcriptionFailed': 'Transcription failed',
      'editor.audioBlock.action.transcribe': 'Transcribe',
      'editor.audioBlock.action.transcribeAndCreate': 'Transcribe and create',
      'editor.audioBlock.action.showPanel': 'Show content panel',
      'editor.audioBlock.action.hidePanel': 'Hide content panel',
      'editor.audioBlock.action.insertTimestamp': 'Insert timestamp',
      'editor.audioBlock.action.bold': 'Bold (Ctrl+B)',
      'editor.audioBlock.action.italic': 'Italic (Ctrl+I)',
      'editor.audioBlock.action.bulletList': 'Bulleted list',
      'editor.audioBlock.action.heading': 'Heading',
      'editor.audioBlock.panel.notes': 'Notes',
      'editor.audioBlock.panel.transcript': 'Transcript',
      'editor.audioBlock.panel.summary': 'Summary',
      'editor.audioBlock.panel.collapse': 'Collapse content panel',
      'editor.audioBlock.panel.expand': 'Expand content panel',
      'editor.audioBlock.create.group': 'Create',
      'editor.audioBlock.transcript.copyFullText': 'Copy full text',
      'editor.audioBlock.transcript.translateTargetLanguage': 'Target language',
      'editor.audioBlock.transcript.translating': 'Translating',
      'editor.audioBlock.transcript.translateTo': 'Translate to',
      'editor.audioBlock.transcript.retranslateTo': 'Retranslate to',
      'editor.audioBlock.transcript.empty': 'No transcript yet',
      'editor.audioBlock.transcript.placeholder': 'No transcript yet...',
      'editor.audioBlock.transcript.language.english': 'English',
      'editor.audioBlock.transcript.language.japanese': 'Japanese',
      'editor.audioBlock.transcript.language.korean': 'Korean',
      'editor.audioBlock.transcript.language.french': 'French',
      'editor.audioBlock.transcript.language.german': 'German',
      'editor.audioBlock.transcript.language.spanish': 'Spanish',
      'editor.audioBlock.content.createdAt': 'Created {time}',
      'editor.audioBlock.content.editedAt': 'Edited {time}',
      'editor.audioBlock.content.yesterday': 'Yesterday',
      'editor.audioBlock.notes.placeholder': 'Record notes here... Type @time to insert a timestamp',
      'editor.audioBlock.summary.placeholder': 'Record meeting notes here... Type @time to insert a timestamp',
      'editor.audioBlock.toast.transcriptionCompleted': 'Transcription complete.',
      'editor.audioBlock.toast.transcriptionFailedRetry': 'Transcription failed. Try again.',
      'editor.audioBlock.toast.durationUnknownSeek': 'Audio duration is unknown, so seeking is unavailable.',
      'editor.audioBlock.toast.durationUnknownDrag': 'Audio duration is unknown, so dragging is unavailable.',
      'editor.audioBlock.toast.transcriptionInProgress': 'Transcription is in progress. Please wait...',
      'editor.audioBlock.toast.transcribingAudio': 'Transcribing audio. Please wait...',
      'editor.audioBlock.toast.transcriptionFailedWithMessage': 'Transcription failed. Please try again.',
      'editor.audioBlock.toast.transcriptionCompletedFilled': 'Transcription complete. Content was added to the transcript panel.',
      'editor.audioBlock.toast.transcriptionCompletedEmpty': 'Transcription complete, but no text was returned.',
      'editor.audioBlock.toast.copied': 'Copied to clipboard',
      'editor.audioBlock.toast.copyFailed': 'Copy failed',
      'editor.audioBlock.toast.noTranscriptToTranslate': 'There is no transcript to translate',
      'editor.audioBlock.toast.translatingTo': 'Translating to {language}...',
      'editor.audioBlock.toast.translationCompleted': 'Translation complete.',
      'editor.audioBlock.toast.translationFailed': 'Translation failed. Please try again.',
      'editor.audioBlock.toast.generatingSummary': 'Generating summary...',
      'editor.audioBlock.toast.summaryCompleted': 'Summary generated.',
      'editor.audioBlock.toast.generateFailed': 'Generation failed. Please try again.',
      'editor.audioBlock.toast.operationFailed': 'Operation failed. Please try again.',
      'editor.audioBlock.error.missingBlockId': 'Missing blockId, so transcription cannot start',
      'editor.audioBlock.error.noRuntime': 'Unable to read the audio block runtime state',
      'editor.audioBlock.error.transcriptionFailed': 'Transcription failed. Try again later.',
      'editor.audioBlock.error.transcriptionNoContent': 'Transcription failed or returned no content',
      'editor.audioBlock.error.noAudioForTranscription': 'No audio data is available for transcription',
      'editor.audioBlock.error.audioDataReadFailed': 'Failed to read audio data',
      'editor.audioBlock.error.audioDataUrlLoadFailed': 'Failed to load audio Data URL',
      'editor.audioBlock.error.fileTooLarge': 'Audio file is too large ({fileSizeMB}MB). Keep the file under 25MB.',
      'editor.audioBlock.error.apiBaseUrlUnavailable': 'Unable to get the API service address.',
      'editor.audioBlock.error.transcriptionErrorParseFailed': 'Transcription failed and the error details could not be parsed.',
      'editor.audioBlock.error.transcriptionServiceReturnedError': 'The transcription service returned an error.',
      'editor.audioBlock.error.emptyTranscriptForTranslation': 'Transcript content is empty, so it cannot be translated',
      'editor.audioBlock.error.emptyTranscriptForSummary': 'Transcript content is empty, so a summary cannot be generated',
      'editor.audioBlock.error.saveFileFailed': 'Failed to save the recording file',
      'editor.audioBlock.menu.unknown': 'Unknown',
      'editor.audioBlock.menu.createdAt': 'Created at',
      'editor.audioBlock.menu.size': 'Size',
      'editor.audioBlock.menu.unsaved': 'Unsaved',
      'editor.audioBlock.menu.format': 'Format',
      'editor.audioBlock.menu.storageLocation': 'Storage location',
      'editor.audioBlock.menu.openLocation': 'Click to open file location',
      'editor.audioBlock.menu.temporaryFile': 'Temporary file (unsaved)',
      'editor.audioBlock.menu.startTranscription': 'Start transcription',
      'editor.audioBlock.menu.retranscribe': 'Retranscribe',
      'editor.audioBlock.menu.properties': 'Properties',
      'editor.tableBlock.toolbar.aiFillTitle': 'AI batch fill',
      'editor.tableBlock.toolbar.aiFill': 'AI fill',
      'editor.tableBlock.toolbar.insertTitle': 'Insert row or column',
      'editor.tableBlock.toolbar.insert': 'Insert',
      'editor.tableBlock.toolbar.deleteRow': 'Delete row',
      'editor.tableBlock.toolbar.deleteColumn': 'Delete column',
      'editor.tableBlock.toolbar.alignTitle': 'Cell alignment',
      'editor.tableBlock.toolbar.align': 'Align',
      'editor.tableBlock.toolbar.mergeCellsTitle': 'Merge cells',
      'editor.tableBlock.toolbar.merge': 'Merge',
      'editor.tableBlock.toolbar.splitCellTitle': 'Split cell',
      'editor.tableBlock.toolbar.split': 'Split',
      'editor.tableBlock.menu.insertRowBefore': 'Insert row above',
      'editor.tableBlock.menu.insertRowAfter': 'Insert row below',
      'editor.tableBlock.menu.insertColumnBefore': 'Insert column left',
      'editor.tableBlock.menu.insertColumnAfter': 'Insert column right',
      'editor.tableBlock.menu.aiAnalyze': 'AI analyze',
      'editor.tableBlock.menu.alignLeft': 'Align left',
      'editor.tableBlock.menu.alignCenter': 'Align center',
      'editor.tableBlock.menu.alignRight': 'Align right',
      'editor.tableBlock.menu.jsonFormat': 'JSON format',
      'editor.tableBlock.menu.csvFormat': 'CSV format',
      'editor.tableBlock.menu.markdownTable': 'Markdown table',
      'editor.tableBlock.menu.rawData': 'Raw data',
      'editor.tableBlock.context.referenceColumns': 'Reference columns',
      'editor.tableBlock.context.insertReference': 'Insert reference: {reference}',
      'editor.tableBlock.context.selectionRange': 'Selection range',
      'editor.tableBlock.context.selectionRangeTitle': 'Selection range: {range}',
      'editor.tableBlock.context.outputColumn': 'Output column',
      'editor.tableBlock.size.display': '{rows} × {cols} table',
      'editor.tableBlock.size.headerRow': 'Header row',
      'editor.tableBlock.alert.selectCellRange': 'Select a cell range in the table first',
      'editor.tableBlock.alert.aiFillFailed': 'AI fill failed. Please try again.',
      'editor.tableBlock.alert.aiAnalyzeUnavailable': 'AI analysis is not implemented yet',
      'editor.tableBlock.alert.missingSubmitContext': 'Cannot submit the AI request: the editor or table information is missing.',
      'editor.tableBlock.notification.missingTableComponents': 'Table components are missing, so the table cannot be created.',
      'editor.tableBlock.selection.invalidState': 'Invalid editor state',
      'editor.tableBlock.selection.noValidSelection': 'No valid table range is selected',
      'editor.tableBlock.selection.emptySelection': 'The table selection does not contain any cells',
      'editor.tableBlock.selection.infoExtractionFailed': 'Could not extract selection information or its rectangle',
      'editor.tableBlock.selection.metadataProcessingFailed': 'Failed to process selection metadata. Please try again.',
      'editor.tableBlock.selection.invalidArguments': 'Invalid arguments',
      'editor.tableBlock.selection.mapUnavailable': 'Could not get the table map',
      'editor.tableBlock.selection.rectUnavailable': 'Could not calculate the selection rectangle',
      'editor.tableBlock.selection.notInsideTableCell': 'The current selection is not inside a table cell',
      'editor.tableBlock.selection.formattingFailed': 'Formatting failed. Please try again.',
      'editor.citation.panel.title': 'Insert citation',
      'editor.citation.panel.tab.knowledgeBase': 'Knowledge base',
      'editor.citation.panel.tab.webManual': 'Web / manual',
      'editor.citation.inlineTrigger.title': 'Citation',
      'editor.citation.kb.searchScope': 'Search scope',
      'editor.citation.kb.noProjectKnowledgeBases': 'This project is not linked to any knowledge base',
      'editor.citation.kb.searchPlaceholder': 'Search knowledge bases by keyword...',
      'editor.citation.kb.search': 'Search',
      'editor.citation.kb.searching': 'Searching...',
      'editor.citation.kb.noResults': 'No matching results',
      'editor.citation.kb.startSearch': 'Enter keywords to search',
      'editor.citation.kb.page': 'Page {page}',
      'editor.citation.kb.insert': 'Insert citation',
      'editor.citation.kb.insertWithCount': 'Insert citation ({count})',
      'editor.citation.kb.searchFailed': 'Knowledge base search failed. Please try again.',
      'editor.citation.source.knowledgeBase': 'Knowledge base',
      'editor.citation.source.web': 'Web',
      'editor.citation.source.manual': 'Manual',
      'editor.citation.source.fallback': 'Citation',
      'editor.citation.popover.jumpToSourceTitle': 'Jump to source document',
      'editor.citation.popover.viewSource': 'View source',
      'editor.citation.popover.openUrlTitle': 'Open in browser',
      'editor.citation.popover.openLink': 'Open link',
      'editor.citation.popover.editTitle': 'Edit citation metadata',
      'editor.citation.popover.edit': 'Edit citation',
      'editor.citation.form.webSource': 'Web citation',
      'editor.citation.form.manualSource': 'Manual entry',
      'editor.citation.form.title': 'Title',
      'editor.citation.form.titlePlaceholder': 'Title of the article or source',
      'editor.citation.form.authors': 'Authors',
      'editor.citation.form.authorsPlaceholder': 'Separate multiple authors with commas',
      'editor.citation.form.authorsHint': 'Example: Alice Zhang, Bob Li, Carol Wang',
      'editor.citation.form.year': 'Year',
      'editor.citation.form.yearDate': 'Year/date',
      'editor.citation.form.yearPlaceholder': 'Example: 2024',
      'editor.citation.form.yearDatePlaceholder': 'Example: 2024 or 2024-01-15',
      'editor.citation.form.datePickerPlaceholder': 'Choose date',
      'editor.citation.form.container': 'Source',
      'editor.citation.form.containerEdit': 'Journal/book',
      'editor.citation.form.containerPlaceholder': 'Journal, book, or website name',
      'editor.citation.form.url': 'Link',
      'editor.citation.form.urlHint': 'Optional: used to show "Open link" in the citation card.',
      'editor.citation.form.snippet': 'Quoted snippet',
      'editor.citation.form.snippetPlaceholder': 'Optional: the quoted content snippet',
      'editor.citation.form.snippetEditPlaceholder': 'Original quoted content',
      'editor.citation.form.reset': 'Reset',
      'editor.citation.form.insert': 'Insert citation',
      'editor.citation.form.cancel': 'Cancel',
      'editor.citation.form.save': 'Save',
      'editor.citation.form.error.titleRequired': 'Title is required',
      'editor.citation.form.error.urlRequired': 'URL is required',
      'editor.citation.form.error.urlInvalid': 'URL format is invalid',
      'editor.citation.edit.title': 'Edit citation',
      'editor.citation.edit.sameSourceNotice': 'This document cites this source {count} times. Saving will update shared metadata such as title, authors, and date. The quoted snippet is only updated for this citation.',
      'editor.citation.bibliography.title': 'References',
      'editor.citation.bibliography.empty': 'No citations yet',
      'editor.citation.bibliography.switchToAuthorDate': 'Switch to author-date format',
      'editor.citation.bibliography.switchToNumeric': 'Switch to numeric format',
      'editor.citation.bibliography.authorDateLabel': '(Author, year)',
      'editor.citation.author.othersSuffix': 'et al.',
      'editor.citation.fallback.unknownDocument': 'Unknown document',
      'editor.citation.fallback.searchFailed': 'Search failed',
      'editor.citation.fallback.projectKbLoadFailed': 'Failed to load linked KBs for this project (unknown error)',
      'editor.revision.action.accept': 'Accept',
      'editor.revision.action.reject': 'Reject',
      'editor.revision.action.acceptAll': 'Accept all',
      'editor.revision.action.rejectAll': 'Reject all',
      'editor.revision.toolbar.acceptAllTitle': 'Accept all revisions (⌘+Enter)',
      'editor.revision.toolbar.rejectAllTitle': 'Reject all revisions (Esc)',
      'editor.revision.global.pendingTitle': 'Pending revisions',
      'editor.revision.global.blockCount': '{count} blocks',
      'editor.revision.global.projectionDeferred': 'Inline preview deferred',
      'editor.revision.error.reloadRequired': 'The revisions were applied in the background, but the editor could not safely load the result. The current view was preserved; reopen the document to sync.',
      'editor.revision.indicator.label': 'Revision',
      'editor.revision.indicator.pending': 'Pending',
      'editor.revision.indicator.statsSeparator': ', ',
      'editor.revision.indicator.insertStat': '{count} additions',
      'editor.revision.indicator.deleteStat': '{count} deletions',
      'editor.revision.indicator.pendingTitle': 'Pending revisions',
      'editor.revision.indicator.pendingTitleWithStats': 'Pending revisions: {stats}',
      'editor.revision.indicator.pendingTitleDeferred': 'Pending revisions: detailed diff not projected yet',
      'editor.revision.indicator.appliedTitle': 'Accepted revisions: {stats}',
      'editor.revision.indicator.discardedTitle': 'Rejected revisions: {stats}',
      'editor.revision.mark.acceptInsert': 'Accept inserted content',
      'editor.revision.mark.acceptDelete': 'Accept deletion (remove this text)',
      'editor.revision.mark.rejectInsert': 'Reject insertion (remove this text)',
      'editor.revision.mark.rejectDelete': 'Reject deletion (keep this text)',
      'editor.revision.time.yesterday': 'Yesterday',
      'editor.review.agent.logicCheck.name': 'Logic check',
      'editor.review.agent.structure.name': 'Structure review',
      'editor.review.agent.polish.name': 'Text polish',
      'editor.review.setup.title': 'Review current document',
      'editor.review.setup.subtitle': 'Configure reviewers, context, and goals',
      'editor.review.setup.historyEntry': 'Existing reviews ({count})',
      'editor.review.setup.selectedAgents': 'Selected reviewers ({count}/3)',
      'editor.review.setup.knowledgeBadge': 'Background knowledge',
      'editor.review.setup.editAgent': 'Edit',
      'editor.review.setup.removeAgent': 'Remove',
      'editor.review.setup.addAgentPlaceholder': 'Add reviewer...',
      'editor.review.setup.systemAgentsGroup': 'System reviewers',
      'editor.review.setup.customAgentsGroup': 'Custom reviewers',
      'editor.review.setup.createCustomAgent': 'Create custom reviewer...',
      'editor.review.setup.backgroundLabel': 'Review background',
      'editor.review.setup.backgroundPlaceholder': 'Example: You are [role]. Review [target], focus on [focus], and ignore [ignore].',
      'editor.review.setup.goalLabel': 'Review goal',
      'editor.review.setup.goalPlaceholder': 'Example: Find logical gaps, clarify the structure...',
      'editor.review.setup.start': 'Start review',
      'editor.review.agentCreator.createTitle': 'Create reviewer',
      'editor.review.agentCreator.editTitle': 'Edit reviewer',
      'editor.review.agentCreator.back': 'Back',
      'editor.review.agentCreator.nameLabel': 'Reviewer name',
      'editor.review.agentCreator.namePlaceholder': 'Example: Risk control',
      'editor.review.agentCreator.promptLabel': 'System prompt',
      'editor.review.agentCreator.promptPlaceholder': 'You are a professional review assistant. Focus on...',
      'editor.review.agentCreator.knowledgeLabel': 'Background knowledge',
      'editor.review.agentCreator.knowledgePlaceholder': 'Enter background knowledge for this reviewer, up to 1500 Chinese characters or English words.',
      'editor.review.agentCreator.save': 'Save',
      'editor.review.processing.title': 'AI is reading the document...',
      'editor.review.processing.preparing': 'Preparing to start the review...',
      'editor.review.processing.reviewingChunk': 'Reviewing part {current}/{total}...',
      'editor.review.processing.completed': 'Review complete',
      'editor.review.processing.failed': 'Review failed. Please try again.',
      'editor.review.dashboard.title': 'Review results',
      'editor.review.dashboard.newReview': 'New review',
      'editor.review.dashboard.filterAriaLabel': 'Filter by reviewer',
      'editor.review.dashboard.all': 'All',
      'editor.review.dashboard.emptyTitle': 'No pending suggestions',
      'editor.review.dashboard.emptySubtitle': 'Click "New review" to adjust the review dimensions or add more context and goals.',
      'editor.review.message.delete': 'Delete',
      'editor.review.message.yesterday': 'Yesterday',
    },
  },
};
