module.exports = {
  extends: ['stylelint-config-standard'],
  plugins: [
    'stylelint-declaration-strict-value',
    './scripts/stylelint/no-legacy-style-tokens.cjs',
  ],
  defaultSeverity: 'warning',
  ignoreFiles: ['node_modules/**', 'dist/**', 'dist_build/**'],
  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html',
    },
    {
      files: [
        'apps/renderer/app/styles/tokens/base.css',
        'apps/renderer/app/styles/themes/light.css',
        'apps/renderer/app/styles/themes/dark.css',
      ],
      rules: {
        'scale-unlimited/declaration-strict-value': null,
      },
    },
  ],
  rules: {
    'alpha-value-notation': null,
    'at-rule-empty-line-before': null,
    'at-rule-no-unknown': [true, { ignoreAtRules: ['tailwind'] }],
    'color-function-notation': null,
    'color-function-alias-notation': null,
    'color-hex-length': null,
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'custom-property-pattern': null,
    'declaration-property-value-keyword-no-deprecated': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'font-family-name-quotes': null,
    'function-url-quotes': null,
    'import-notation': null,
    'keyframes-name-pattern': null,
    'length-zero-no-unit': null,
    'media-feature-range-notation': null,
    'no-descending-specificity': null,
    'property-no-vendor-prefix': null,
    'rule-empty-line-before': null,
    'selector-class-pattern': null,
    'selector-id-pattern': null,
    'selector-no-vendor-prefix': null,
    'selector-pseudo-class-no-unknown': null,
    'selector-pseudo-element-colon-notation': null,
    'shorthand-property-no-redundant-values': null,
    'value-keyword-case': null,
    'value-no-vendor-prefix': null,
    'linnya/no-legacy-style-tokens': true,
    'scale-unlimited/declaration-strict-value': [
      [
        'color',
        'background-color',
        'border-color',
        'border-top-color',
        'border-right-color',
        'border-bottom-color',
        'border-left-color',
        'outline-color',
        'text-decoration-color',
      ],
      {
        ignoreFunctions: true,
        ignoreValues: {
          '': ['transparent', 'currentColor', 'inherit', 'initial', 'unset', 'none'],
        },
      },
    ],
  },
};
