import type { MessageCatalogContribution } from '@app/localization';
import type { ConversationMessageKey } from './conversationMessages';

export const CONVERSATION_MESSAGE_FALLBACKS = {
  'conversation.view.historyLoading': '正在加载历史对话',
  'conversation.view.empty.title': '开启新对话',
  'conversation.view.empty.description': '输入你的问题，或交给 Linnya 一个任务',
  'conversation.input.placeholder': '输入您的问题...',
  'conversation.input.model.placeholder': '选择模型',
  'conversation.input.model.loading': '加载中...',
  'conversation.input.model.unknown': '未知模型',
  'conversation.input.modelGroup.custom': '自定义模型',
  'conversation.input.modelGroup.provider': '模型供应商',
  'conversation.input.modelGroup.current': '当前模型',
  'conversation.input.model.manage': '管理模型…',
  'conversation.input.model.imageUnsupported': '不支持图片',
  'conversation.input.model.unavailable': '当前不可用',
  'conversation.input.reasoning.placeholder': '思考程度',
  'conversation.input.reasoning.off': '关闭',
  'conversation.input.reasoning.minimal': '最低',
  'conversation.input.reasoning.low': '低',
  'conversation.input.reasoning.medium': '中',
  'conversation.input.reasoning.high': '高',
  'conversation.input.reasoning.xhigh': '超高',
  'conversation.contextUsage.title': '上下文用量',
  'conversation.contextUsage.trigger.unavailable': '上下文用量暂不可用',
  'conversation.contextUsage.trigger.available': '上下文已使用 {percentage}，{used} / {budget} Tokens',
  'conversation.contextUsage.summary': '已使用 {percentage}',
  'conversation.contextUsage.total': '{used} / {budget} Tokens',
  'conversation.contextUsage.row.systemPrompt': '系统提示词',
  'conversation.contextUsage.row.conversation': '对话消息',
  'conversation.contextUsage.row.toolDefinitions': '工具定义',
  'conversation.contextUsage.empty.tailUnavailable': '当前只加载了部分历史消息；回到对话尾部后才能确定最近一次上下文用量。',
  'conversation.contextUsage.conversationInfo.createdAt': '创建时间',
  'conversation.contextUsage.conversationInfo.userMessageCount': '用户消息数',
  'conversation.input.actionMenu.open': '添加',
  'conversation.input.actionMenu.attachmentGroup': '添加附件',
  'conversation.input.actionMenu.agentGroup': 'Agent',
  'conversation.input.agentChoice.closeCurrent': '关闭当前 Agent',
  'conversation.input.agentChoice.close': '关闭',
  'conversation.input.agentChoice.persistFailed': '无法更新会话 Agent，请重试。',
  'conversation.input.mention.empty': '没有匹配的引用',
  'conversation.input.image.add': '添加图片',
  'conversation.input.image.menuItem': '图片',
  'conversation.input.image.extensionUnsupported': '当前输入模式不支持图片附件。',
  'conversation.input.image.drafts': '待发送图片',
  'conversation.input.image.preview': '预览图片',
  'conversation.input.image.uploading': '上传中',
  'conversation.input.image.remove': '移除图片',
  'conversation.input.image.removeNamed': '移除图片 {name}',
  'conversation.input.image.retry': '重试上传',
  'conversation.input.image.retryNamed': '重试上传图片 {name}',
  'conversation.input.image.drop': '拖放图片到这里',
  'conversation.input.image.dropBlocked': '当前输入模式不能接收图片',
  'conversation.input.image.genericTitle': '图片',
  'conversation.commandApproval.title': '允许执行这条命令吗？',
  'conversation.commandApproval.terminal': '终端',
  'conversation.commandApproval.description': '请确认命令和运行目录。命令会使用当前对话的权限执行。',
  'conversation.commandApproval.command': '命令',
  'conversation.commandApproval.cwd': '运行目录',
  'conversation.commandApproval.processing': '正在保存选择并准备执行...',
  'conversation.commandApproval.queue': '还有 {count} 条命令等待确认',
  'conversation.commandApproval.allowOnce': '允许本次',
  'conversation.commandApproval.allowForConversation': '本对话内允许相同命令',
  'conversation.commandApproval.moreAllowOptions': '更多允许方式',
  'conversation.commandApproval.rememberedPrefix': '本对话将记住的命令',
  'conversation.commandApproval.deny': '拒绝',
  'conversation.commandApproval.reason.permissionElevation': '这条命令需要写入文件。',
  'conversation.commandApproval.reason.delete': '这条命令可能删除文件或目录。',
  'conversation.commandApproval.reason.moveOverwriteRename': '这条命令可能移动、覆盖或重命名文件。',
  'conversation.commandApproval.reason.externalUpload': '这条命令可能向外部位置上传数据。',
  'conversation.commandApproval.reason.downloadAndExecute': '这条命令可能下载并运行内容。',
  'conversation.commandApproval.reason.systemOrDiskImpact': '这条命令可能影响系统或磁盘。',
  'conversation.sidebar.loading': '加载中...',
  'conversation.sidebar.newConversation': '新对话',
  'conversation.sidebar.noConversation': '无对话',
  'conversation.sidebar.empty.noMatch': '没有匹配的对话',
  'conversation.sidebar.empty.noConversations': '暂无对话',
  'conversation.sidebar.untitled': '未命名对话',
  'conversation.sidebar.moreOptions': '更多选项',
  'conversation.sidebar.expand': '展开显示',
  'conversation.sidebar.collapse': '折叠显示',
  'conversation.sidebar.menu.pin': '置顶',
  'conversation.sidebar.menu.unpin': '取消置顶',
  'conversation.sidebar.menu.rename': '重命名',
  'conversation.sidebar.menu.delete': '删除',
  'conversation.sidebar.menu.retryCleanup': '重试清理',
  'conversation.sidebar.renameFailed': '重命名失败，请稍后重试。',
  'conversation.sidebar.delete.title': '删除对话',
  'conversation.sidebar.delete.message': '确定要删除“{title}”吗？此操作无法撤销。',
  'conversation.sidebar.delete.confirm': '删除',
  'conversation.sidebar.delete.cancel': '取消',
  'conversation.sidebar.deleting': '正在删除…',
  'conversation.sidebar.cleanupPending': '清理未完成',
  'conversation.sidebar.cleanupRetry.title': '重试清理',
  'conversation.sidebar.cleanupRetry.message': '上次清理“{title}”时没有完成。重试会继续原来的清理操作。',
  'conversation.sidebar.cleanupRetry.confirm': '重试',
  'conversation.sidebar.cleanupRetry.success': '清理已完成：{title}',
  'conversation.sidebar.deleteSuccess': '已删除对话：{title}',
  'conversation.sidebar.deleteFailed': '删除失败，请稍后重试。',
  'conversation.sidebar.loadFailed': '加载对话失败，请稍后重试。',
  'conversation.sidebar.renameFailedGeneric': '重命名失败，请稍后重试。',
  'conversation.sidebar.deleteFailedGeneric': '删除失败，请稍后重试。',
  'conversation.sidebar.batchDelete.title': '批量删除对话',
  'conversation.sidebar.batchDelete.message': '确定要删除选中的 {count} 个对话吗？此操作无法撤销。',
  'conversation.sidebar.batchDelete.success': '已删除 {count} 个对话',
  'conversation.sidebar.batchDelete.partial': '已删除 {successCount} 个对话，{failCount} 个删除失败',
  'conversation.history.group.recent': '最近对话',
  'conversation.history.loading': '加载中...',
  'conversation.history.empty': '暂无对话历史',
  'conversation.history.viewAll': '全部历史对话...',
  'conversation.timeline.loadFailed': '时间轴加载失败，请稍后重试。',
  'conversation.error.title': '错误',
  'conversation.error.close': '关闭',
  'conversation.error.regenerateNoConversation': '没有可重新生成的对话',
  'conversation.error.regenerateMessageNotFound': '未找到要重新生成的用户消息',
  'conversation.error.generic': '发生错误，请稍后重试。',
  'conversation.error.rateLimit': '请求过于频繁（触发限流），请稍后再试。若频繁出现，可尝试切换模型或降低请求频率。',
  'conversation.error.providerLimit': '模型服务返回 429，可能是额度已用尽或请求过于频繁。请稍后重试，或切换模型。',
  'conversation.error.serviceUnavailable': '服务暂时不可用，请稍后再试。',
  'conversation.error.badRequest': '请求参数错误，请检查输入或重试。',
  'conversation.error.auth': '权限校验失败，请检查模型配置或登录状态。',
  'conversation.error.requestFailed': '请求失败，请稍后重试。',
  'conversation.error.quotaExceeded': '该模型到额度上限啦，明天再来或者换其他模型试试吧～',
  'conversation.error.http502': '上游服务暂时不可用（502），请稍后重试。',
  'conversation.error.http503': '服务暂时不可用（503），请稍后重试。',
  'conversation.error.http504': '请求超时（504），请稍后重试。',
  'conversation.error.providerUnavailable': '模型服务当前拥堵（Overloaded），请稍后重试。若持续出现，可尝试切换模型或降低并发。',
  'conversation.error.thinkingProtocolMismatch': '模型开启了“思考(Thinking)”模式，但本轮消息格式不符合供应商要求，导致请求被拒绝。请尝试切换非 Thinking 模型，或关闭 Thinking 后重试。',
  'conversation.error.outputLimitReached': '模型输出达到当前上限，本次回答未完成。请继续任务或改用输出容量更大的模型。',
  'conversation.error.contentFiltered': '模型服务因内容过滤中止了本次回答。请调整请求后重试。',
  'conversation.error.imageModelUnsupported': '当前模型不支持图片识别，请切换到支持图片的模型。',
  'conversation.error.imageModelUnsupportedWithAlternatives': '当前模型不支持图片识别，可切换到：{models}。',
  'conversation.error.imagePlacementUnsupported': '当前模型的连接方式暂不支持此处的图片输入，请切换模型或连接方式。',
  'conversation.error.imagePlacementUnsupportedWithAlternatives': '当前模型的连接方式暂不支持此处的图片输入，可切换到：{models}。',
  'conversation.error.userImagePlacementUnsupported': '当前模型的连接方式不支持用户发送的图片，请切换模型或连接方式。',
  'conversation.error.userImagePlacementUnsupportedWithAlternatives': '当前模型的连接方式不支持用户发送的图片，可切换到：{models}。',
  'conversation.error.toolResultImagePlacementUnsupported': '当前模型的连接方式不支持工具返回的图片；图片结果仍会保留在对话中。',
  'conversation.error.toolResultImagePlacementUnsupportedWithAlternatives': '当前模型的连接方式不支持工具返回的图片，可切换到：{models}；图片结果仍会保留在对话中。',
  'conversation.error.imageMaterializationPending': '图片尚未准备好发送，请稍后重试。',
  'conversation.error.imageAttachmentUnavailable': '图片文件已不可用，请重新添加或移除后再发送。',
  'conversation.error.imageAttachmentIntegrityFailed': '图片文件已损坏或发生变化，请重新添加后再发送。',
  'conversation.error.imageRouteLimitExceeded': '当前模型连接无法接收这么多或这么大的图片，请移除部分图片或切换连接。',
  'conversation.error.imageMappingUnsupported': '当前模型连接暂时无法正确发送图片，请切换模型或连接方式。',
  'conversation.error.imageContextBudgetExceeded': '这些图片超出了当前会话的上下文容量，请移除旧图片、切换更大上下文模型或新建会话。',
  'conversation.error.imageUploadInvalidRequest': '图片上传请求无效，请重新选择图片。',
  'conversation.error.imageTooLarge': '图片文件过大，请选择不超过 10 MB 的图片。',
  'conversation.error.imageUnsupportedFormat': '仅支持 JPEG、PNG 和 WebP 图片。',
  'conversation.error.imageInvalid': '无法读取这张图片，请选择有效的图片文件。',
  'conversation.error.imagePixelLimitExceeded': '图片尺寸过大，请缩小后重新添加。',
  'conversation.error.imageInvalidFileName': '图片文件名无效，请重命名后重新添加。',
  'conversation.error.imageStagingFailed': '图片暂时无法添加，请稍后重试。',
  'conversation.error.imageDraftUnavailable': '图片草稿已失效，请重新添加。',
  'conversation.error.imageTooManyAttachments': '单条消息最多添加 100 张图片。',
  'conversation.error.imageTotalBytesExceeded': '图片总大小超过限制，请移除部分图片。',
  'conversation.error.imagePreviewUnavailable': '图片暂时无法预览。',
  'conversation.error.imagePreviewIntegrityFailed': '图片已损坏或发生变化，无法预览。',
  'conversation.error.imagePreviewFailed': '图片预览加载失败，请稍后重试。',
  'conversation.userMessage.action.edit': '编辑',
  'conversation.userMessage.action.regenerate': '重新生成',
  'conversation.userMessage.action.copy': '复制',
  'conversation.userMessage.action.copied': '已复制',
  'conversation.userMessage.action.cancel': '取消 (Esc)',
  'conversation.userMessage.action.save': '保存 (Enter)',
  'conversation.userMessage.quoteLabel': '引用内容',
  'conversation.userMessage.image.gallery': '消息图片',
  'conversation.userMessage.image.edit': '编辑消息图片',
  'conversation.userMessage.image.loading': '正在加载图片',
  'conversation.userMessage.image.moveLeft': '向左移动图片',
  'conversation.userMessage.image.moveRight': '向右移动图片',
  'conversation.userMessage.image.previewNamed': '预览图片 {name}',
  'conversation.userMessage.image.retryNamed': '重新加载图片 {name}',
  'conversation.userMessage.image.unnamed': '图片',
  'conversation.thought.running': '正在思考',
  'conversation.thought.completed': '已思考{duration}',
  'conversation.thought.duration.seconds': '{seconds}秒',
  'conversation.thought.duration.minutesSeconds': '{minutes}分钟{seconds}秒',
  'conversation.turn.workDuration': '已工作 {duration}',
  'conversation.turn.action.saveAsDocument': '另存为文档',
  'conversation.turn.action.copyAnswer': '复制本轮回答',
  'conversation.turn.action.copied': '已复制',
  'conversation.turn.saveAsDocument.failed': '另存为文档失败',
  'conversation.turn.saveAsDocument.defaultTitle': 'Deep Research 报告 - {date} {time}',
  'conversation.turn.export.noContent': '没有可导出的内容',
  'conversation.turn.export.renderedHtmlMissing': '无法提取渲染 HTML',
  'conversation.turn.export.copyFailed': '复制失败，请稍后重试。',
  'conversation.turn.copy.noContent': '没有可复制的内容',
  'conversation.turn.saveStatus.saved': '已保存',
  'conversation.turn.saveStatus.saving': '保存中...',
  'conversation.turn.saveStatus.empty': '内容为空',
  'conversation.turn.saveStatus.failed': '保存失败',
  'conversation.card.windowHint': '已隐藏更早的 {count} 条消息（避免渲染卡顿）',
  'conversation.card.showAll': '显示全部',
  'conversation.card.action.copyAnswer': '复制本卡片回答',
  'conversation.card.fallbackRun': '运行',
  'conversation.quote.label': '引用内容',
  'conversation.quote.clear': '清空引用',
  'conversation.quote.remove': '移除引用',
  'conversation.flow.missingProjectForSend': '当前版本会话必须依附项目：缺少 projectId，已中止发送。',
  'conversation.flow.missingProjectForRun': '当前版本会话必须依附项目：缺少 projectId，已中止运行。',
  'conversation.flow.pluginRun.missingProject': '无法启动 AI 运行：当前未绑定项目（缺少 projectId）。',
  'conversation.flow.pluginRun.agentChoiceUnavailable': '当前会话 Agent 未注册或未启用: {agentChoiceId}',
  'conversation.flow.pluginRun.noConversation': '无法启动 AI 运行：当前没有可用对话。',
  'conversation.flow.pluginRun.executionFailed': 'AI 运行失败，请稍后重试。',
  'conversation.flow.subrun.missingProject': '无法发起子运行：当前未绑定项目。',
  'conversation.flow.subrun.noConversation': '无法发起子运行：当前没有可用对话。',
  'conversation.flow.subrun.executionFailed': '子运行执行失败，请稍后重试。',
  'conversation.flow.deepResearch.resetFallback': '下周一 00:00',
  'conversation.flow.deepResearch.weeklyLimitReached': '本周 Deep Research 已达上限（{usedCount}/{limit}）。\n恢复时间：{resetText}',
  'conversation.flow.chatInvocationFailed': '发送消息失败，请稍后重试。',
  'conversation.flow.taskInvocationFailed': '任务执行失败，请稍后重试。',
  'conversation.flow.conversationExecutionFailed': 'Conversation 执行失败',
  'conversation.flow.agentExecutionFailed': 'Agent 执行失败',
  'conversation.flow.streamFailed': 'AI 响应中断，请稍后重试。',
  'conversation.flow.continueFailed': '继续 AI 执行失败，请稍后重试。',
  'conversation.flow.resumeFailed': '恢复 Agent 执行失败，请稍后重试。',
  'conversation.tool.error.title': '{toolName} · 执行失败',
  'conversation.tool.error.fallbackTitle': '执行失败',
  'conversation.tool.error.unknown': '未知错误',
  'conversation.tool.error.imageModelNotConfigured': '尚未配置图片生成模型。',
  'conversation.tool.error.configureImageModel': '去配置',
  'conversation.tool.error.openDocumentFailed': '打开文件失败，请稍后重试。',
  'conversation.tool.error.openDocumentFailedGeneric': '打开文件失败，请稍后重试。',
  'conversation.tool.command.running': '正在运行命令',
  'conversation.tool.command.completed': '命令已结束',
  'conversation.tool.command.rejected': '命令未执行',
  'conversation.tool.command.failed': '命令执行失败',
  'conversation.tool.command.shellRunning': '正在运行 {command}',
  'conversation.tool.command.shellCompleted': '已运行 {command}',
  'conversation.tool.command.shellRejected': '未运行 {command}',
  'conversation.tool.command.shellFailed': '运行失败 {command}',
  'conversation.tool.command.terminal': '终端输出',
  'conversation.tool.command.omittedLines': '已省略前面的 {count} 行',
  'conversation.tool.command.outputIncomplete': '完整输出不完整',
  'conversation.tool.command.outputIncomplete.retainedWindowOmitted': '较早输出已超出当前保留窗口',
  'conversation.tool.command.outputIncomplete.textProjectionFailed': '部分输出无法转换为安全文本',
  'conversation.tool.command.auditIncomplete': '审计记录不完整',
  'conversation.tool.command.copy': '复制命令和输出',
  'conversation.tool.command.starting': '正在启动...',
  'conversation.tool.command.processAction': '进程操作：{action}',
  'conversation.tool.command.compact.shell': '运行命令“{command}”',
  'conversation.tool.command.compact.process.poll': '查看命令输出',
  'conversation.tool.command.compact.process.wait': '等待命令完成',
  'conversation.tool.command.compact.process.cancel': '终止命令',
  'conversation.tool.command.compact.process.write': '向命令输入内容',
  'conversation.tool.command.compact.process.submit': '向命令输入内容',
  'conversation.tool.command.compact.process.eof': '结束命令输入',
  'conversation.tool.command.compact.process.resize': '调整终端大小',
  'conversation.tool.command.state.starting': '正在启动',
  'conversation.tool.command.state.running': '运行中',
  'conversation.tool.command.state.completed': '已结束',
  'conversation.tool.command.state.rejected': '未执行',
  'conversation.tool.command.state.failed': '执行失败',
  'conversation.tool.command.runtimeFailure': '命令运行环境发生错误',
  'conversation.tool.command.terminated.cancelled': '已取消',
  'conversation.tool.command.cancel': '取消命令',
  'conversation.tool.command.protectedInput.open': '保护输入',
  'conversation.tool.command.protectedInput.title': '向命令发送保护输入',
  'conversation.tool.command.protectedInput.description': '输入会直接发送到当前交互命令，不会加入对话或提供给 Agent。',
  'conversation.tool.command.protectedInput.label': '密码、验证码或口令',
  'conversation.tool.command.protectedInput.boundary': '目标命令仍可能自行回显、保存或发送这些内容。',
  'conversation.tool.command.protectedInput.cancel': '取消',
  'conversation.tool.command.protectedInput.send': '发送',
  'conversation.tool.command.protectedInput.sending': '正在发送...',
  'conversation.tool.command.protectedInput.unavailable': '当前交互命令已结束或输入入口已失效。',
  'conversation.tool.command.protectedInput.failed': '保护输入发送失败，请确认命令仍在等待输入后重试。',
  'conversation.tool.command.settlementSaveFailed': '命令已结束，但状态保存失败。',
  'conversation.tool.command.controlUnavailable': '无法读取当前命令状态。',
  'conversation.tool.command.cancelFailed': '取消命令失败，请重试。',
  'conversation.tool.command.terminated.timed_out': '已超时',
  'conversation.tool.command.terminated.owner_ended': '会话运行已结束',
  'conversation.tool.command.actionRejected': '进程操作 {action} 未被接受',
  'conversation.tool.raw.loading': '正在处理...',
  'conversation.tool.raw.empty': '无内容',
  'conversation.tool.raw.loadFailed': '加载失败，请稍后重试。',
  'conversation.tool.registry.knowledgeSearching': '正在搜索知识库...',
  'conversation.tool.deepResearch.writeReport': '撰写研究报告',
  'conversation.tool.markdown.createAnnotations': '创建文档批注',
  'conversation.tool.workspace.files.list': '查看项目文件',
  'conversation.tool.workspace.file.read': '阅读',
  'conversation.tool.workspace.file.readTarget': '阅读 {target}',
  'conversation.tool.workspace.file.target': '{target}',
  'conversation.tool.workspace.file.write': '写入',
  'conversation.tool.workspace.file.writeTarget': '写入 {target}',
  'conversation.tool.workspace.file.create': '新建',
  'conversation.tool.workspace.file.createLoading': '正在创建文件...',
  'conversation.tool.workspace.file.edit': '编辑',
  'conversation.tool.workspace.file.editTarget': '编辑 {target}',
  'conversation.tool.workspace.file.editLoading': '正在编辑文件...',
  'conversation.tool.workspace.search': '搜索',
  'conversation.tool.workspace.searchWithPattern': '搜索 {pattern}',
  'conversation.tool.workspace.compact.read': '读取项目文件',
  'conversation.tool.workspace.compact.write': '写入项目文件',
  'conversation.tool.workspace.compact.edit': '编辑项目文件',
  'conversation.tool.workspace.compact.grep': '搜索项目文件',
  'conversation.tool.workspace.document.list': '查看项目文档',
  'conversation.tool.workspace.document.read': '阅读项目文档',
  'conversation.tool.workspace.document.untitled': '未命名文档',
  'conversation.tool.workspace.document.createdTag': '新建',
  'conversation.tool.workspace.document.createLoading': '正在创建文档...',
  'conversation.tool.workspace.document.createFailed': '创建文档失败',
  'conversation.tool.workspace.document.readLoading': '正在读取 Workspace 文档...',
  'conversation.tool.workspace.document.readFallbackName': 'Workspace 文档',
  'conversation.tool.workspace.document.emptyBlock': '（空块）',
  'conversation.tool.workspace.document.nodeCount': '节点 {count}',
  'conversation.tool.workspace.document.nodeEmpty': '节点 -',
  'conversation.tool.workspace.document.paragraphEmpty': '段落 -',
  'conversation.tool.workspace.document.paragraph': '段落 {index}',
  'conversation.tool.workspace.document.paragraphRange': '段落 {start}–{end}',
  'conversation.tool.workspace.document.readFailed': '读取 Workspace 文档失败',
  'conversation.tool.workspace.reference.label': '引用',
  'conversation.tool.workspace.reference.documentLabel': '文档引用',
  'conversation.tool.workspace.reference.paragraphLabel': '第{index}段',
  'conversation.tool.workspace.reference.locateTitle': '定位到 {ref}',
  'conversation.tool.workspace.reference.noContextDocument': '未找到可用于解析引用的上下文文档',
  'conversation.tool.workspace.reference.missingTarget': '该引用未指定目标文档：请使用 #ref@文档类型:documentId 或 #ref@documentId',
  'conversation.tool.workspace.reference.markdownNotFound': '未找到对应段落引用：可能已删除或属于其他文档',
  'conversation.tool.workspace.reference.ambiguous': '该引用在多个文档中都能匹配：请使用 [#ref@documentId] 指明目标文档',
  'conversation.tool.workspace.reference.editorNotReady': '编辑器尚未就绪，请稍后重试',
  'conversation.tool.workspace.reference.paragraphNotFound': '未找到对应段落，可能已删除或位于其他文档',
  'conversation.tool.workspace.reference.pluginNotFound': '未找到对应文档引用：可能已删除或属于其他文档',
  'conversation.tool.workspace.reference.pluginDisabled': '对应插件未启用，无法定位该文档引用',
  'conversation.tool.workspace.reference.documentNotReady': '文档尚未就绪，请稍后重试',
  'conversation.tool.workspace.reference.targetNotFound': '未找到对应引用目标（可能被折叠或已删除）',
  'conversation.tool.workspace.reference.locateFailed': '定位失败，请稍后重试。',
  'conversation.tool.workspace.reference.locateFailedGeneric': '定位失败，请稍后重试。',
  'conversation.tool.evidence.write': '写入证据库',
  'conversation.tool.evidence.read': '读取证据库',
  'conversation.tool.evidence.assemble': '整理结果',
  'conversation.tool.sharedMemory.list': '查看内部产物',
  'conversation.tool.sharedMemory.read': '读取内部产物',
  'conversation.tool.sharedMemory.readEvidence': '读取证据',
  'conversation.tool.sharedMemory.readCitationSnapshot': '读取引用快照',
  'conversation.tool.sharedMemory.write': '写入内部产物',
  'conversation.tool.taskState.read': '读取 TaskState',
  'conversation.tool.taskState.readMissing': '读取 TaskState · 未创建',
  'conversation.tool.taskState.readVersion': '读取 TaskState · v{version}',
  'conversation.tool.taskState.update': '更新 TaskState',
  'conversation.tool.taskState.updateVersion': '更新 TaskState · v{version}',
  'conversation.tool.taskState.updateVersionPhase': '更新 TaskState · v{version} · {phase}',
  'conversation.tool.todo.empty': '未创建 ToDo',
  'conversation.tool.todo.read': '读取 ToDo',
  'conversation.tool.todo.readCount': '读取 ToDo · {count} 条',
  'conversation.tool.todo.update': '更新 ToDo',
  'conversation.tool.todo.updateCount': '更新 ToDo · {count} 条',
  'conversation.tool.skill.compact': '学习技能',
  'conversation.tool.askQuestions.compact': '向用户提问',
  'conversation.tool.imageGeneration.compact': '生成图片',
  'conversation.tool.subrun.compact': '执行子任务',
  'conversation.tool.subrun.batchCompact': '并行执行子任务',
  'conversation.tool.output.continue': '继续读取工具结果',
  'conversation.tool.deepResearch.scout': '检索',
  'conversation.tool.deepResearch.reasoner': '推理',
  'conversation.tool.deepResearch.challenger': '挑战',
  'conversation.tool.deepResearch.writer': '写作',
  'conversation.tool.deepResearch.running': '正在研究',
  'conversation.tool.deepResearch.completed': '研究过程',
  'conversation.tool.webSearch.loading': '正在搜索...',
  'conversation.tool.webSearch.configTitle': '联网搜索',
  'conversation.tool.webSearch.configTitleWithQuery': '联网搜索："{query}"',
  'conversation.tool.webSearch.compactQuery': '联网搜索“{query}”',
  'conversation.tool.webSearch.failed': '搜索失败',
  'conversation.tool.webSearch.untitled': '无标题',
  'conversation.tool.webSearch.empty': '未找到相关结果',
  'conversation.tool.webRead.loading': '正在读取网页...',
  'conversation.tool.webRead.configTitle': '读取网页',
  'conversation.tool.webRead.configTitleWithTarget': '读取网页：{target}',
  'conversation.tool.webRead.failed': '读取失败',
  'conversation.tool.webRead.untitled': '无标题',
  'conversation.tool.webRead.characterCount': '{count} 字符',
  'conversation.tool.webRead.truncated': '已截断',
  'conversation.tool.webRead.empty': '未获取到网页内容',
  'conversation.tool.knowledgeSearch.relatedDocuments': '发现 {count} 个相关文档',
  'conversation.tool.knowledgeSearch.snapshotPointerWithCount': '结果已写入引用快照库：{count} 条（可按需加载）',
  'conversation.tool.knowledgeSearch.snapshotPointer': '结果已写入引用快照库（可按需加载）',
  'conversation.tool.knowledgeSearch.empty': '没有找到相关结果，请尝试调整搜索词',
  'conversation.tool.knowledgeSearch.loadLoading': '加载中...',
  'conversation.tool.knowledgeSearch.loadDetails': '加载详细结果',
  'conversation.tool.knowledgeSearch.exportLoading': '导出中...',
  'conversation.tool.knowledgeSearch.exportJson': '导出 JSON',
  'conversation.tool.knowledgeSearch.loadFailed': '加载失败，请稍后重试。',
  'conversation.tool.knowledgeSearch.loadFailedGeneric': '加载失败，请稍后重试。',
  'conversation.tool.knowledgeSearch.error': '搜索知识库时发生错误',
  'conversation.tool.knowledgeSearch.noActiveConversationLoad': '当前没有活跃会话，无法加载 Citation Snapshot Bundle',
  'conversation.tool.knowledgeSearch.invalidSnapshotBundle': 'Citation Snapshot Bundle 结构不符合预期',
  'conversation.tool.knowledgeSearch.noActiveConversationExport': '当前没有活跃会话，无法导出 Citation Snapshot Bundle',
  'conversation.tool.knowledgeSearch.unknownDocument': '未知文档',
  'conversation.tool.knowledgeSearch.scopeDocument': '在文档「{docName}」中',
  'conversation.tool.knowledgeSearch.scopeKnowledgeBase': '在知识库中',
  'conversation.tool.knowledgeSearch.actionDeepSearch': '深度搜索',
  'conversation.tool.knowledgeSearch.actionSearch': '搜索',
  'conversation.tool.knowledgeSearch.configListTitle': '查看知识库',
  'conversation.tool.knowledgeSearch.configSearchTitle': '搜索知识库',
  'conversation.tool.knowledgeSearch.configSearchInDocument': '搜索知识库：在「{docName}」中搜索',
  'conversation.tool.knowledgeSearch.configSearchKeyword': '搜索知识库：关键词"{query}"',
  'conversation.tool.knowledgeSearch.compactQuery': '在知识库中搜索“{query}”',
  'conversation.tool.knowledgeSearch.configReadDocument': '阅读知识库文件',
  'conversation.tool.knowledgeSearch.traceExecuting': '正在深度搜索',
  'conversation.tool.knowledgeSearch.traceCompleted': '深度搜索过程',
  'conversation.tool.subrunTrace.stepCount': '{count} 步',
  'conversation.tool.subrunTrace.collapse': '收起',
  'conversation.tool.subrunTrace.expand': '展开',
  'conversation.tool.subrunTrace.defaultExecuting': '正在执行',
  'conversation.tool.subrunTrace.defaultCompleted': '执行过程',
  'conversation.tool.subrunTrace.retry': '重新加载过程',
  'conversation.tool.subrunTrace.executeNamedTool': '执行「{toolName}」',
  'conversation.tool.subrunTrace.status.failed': '失败',
  'conversation.tool.subrunTrace.status.succeeded': '成功',
  'conversation.tool.documentList.loading': '正在读取文档列表...',
  'conversation.tool.documentList.count': '发现 {count} 篇文档',
  'conversation.tool.documentList.empty': '知识库暂无文档',
  'conversation.tool.documentList.failed': '获取文档列表失败',
  'conversation.tool.documentContent.loading': '正在读取文档内容...',
  'conversation.tool.documentContent.paragraph': '段落 {start}',
  'conversation.tool.documentContent.paragraphRange': '段落 {start}–{end}',
  'conversation.tool.documentContent.failed': '读取文档失败',
  'conversation.tool.taskState.notCreated': '尚未创建 TaskState，需要时可通过 task_write 创建。',
  'conversation.tool.taskState.planCount': '{count} 计划',
  'conversation.tool.taskState.nextStepCount': '{count} 下一步',
  'conversation.tool.taskState.loadingUpdate': '正在更新 TaskState...',
  'conversation.tool.taskState.loadingRead': '正在读取 TaskState...',
  'conversation.tool.taskState.unsetPhase': '未设置阶段',
  'conversation.tool.taskState.failed': 'TaskState 操作失败',
  'conversation.tool.subrun.unnamed': '（未命名）',
  'conversation.tool.subrun.title': '子任务 · {description}',
  'conversation.tool.subrun.batchTitle': '并行子任务 · {count} 个',
  'conversation.tool.subrun.headerFallback': '任务',
  'conversation.tool.subrun.failedNoFinalAnswer': '子任务未成功完成，且未返回最终答案。',
  'conversation.tool.subrun.completedNoFinalAnswer': '子任务已完成，但未返回可渲染的最终答案。',
  'conversation.tool.subrunDetail.back': '返回主对话',
  'conversation.tool.subrunDetail.open': '查看详情',
  'conversation.tool.subrunDetail.parentMissing': '父任务已不在当前消息窗口中，无法继续展示详情。',
  'conversation.tool.subrunDetail.projectionFailed': '子任务过程未能通过展示校验。',
  'conversation.tool.subrunDetail.loadFailed': '子任务过程加载失败。',
  'conversation.tool.subrunDetail.status.running': '子任务执行中',
  'conversation.tool.subrunDetail.status.completed': '子任务已完成',
  'conversation.tool.subrunDetail.status.partial': '子任务部分完成',
  'conversation.tool.subrunDetail.status.failed': '子任务执行失败',
  'conversation.tool.subrunDetail.status.cancelled': '子任务已取消',
  'conversation.tool.subrunDetail.model': '模型 · {model}',
  'conversation.tool.todo.failed': 'ToDo 更新失败',
  'conversation.tool.todo.status.inProgress': '进行中',
  'conversation.tool.todo.status.pending': '待办',
  'conversation.tool.todo.status.completed': '完成',
  'conversation.tool.todo.status.cancelled': '取消',
  'conversation.tool.todo.emptyTitle': '暂无 ToDo',
  'conversation.tool.todo.emptySubtitle': '需要时可以通过 todo_write 写入计划。',
  'conversation.tool.todo.progress': '完成度 {percent}%（{completed}/{total}）',
  'conversation.tool.todo.loading': '正在同步 ToDo...',
  'conversation.tool.todo.title': 'ToDo',
  'conversation.tool.workspace.document.newBadge': '新建',
  'conversation.tool.sharedMemory.listLoading': '正在读取内部产物列表...',
  'conversation.tool.sharedMemory.listCount': '发现 {count} 个文档',
  'conversation.tool.sharedMemory.listEmpty': '暂无内部产物',
  'conversation.tool.sharedMemory.listTitleSize': '大小：{size}',
  'conversation.tool.sharedMemory.listTitleUpdatedAt': '更新时间：{time}',
  'conversation.tool.sharedMemory.listFailed': '获取内部产物列表失败',
  'conversation.tool.sharedMemory.sizeCharacters': '{count} 字符',
  'conversation.tool.sharedMemory.readSharedMemoryLoading': '正在读取内部产物...',
  'conversation.tool.sharedMemory.readEvidenceLoading': '正在读取证据...',
  'conversation.tool.sharedMemory.readCitationSnapshotLoading': '正在读取引用快照...',
  'conversation.tool.sharedMemory.readSharedMemoryFailed': '读取内部产物失败',
  'conversation.tool.sharedMemory.readEvidenceFailed': '读取证据失败',
  'conversation.tool.sharedMemory.readCitationSnapshotFailed': '读取引用快照失败',
  'conversation.tool.sharedMemory.writeLoading': '正在写入内部产物...',
  'conversation.tool.sharedMemory.untitledDocument': '未命名文档',
  'conversation.tool.sharedMemory.updatedUnits': '更新了 {count} 字',
  'conversation.tool.sharedMemory.writeFailed': '写入内部产物失败',
  'conversation.tool.toolOutput.loading': '正在读取 ToolOutputStore...',
  'conversation.tool.toolOutput.moreResults': '更多工具结果',
  'conversation.tool.toolOutput.failed': '读取 ToolOutputStore 失败',
  'conversation.tool.toolOutput.knowledgeFallbackFile': '知识库文件',
  'conversation.tool.skill.loadingResourceNamed': '正在进一步学习{name}技能...',
  'conversation.tool.skill.loadingResource': '正在进一步学习技能...',
  'conversation.tool.skill.resourceNamed': '进一步学习{name}技能',
  'conversation.tool.skill.resource': '进一步学习技能',
  'conversation.tool.skill.loadingNamed': '正在学习{name}技能...',
  'conversation.tool.skill.loading': '正在学习技能...',
  'conversation.tool.skill.learnedNamed': '已学习{name}技能',
  'conversation.tool.skill.learned': '已学习技能',
  'conversation.tool.skill.viewedResourcesNamed': '已查看{name}技能资源',
  'conversation.tool.skill.viewedResources': '已查看技能资源',
  'conversation.tool.skill.readResourceNamed': '已读取{name}技能资源',
  'conversation.tool.skill.readResource': '已读取技能资源',
  'conversation.tool.skill.processed': '技能已处理',
  'conversation.tool.askQuestions.loading': '正在创建提问...',
  'conversation.tool.askQuestions.emptyTitle': '暂无问题',
  'conversation.tool.askQuestions.emptyText': '暂无可用问题',
  'conversation.tool.askQuestions.emptyError': '提问工具没有返回可用问题，请稍后重试。',
  'conversation.tool.askQuestions.otherOption': '其他',
  'conversation.tool.askQuestions.otherPlaceholder': '请输入...',
  'conversation.tool.askQuestions.textPlaceholder': '请输入您的答案...',
  'conversation.tool.askQuestions.selectedCount': '已选择 {count} 项',
  'conversation.tool.askQuestions.selectedMax': '，最多选择 {count} 项',
  'conversation.tool.askQuestions.shortcutSubmit': '提交',
  'conversation.tool.askQuestions.shortcutSkip': '跳过',
  'conversation.tool.askQuestions.submitted': '已提交',
  'conversation.tool.askQuestions.skipped': '已跳过',
  'conversation.tool.askQuestions.skipAction': '不想回答',
  'conversation.tool.askQuestions.submitting': '提交中...',
  'conversation.tool.askQuestions.submitFallback': '提交',
  'conversation.tool.askQuestions.validation.singleRequired': '此题为必填项，需选择一项',
  'conversation.tool.askQuestions.validation.singleOtherRequired': '选择了"其他"，请填写内容',
  'conversation.tool.askQuestions.validation.multiRequired': '此题为必填项，至少选择一项',
  'conversation.tool.askQuestions.validation.multiOtherRequired': '已选择"其他"，请填写内容',
  'conversation.tool.askQuestions.validation.maxSelect': '最多可选 {count} 项',
  'conversation.tool.askQuestions.validation.textRequired': '此题为必填项，请填写文本',
  'conversation.tool.askQuestions.validation.submitMissingToolCall': '提交失败：缺少 toolCallId（请刷新会话后重试）',
  'conversation.tool.askQuestions.validation.actionMissingToolCall': '操作失败：缺少 toolCallId（请刷新会话后重试）',
  'conversation.tool.image.loading': '正在生成图片...',
  'conversation.tool.image.alt': 'AI 生成的图片',
  'conversation.tool.image.altIndexed': 'AI 生成的图片 {index}',
  'conversation.tool.image.copy': '复制图片',
  'conversation.tool.image.copied': '已复制',
  'conversation.tool.image.preview': '全屏预览',
  'conversation.tool.image.download': '下载图片',
  'conversation.tool.image.failed': '图片生成失败',
  'conversation.tool.image.retryLater': '生成过程中遇到问题，请稍后重试',
  'conversation.tool.image.empty': '暂无图片内容',
  'conversation.tool.imageRead.title': '查看图片',
  'conversation.tool.imageRead.unavailable': '图片内容暂不可用',
  'conversation.code.plainText': '纯文本',
  'conversation.code.copy': '复制代码',
  'conversation.code.copied': '已复制!',
  'conversation.math.copySource': '复制公式源码',
  'conversation.math.copied': '已复制',
  'conversation.citation.ariaLabel': '引用',
  'conversation.citation.loading': '加载中...',
  'conversation.citation.openWebPage': '打开原网页',
  'conversation.citation.page': '第 {page} 页',
  'conversation.citation.empty': '未找到引用信息',
  'conversation.summary.title.summarizing': '正在整理历史对话',
  'conversation.summary.title.completed': '历史对话整理完成',
  'conversation.summary.title.error': '历史对话整理失败',
  'conversation.summary.text.summarizing': '正在整理历史对话...',
  'conversation.summary.text.completed': '已整理历史对话',
  'conversation.summary.text.error': '历史对话整理失败',
  'conversation.image.loading': '正在加载图片...',
  'conversation.image.error': '图片加载失败',
  'conversation.image.alt': '生成的图片',
  'conversation.date.yesterday': '昨天',
  'conversation.project.fallbackName': '项目',
  'conversation.project.inputPlaceholder': '询问与「{projectName}」有关的一切',
  'conversation.project.suggestion.status': '总结项目现状',
  'conversation.project.suggestion.issues': '分析关键问题',
  'conversation.project.suggestion.plan': '制定下一步计划',
  'conversation.project.action.manageKnowledgeBase': '管理知识库',
  'conversation.resourceLink.genericTitle': '文件',
  'conversation.resourceLink.status.invalid': '格式无效',
  'conversation.resourceLink.status.unavailable': '不可用',
  'conversation.resourceLink.status.resolving': '正在解析',
  'conversation.resourceLink.status.missing': '文件不存在',
  'conversation.resourceLink.tooltip.missing': '文件不存在或路径已变化：{locator}',
  'conversation.resourceLink.tooltip.unavailable': '当前无法打开：{locator}',
  'conversation.resourceLink.openFailed': '无法打开这个文件链接',
  'conversation.startupSubtitle.newProject': '要开始一个新项目吗？',
  'conversation.startupSubtitle.linkInsights': '梳理思绪，链接洞察。',
  'conversation.startupSubtitle.paper': '让思绪落入纸面。',
  'conversation.startupSubtitle.oneSentence': '从一句话开始也很好。',
  'conversation.startupSubtitle.newChapter': '开个新篇章吧。',
  'conversation.startupSubtitle.todayThoughts': '开始整理今天的思路吧。',
  'conversation.startupSubtitle.captureIdea': '记录此刻的一个想法。',
  'conversation.startupSubtitle.deepThinking': '深度思考，清晰表达。',
  'conversation.startupSubtitle.projectToday': '今天，推进哪个项目？',
  'conversation.startupSubtitle.focusedStart': '一个专注的开始，一个高效的产出。',
  'conversation.startupSubtitle.growthRings': '每一行文字，都是成长的年轮。',
  'conversation.startupSubtitle.planToday': '今天打算做些什么？',
  'conversation.startupSubtitle.goodStory': '好的故事，需要一个好的开始。',
  'conversation.startupSubtitle.thinkingRoots': '让思考生根发芽。',
  'conversation.startupSubtitle.thinkingBranches': '让思考枝繁叶茂。',
} as const satisfies Readonly<Record<ConversationMessageKey, string>>;

export const CONVERSATION_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'conversation',
  catalogs: {
    'zh-CN': CONVERSATION_MESSAGE_FALLBACKS,
    'en-US': {
      'conversation.view.historyLoading': 'Loading conversation history',
      'conversation.view.empty.title': 'Start a new chat',
      'conversation.view.empty.description': 'Ask a question, or give Linnya a task',
      'conversation.input.placeholder': 'Ask anything...',
      'conversation.input.model.placeholder': 'Select model',
      'conversation.input.model.loading': 'Loading...',
      'conversation.input.model.unknown': 'Unknown model',
      'conversation.input.modelGroup.custom': 'Custom models',
      'conversation.input.modelGroup.provider': 'Model providers',
      'conversation.input.modelGroup.current': 'Current model',
      'conversation.input.model.manage': 'Manage models…',
      'conversation.input.model.imageUnsupported': 'Images unsupported',
      'conversation.input.model.unavailable': 'Currently unavailable',
      'conversation.input.reasoning.placeholder': 'Reasoning effort',
      'conversation.input.reasoning.off': 'Off',
      'conversation.input.reasoning.minimal': 'Minimal',
      'conversation.input.reasoning.low': 'Low',
      'conversation.input.reasoning.medium': 'Medium',
      'conversation.input.reasoning.high': 'High',
      'conversation.input.reasoning.xhigh': 'Extra high',
      'conversation.contextUsage.title': 'Context Usage',
      'conversation.contextUsage.trigger.unavailable': 'Context usage is not available yet',
      'conversation.contextUsage.trigger.available': 'Context {percentage} used, {used} / {budget} Tokens',
      'conversation.contextUsage.summary': '{percentage} used',
      'conversation.contextUsage.total': '{used} / {budget} Tokens',
      'conversation.contextUsage.row.systemPrompt': 'System prompt',
      'conversation.contextUsage.row.conversation': 'Conversation',
      'conversation.contextUsage.row.toolDefinitions': 'Tool definitions',
      'conversation.contextUsage.empty.tailUnavailable': 'Only part of the history is loaded. Return to the conversation tail to resolve the latest context usage.',
      'conversation.contextUsage.conversationInfo.createdAt': 'Created',
      'conversation.contextUsage.conversationInfo.userMessageCount': 'User messages',
      'conversation.input.actionMenu.open': 'Add',
      'conversation.input.actionMenu.attachmentGroup': 'Add attachments',
      'conversation.input.actionMenu.agentGroup': 'Agent',
      'conversation.input.agentChoice.closeCurrent': 'Close current agent',
      'conversation.input.agentChoice.close': 'Close',
      'conversation.input.agentChoice.persistFailed': 'Unable to update the conversation agent. Please try again.',
      'conversation.input.mention.empty': 'No matching references',
      'conversation.input.image.add': 'Add images',
      'conversation.input.image.menuItem': 'Images',
      'conversation.input.image.extensionUnsupported': 'The current input mode does not support image attachments.',
      'conversation.input.image.drafts': 'Images to send',
      'conversation.input.image.preview': 'Preview image',
      'conversation.input.image.uploading': 'Uploading',
      'conversation.input.image.remove': 'Remove image',
      'conversation.input.image.removeNamed': 'Remove image {name}',
      'conversation.input.image.retry': 'Retry upload',
      'conversation.input.image.retryNamed': 'Retry upload for {name}',
      'conversation.input.image.drop': 'Drop images here',
      'conversation.input.image.dropBlocked': 'The current input mode cannot accept images',
      'conversation.input.image.genericTitle': 'Image',
      'conversation.commandApproval.title': 'Allow this command?',
      'conversation.commandApproval.terminal': 'Terminal',
      'conversation.commandApproval.description': 'Review the command and working directory. It will run with this conversation\'s current permission.',
      'conversation.commandApproval.command': 'Command',
      'conversation.commandApproval.cwd': 'Working directory',
      'conversation.commandApproval.processing': 'Saving your choice and preparing the command...',
      'conversation.commandApproval.queue': '{count} more commands are waiting for approval',
      'conversation.commandApproval.allowOnce': 'Allow once',
      'conversation.commandApproval.allowForConversation': 'Allow the same command in this conversation',
      'conversation.commandApproval.moreAllowOptions': 'More approval options',
      'conversation.commandApproval.rememberedPrefix': 'Command remembered for this conversation',
      'conversation.commandApproval.deny': 'Deny',
      'conversation.commandApproval.reason.permissionElevation': 'This command needs permission to write files.',
      'conversation.commandApproval.reason.delete': 'This command may delete files or folders.',
      'conversation.commandApproval.reason.moveOverwriteRename': 'This command may move, overwrite, or rename files.',
      'conversation.commandApproval.reason.externalUpload': 'This command may upload data to an external location.',
      'conversation.commandApproval.reason.downloadAndExecute': 'This command may download and run content.',
      'conversation.commandApproval.reason.systemOrDiskImpact': 'This command may affect the system or disk.',
      'conversation.sidebar.loading': 'Loading...',
      'conversation.sidebar.newConversation': 'New chat',
      'conversation.sidebar.noConversation': 'No conversation',
      'conversation.sidebar.empty.noMatch': 'No matching conversations',
      'conversation.sidebar.empty.noConversations': 'No conversations yet',
      'conversation.sidebar.untitled': 'Untitled conversation',
      'conversation.sidebar.moreOptions': 'More options',
      'conversation.sidebar.expand': 'Show more',
      'conversation.sidebar.collapse': 'Show less',
      'conversation.sidebar.menu.pin': 'Pin',
      'conversation.sidebar.menu.unpin': 'Unpin',
      'conversation.sidebar.menu.rename': 'Rename',
      'conversation.sidebar.menu.delete': 'Delete',
      'conversation.sidebar.renameFailed': 'Rename failed. Please try again later.',
      'conversation.sidebar.delete.title': 'Delete conversation',
      'conversation.sidebar.delete.message': 'Delete "{title}"? This action cannot be undone.',
      'conversation.sidebar.delete.confirm': 'Delete',
      'conversation.sidebar.delete.cancel': 'Cancel',
      'conversation.sidebar.deleting': 'Deleting…',
      'conversation.sidebar.deleteSuccess': 'Deleted conversation: {title}',
      'conversation.sidebar.deleteFailed': 'Delete failed. Please try again later.',
      'conversation.sidebar.loadFailed': 'Failed to load conversations. Please try again later.',
      'conversation.sidebar.renameFailedGeneric': 'Rename failed. Please try again later.',
  'conversation.sidebar.deleteFailedGeneric': 'Delete failed. Please try again later.',
  'conversation.sidebar.batchDelete.title': 'Delete conversations',
  'conversation.sidebar.batchDelete.message': 'Delete the selected {count} conversations? This cannot be undone.',
  'conversation.sidebar.batchDelete.success': 'Deleted {count} conversations',
  'conversation.sidebar.batchDelete.partial': 'Deleted {successCount} conversations; {failCount} failed',
      'conversation.history.group.recent': 'Recent conversations',
      'conversation.history.loading': 'Loading...',
      'conversation.history.empty': 'No conversation history',
      'conversation.history.viewAll': 'All conversation history...',
      'conversation.timeline.loadFailed': 'Failed to load the timeline. Please try again later.',
      'conversation.error.title': 'Error',
      'conversation.error.close': 'Close',
      'conversation.error.regenerateNoConversation': 'No conversation is available to regenerate',
      'conversation.error.regenerateMessageNotFound': 'The user message to regenerate was not found',
      'conversation.error.generic': 'Something went wrong. Please try again later.',
      'conversation.error.rateLimit': 'Requests are being sent too frequently. Please try again later. If this keeps happening, switch models or reduce the request rate.',
      'conversation.error.providerLimit': 'The model service returned 429. Its quota may be exhausted or requests may be too frequent. Try again later or switch models.',
      'conversation.error.serviceUnavailable': 'The service is temporarily unavailable. Please try again later.',
      'conversation.error.badRequest': 'The request is invalid. Check your input and try again.',
      'conversation.error.auth': 'Authentication failed. Check your model configuration or sign-in status.',
      'conversation.error.requestFailed': 'The request failed. Please try again later.',
      'conversation.error.quotaExceeded': 'This model has reached its quota. Try again tomorrow or switch to another model.',
      'conversation.error.http502': 'The upstream service is temporarily unavailable (502). Please try again later.',
      'conversation.error.http503': 'The service is temporarily unavailable (503). Please try again later.',
      'conversation.error.http504': 'The request timed out (504). Please try again later.',
      'conversation.error.providerUnavailable': 'The model service is currently overloaded. Please try again later. If this continues, switch models or reduce concurrency.',
      'conversation.error.thinkingProtocolMismatch': 'This model has Thinking mode enabled, but the current message format does not meet the provider requirements. Switch to a non-Thinking model or disable Thinking and try again.',
      'conversation.error.outputLimitReached': 'The model reached its output limit before completing this turn. Continue the task or switch to a model with a larger output capacity.',
      'conversation.error.contentFiltered': 'The model service stopped this response because of content filtering. Revise the request and try again.',
      'conversation.error.imageModelUnsupported': 'The current model does not support image understanding. Switch to an image-capable model.',
      'conversation.error.imageModelUnsupportedWithAlternatives': 'The current model does not support image understanding. Available alternatives: {models}.',
      'conversation.error.imagePlacementUnsupported': 'The current model connection does not support images from this source. Switch models or connections.',
      'conversation.error.imagePlacementUnsupportedWithAlternatives': 'The current model connection does not support images from this source. Available alternatives: {models}.',
      'conversation.error.userImagePlacementUnsupported': 'The current model connection does not support images sent by the user. Switch models or connections.',
      'conversation.error.userImagePlacementUnsupportedWithAlternatives': 'The current model connection does not support images sent by the user. Available alternatives: {models}.',
      'conversation.error.toolResultImagePlacementUnsupported': 'The current model connection does not support images returned by tools. The image result remains available in the conversation.',
      'conversation.error.toolResultImagePlacementUnsupportedWithAlternatives': 'The current model connection does not support images returned by tools. Available alternatives: {models}. The image result remains available in the conversation.',
      'conversation.error.imageMaterializationPending': 'The image is not ready to send yet. Please try again shortly.',
      'conversation.error.imageAttachmentUnavailable': 'The image file is no longer available. Add it again or remove it before sending.',
      'conversation.error.imageAttachmentIntegrityFailed': 'The image file is damaged or has changed. Add it again before sending.',
      'conversation.error.imageRouteLimitExceeded': 'This model connection cannot accept this many images or images this large. Remove some images or switch connections.',
      'conversation.error.imageMappingUnsupported': 'This model connection cannot send images correctly yet. Switch models or connections.',
      'conversation.error.imageContextBudgetExceeded': 'These images exceed the conversation context capacity. Remove older images, switch to a larger-context model, or start a new conversation.',
      'conversation.error.imageUploadInvalidRequest': 'The image upload request is invalid. Select the image again.',
      'conversation.error.imageTooLarge': 'The image is too large. Choose an image no larger than 10 MB.',
      'conversation.error.imageUnsupportedFormat': 'Only JPEG, PNG, and WebP images are supported.',
      'conversation.error.imageInvalid': 'This image cannot be read. Choose a valid image file.',
      'conversation.error.imagePixelLimitExceeded': 'The image dimensions are too large. Resize it and add it again.',
      'conversation.error.imageInvalidFileName': 'The image file name is invalid. Rename it and add it again.',
      'conversation.error.imageStagingFailed': 'The image cannot be added right now. Try again later.',
      'conversation.error.imageDraftUnavailable': 'The image draft has expired. Add it again.',
      'conversation.error.imageTooManyAttachments': 'A message can contain up to 100 images.',
      'conversation.error.imageTotalBytesExceeded': 'The images exceed the total size limit. Remove some images.',
      'conversation.error.imagePreviewUnavailable': 'The image preview is unavailable.',
      'conversation.error.imagePreviewIntegrityFailed': 'The image is damaged or has changed and cannot be previewed.',
      'conversation.error.imagePreviewFailed': 'The image preview failed to load. Try again later.',
      'conversation.userMessage.action.edit': 'Edit',
      'conversation.userMessage.action.regenerate': 'Regenerate',
      'conversation.userMessage.action.copy': 'Copy',
      'conversation.userMessage.action.copied': 'Copied',
      'conversation.userMessage.action.cancel': 'Cancel (Esc)',
      'conversation.userMessage.action.save': 'Save (Enter)',
      'conversation.userMessage.quoteLabel': 'Referenced content',
      'conversation.userMessage.image.gallery': 'Message images',
      'conversation.userMessage.image.edit': 'Edit message images',
      'conversation.userMessage.image.loading': 'Loading image',
      'conversation.userMessage.image.moveLeft': 'Move image left',
      'conversation.userMessage.image.moveRight': 'Move image right',
      'conversation.userMessage.image.previewNamed': 'Preview image {name}',
      'conversation.userMessage.image.retryNamed': 'Reload image {name}',
      'conversation.userMessage.image.unnamed': 'Image',
      'conversation.thought.running': 'Thinking',
      'conversation.thought.completed': 'Thought for {duration}',
      'conversation.thought.duration.seconds': '{seconds}s',
      'conversation.thought.duration.minutesSeconds': '{minutes}m {seconds}s',
      'conversation.turn.workDuration': 'Worked for {duration}',
      'conversation.turn.action.saveAsDocument': 'Save as document',
      'conversation.turn.action.copyAnswer': 'Copy this answer',
      'conversation.turn.action.copied': 'Copied',
      'conversation.turn.saveAsDocument.failed': 'Failed to save as document',
      'conversation.turn.saveAsDocument.defaultTitle': 'Deep Research report - {date} {time}',
      'conversation.turn.export.noContent': 'No content to export',
      'conversation.turn.export.renderedHtmlMissing': 'Could not extract rendered HTML',
      'conversation.turn.export.copyFailed': 'Copy failed. Please try again.',
      'conversation.turn.copy.noContent': 'No content to copy',
      'conversation.turn.saveStatus.saved': 'Saved',
      'conversation.turn.saveStatus.saving': 'Saving...',
      'conversation.turn.saveStatus.empty': 'No content',
      'conversation.turn.saveStatus.failed': 'Save failed',
      'conversation.card.windowHint': '{count} earlier messages hidden to keep rendering smooth',
      'conversation.card.showAll': 'Show all',
      'conversation.card.action.copyAnswer': 'Copy card answer',
      'conversation.card.fallbackRun': 'Run',
      'conversation.quote.label': 'Referenced content',
      'conversation.quote.clear': 'Clear references',
      'conversation.quote.remove': 'Remove reference',
      'conversation.flow.missingProjectForSend': 'This conversation must belong to a project. projectId is missing, so sending was stopped.',
      'conversation.flow.missingProjectForRun': 'This conversation must belong to a project. projectId is missing, so the run was stopped.',
      'conversation.flow.pluginRun.missingProject': 'The AI run cannot start because the current project is missing projectId.',
      'conversation.flow.pluginRun.agentChoiceUnavailable': 'The current conversation agent is not registered or enabled: {agentChoiceId}',
      'conversation.flow.pluginRun.noConversation': 'The AI run cannot start because no conversation is available.',
      'conversation.flow.pluginRun.executionFailed': 'The AI run failed. Please try again later.',
      'conversation.flow.subrun.missingProject': 'Subruns cannot start because the current project is unavailable.',
      'conversation.flow.subrun.noConversation': 'Subruns cannot start because no conversation is available.',
      'conversation.flow.subrun.executionFailed': 'Subrun execution failed. Please try again later.',
      'conversation.flow.deepResearch.resetFallback': 'Next Monday 00:00',
      'conversation.flow.deepResearch.weeklyLimitReached': "Deep Research has reached this week's limit ({usedCount}/{limit}).\nReset time: {resetText}",
      'conversation.flow.chatInvocationFailed': 'Failed to send the message. Please try again later.',
      'conversation.flow.taskInvocationFailed': 'Task execution failed. Please try again later.',
      'conversation.flow.conversationExecutionFailed': 'Conversation execution failed',
      'conversation.flow.agentExecutionFailed': 'Agent execution failed',
      'conversation.flow.streamFailed': 'The AI response was interrupted. Please try again later.',
      'conversation.flow.continueFailed': 'Failed to continue AI execution. Please try again later.',
      'conversation.flow.resumeFailed': 'Failed to resume Agent execution. Please try again later.',
      'conversation.tool.error.title': '{toolName} · execution failed',
      'conversation.tool.error.fallbackTitle': 'Execution failed',
      'conversation.tool.error.unknown': 'Unknown error',
      'conversation.tool.error.imageModelNotConfigured': 'No image generation model is configured.',
      'conversation.tool.error.configureImageModel': 'Configure',
      'conversation.tool.error.openDocumentFailed': 'Failed to open the file. Please try again later.',
      'conversation.tool.error.openDocumentFailedGeneric': 'Failed to open the file. Please try again later.',
      'conversation.tool.command.running': 'Running command',
      'conversation.tool.command.completed': 'Command completed',
      'conversation.tool.command.rejected': 'Command not executed',
      'conversation.tool.command.failed': 'Command failed',
      'conversation.tool.command.shellRunning': 'Running {command}',
      'conversation.tool.command.shellCompleted': 'Ran {command}',
      'conversation.tool.command.shellRejected': 'Did not run {command}',
      'conversation.tool.command.shellFailed': 'Failed to run {command}',
      'conversation.tool.command.terminal': 'Terminal output',
      'conversation.tool.command.omittedLines': '{count} earlier lines omitted',
      'conversation.tool.command.outputIncomplete': 'Full output is incomplete',
      'conversation.tool.command.outputIncomplete.retainedWindowOmitted': 'Earlier output is outside the retained window',
      'conversation.tool.command.outputIncomplete.textProjectionFailed': 'Some output could not be converted to safe text',
      'conversation.tool.command.auditIncomplete': 'Audit record incomplete',
      'conversation.tool.command.copy': 'Copy command and output',
      'conversation.tool.command.starting': 'Starting...',
      'conversation.tool.command.processAction': 'Process action: {action}',
      'conversation.tool.command.compact.shell': 'Run command “{command}”',
      'conversation.tool.command.compact.process.poll': 'View command output',
      'conversation.tool.command.compact.process.wait': 'Wait for command completion',
      'conversation.tool.command.compact.process.cancel': 'Terminate command',
      'conversation.tool.command.compact.process.write': 'Send input to command',
      'conversation.tool.command.compact.process.submit': 'Send input to command',
      'conversation.tool.command.compact.process.eof': 'Close command input',
      'conversation.tool.command.compact.process.resize': 'Resize terminal',
      'conversation.tool.command.state.starting': 'Starting',
      'conversation.tool.command.state.running': 'Running',
      'conversation.tool.command.state.completed': 'Completed',
      'conversation.tool.command.state.rejected': 'Not executed',
      'conversation.tool.command.state.failed': 'Failed',
      'conversation.tool.command.runtimeFailure': 'The command runtime failed',
      'conversation.tool.command.terminated.cancelled': 'Cancelled',
      'conversation.tool.command.cancel': 'Cancel command',
      'conversation.tool.command.protectedInput.open': 'Protected input',
      'conversation.tool.command.protectedInput.title': 'Send protected input to command',
      'conversation.tool.command.protectedInput.description': 'This input goes directly to the current interactive command. It is not added to the conversation or shared with the Agent.',
      'conversation.tool.command.protectedInput.label': 'Password, verification code, or passphrase',
      'conversation.tool.command.protectedInput.boundary': 'The target command may still echo, store, or transmit this content.',
      'conversation.tool.command.protectedInput.cancel': 'Cancel',
      'conversation.tool.command.protectedInput.send': 'Send',
      'conversation.tool.command.protectedInput.sending': 'Sending...',
      'conversation.tool.command.protectedInput.unavailable': 'The interactive command has ended or this input capability is no longer valid.',
      'conversation.tool.command.protectedInput.failed': 'Protected input could not be sent. Confirm that the command is still waiting for input, then try again.',
      'conversation.tool.command.settlementSaveFailed': 'The command ended, but its status could not be saved.',
      'conversation.tool.command.controlUnavailable': 'The current command status is unavailable.',
      'conversation.tool.command.cancelFailed': 'The command could not be cancelled. Try again.',
      'conversation.tool.command.terminated.timed_out': 'Timed out',
      'conversation.tool.command.terminated.owner_ended': 'Conversation run ended',
      'conversation.tool.command.actionRejected': 'Process action {action} was rejected',
      'conversation.tool.raw.loading': 'Processing...',
      'conversation.tool.raw.empty': 'No content',
      'conversation.tool.raw.loadFailed': 'Load failed. Please try again later.',
      'conversation.tool.registry.knowledgeSearching': 'Searching knowledge base...',
      'conversation.tool.deepResearch.writeReport': 'Write research report',
      'conversation.tool.markdown.createAnnotations': 'Create document annotations',
      'conversation.tool.workspace.files.list': 'View project files',
      'conversation.tool.workspace.file.read': 'Read',
      'conversation.tool.workspace.file.readTarget': 'Read {target}',
      'conversation.tool.workspace.file.target': '{target}',
      'conversation.tool.workspace.file.write': 'Write',
      'conversation.tool.workspace.file.writeTarget': 'Write {target}',
      'conversation.tool.workspace.file.create': 'Create',
      'conversation.tool.workspace.file.createLoading': 'Creating file...',
      'conversation.tool.workspace.file.edit': 'Edit',
      'conversation.tool.workspace.file.editTarget': 'Edit {target}',
      'conversation.tool.workspace.file.editLoading': 'Editing file...',
      'conversation.tool.workspace.search': 'Search',
      'conversation.tool.workspace.searchWithPattern': 'Search {pattern}',
      'conversation.tool.workspace.compact.read': 'Read project file',
      'conversation.tool.workspace.compact.write': 'Write project file',
      'conversation.tool.workspace.compact.edit': 'Edit project file',
      'conversation.tool.workspace.compact.grep': 'Search project files',
      'conversation.tool.workspace.document.list': 'View project documents',
      'conversation.tool.workspace.document.read': 'Read project documents',
      'conversation.tool.workspace.document.untitled': 'Untitled document',
      'conversation.tool.workspace.document.createdTag': 'Created',
      'conversation.tool.workspace.document.createLoading': 'Creating document...',
      'conversation.tool.workspace.document.createFailed': 'Failed to create document',
      'conversation.tool.workspace.document.readLoading': 'Reading Workspace document...',
      'conversation.tool.workspace.document.readFallbackName': 'Workspace document',
      'conversation.tool.workspace.document.emptyBlock': '(empty block)',
      'conversation.tool.workspace.document.nodeCount': '{count} nodes',
      'conversation.tool.workspace.document.nodeEmpty': 'Nodes -',
      'conversation.tool.workspace.document.paragraphEmpty': 'Paragraph -',
      'conversation.tool.workspace.document.paragraph': 'Paragraph {index}',
      'conversation.tool.workspace.document.paragraphRange': 'Paragraphs {start}–{end}',
      'conversation.tool.workspace.document.readFailed': 'Failed to read Workspace document',
      'conversation.tool.workspace.reference.label': 'Reference',
      'conversation.tool.workspace.reference.documentLabel': 'Document reference',
      'conversation.tool.workspace.reference.paragraphLabel': 'Paragraph {index}',
      'conversation.tool.workspace.reference.locateTitle': 'Go to {ref}',
      'conversation.tool.workspace.reference.noContextDocument': 'No context document was found for resolving this reference',
      'conversation.tool.workspace.reference.missingTarget': 'This reference does not specify a target document. Use #ref@documentType:documentId or #ref@documentId.',
      'conversation.tool.workspace.reference.markdownNotFound': 'Could not find the matching paragraph reference. It may have been deleted or belong to another document.',
      'conversation.tool.workspace.reference.ambiguous': 'This reference matches multiple documents. Use [#ref@documentId] to specify the target document.',
      'conversation.tool.workspace.reference.editorNotReady': 'The editor is not ready yet. Try again shortly.',
      'conversation.tool.workspace.reference.paragraphNotFound': 'Could not find the matching paragraph. It may have been deleted or be in another document.',
      'conversation.tool.workspace.reference.pluginNotFound': 'Could not find the matching document reference. It may have been deleted or belong to another document.',
      'conversation.tool.workspace.reference.pluginDisabled': 'The matching plugin is not enabled, so this document reference cannot be located.',
      'conversation.tool.workspace.reference.documentNotReady': 'The document is not ready yet. Try again shortly.',
      'conversation.tool.workspace.reference.targetNotFound': 'Could not find the matching reference target. It may be collapsed or deleted.',
      'conversation.tool.workspace.reference.locateFailed': 'Failed to locate the reference. Please try again later.',
      'conversation.tool.workspace.reference.locateFailedGeneric': 'Failed to locate the reference. Please try again later.',
      'conversation.tool.evidence.write': 'Write evidence library',
      'conversation.tool.evidence.read': 'Read evidence library',
      'conversation.tool.evidence.assemble': 'Assemble results',
      'conversation.tool.sharedMemory.list': 'View internal artifacts',
      'conversation.tool.sharedMemory.read': 'Read internal artifact',
      'conversation.tool.sharedMemory.readEvidence': 'Read evidence',
      'conversation.tool.sharedMemory.readCitationSnapshot': 'Read citation snapshot',
      'conversation.tool.sharedMemory.write': 'Write internal artifact',
      'conversation.tool.taskState.read': 'Read TaskState',
      'conversation.tool.taskState.readMissing': 'Read TaskState · not created',
      'conversation.tool.taskState.readVersion': 'Read TaskState · v{version}',
      'conversation.tool.taskState.update': 'Update TaskState',
      'conversation.tool.taskState.updateVersion': 'Update TaskState · v{version}',
      'conversation.tool.taskState.updateVersionPhase': 'Update TaskState · v{version} · {phase}',
      'conversation.tool.todo.empty': 'No ToDo created',
      'conversation.tool.todo.read': 'Read ToDo',
      'conversation.tool.todo.readCount': 'Read ToDo · {count} items',
      'conversation.tool.todo.update': 'Update ToDo',
      'conversation.tool.todo.updateCount': 'Update ToDo · {count} items',
      'conversation.tool.skill.compact': 'Learn skill',
      'conversation.tool.askQuestions.compact': 'Ask the user',
      'conversation.tool.imageGeneration.compact': 'Generate image',
      'conversation.tool.subrun.compact': 'Run subtask',
      'conversation.tool.subrun.batchCompact': 'Run parallel subtasks',
      'conversation.tool.output.continue': 'Continue reading tool result',
      'conversation.tool.deepResearch.scout': 'Search',
      'conversation.tool.deepResearch.reasoner': 'Reason',
      'conversation.tool.deepResearch.challenger': 'Challenge',
      'conversation.tool.deepResearch.writer': 'Write',
      'conversation.tool.deepResearch.running': 'Researching',
      'conversation.tool.deepResearch.completed': 'Research process',
      'conversation.tool.webSearch.loading': 'Searching...',
      'conversation.tool.webSearch.configTitle': 'Web search',
      'conversation.tool.webSearch.configTitleWithQuery': 'Web search: "{query}"',
      'conversation.tool.webSearch.compactQuery': 'Search the web for “{query}”',
      'conversation.tool.webSearch.failed': 'Search failed',
      'conversation.tool.webSearch.untitled': 'Untitled',
      'conversation.tool.webSearch.empty': 'No relevant results found',
      'conversation.tool.webRead.loading': 'Reading web page...',
      'conversation.tool.webRead.configTitle': 'Read web page',
      'conversation.tool.webRead.configTitleWithTarget': 'Read web page: {target}',
      'conversation.tool.webRead.failed': 'Read failed',
      'conversation.tool.webRead.untitled': 'Untitled',
      'conversation.tool.webRead.characterCount': '{count} characters',
      'conversation.tool.webRead.truncated': 'Truncated',
      'conversation.tool.webRead.empty': 'No web page content was returned',
      'conversation.tool.knowledgeSearch.relatedDocuments': 'Found {count} related documents',
      'conversation.tool.knowledgeSearch.snapshotPointerWithCount': 'Results were saved to the citation snapshot library: {count} items (load on demand)',
      'conversation.tool.knowledgeSearch.snapshotPointer': 'Results were saved to the citation snapshot library (load on demand)',
      'conversation.tool.knowledgeSearch.empty': 'No relevant results found. Try adjusting the search terms.',
      'conversation.tool.knowledgeSearch.loadLoading': 'Loading...',
      'conversation.tool.knowledgeSearch.loadDetails': 'Load details',
      'conversation.tool.knowledgeSearch.exportLoading': 'Exporting...',
      'conversation.tool.knowledgeSearch.exportJson': 'Export JSON',
      'conversation.tool.knowledgeSearch.loadFailed': 'Load failed. Please try again later.',
      'conversation.tool.knowledgeSearch.loadFailedGeneric': 'Load failed. Please try again later.',
      'conversation.tool.knowledgeSearch.error': 'An error occurred while searching the knowledge base',
      'conversation.tool.knowledgeSearch.noActiveConversationLoad': 'No active conversation is available to load the Citation Snapshot Bundle',
      'conversation.tool.knowledgeSearch.invalidSnapshotBundle': 'Citation Snapshot Bundle has an unexpected structure',
      'conversation.tool.knowledgeSearch.noActiveConversationExport': 'No active conversation is available to export the Citation Snapshot Bundle',
      'conversation.tool.knowledgeSearch.unknownDocument': 'Unknown document',
      'conversation.tool.knowledgeSearch.scopeDocument': 'In "{docName}"',
      'conversation.tool.knowledgeSearch.scopeKnowledgeBase': 'In the knowledge base',
      'conversation.tool.knowledgeSearch.actionDeepSearch': 'Deep search',
      'conversation.tool.knowledgeSearch.actionSearch': 'Search',
      'conversation.tool.knowledgeSearch.configListTitle': 'View knowledge base',
      'conversation.tool.knowledgeSearch.configSearchTitle': 'Search knowledge base',
      'conversation.tool.knowledgeSearch.configSearchInDocument': 'Search knowledge base: in "{docName}"',
      'conversation.tool.knowledgeSearch.configSearchKeyword': 'Search knowledge base: keyword "{query}"',
      'conversation.tool.knowledgeSearch.compactQuery': 'Search the knowledge base for “{query}”',
      'conversation.tool.knowledgeSearch.configReadDocument': 'Read knowledge base file',
      'conversation.tool.knowledgeSearch.traceExecuting': 'Running deep search',
      'conversation.tool.knowledgeSearch.traceCompleted': 'Deep search process',
      'conversation.tool.subrunTrace.stepCount': '{count} steps',
      'conversation.tool.subrunTrace.collapse': 'Collapse',
      'conversation.tool.subrunTrace.expand': 'Expand',
      'conversation.tool.subrunTrace.defaultExecuting': 'Running',
      'conversation.tool.subrunTrace.defaultCompleted': 'Execution process',
      'conversation.tool.subrunTrace.retry': 'Reload process',
      'conversation.tool.subrunTrace.executeNamedTool': 'Run "{toolName}"',
      'conversation.tool.subrunTrace.status.failed': 'Failed',
      'conversation.tool.subrunTrace.status.succeeded': 'Succeeded',
      'conversation.tool.documentList.loading': 'Reading document list...',
      'conversation.tool.documentList.count': 'Found {count} documents',
      'conversation.tool.documentList.empty': 'No documents in the knowledge base',
      'conversation.tool.documentList.failed': 'Failed to get document list',
      'conversation.tool.documentContent.loading': 'Reading document content...',
      'conversation.tool.documentContent.paragraph': 'Paragraph {start}',
      'conversation.tool.documentContent.paragraphRange': 'Paragraphs {start}–{end}',
      'conversation.tool.documentContent.failed': 'Failed to read document',
      'conversation.tool.taskState.notCreated': 'TaskState has not been created. Use task_write when needed.',
      'conversation.tool.taskState.planCount': '{count} plans',
      'conversation.tool.taskState.nextStepCount': '{count} next steps',
      'conversation.tool.taskState.loadingUpdate': 'Updating TaskState...',
      'conversation.tool.taskState.loadingRead': 'Reading TaskState...',
      'conversation.tool.taskState.unsetPhase': 'No phase set',
      'conversation.tool.taskState.failed': 'TaskState operation failed',
      'conversation.tool.subrun.unnamed': '(unnamed)',
      'conversation.tool.subrun.title': 'Subtask · {description}',
      'conversation.tool.subrun.batchTitle': 'Parallel subtasks · {count}',
      'conversation.tool.subrun.headerFallback': 'Task',
      'conversation.tool.subrun.failedNoFinalAnswer': 'The subrun did not complete successfully and returned no final answer.',
      'conversation.tool.subrun.completedNoFinalAnswer': 'The subrun completed but returned no renderable final answer.',
      'conversation.tool.subrunDetail.back': 'Back to conversation',
      'conversation.tool.subrunDetail.open': 'View details',
      'conversation.tool.subrunDetail.parentMissing': 'The parent task is no longer in the current message window.',
      'conversation.tool.subrunDetail.projectionFailed': 'The subtask trace failed presentation admission.',
      'conversation.tool.subrunDetail.loadFailed': 'Failed to load the subtask trace.',
      'conversation.tool.subrunDetail.status.running': 'Subtask running',
      'conversation.tool.subrunDetail.status.completed': 'Subtask completed',
      'conversation.tool.subrunDetail.status.partial': 'Subtask partially completed',
      'conversation.tool.subrunDetail.status.failed': 'Subtask failed',
      'conversation.tool.subrunDetail.status.cancelled': 'Subtask cancelled',
      'conversation.tool.subrunDetail.model': 'Model · {model}',
      'conversation.tool.todo.failed': 'ToDo update failed',
      'conversation.tool.todo.status.inProgress': 'In progress',
      'conversation.tool.todo.status.pending': 'Pending',
      'conversation.tool.todo.status.completed': 'Complete',
      'conversation.tool.todo.status.cancelled': 'Cancelled',
      'conversation.tool.todo.emptyTitle': 'No ToDo',
      'conversation.tool.todo.emptySubtitle': 'Use todo_write to add a plan when needed.',
      'conversation.tool.todo.progress': 'Progress {percent}% ({completed}/{total})',
      'conversation.tool.todo.loading': 'Syncing ToDo...',
      'conversation.tool.todo.title': 'ToDo',
      'conversation.tool.workspace.document.newBadge': 'NEW',
      'conversation.tool.sharedMemory.listLoading': 'Reading internal artifact list...',
      'conversation.tool.sharedMemory.listCount': 'Found {count} documents',
      'conversation.tool.sharedMemory.listEmpty': 'No internal artifacts',
      'conversation.tool.sharedMemory.listTitleSize': 'Size: {size}',
      'conversation.tool.sharedMemory.listTitleUpdatedAt': 'Updated: {time}',
      'conversation.tool.sharedMemory.listFailed': 'Failed to get internal artifact list',
      'conversation.tool.sharedMemory.sizeCharacters': '{count} characters',
      'conversation.tool.sharedMemory.readSharedMemoryLoading': 'Reading internal artifact...',
      'conversation.tool.sharedMemory.readEvidenceLoading': 'Reading evidence...',
      'conversation.tool.sharedMemory.readCitationSnapshotLoading': 'Reading citation snapshot...',
      'conversation.tool.sharedMemory.readSharedMemoryFailed': 'Failed to read internal artifact',
      'conversation.tool.sharedMemory.readEvidenceFailed': 'Failed to read evidence',
      'conversation.tool.sharedMemory.readCitationSnapshotFailed': 'Failed to read citation snapshot',
      'conversation.tool.sharedMemory.writeLoading': 'Writing internal artifact...',
      'conversation.tool.sharedMemory.untitledDocument': 'Untitled document',
      'conversation.tool.sharedMemory.updatedUnits': 'Updated {count} words',
      'conversation.tool.sharedMemory.writeFailed': 'Failed to write internal artifact',
      'conversation.tool.toolOutput.loading': 'Reading ToolOutputStore...',
      'conversation.tool.toolOutput.moreResults': 'More tool results',
      'conversation.tool.toolOutput.failed': 'Failed to read ToolOutputStore',
      'conversation.tool.toolOutput.knowledgeFallbackFile': 'Knowledge base file',
      'conversation.tool.skill.loadingResourceNamed': 'Continuing to learn {name}...',
      'conversation.tool.skill.loadingResource': 'Continuing to learn skill...',
      'conversation.tool.skill.resourceNamed': 'Continue learning {name}',
      'conversation.tool.skill.resource': 'Continue learning skill',
      'conversation.tool.skill.loadingNamed': 'Learning {name}...',
      'conversation.tool.skill.loading': 'Learning skill...',
      'conversation.tool.skill.learnedNamed': 'Learned {name}',
      'conversation.tool.skill.learned': 'Learned skill',
      'conversation.tool.skill.viewedResourcesNamed': 'Viewed {name} skill resources',
      'conversation.tool.skill.viewedResources': 'Viewed skill resources',
      'conversation.tool.skill.readResourceNamed': 'Read {name} skill resource',
      'conversation.tool.skill.readResource': 'Read skill resource',
      'conversation.tool.skill.processed': 'Skill processed',
      'conversation.tool.askQuestions.loading': 'Creating questions...',
      'conversation.tool.askQuestions.emptyTitle': 'No questions',
      'conversation.tool.askQuestions.emptyText': 'No available questions',
      'conversation.tool.askQuestions.emptyError': 'The question tool did not return usable questions. Please try again later.',
      'conversation.tool.askQuestions.otherOption': 'Other',
      'conversation.tool.askQuestions.otherPlaceholder': 'Type here...',
      'conversation.tool.askQuestions.textPlaceholder': 'Enter your answer...',
      'conversation.tool.askQuestions.selectedCount': '{count} selected',
      'conversation.tool.askQuestions.selectedMax': ', up to {count}',
      'conversation.tool.askQuestions.shortcutSubmit': 'Submit',
      'conversation.tool.askQuestions.shortcutSkip': 'Skip',
      'conversation.tool.askQuestions.submitted': 'Submitted',
      'conversation.tool.askQuestions.skipped': 'Skipped',
      'conversation.tool.askQuestions.skipAction': 'Skip',
      'conversation.tool.askQuestions.submitting': 'Submitting...',
      'conversation.tool.askQuestions.submitFallback': 'Submit',
      'conversation.tool.askQuestions.validation.singleRequired': 'This question is required. Select one option.',
      'conversation.tool.askQuestions.validation.singleOtherRequired': 'You selected "Other". Please enter a value.',
      'conversation.tool.askQuestions.validation.multiRequired': 'This question is required. Select at least one option.',
      'conversation.tool.askQuestions.validation.multiOtherRequired': 'You selected "Other". Please enter a value.',
      'conversation.tool.askQuestions.validation.maxSelect': 'Select at most {count} items',
      'conversation.tool.askQuestions.validation.textRequired': 'This question is required. Enter text.',
      'conversation.tool.askQuestions.validation.submitMissingToolCall': 'Submit failed: missing toolCallId. Refresh the conversation and try again.',
      'conversation.tool.askQuestions.validation.actionMissingToolCall': 'Action failed: missing toolCallId. Refresh the conversation and try again.',
      'conversation.tool.image.loading': 'Generating image...',
      'conversation.tool.image.alt': 'AI-generated image',
      'conversation.tool.image.altIndexed': 'AI-generated image {index}',
      'conversation.tool.image.copy': 'Copy image',
      'conversation.tool.image.copied': 'Copied',
      'conversation.tool.image.preview': 'Full-screen preview',
      'conversation.tool.image.download': 'Download image',
      'conversation.tool.image.failed': 'Image generation failed',
      'conversation.tool.image.retryLater': 'Something went wrong while generating the image. Try again later.',
      'conversation.tool.image.empty': 'No image content',
      'conversation.tool.imageRead.title': 'View image',
      'conversation.tool.imageRead.unavailable': 'Image content is unavailable',
      'conversation.code.plainText': 'Plain text',
      'conversation.code.copy': 'Copy code',
      'conversation.code.copied': 'Copied!',
      'conversation.math.copySource': 'Copy formula source',
      'conversation.math.copied': 'Copied',
      'conversation.citation.ariaLabel': 'Citation',
      'conversation.citation.loading': 'Loading...',
      'conversation.citation.openWebPage': 'Open original page',
      'conversation.citation.page': 'Page {page}',
      'conversation.citation.empty': 'Citation not found',
      'conversation.summary.title.summarizing': 'Summarizing conversation history',
      'conversation.summary.title.completed': 'Conversation history summarized',
      'conversation.summary.title.error': 'Conversation history summary failed',
      'conversation.summary.text.summarizing': 'Summarizing conversation history...',
      'conversation.summary.text.completed': 'Conversation history summarized',
      'conversation.summary.text.error': 'Conversation history summary failed',
      'conversation.image.loading': 'Loading image...',
      'conversation.image.error': 'Image failed to load',
      'conversation.image.alt': 'Generated image',
      'conversation.date.yesterday': 'Yesterday',
      'conversation.project.fallbackName': 'Project',
      'conversation.project.inputPlaceholder': 'Ask anything about "{projectName}"',
      'conversation.project.suggestion.status': 'Summarize project status',
      'conversation.project.suggestion.issues': 'Analyze key issues',
      'conversation.project.suggestion.plan': 'Plan next steps',
      'conversation.project.action.manageKnowledgeBase': 'Manage knowledge base',
      'conversation.resourceLink.genericTitle': 'File',
      'conversation.resourceLink.status.invalid': 'Invalid link',
      'conversation.resourceLink.status.unavailable': 'Unavailable',
      'conversation.resourceLink.status.resolving': 'Resolving',
      'conversation.resourceLink.status.missing': 'File not found',
      'conversation.resourceLink.tooltip.missing': 'The file is missing or its path changed: {locator}',
      'conversation.resourceLink.tooltip.unavailable': 'This file cannot be opened: {locator}',
      'conversation.resourceLink.openFailed': 'Unable to open this file link',
      'conversation.startupSubtitle.newProject': 'Ready to start a new project?',
      'conversation.startupSubtitle.linkInsights': 'Organize your thoughts and connect the insights.',
      'conversation.startupSubtitle.paper': 'Let your thoughts land on the page.',
      'conversation.startupSubtitle.oneSentence': 'A single sentence is a fine place to begin.',
      'conversation.startupSubtitle.newChapter': 'Open a new chapter.',
      'conversation.startupSubtitle.todayThoughts': "Start shaping today's thoughts.",
      'conversation.startupSubtitle.captureIdea': 'Capture one idea from this moment.',
      'conversation.startupSubtitle.deepThinking': 'Think deeply. Express clearly.',
      'conversation.startupSubtitle.projectToday': 'Which project moves forward today?',
      'conversation.startupSubtitle.focusedStart': 'A focused start, a clearer outcome.',
      'conversation.startupSubtitle.growthRings': 'Every line of text records a little growth.',
      'conversation.startupSubtitle.planToday': 'What would you like to do today?',
      'conversation.startupSubtitle.goodStory': 'A good story needs a good beginning.',
      'conversation.startupSubtitle.thinkingRoots': 'Let your thinking take root.',
      'conversation.startupSubtitle.thinkingBranches': 'Let your thinking branch out.',
    },
  },
};
