import type { MessageCatalogContribution } from '@app/localization';
import type { SystemMessageKey } from './systemMessages';

export const SYSTEM_MESSAGE_FALLBACKS = {
  'system.media.dialog.openFailed': '无法打开文件选择窗口，请稍后重试。',
  'system.media.dialog.sourceWindowMissing': '当前窗口不可用，无法打开文件选择窗口。',
  'system.media.file.invalidPath': '文件路径无效。',
  'system.media.file.notFile': '选择的路径不是文件。',
  'system.media.file.sizeFailed': '无法读取文件大小。',
  'system.media.image.loadFailed': '无法加载图片，请确认文件仍可访问。',
  'system.media.image.embedFailed': '无法把图片嵌入文档，请稍后重试。',
  'system.media.image.unknownMimeType': '无法识别图片格式。',
  'system.media.image.statFailed': '无法读取图片文件信息。',
  'system.media.generatedImage.loadFailed': '无法加载生成的图片，请确认文件仍可访问。',
  'system.media.audio.emptyData': '没有可保存的音频数据。',
  'system.media.audio.saveFailed': '保存音频文件失败。',
  'system.media.audio.loadFailed': '加载音频文件失败。',
  'system.export.dialog.openFileFailed': '无法打开文件选择窗口，请稍后重试。',
  'system.export.dialog.openDirectoryFailed': '无法打开目录选择窗口，请稍后重试。',
  'system.export.window.focusedMissing': '当前窗口不可用，无法导出文件。',
  'system.export.window.sourceMissing': '当前窗口不可用，无法导出 PDF。',
  'system.export.file.saveFailed': '保存导出文件失败。',
  'system.export.pdf.saveFailed': '生成或保存 PDF 失败。',
  'system.export.batch.invalidPayload': '批量导出请求无效。',
  'system.export.batch.directoryRequired': '缺少导出目录。',
  'system.export.batch.filesRequired': '缺少要导出的文件列表。',
  'system.export.batch.writeFailed': '批量写入导出文件失败。',
  'system.shell.external.openFailed': '无法打开外部链接。',
  'system.shell.external.urlRequired': '缺少要打开的链接。',
  'system.shell.external.urlInvalid': '链接格式无效。',
  'system.shell.external.unsupportedProtocol': '只能打开 http 或 https 链接。',
  'system.shell.item.pathRequired': '缺少要显示的文件路径。',
  'system.shell.item.showInFolderFailed': '无法在文件管理器中显示该项目。',
  'system.quota.idRequired': '缺少配额标识。',
  'system.quota.policyNotFound': '当前功能的配额规则未配置。',
  'system.quota.getFailed': '无法读取配额信息。',
  'system.quota.consumeFailed': '无法更新配额信息。',
  'system.transcription.failed': '音频转录失败，请稍后重试。',
  'system.transcription.modelUnavailable': '没有可用的音频转录模型，请先在设置中添加或启用一个。',
  'system.transcription.serviceUnavailable': '音频转录服务暂不可用，请稍后重试。',
  'system.transcription.audioFileMissing': '未找到要转录的音频文件。',
  'system.memoryDiagnostics.title': '内存诊断',
  'system.memoryDiagnostics.description': '录制 Linnya 各 Electron 进程的内存变化。关闭设置页不会停止录制；样本只保存在本次运行内存中。',
  'system.memoryDiagnostics.recording.title': '录制会话',
  'system.memoryDiagnostics.recording.description': '开始后每秒采样一次。完成目标操作后再等待一段时间，可以判断峰值是否正常回落。',
  'system.memoryDiagnostics.state.idle': '尚未录制',
  'system.memoryDiagnostics.state.recording': '正在录制',
  'system.memoryDiagnostics.state.stopped': '录制已停止',
  'system.memoryDiagnostics.samples': '个样本',
  'system.memoryDiagnostics.actions.start': '开始录制',
  'system.memoryDiagnostics.actions.stop': '停止录制',
  'system.memoryDiagnostics.actions.clear': '清空',
  'system.memoryDiagnostics.actions.sample': '立即采样',
  'system.memoryDiagnostics.actions.export': '导出报告',
  'system.memoryDiagnostics.summary.title': '会话摘要',
  'system.memoryDiagnostics.summary.baseline': '基线 Working Set',
  'system.memoryDiagnostics.summary.peak': '峰值 Working Set',
  'system.memoryDiagnostics.summary.latest': '当前 Working Set',
  'system.memoryDiagnostics.summary.delta': '相对基线',
  'system.memoryDiagnostics.summary.released': '峰值后释放',
  'system.memoryDiagnostics.summary.mainExternal': '主进程 External 峰值',
  'system.memoryDiagnostics.summary.mainArrayBuffers': '主进程 ArrayBuffer 峰值',
  'system.memoryDiagnostics.summary.rendererHeap': '界面 JS Heap 峰值',
  'system.memoryDiagnostics.summary.largestProcess': '最大单进程',
  'system.memoryDiagnostics.timeline.title': '内存时间线',
  'system.memoryDiagnostics.timeline.description': 'Working Set 可能包含共享内存；判断泄漏时应同时观察进程归属、主进程 External 和停止后的回落。',
  'system.memoryDiagnostics.timeline.ariaLabel': 'Linnya 进程内存时间线',
  'system.memoryDiagnostics.timeline.total': 'Electron 合计',
  'system.memoryDiagnostics.processes.title': '最新进程快照',
  'system.memoryDiagnostics.processes.process': '进程',
  'system.memoryDiagnostics.processes.workingSet': 'Working Set',
  'system.memoryDiagnostics.processes.private': 'Private',
  'system.memoryDiagnostics.processes.peak': '系统记录峰值',
  'system.memoryDiagnostics.role.main': '主进程',
  'system.memoryDiagnostics.role.renderer': '主界面 Renderer',
  'system.memoryDiagnostics.role.hiddenWorker': '隐藏 Worker',
  'system.memoryDiagnostics.role.gpu': 'GPU 进程',
  'system.memoryDiagnostics.role.utility': 'Utility 进程',
  'system.memoryDiagnostics.role.other': '其他进程',
  'system.memoryDiagnostics.marker.title': '会话标记',
  'system.memoryDiagnostics.marker.description': '为当前时间点添加说明，例如“开始 4K 导出”或“ZIP 保存完成”。',
  'system.memoryDiagnostics.marker.label': '标记',
  'system.memoryDiagnostics.marker.placeholder': '输入阶段说明',
  'system.memoryDiagnostics.marker.add': '添加',
  'system.memoryDiagnostics.export.saved': '内存诊断报告已导出。',
} as const satisfies Readonly<Record<SystemMessageKey, string>>;

export const SYSTEM_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'app-system',
  catalogs: {
    'zh-CN': SYSTEM_MESSAGE_FALLBACKS,
    'en-US': {
      'system.media.dialog.openFailed': 'Could not open the file picker. Please try again.',
      'system.media.dialog.sourceWindowMissing': 'The current window is unavailable, so the file picker cannot be opened.',
      'system.media.file.invalidPath': 'The file path is invalid.',
      'system.media.file.notFile': 'The selected path is not a file.',
      'system.media.file.sizeFailed': 'Could not read the file size.',
      'system.media.image.loadFailed': 'Could not load the image. Make sure the file is still accessible.',
      'system.media.image.embedFailed': 'Could not embed the image into the document. Please try again.',
      'system.media.image.unknownMimeType': 'The image format could not be recognized.',
      'system.media.image.statFailed': 'Could not read the image file information.',
      'system.media.generatedImage.loadFailed': 'Could not load the generated image. Make sure the file is still accessible.',
      'system.media.audio.emptyData': 'There is no audio data to save.',
      'system.media.audio.saveFailed': 'Failed to save the audio file.',
      'system.media.audio.loadFailed': 'Failed to load the audio file.',
      'system.export.dialog.openFileFailed': 'Could not open the file picker. Please try again.',
      'system.export.dialog.openDirectoryFailed': 'Could not open the folder picker. Please try again.',
      'system.export.window.focusedMissing': 'The current window is unavailable, so the file cannot be exported.',
      'system.export.window.sourceMissing': 'The current window is unavailable, so the PDF cannot be exported.',
      'system.export.file.saveFailed': 'Failed to save the exported file.',
      'system.export.pdf.saveFailed': 'Failed to generate or save the PDF.',
      'system.export.batch.invalidPayload': 'The batch export request is invalid.',
      'system.export.batch.directoryRequired': 'The export folder is missing.',
      'system.export.batch.filesRequired': 'The file list to export is missing.',
      'system.export.batch.writeFailed': 'Failed to write the exported files.',
      'system.shell.external.openFailed': 'Could not open the external link.',
      'system.shell.external.urlRequired': 'The link to open is missing.',
      'system.shell.external.urlInvalid': 'The link format is invalid.',
      'system.shell.external.unsupportedProtocol': 'Only http and https links can be opened.',
      'system.shell.item.pathRequired': 'The file path to show is missing.',
      'system.shell.item.showInFolderFailed': 'Could not show the item in the file manager.',
      'system.quota.idRequired': 'The quota id is missing.',
      'system.quota.policyNotFound': 'The quota rule for this feature is not configured.',
      'system.quota.getFailed': 'Could not read quota information.',
      'system.quota.consumeFailed': 'Could not update quota information.',
      'system.transcription.failed': 'Audio transcription failed. Please try again later.',
      'system.transcription.modelUnavailable': 'No audio transcription model is available. Add or enable one in Settings first.',
      'system.transcription.serviceUnavailable': 'Audio transcription is currently unavailable. Please try again later.',
      'system.transcription.audioFileMissing': 'The audio file to transcribe was not found.',
      'system.memoryDiagnostics.title': 'Memory Diagnostics',
      'system.memoryDiagnostics.description': 'Record memory changes across Linnya Electron processes. Closing Settings does not stop recording; samples stay in memory for this app run only.',
      'system.memoryDiagnostics.recording.title': 'Recording session',
      'system.memoryDiagnostics.recording.description': 'Samples are captured once per second. Wait after the target operation to see whether the peak returns to baseline.',
      'system.memoryDiagnostics.state.idle': 'Not recording',
      'system.memoryDiagnostics.state.recording': 'Recording',
      'system.memoryDiagnostics.state.stopped': 'Recording stopped',
      'system.memoryDiagnostics.samples': 'samples',
      'system.memoryDiagnostics.actions.start': 'Start recording',
      'system.memoryDiagnostics.actions.stop': 'Stop recording',
      'system.memoryDiagnostics.actions.clear': 'Clear',
      'system.memoryDiagnostics.actions.sample': 'Sample now',
      'system.memoryDiagnostics.actions.export': 'Export report',
      'system.memoryDiagnostics.summary.title': 'Session summary',
      'system.memoryDiagnostics.summary.baseline': 'Baseline working set',
      'system.memoryDiagnostics.summary.peak': 'Peak working set',
      'system.memoryDiagnostics.summary.latest': 'Current working set',
      'system.memoryDiagnostics.summary.delta': 'From baseline',
      'system.memoryDiagnostics.summary.released': 'Released after peak',
      'system.memoryDiagnostics.summary.mainExternal': 'Main external peak',
      'system.memoryDiagnostics.summary.mainArrayBuffers': 'Main ArrayBuffer peak',
      'system.memoryDiagnostics.summary.rendererHeap': 'UI JS heap peak',
      'system.memoryDiagnostics.summary.largestProcess': 'Largest process',
      'system.memoryDiagnostics.timeline.title': 'Memory timeline',
      'system.memoryDiagnostics.timeline.description': 'Working set may include shared pages. Use process ownership, main external memory, and post-operation release together when diagnosing leaks.',
      'system.memoryDiagnostics.timeline.ariaLabel': 'Linnya process memory timeline',
      'system.memoryDiagnostics.timeline.total': 'Electron total',
      'system.memoryDiagnostics.processes.title': 'Latest process snapshot',
      'system.memoryDiagnostics.processes.process': 'Process',
      'system.memoryDiagnostics.processes.workingSet': 'Working set',
      'system.memoryDiagnostics.processes.private': 'Private',
      'system.memoryDiagnostics.processes.peak': 'System peak',
      'system.memoryDiagnostics.role.main': 'Main process',
      'system.memoryDiagnostics.role.renderer': 'Main UI renderer',
      'system.memoryDiagnostics.role.hiddenWorker': 'Hidden worker',
      'system.memoryDiagnostics.role.gpu': 'GPU process',
      'system.memoryDiagnostics.role.utility': 'Utility process',
      'system.memoryDiagnostics.role.other': 'Other process',
      'system.memoryDiagnostics.marker.title': 'Session marker',
      'system.memoryDiagnostics.marker.description': 'Label the current moment, for example “start 4K export” or “ZIP saved”.',
      'system.memoryDiagnostics.marker.label': 'Marker',
      'system.memoryDiagnostics.marker.placeholder': 'Describe this stage',
      'system.memoryDiagnostics.marker.add': 'Add',
      'system.memoryDiagnostics.export.saved': 'The memory diagnostics report was exported.',
    },
  },
};
