export const SVG_NAMESPACE = 'http://www.w3.org/2000/svg';
export const XML_NAMESPACE = 'http://www.w3.org/XML/1998/namespace';
export const XMLNS_NAMESPACE = 'http://www.w3.org/2000/xmlns/';

export const ALLOWED_ELEMENTS = new Set([
  'svg',
  'defs',
  'g',
  'title',
  'desc',
  'rect',
  'circle',
  'ellipse',
  'line',
  'polyline',
  'polygon',
  'path',
  'text',
  'tspan',
  'linearGradient',
  'radialGradient',
  'stop',
  'marker',
]);

export const GLOBAL_ATTRIBUTES = new Set([
  'id',
  'fill',
  'stroke',
  'stroke-width',
  'opacity',
  'fill-opacity',
  'stroke-opacity',
  'stroke-dasharray',
  'stroke-linecap',
  'stroke-linejoin',
  'marker-start',
  'marker-mid',
  'marker-end',
  'transform',
]);

export const ELEMENT_ATTRIBUTES: Readonly<Record<string, ReadonlySet<string>>> = {
  svg: new Set(['xmlns', 'viewBox', 'width', 'height', 'preserveAspectRatio', 'version']),
  defs: new Set(),
  g: new Set(),
  title: new Set(['xml:space']),
  desc: new Set(['xml:space']),
  rect: new Set(['x', 'y', 'width', 'height', 'rx', 'ry']),
  circle: new Set(['cx', 'cy', 'r']),
  ellipse: new Set(['cx', 'cy', 'rx', 'ry']),
  line: new Set(['x1', 'y1', 'x2', 'y2']),
  polyline: new Set(['points']),
  polygon: new Set(['points']),
  path: new Set(['d']),
  text: new Set([
    'x',
    'y',
    'dx',
    'dy',
    'font-family',
    'font-size',
    'font-weight',
    'font-style',
    'text-anchor',
    'dominant-baseline',
    'letter-spacing',
    'xml:space',
  ]),
  tspan: new Set([
    'x',
    'y',
    'dx',
    'dy',
    'font-family',
    'font-size',
    'font-weight',
    'font-style',
    'text-anchor',
    'dominant-baseline',
    'letter-spacing',
    'xml:space',
  ]),
  linearGradient: new Set([
    'x1',
    'y1',
    'x2',
    'y2',
    'gradientUnits',
    'gradientTransform',
    'spreadMethod',
  ]),
  radialGradient: new Set([
    'cx',
    'cy',
    'r',
    'fx',
    'fy',
    'fr',
    'gradientUnits',
    'gradientTransform',
    'spreadMethod',
  ]),
  stop: new Set(['offset', 'stop-color', 'stop-opacity']),
  marker: new Set([
    'viewBox',
    'refX',
    'refY',
    'markerWidth',
    'markerHeight',
    'markerUnits',
    'orient',
    'preserveAspectRatio',
  ]),
};

export const GEOMETRY_NUMBER_ATTRIBUTES = new Set([
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'dx',
  'dy',
  'width',
  'height',
  'rx',
  'ry',
  'cx',
  'cy',
  'r',
  'fx',
  'fy',
  'fr',
  'refX',
  'refY',
  'markerWidth',
  'markerHeight',
  'stroke-width',
  'font-size',
  'letter-spacing',
]);

export const OPACITY_ATTRIBUTES = new Set([
  'opacity',
  'fill-opacity',
  'stroke-opacity',
  'stop-opacity',
]);

export const NON_NEGATIVE_NUMBER_ATTRIBUTES = new Set(['rx', 'ry', 'stroke-width']);

export const POSITIVE_NUMBER_ATTRIBUTES = new Set([
  'width',
  'height',
  'r',
  'markerWidth',
  'markerHeight',
  'font-size',
]);

export const CONTAINER_CHILDREN = new Set([
  'defs',
  'g',
  'rect',
  'circle',
  'ellipse',
  'line',
  'polyline',
  'polygon',
  'path',
  'text',
]);
