import type { MessageCatalogContribution } from '@app/localization';
import type { KnowledgeBaseMessageKey } from './knowledgeBaseMessages';

export const KNOWLEDGE_BASE_MESSAGE_FALLBACKS = {
  'knowledgeBase.common.defaultBadge': '默认',
  'knowledgeBase.common.unknown': '未知',
  'knowledgeBase.common.unknownKnowledgeBase': '未知知识库',
  'knowledgeBase.common.notFound': '这个知识库不存在或已被删除',
  'knowledgeBase.common.emptyDate': '—',
  'knowledgeBase.common.cancel': '取消',
  'knowledgeBase.common.delete': '删除',
  'knowledgeBase.common.file': '文件',
  'knowledgeBase.common.size': '大小',
  'knowledgeBase.common.knowledgeBase': '知识库',
  'knowledgeBase.common.status': '状态',
  'knowledgeBase.common.progress': '进度',
  'knowledgeBase.common.actions': '操作',
  'knowledgeBase.common.retry': '重试',
  'knowledgeBase.common.clear': '清除',
  'knowledgeBase.common.no': '无',
  'knowledgeBase.common.add': '添加',
  'knowledgeBase.modal.title': '知识库管理',
  'knowledgeBase.list.title': '知识库',
  'knowledgeBase.list.subtitle': '管理项目中的文档，让 AI 搜索、阅读和理解外部知识。',
  'knowledgeBase.list.meta.count': '共 {count} 个知识库',
  'knowledgeBase.list.action.create': '新建知识库',
  'knowledgeBase.list.action.globalUpload': '文件上传',
  'knowledgeBase.list.grid.ariaLabel': '知识库列表',
  'knowledgeBase.list.card.emptyDescription': '暂无简介',
  'knowledgeBase.list.card.documentCount': '{count} 篇文档',
  'knowledgeBase.list.createCard.title': '新建知识库',
  'knowledgeBase.list.createCard.description': '为不同项目或场景创建独立空间，单独上传和管理文件。',
  'knowledgeBase.list.empty.title': '暂无知识库',
  'knowledgeBase.list.empty.description': '创建一个知识库，用于存放手册、技术文档、会议纪要或设计稿等内容。',
  'knowledgeBase.list.empty.createFirst': '新建第一个知识库',
  'knowledgeBase.detail.backTitle': '返回列表',
  'knowledgeBase.detail.tabs.ariaLabel': '知识库操作',
  'knowledgeBase.detail.tabs.upload': '文件上传',
  'knowledgeBase.detail.tabs.manage': '文件管理',
  'knowledgeBase.detail.tabs.settings': '知识库设置',
  'knowledgeBase.detail.tabs.parsing': '解析设置',
  'knowledgeBase.detail.meta.updatedAt': '最近更新：{date}',
  'knowledgeBase.detail.meta.documentCount': '共计 {count} 篇文档',
  'knowledgeBase.globalUpload.title': '文件上传管理',
  'knowledgeBase.globalUpload.targetLabel': '知识库',
  'knowledgeBase.globalUpload.placeholder': '选择知识库',
  'knowledgeBase.globalUpload.selectTitle': '选择上传目标知识库',
  'knowledgeBase.globalUpload.hint': '这里展示所有知识库的上传/解析任务；新添加的文件会进入当前选择的知识库。',
  'knowledgeBase.addTo.title': '添加到知识库',
  'knowledgeBase.addTo.documentLabel': '将添加文档：',
  'knowledgeBase.addTo.targetLabel': '目标知识库',
  'knowledgeBase.addTo.placeholder': '选择知识库',
  'knowledgeBase.addTo.selectTitle': '选择目标知识库',
  'knowledgeBase.addTo.hint': '文档将被解析并存入知识库，供 AI 检索和引用。',
  'knowledgeBase.addTo.confirm': '确定',
  'knowledgeBase.addTo.untitledDocument': '未命名文档',
  'knowledgeBase.addTo.error.targetRequired': '请选择目标知识库',
  'knowledgeBase.addTo.error.editorUnavailable': '编辑器实例不可用',
  'knowledgeBase.addTo.error.emptyDocument': '文档内容为空，无法添加到知识库',
  'knowledgeBase.addTo.error.unknown': '未知错误',
  'knowledgeBase.create.title': '新建知识库',
  'knowledgeBase.create.nameLabel': '知识库名称',
  'knowledgeBase.create.namePlaceholder': '请输入知识库名称',
  'knowledgeBase.create.descriptionLabel': '知识库描述',
  'knowledgeBase.create.descriptionPlaceholder': '可选：简单说明这个知识库里主要放什么内容',
  'knowledgeBase.create.tagsLabel': '知识库标签',
  'knowledgeBase.create.tagPlaceholder': '添加标签...',
  'knowledgeBase.create.projectsLabel': '关联项目',
  'knowledgeBase.create.projectPlaceholder': '选择项目...',
  'knowledgeBase.create.projectSelectTitle': '选择要关联的项目',
  'knowledgeBase.create.creating': '创建中...',
  'knowledgeBase.create.create': '创建',
  'knowledgeBase.create.error.nameRequired': '知识库名称不能为空',
  'knowledgeBase.create.error.saveTagsFailed': '保存标签失败，请重试（可查看日志定位原因）',
  'knowledgeBase.create.error.linkProjectsFailed': '更新知识库关联项目失败',
  'knowledgeBase.create.error.linkProjectsIpcFailed': '关联项目失败：IPC 调用异常，请查看日志',
  'knowledgeBase.create.error.createFailed': '创建知识库失败',
  'knowledgeBase.upload.dropTitle': '拖拽文件或文件夹到此区域',
  'knowledgeBase.upload.dropSubtitle': '或点击选择文件',
  'knowledgeBase.upload.supportedFileTypes': '支持的文件类型：{types}',
  'knowledgeBase.upload.controlHint': '上传文件后会出现在下方列表中，确认无误后点击右侧「开始解析」',
  'knowledgeBase.upload.scopeHint.beforeLink': '仅显示当前知识库的任务。需要查看全局任务，请点击',
  'knowledgeBase.upload.scopeHint.link': '这里',
  'knowledgeBase.upload.scopeHint.afterLink': '。',
  'knowledgeBase.upload.pdfForceOcrLimit': '已开启强制 OCR 解析：PDF 会受当前 OCR 模型页数上限影响，超出上限会被拒绝。',
  'knowledgeBase.upload.startParsing': '开始解析',
  'knowledgeBase.upload.empty.title': '暂无文件',
  'knowledgeBase.upload.empty.description': '将文件拖拽到上方上传区域，或点击上传区域选择文件',
  'knowledgeBase.upload.action.cancel': '取消',
  'knowledgeBase.upload.action.delete': '删除',
  'knowledgeBase.upload.toast.skippedDuplicate': '已跳过 {count} 个重复文件',
  'knowledgeBase.upload.status.waiting': '等待中',
  'knowledgeBase.upload.status.waitingRetry': '等待重试',
  'knowledgeBase.upload.status.uploading': '上传中',
  'knowledgeBase.upload.status.parsing': '解析中',
  'knowledgeBase.upload.status.processing': '处理中',
  'knowledgeBase.upload.status.completed': '已完成',
  'knowledgeBase.upload.status.duplicate': '重复文件',
  'knowledgeBase.upload.status.failed': '上传失败',
  'knowledgeBase.upload.status.canceled': '已取消',
  'knowledgeBase.upload.error.currentConfigMissing': '未找到当前知识库配置，请刷新后重试。',
  'knowledgeBase.upload.error.embeddingModelRequired': "请在'模型配置'标签页中选择有效的嵌入模型。",
  'knowledgeBase.upload.error.failed': '上传失败',
  'knowledgeBase.upload.error.canceledByUser': '用户取消',
  'knowledgeBase.service.error.apiBaseUrlUnavailable': '未能获取到 API 基础 URL',
  'knowledgeBase.service.error.getAllIpcFailed': '获取知识库列表失败（IPC）',
  'knowledgeBase.service.create.success': '知识库创建成功',
  'knowledgeBase.service.error.createIpcFailed': '创建知识库失败（IPC）',
  'knowledgeBase.service.error.deleteIpcFailed': '删除知识库失败（IPC）: {knowledgeBaseId}',
  'knowledgeBase.service.error.getDocumentsIpcFailed': '获取知识库 {knowledgeBaseId} 的文档失败（IPC）',
  'knowledgeBase.service.error.updateSettingsIpcFailed': '更新知识库 {knowledgeBaseId} 设置失败（IPC）',
  'knowledgeBase.service.error.searchFailed': '知识库搜索失败，请稍后重试。',
  'knowledgeBase.service.error.server': '服务器错误: {statusCode}',
  'knowledgeBase.service.error.network': '网络错误: 无法连接到服务器。',
  'knowledgeBase.service.error.requestSetup': '请求设置错误，请稍后重试。',
  'knowledgeBase.store.error.fetchListFailed': '获取知识库列表失败，请稍后重试。',
  'knowledgeBase.store.error.fetchDocumentsFailed': '获取文档列表失败，请稍后重试。',
  'knowledgeBase.store.error.updateModelSettingsFailed': '更新模型配置失败，请稍后重试。',
  'knowledgeBase.store.error.deleteKnowledgeBaseFailed': '删除知识库失败，请稍后重试。',
  'knowledgeBase.manage.uploadTime': '上传时间',
  'knowledgeBase.manage.parseStatus': '解析状态',
  'knowledgeBase.manage.parseStatus.completed': '已完成',
  'knowledgeBase.manage.parseStatus.partial': '部分成功 {parsed}/{total}',
  'knowledgeBase.manage.continueFailedPages.action': '继续解析',
  'knowledgeBase.manage.continueFailedPages.running': '解析中...',
  'knowledgeBase.manage.continueFailedPages.failed': '继续解析失败，请稍后重试',
  'knowledgeBase.manage.clearFiles': '清空文件',
  'knowledgeBase.manage.clearing': '清空中...',
  'knowledgeBase.manage.empty.title': '暂无文件',
  'knowledgeBase.manage.empty.description': '当前知识库中暂无文件，请先在上方「文件上传」标签中添加文档',
  'knowledgeBase.manage.clearDialog.title': '确认清空知识库',
  'knowledgeBase.manage.clearDialog.message': "该操作会彻底删除知识库 '{knowledgeBaseName}' 中的所有文件且不可恢复。\n\n是否确认删除？",
  'knowledgeBase.manage.clearDialog.confirm': '确认删除',
  'knowledgeBase.manage.errorDialog.title': '操作失败',
  'knowledgeBase.manage.deleteDocument.confirm': '确定要删除文档 "{fileName}" 吗？',
  'knowledgeBase.manage.deleteDocument.failed': '删除文档失败',
  'knowledgeBase.manage.clearPartialFailed': '操作有部分失败。已删除 {deletedCount} 个文件, 但以下 {failedCount} 个文件删除失败: {failedNames}',
  'knowledgeBase.settings.basicInfo': '基础信息',
  'knowledgeBase.settings.save': '保存',
  'knowledgeBase.settings.saving': '保存中...',
  'knowledgeBase.settings.nameLabel': '知识库名称',
  'knowledgeBase.settings.namePlaceholder': '请输入知识库名称',
  'knowledgeBase.settings.descriptionLabel': '知识库描述',
  'knowledgeBase.settings.descriptionPlaceholder': '可选：简要说明该知识库的用途',
  'knowledgeBase.settings.tagsLabel': '知识库标签',
  'knowledgeBase.settings.tagPlaceholder': '添加标签...',
  'knowledgeBase.settings.noTags': '暂无标签',
  'knowledgeBase.settings.projects': '关联项目',
  'knowledgeBase.settings.linkedProjects': '已关联项目',
  'knowledgeBase.settings.availableProjects': '可关联项目',
  'knowledgeBase.settings.unlinkTitle': '解除关联',
  'knowledgeBase.settings.linkTitle': '关联到知识库',
  'knowledgeBase.settings.noLinkedProjects': '暂未关联任何项目',
  'knowledgeBase.settings.noAvailableProjects': '暂无可关联项目',
  'knowledgeBase.settings.danger.title': '删除知识库',
  'knowledgeBase.settings.danger.description': '删除后将移除该知识库及其所有文档，此操作不可撤销。',
  'knowledgeBase.settings.danger.deleteCurrent': '删除当前知识库',
  'knowledgeBase.settings.deleteDialog.title': '删除知识库',
  'knowledgeBase.settings.deleteDialog.message': '确定要删除「{knowledgeBaseName}」吗？\n此操作不可撤销，知识库及其文档将被永久移除。',
  'knowledgeBase.settings.placeholderName': '示例知识库名称',
  'knowledgeBase.settings.placeholderDescription': '这里是知识库描述的占位示例，接入后端后会展示真实描述信息。',
  'knowledgeBase.settings.untitledName': '未命名知识库',
  'knowledgeBase.settings.toast.deleted': '知识库已删除',
  'knowledgeBase.settings.toast.saved': '知识库信息已保存',
  'knowledgeBase.settings.error.deleteFailed': '删除知识库失败',
  'knowledgeBase.settings.error.saveFailed': '保存知识库信息失败',
  'knowledgeBase.settings.error.linkProjectsFailed': '更新知识库关联项目失败',
  'knowledgeBase.settings.error.defaultDeleteBlocked': '默认知识库不能删除',
  'knowledgeBase.graph.ariaLabel': '知识图谱构建进度',
  'knowledgeBase.graph.popover.progress': '进度：{percent}',
  'knowledgeBase.graph.status.notStarted': '知识图谱尚未构建',
  'knowledgeBase.graph.status.completed': '知识图谱已构建完成',
  'knowledgeBase.graph.status.inProgress': '正在构建知识图谱',
  'knowledgeBase.graph.tooltip.withPercent': '{statusText}（{percent}%）',
  'knowledgeBase.graph.tooltip.empty': '{statusText}（—）',
  'knowledgeBase.graph.error.progressLoadFailed': '加载知识图谱进度失败',
  'knowledgeBase.parsing.settings.title': '解析设置',
  'knowledgeBase.parsing.modelSettings.open': '模型解析设置',
  'knowledgeBase.parsing.graph.title': '知识图谱构建',
  'knowledgeBase.parsing.scope.current': '仅当前知识库',
  'knowledgeBase.parsing.graph.description': '启用后，系统会在文档摄入完成后异步构建知识图谱，用于增强搜索与深度研究。\n关闭后不再对新文档进行图谱构建，但已建立的图谱仍可正常用于搜索增强。',
  'knowledgeBase.parsing.resourceNote': '注意：处理时间较长，会消耗更多 AI 资源。',
  'knowledgeBase.parsing.pdfStrategy.title': 'PDF 解析策略',
  'knowledgeBase.parsing.scope.all': '适用于所有知识库',
  'knowledgeBase.parsing.pdfStrategy.description': '智能解析会优先使用可复制文本，必要时再进入 OCR；强制 OCR 会让 PDF 直接走所选 OCR 引擎。',
  'knowledgeBase.parsing.pdfStrategy.selectTitle': '选择 PDF 解析策略',
  'knowledgeBase.parsing.pdfStrategy.smart': '智能解析',
  'knowledgeBase.parsing.pdfStrategy.forceOcr': '强制 OCR',
  'knowledgeBase.parsing.pdfStrategy.note': '强制 OCR 会更慢，并消耗更多 AI 资源。',
  'knowledgeBase.parsing.toast.noKnowledgeBase': '未选中知识库，无法更新设置',
  'knowledgeBase.parsing.toast.updateFailed': '更新失败，请稍后重试',
  'knowledgeBase.parsing.toast.graphEnabled': '已启用知识图谱构建',
  'knowledgeBase.parsing.toast.graphDisabled': '已关闭知识图谱构建',
} as const satisfies Readonly<Record<KnowledgeBaseMessageKey, string>>;

export const KNOWLEDGE_BASE_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'knowledgebase',
  catalogs: {
    'zh-CN': KNOWLEDGE_BASE_MESSAGE_FALLBACKS,
    'en-US': {
      'knowledgeBase.common.defaultBadge': 'Default',
      'knowledgeBase.common.unknown': 'Unknown',
      'knowledgeBase.common.unknownKnowledgeBase': 'Unknown knowledge base',
      'knowledgeBase.common.notFound': 'This knowledge base does not exist or has been deleted',
      'knowledgeBase.common.emptyDate': '—',
      'knowledgeBase.common.cancel': 'Cancel',
      'knowledgeBase.common.delete': 'Delete',
      'knowledgeBase.common.file': 'File',
      'knowledgeBase.common.size': 'Size',
      'knowledgeBase.common.knowledgeBase': 'Knowledge base',
      'knowledgeBase.common.status': 'Status',
      'knowledgeBase.common.progress': 'Progress',
      'knowledgeBase.common.actions': 'Actions',
      'knowledgeBase.common.retry': 'Retry',
      'knowledgeBase.common.clear': 'Clear',
      'knowledgeBase.common.no': 'None',
      'knowledgeBase.common.add': 'Add',
      'knowledgeBase.modal.title': 'Knowledge base management',
      'knowledgeBase.list.title': 'Knowledge Base',
      'knowledgeBase.list.subtitle': 'Manage project documents so AI can search, read, and understand external knowledge.',
      'knowledgeBase.list.meta.count': '{count} knowledge bases',
      'knowledgeBase.list.action.create': 'New knowledge base',
      'knowledgeBase.list.action.globalUpload': 'File upload',
      'knowledgeBase.list.grid.ariaLabel': 'Knowledge base list',
      'knowledgeBase.list.card.emptyDescription': 'No description yet',
      'knowledgeBase.list.card.documentCount': '{count} documents',
      'knowledgeBase.list.createCard.title': 'New knowledge base',
      'knowledgeBase.list.createCard.description': 'Create a separate space for each project or scenario, with its own uploads and file management.',
      'knowledgeBase.list.empty.title': 'No knowledge bases yet',
      'knowledgeBase.list.empty.description': 'Create a knowledge base for manuals, technical docs, meeting notes, design files, and more.',
      'knowledgeBase.list.empty.createFirst': 'Create first knowledge base',
      'knowledgeBase.detail.backTitle': 'Back to list',
      'knowledgeBase.detail.tabs.ariaLabel': 'Knowledge base actions',
      'knowledgeBase.detail.tabs.upload': 'File upload',
      'knowledgeBase.detail.tabs.manage': 'File management',
      'knowledgeBase.detail.tabs.settings': 'Knowledge base settings',
      'knowledgeBase.detail.tabs.parsing': 'Parsing settings',
      'knowledgeBase.detail.meta.updatedAt': 'Updated: {date}',
      'knowledgeBase.detail.meta.documentCount': 'Total documents: {count}',
      'knowledgeBase.globalUpload.title': 'File Upload Manager',
      'knowledgeBase.globalUpload.targetLabel': 'Knowledge base',
      'knowledgeBase.globalUpload.placeholder': 'Choose knowledge base',
      'knowledgeBase.globalUpload.selectTitle': 'Choose upload target knowledge base',
      'knowledgeBase.globalUpload.hint': 'This shows upload and parsing tasks for all knowledge bases. Newly added files will go into the currently selected knowledge base.',
      'knowledgeBase.addTo.title': 'Add to Knowledge Base',
      'knowledgeBase.addTo.documentLabel': 'Document to add:',
      'knowledgeBase.addTo.targetLabel': 'Target knowledge base',
      'knowledgeBase.addTo.placeholder': 'Choose knowledge base',
      'knowledgeBase.addTo.selectTitle': 'Choose target knowledge base',
      'knowledgeBase.addTo.hint': 'The document will be parsed and stored in the knowledge base for AI search and citation.',
      'knowledgeBase.addTo.confirm': 'Confirm',
      'knowledgeBase.addTo.untitledDocument': 'Untitled document',
      'knowledgeBase.addTo.error.targetRequired': 'Choose a target knowledge base',
      'knowledgeBase.addTo.error.editorUnavailable': 'Editor instance is unavailable',
      'knowledgeBase.addTo.error.emptyDocument': 'The document is empty and cannot be added to the knowledge base',
      'knowledgeBase.addTo.error.unknown': 'Unknown error',
      'knowledgeBase.create.title': 'New knowledge base',
      'knowledgeBase.create.nameLabel': 'Knowledge base name',
      'knowledgeBase.create.namePlaceholder': 'Enter knowledge base name',
      'knowledgeBase.create.descriptionLabel': 'Knowledge base description',
      'knowledgeBase.create.descriptionPlaceholder': 'Optional: briefly describe what this knowledge base will contain',
      'knowledgeBase.create.tagsLabel': 'Knowledge base tags',
      'knowledgeBase.create.tagPlaceholder': 'Add tag...',
      'knowledgeBase.create.projectsLabel': 'Linked projects',
      'knowledgeBase.create.projectPlaceholder': 'Choose project...',
      'knowledgeBase.create.projectSelectTitle': 'Choose project to link',
      'knowledgeBase.create.creating': 'Creating...',
      'knowledgeBase.create.create': 'Create',
      'knowledgeBase.create.error.nameRequired': 'Knowledge base name is required',
      'knowledgeBase.create.error.saveTagsFailed': 'Failed to save tags. Please retry. Check logs for details.',
      'knowledgeBase.create.error.linkProjectsFailed': 'Failed to update linked projects',
      'knowledgeBase.create.error.linkProjectsIpcFailed': 'Failed to link projects: IPC call failed. Check logs for details.',
      'knowledgeBase.create.error.createFailed': 'Failed to create knowledge base',
      'knowledgeBase.upload.dropTitle': 'Drag files or folders here',
      'knowledgeBase.upload.dropSubtitle': 'or click to choose files',
      'knowledgeBase.upload.supportedFileTypes': 'Supported file types: {types}',
      'knowledgeBase.upload.controlHint': 'Uploaded files appear below. After checking them, click "Start parsing" on the right.',
      'knowledgeBase.upload.scopeHint.beforeLink': 'Only tasks for the current knowledge base are shown. To view all tasks, click',
      'knowledgeBase.upload.scopeHint.link': 'here',
      'knowledgeBase.upload.scopeHint.afterLink': '.',
      'knowledgeBase.upload.pdfForceOcrLimit': 'Forced OCR parsing is enabled. PDFs are limited by the selected OCR model page cap and will be rejected when they exceed it.',
      'knowledgeBase.upload.startParsing': 'Start parsing',
      'knowledgeBase.upload.empty.title': 'No files yet',
      'knowledgeBase.upload.empty.description': 'Drag files to the upload area above, or click the upload area to choose files',
      'knowledgeBase.upload.action.cancel': 'Cancel',
      'knowledgeBase.upload.action.delete': 'Delete',
      'knowledgeBase.upload.toast.skippedDuplicate': 'Skipped {count} duplicate files',
      'knowledgeBase.upload.status.waiting': 'Waiting',
      'knowledgeBase.upload.status.waitingRetry': 'Waiting to retry',
      'knowledgeBase.upload.status.uploading': 'Uploading',
      'knowledgeBase.upload.status.parsing': 'Parsing',
      'knowledgeBase.upload.status.processing': 'Processing',
      'knowledgeBase.upload.status.completed': 'Completed',
      'knowledgeBase.upload.status.duplicate': 'Duplicate file',
      'knowledgeBase.upload.status.failed': 'Upload failed',
      'knowledgeBase.upload.status.canceled': 'Canceled',
      'knowledgeBase.upload.error.currentConfigMissing': 'Current knowledge base configuration was not found. Refresh and try again.',
      'knowledgeBase.upload.error.embeddingModelRequired': 'Choose a valid embedding model in the Model configuration tab.',
      'knowledgeBase.upload.error.failed': 'Upload failed',
      'knowledgeBase.upload.error.canceledByUser': 'Canceled by user',
      'knowledgeBase.service.error.apiBaseUrlUnavailable': 'Could not get the API base URL',
      'knowledgeBase.service.error.getAllIpcFailed': 'Failed to get knowledge base list (IPC)',
      'knowledgeBase.service.create.success': 'Knowledge base created',
      'knowledgeBase.service.error.createIpcFailed': 'Failed to create knowledge base (IPC)',
      'knowledgeBase.service.error.deleteIpcFailed': 'Failed to delete knowledge base (IPC): {knowledgeBaseId}',
      'knowledgeBase.service.error.getDocumentsIpcFailed': 'Failed to get documents for knowledge base {knowledgeBaseId} (IPC)',
      'knowledgeBase.service.error.updateSettingsIpcFailed': 'Failed to update settings for knowledge base {knowledgeBaseId} (IPC)',
      'knowledgeBase.service.error.searchFailed': 'Knowledge base search failed. Please try again.',
      'knowledgeBase.service.error.server': 'Server error: {statusCode}',
      'knowledgeBase.service.error.network': 'Network error: could not connect to the server.',
      'knowledgeBase.service.error.requestSetup': 'Request setup failed. Please try again.',
      'knowledgeBase.store.error.fetchListFailed': 'Failed to fetch knowledge base list. Please try again.',
      'knowledgeBase.store.error.fetchDocumentsFailed': 'Failed to fetch document list. Please try again.',
      'knowledgeBase.store.error.updateModelSettingsFailed': 'Failed to update model configuration. Please try again.',
      'knowledgeBase.store.error.deleteKnowledgeBaseFailed': 'Failed to delete knowledge base. Please try again.',
      'knowledgeBase.manage.uploadTime': 'Uploaded',
      'knowledgeBase.manage.parseStatus': 'Parse status',
      'knowledgeBase.manage.parseStatus.completed': 'Completed',
      'knowledgeBase.manage.parseStatus.partial': 'Partial {parsed}/{total}',
      'knowledgeBase.manage.continueFailedPages.action': 'Continue',
      'knowledgeBase.manage.continueFailedPages.running': 'Parsing...',
      'knowledgeBase.manage.continueFailedPages.failed': 'Continue parsing failed. Please try again.',
      'knowledgeBase.manage.clearFiles': 'Clear files',
      'knowledgeBase.manage.clearing': 'Clearing...',
      'knowledgeBase.manage.empty.title': 'No files yet',
      'knowledgeBase.manage.empty.description': 'There are no files in this knowledge base. Add documents from the File Upload tab above.',
      'knowledgeBase.manage.clearDialog.title': 'Confirm clearing knowledge base',
      'knowledgeBase.manage.clearDialog.message': "This will permanently delete all files in knowledge base '{knowledgeBaseName}' and cannot be undone.\n\nDelete them?",
      'knowledgeBase.manage.clearDialog.confirm': 'Confirm delete',
      'knowledgeBase.manage.errorDialog.title': 'Operation failed',
      'knowledgeBase.manage.deleteDocument.confirm': 'Delete document "{fileName}"?',
      'knowledgeBase.manage.deleteDocument.failed': 'Failed to delete document',
      'knowledgeBase.manage.clearPartialFailed': 'Part of the operation failed. Deleted {deletedCount} files, but these {failedCount} files failed: {failedNames}',
      'knowledgeBase.settings.basicInfo': 'Basic info',
      'knowledgeBase.settings.save': 'Save',
      'knowledgeBase.settings.saving': 'Saving...',
      'knowledgeBase.settings.nameLabel': 'Knowledge base name',
      'knowledgeBase.settings.namePlaceholder': 'Enter knowledge base name',
      'knowledgeBase.settings.descriptionLabel': 'Knowledge base description',
      'knowledgeBase.settings.descriptionPlaceholder': 'Optional: briefly describe what this knowledge base is for',
      'knowledgeBase.settings.tagsLabel': 'Knowledge base tags',
      'knowledgeBase.settings.tagPlaceholder': 'Add tag...',
      'knowledgeBase.settings.noTags': 'No tags yet',
      'knowledgeBase.settings.projects': 'Linked projects',
      'knowledgeBase.settings.linkedProjects': 'Linked projects',
      'knowledgeBase.settings.availableProjects': 'Available projects',
      'knowledgeBase.settings.unlinkTitle': 'Unlink',
      'knowledgeBase.settings.linkTitle': 'Link to knowledge base',
      'knowledgeBase.settings.noLinkedProjects': 'No linked projects yet',
      'knowledgeBase.settings.noAvailableProjects': 'No projects available to link',
      'knowledgeBase.settings.danger.title': 'Delete knowledge base',
      'knowledgeBase.settings.danger.description': 'Deleting removes this knowledge base and all its documents. This cannot be undone.',
      'knowledgeBase.settings.danger.deleteCurrent': 'Delete current knowledge base',
      'knowledgeBase.settings.deleteDialog.title': 'Delete knowledge base',
      'knowledgeBase.settings.deleteDialog.message': 'Delete "{knowledgeBaseName}"?\nThis cannot be undone. The knowledge base and its documents will be permanently removed.',
      'knowledgeBase.settings.placeholderName': 'Example knowledge base name',
      'knowledgeBase.settings.placeholderDescription': 'This is placeholder text for the knowledge base description. Real backend data will be shown here when connected.',
      'knowledgeBase.settings.untitledName': 'Untitled knowledge base',
      'knowledgeBase.settings.toast.deleted': 'Knowledge base deleted',
      'knowledgeBase.settings.toast.saved': 'Knowledge base info saved',
      'knowledgeBase.settings.error.deleteFailed': 'Failed to delete knowledge base',
      'knowledgeBase.settings.error.saveFailed': 'Failed to save knowledge base info',
      'knowledgeBase.settings.error.linkProjectsFailed': 'Failed to update linked projects',
      'knowledgeBase.settings.error.defaultDeleteBlocked': 'The default knowledge base cannot be deleted',
      'knowledgeBase.graph.ariaLabel': 'Knowledge graph build progress',
      'knowledgeBase.graph.popover.progress': 'Progress: {percent}',
      'knowledgeBase.graph.status.notStarted': 'Knowledge graph has not been built',
      'knowledgeBase.graph.status.completed': 'Knowledge graph build complete',
      'knowledgeBase.graph.status.inProgress': 'Building knowledge graph',
      'knowledgeBase.graph.tooltip.withPercent': '{statusText} ({percent}%)',
      'knowledgeBase.graph.tooltip.empty': '{statusText} (—)',
      'knowledgeBase.graph.error.progressLoadFailed': 'Failed to load knowledge graph progress',
      'knowledgeBase.parsing.settings.title': 'Parsing settings',
      'knowledgeBase.parsing.modelSettings.open': 'Model parsing settings',
      'knowledgeBase.parsing.graph.title': 'Knowledge graph build',
      'knowledgeBase.parsing.scope.current': 'Current knowledge base only',
      'knowledgeBase.parsing.graph.description': 'When enabled, the system builds a knowledge graph asynchronously after document ingestion to improve search and deep research.\nWhen disabled, new documents will not trigger graph building, but existing graphs remain available for search enhancement.',
      'knowledgeBase.parsing.resourceNote': 'Note: this takes longer and consumes more AI resources.',
      'knowledgeBase.parsing.pdfStrategy.title': 'PDF parsing strategy',
      'knowledgeBase.parsing.scope.all': 'Applies to all knowledge bases',
      'knowledgeBase.parsing.pdfStrategy.description': 'Smart parsing prefers selectable text first and uses OCR only when needed. Forced OCR sends PDFs directly to the selected OCR engine.',
      'knowledgeBase.parsing.pdfStrategy.selectTitle': 'Choose PDF parsing strategy',
      'knowledgeBase.parsing.pdfStrategy.smart': 'Smart',
      'knowledgeBase.parsing.pdfStrategy.forceOcr': 'Force OCR',
      'knowledgeBase.parsing.pdfStrategy.note': 'Forced OCR is slower and consumes more AI resources.',
      'knowledgeBase.parsing.toast.noKnowledgeBase': 'No knowledge base selected, so settings cannot be updated',
      'knowledgeBase.parsing.toast.updateFailed': 'Update failed. Please try again later.',
      'knowledgeBase.parsing.toast.graphEnabled': 'Knowledge graph build enabled',
      'knowledgeBase.parsing.toast.graphDisabled': 'Knowledge graph build disabled',
    },
  },
};
