import type { MessageCatalogContribution } from '@app/localization';
import type { LayoutMessageKey } from './layoutMessages';

export const LAYOUT_MESSAGE_FALLBACKS = {
  'layout.header.sidebar': '侧边栏',
  'layout.header.knowledgeBase': '知识库',
  'layout.header.settings': '设置',
  'layout.header.newConversation': '新对话',
  'layout.header.history': '历史对话',
  'layout.header.moreMenu': '更多菜单',
  'layout.header.markdownDocumentMenu': '当前 Markdown 文档菜单',
  'layout.header.noMarkdownDocument': '当前没有打开的 Markdown 文档',
  'layout.header.pluginDocumentMenu': '当前插件文档菜单',
  'layout.header.swapPanes': '交换对话和文档位置',
  'layout.header.rightPane.toggle': '展开或收起右侧栏',
  'layout.header.rightPane.expand': '展开右侧栏',
  'layout.header.rightPane.collapse': '收起右侧栏',
  'layout.header.rightPane.windowTooNarrow': '窗口过窄，无法同时显示两个窗口',
  'layout.header.swap.documentToMain': '文档放到中间',
  'layout.header.swap.conversationToMain': '对话放到中间',
  'layout.header.panel.close': '关闭',
  'layout.header.window.minimize': '最小化',
  'layout.header.window.maximizeRestore': '最大化/恢复',
  'layout.header.untitledProject': '未命名项目',
  'layout.header.projectSetup': 'AI 项目初始化',
  'layout.header.timeline.empty': '暂无时间轴',
  'layout.header.timeline.expand': '展开时间轴',
  'layout.header.timeline.collapse': '收缩时间轴',
  'layout.header.review': 'AI 审阅',
  'layout.header.documentMenu.export': '导出',
  'layout.header.documentMenu.exportTxt': '导出为 TXT',
  'layout.header.documentMenu.exportMarkdown': '导出为 Markdown',
  'layout.header.documentMenu.exportPdf': '导出为 PDF',
  'layout.header.documentMenu.exportDocx': '导出为 DOCX',
  'layout.header.documentMenu.review': '审阅此文档',
  'layout.header.documentMenu.addToKnowledgeBase': '添加到知识库',
  'layout.header.untitledDocument': '未命名文档',
  'layout.header.addToKnowledgeBase.editorUnavailable': '编辑器实例不可用，无法添加到知识库',
  'layout.header.addToKnowledgeBase.success': '已将「{fileName}」加入上传队列，正在解析入库',
  'layout.header.addToKnowledgeBase.failed': '添加到知识库失败，请稍后重试。',
  'layout.header.documentMenu.unavailable': '当前没有打开的 Markdown 文档，无法使用文档菜单',
  'layout.sidebar.nav.newConversation': '新对话',
  'layout.sidebar.nav.newProject': '新项目',
  'layout.sidebar.nav.knowledgeBase': '知识库',
  'layout.sidebar.nav.plugins': '插件',
  'layout.sidebar.project.back': '返回',
  'layout.sidebar.project.viewGroup': '项目侧栏视图',
  'layout.sidebar.project.chat': '对话',
  'layout.sidebar.project.files': '文件',
  'layout.sidebar.project.newConversation': '新对话',
  'layout.sidebar.project.searchChats': '搜索对话',
  'layout.sidebar.project.create': '新建',
  'layout.sidebar.project.searchFiles': '搜索文件',
  'layout.sidebar.project.planningConversationTitle': '{projectName} - 项目规划',
  'layout.sidebar.assetPreview.loadingImage': '正在加载图片...',
  'layout.sidebar.assetPreview.loadingText': '正在读取内容...',
  'layout.sidebar.assetPreview.close': '关闭预览',
  'layout.pane.resizeSidebar': '调整左侧栏宽度',
  'layout.pane.resizeDocument': '调整文档宽度',
  'layout.pane.resizeConversation': '调整对话宽度',
  'layout.projectSetup.generate': '完成并生成',
  'layout.projectSetup.skip': '跳过',
  'layout.projectSetup.generating': '生成中...',
  'layout.projectSetup.refreshAfterGenerationFailed': '生成完成，但刷新文件列表时出错，请手动刷新',
  'layout.projectSetup.sendMessageFailed': '发送消息失败',
  'layout.projectSetup.sendGenerateCommandFailed': '发送生成指令失败，请稍后重试。',
  'layout.projectSetup.unknownError': '未知错误',
  'layout.projectSetup.exitFailed': '退出项目初始化失败',
  'layout.projectSetup.missingCurrentProject': '无法退出项目初始化：当前项目不存在',
  'layout.documentSurface.disabledTitle': '{documentType} 插件已禁用',
  'layout.documentSurface.disabledMessage': '这个文件还在项目里，但当前插件没有启用。启用对应插件后即可继续打开。',
  'layout.documentSurface.missingTitle': '缺少文档类型插件',
  'layout.documentSurface.missingMessage': '当前工作区没有注册 {documentType} 对应的文档类型插件。',
  'layout.workspaceFiles.empty': '暂无文件',
  'layout.shortcuts.save.noOpenFile': '无打开的文件，无法保存',
  'layout.shortcuts.save.saving': '正在保存，请稍候...',
  'layout.shortcuts.save.unexpectedError': '保存时发生意外错误',
  'layout.workspaceDocumentExport.noActiveProject': '没有活动项目，无法创建文档',
  'layout.workspaceDocumentExport.editorUnavailable': '编辑器实例不可用（文档打开失败）',
  'layout.workspaceDocumentExport.autoSaveFailed': '内容已插入编辑器，但自动保存失败（请手动保存）',
} as const satisfies Readonly<Record<LayoutMessageKey, string>>;

export const LAYOUT_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'app-layout',
  catalogs: {
    'zh-CN': LAYOUT_MESSAGE_FALLBACKS,
    'en-US': {
      'layout.header.sidebar': 'Sidebar',
      'layout.header.knowledgeBase': 'Knowledge base',
      'layout.header.settings': 'Settings',
      'layout.header.newConversation': 'New chat',
      'layout.header.history': 'Chat history',
      'layout.header.moreMenu': 'More menu',
      'layout.header.markdownDocumentMenu': 'Current Markdown document menu',
      'layout.header.noMarkdownDocument': 'No Markdown document is open',
      'layout.header.pluginDocumentMenu': 'Current plugin document menu',
      'layout.header.swapPanes': 'Swap chat and document positions',
      'layout.header.rightPane.toggle': 'Expand or collapse right pane',
      'layout.header.rightPane.expand': 'Expand right pane',
      'layout.header.rightPane.collapse': 'Collapse right pane',
      'layout.header.rightPane.windowTooNarrow': 'The window is too narrow to show both panes',
      'layout.header.swap.documentToMain': 'Move document to center',
      'layout.header.swap.conversationToMain': 'Move chat to center',
      'layout.header.panel.close': 'Close',
      'layout.header.window.minimize': 'Minimize',
      'layout.header.window.maximizeRestore': 'Maximize / restore',
      'layout.header.untitledProject': 'Untitled project',
      'layout.header.projectSetup': 'AI project setup',
      'layout.header.timeline.empty': 'No timeline yet',
      'layout.header.timeline.expand': 'Expand timeline',
      'layout.header.timeline.collapse': 'Collapse timeline',
      'layout.header.review': 'AI review',
      'layout.header.documentMenu.export': 'Export',
      'layout.header.documentMenu.exportTxt': 'Export as TXT',
      'layout.header.documentMenu.exportMarkdown': 'Export as Markdown',
      'layout.header.documentMenu.exportPdf': 'Export as PDF',
      'layout.header.documentMenu.exportDocx': 'Export as DOCX',
      'layout.header.documentMenu.review': 'Review this document',
      'layout.header.documentMenu.addToKnowledgeBase': 'Add to knowledge base',
      'layout.header.untitledDocument': 'Untitled document',
      'layout.header.addToKnowledgeBase.editorUnavailable': 'The editor instance is unavailable, so this cannot be added to the knowledge base',
      'layout.header.addToKnowledgeBase.success': '"{fileName}" was added to the upload queue and is being parsed',
      'layout.header.addToKnowledgeBase.failed': 'Failed to add to the knowledge base. Please try again.',
      'layout.header.documentMenu.unavailable': 'No Markdown document is open, so the document menu cannot be used',
      'layout.sidebar.nav.newConversation': 'New chat',
      'layout.sidebar.nav.newProject': 'New project',
      'layout.sidebar.nav.knowledgeBase': 'Knowledge base',
      'layout.sidebar.nav.plugins': 'Plugins',
      'layout.sidebar.project.back': 'Back',
      'layout.sidebar.project.viewGroup': 'Project sidebar view',
      'layout.sidebar.project.chat': 'Chats',
      'layout.sidebar.project.files': 'Files',
      'layout.sidebar.project.newConversation': 'New chat',
      'layout.sidebar.project.searchChats': 'Search chats',
      'layout.sidebar.project.create': 'Create',
      'layout.sidebar.project.searchFiles': 'Search files',
      'layout.sidebar.project.planningConversationTitle': '{projectName} - Project planning',
      'layout.sidebar.assetPreview.loadingImage': 'Loading image...',
      'layout.sidebar.assetPreview.loadingText': 'Reading content...',
      'layout.sidebar.assetPreview.close': 'Close preview',
      'layout.pane.resizeSidebar': 'Resize left sidebar',
      'layout.pane.resizeDocument': 'Resize document pane',
      'layout.pane.resizeConversation': 'Resize chat pane',
      'layout.projectSetup.generate': 'Finish and generate',
      'layout.projectSetup.skip': 'Skip',
      'layout.projectSetup.generating': 'Generating...',
      'layout.projectSetup.refreshAfterGenerationFailed': 'Generation finished, but the file list could not be refreshed. Refresh it manually.',
      'layout.projectSetup.sendMessageFailed': 'Failed to send message',
      'layout.projectSetup.sendGenerateCommandFailed': 'Failed to send the generation command. Please try again later.',
      'layout.projectSetup.unknownError': 'Unknown error',
      'layout.projectSetup.exitFailed': 'Failed to exit project setup',
      'layout.projectSetup.missingCurrentProject': 'Cannot exit project setup because the current project no longer exists',
      'layout.documentSurface.disabledTitle': '{documentType} plugin is disabled',
      'layout.documentSurface.disabledMessage': 'This file is still in the project, but its plugin is not enabled. Enable the plugin to open it again.',
      'layout.documentSurface.missingTitle': 'Missing document type plugin',
      'layout.documentSurface.missingMessage': 'No document type plugin is registered for {documentType} in the current workspace.',
      'layout.workspaceFiles.empty': 'No files',
      'layout.shortcuts.save.noOpenFile': 'No file is open, so nothing can be saved',
      'layout.shortcuts.save.saving': 'Saving. Please wait...',
      'layout.shortcuts.save.unexpectedError': 'Unexpected error while saving',
      'layout.workspaceDocumentExport.noActiveProject': 'No active project is available, so the document cannot be created',
      'layout.workspaceDocumentExport.editorUnavailable': 'The editor instance is unavailable, so the document could not be opened',
      'layout.workspaceDocumentExport.autoSaveFailed': 'The content was inserted into the editor, but autosave failed. Please save manually.',
    },
  },
};
