import type { MessageCatalogContribution } from '@app/localization';
import type { SettingsMessageKey } from './settingsMessages';

export const SETTINGS_MESSAGE_FALLBACKS = {
  'settings.modal.title': '设置',
  'settings.modal.close': '关闭设置',
  'settings.groups.general': '通用',
  'settings.groups.models': '模型',
  'settings.groups.documentTypes': '文档与插件',
  'settings.tabs.appearance': '外观',
  'settings.tabs.conversation': '对话',
  'settings.tabs.modelConfig': '模型配置',
  'settings.tabs.modelManagement': '模型管理',
  'settings.tabs.addModel': '添加模型',
  'settings.modelPicker.description': '控制对话输入框中显示哪些模型供应商和模型。',
  'settings.modelPicker.loading': '正在读取模型可见性...',
  'settings.modelPicker.failure': '无法读取模型可见性。',
  'settings.modelPicker.empty': '尚未配置可用于对话的模型供应商或自定义模型。',
  'settings.modelPicker.sourceSearch': '搜索模型供应商',
  'settings.modelPicker.modelSearch': '搜索模型',
  'settings.modelPicker.customModels': '自定义模型',
  'settings.modelPicker.credentialUnavailable': '凭据不可用，请删除后重新添加。',
  'settings.modelPicker.credentialReason.missing': '未找到本机凭据。请删除后重新添加。',
  'settings.modelPicker.credentialReason.temporarilyUnavailable':
    '系统安全存储暂时不可用。请稍后重试，或删除后重新添加。',
  'settings.modelPicker.credentialReason.invalidated':
    '系统安全存储无法解密该凭据（可能是 macOS 钥匙串已重置）。请删除后重新添加。',
  'settings.modelPicker.credentialReason.malformedCiphertext':
    '凭据密文格式无效。请删除后重新添加。',
  'settings.modelPicker.credentialReason.unknown':
    '系统安全存储处理凭据时发生未知错误。请删除后重新添加。',
  'settings.modelPicker.removeProvider': '删除 Provider',
  'settings.modelPicker.removeProvider.confirm':
    '将删除该 Provider 的配置、凭据及其已启用模型，之后可以重新添加。是否继续？',
  'settings.modelPicker.removeProvider.failed': '删除 Provider 失败，请稍后重试。',
  'settings.modelPicker.runtimeUnavailable': '当前不可用',
  'settings.modelPicker.imageGeneration': '图片生成',
  'settings.tabs.about': '关于',
  'settings.tabs.webSearch': '网络搜索',
  'settings.tabs.commandPermission': '命令权限',
  'settings.tabs.storageSpace': '存储空间',
  'settings.commandPermission.title': '命令权限',
  'settings.commandPermission.loading': '正在读取命令权限...',
  'settings.commandPermission.unavailable': '命令权限配置不可用。',
  'settings.commandPermission.status.saved': '命令权限已更新，将从下一次运行开始生效。',
  'settings.commandPermission.status.revisionConflict':
    '设置已在其他页面更改。已显示最新设置，请重新选择。',
  'settings.commandPermission.status.writeFailed': '更新失败，原设置未改变。请稍后重试。',
  'settings.commandPermission.status.saveFailed': '无法更新命令权限设置。',
  'settings.commandPermission.confirmExpansion.standard.title': '开启标准权限',
  'settings.commandPermission.confirmExpansion.standard.message':
    'Linnya 将能够在无需逐条许可的情况下，在这台计算机上运行普通命令、访问互联网，以及在允许范围内创建和编辑文件。\n\nLinnya 会拦截常见高风险命令并等待您的审批，但无法识别所有脚本和外部工具行为。\n\n这包括但不限于：',
  'settings.commandPermission.confirmExpansion.standard.files.title': '文件和文件夹',
  'settings.commandPermission.confirmExpansion.standard.files.scope':
    '读取文件，以及在允许范围内创建或修改文件',
  'settings.commandPermission.confirmExpansion.standard.files.riskyOperations':
    '常见的上传、删除、剪切或移动操作会等待审批',
  'settings.commandPermission.confirmExpansion.standard.commands.title': '终端命令',
  'settings.commandPermission.confirmExpansion.standard.commands.run':
    '运行命令、调用软件和更改部分设置',
  'settings.commandPermission.confirmExpansion.standard.commands.network':
    '访问互联网、下载文件、发送数据等',
  'settings.commandPermission.confirmExpansion.standard.risk':
    '仍可能带来敏感数据丢失、泄露、提示词注入等风险。',
  'settings.commandPermission.confirmExpansion.fullAccess.title': '开启完全访问',
  'settings.commandPermission.confirmExpansion.fullAccess.message':
    'Linnya 将能够在未经您许可的情况下，在这台计算机上运行任何命令、访问互联网、创建和编辑文件。\n\n这包括但不限于：',
  'settings.commandPermission.confirmExpansion.fullAccess.files.title': '文件和文件夹',
  'settings.commandPermission.confirmExpansion.fullAccess.files.operations':
    '读取、创建、修改、上传或删除文件',
  'settings.commandPermission.confirmExpansion.fullAccess.commands.title': '终端命令',
  'settings.commandPermission.confirmExpansion.fullAccess.commands.run':
    '运行命令、安装软件和更改系统设置',
  'settings.commandPermission.confirmExpansion.fullAccess.commands.network':
    '访问互联网、下载文件、发送数据等',
  'settings.commandPermission.confirmExpansion.fullAccess.risk':
    '这会带来敏感数据丢失、泄露、提示词注入等风险。',
  'settings.commandPermission.confirmExpansion.internalData.title': '允许访问 Linnya 内部数据',
  'settings.commandPermission.confirmExpansion.internalData.message':
    '开启后，命令可以读取 Linnya 的本地数据库和其他内部数据。请仅在您信任当前任务时开启。',
  'settings.commandPermission.confirmExpansion.confirm': '接受风险，确认开启',
  'settings.commandPermission.confirmExpansion.cancel': '取消',
  'settings.commandPermission.level.title': '权限级别',
  'settings.commandPermission.level.readOnly': '只读',
  'settings.commandPermission.level.readOnlyDescription':
    '默认只允许读取；超出权限的操作需要批准。',
  'settings.commandPermission.level.standard': '标准',
  'settings.commandPermission.level.standardDescription': '命中固定高风险规则的命令需要批准。',
  'settings.commandPermission.level.fullAccess': '完全访问',
  'settings.commandPermission.level.fullAccessDescription': '自动允许所有命令，但会极大增加风险。',
  'settings.commandPermission.internalData.title': 'Linnya 内部数据',
  'settings.commandPermission.internalData.label': '允许命令访问 Linnya 内部数据',
  'settings.storageSpace.title': '存储空间',
  'settings.storageSpace.loading': '正在读取存储空间...',
  'settings.storageSpace.unavailable': '暂时无法读取存储空间，请稍后重试。',
  'settings.storageSpace.empty': '暂无对话工作文件。',
  'settings.storageSpace.total': '总占用',
  'settings.storageSpace.categories': '分类占用',
  'settings.storageSpace.conversations': '对话工作文件',
  'settings.storageSpace.unnamedConversation': '未命名对话',
  'settings.storageSpace.measuredAt': '统计时间',
  'settings.storageSpace.actions.refresh': '刷新',
  'settings.storageSpace.actions.refreshing': '正在刷新...',
  'settings.storageSpace.actions.clear': '清理',
  'settings.storageSpace.actions.clearing': '正在删除中...',
  'settings.storageSpace.confirm.title': '清理对话工作文件',
  'settings.storageSpace.confirm.message':
    '将永久删除这个对话的本地工作文件，无法恢复。聊天记录和 Workspace 文件不会被删除。',
  'settings.storageSpace.confirm.confirm': '确认清理',
  'settings.storageSpace.confirm.cancel': '取消',
  'settings.storageSpace.status.notCreated': '尚未创建',
  'settings.storageSpace.status.previousFilesUnavailable': '本地工作文件已清理',
  'settings.storageSpace.status.available': '可用',
  'settings.storageSpace.status.unavailable': '暂时无法读取',
  'settings.storageSpace.valueUnavailable': '无法读取',
  'settings.storageSpace.failure.notFound': '对话不存在或已删除。',
  'settings.storageSpace.failure.deletionInProgress': '该对话正在删除中。',
  'settings.storageSpace.failure.clearFailed': '清理失败，请稍后重试。',
  'settings.storageSpace.category.conversationWorkFiles': '对话工作文件',
  'settings.storageSpace.category.workspace': 'Workspace 文件',
  'settings.storageSpace.category.attachments': '附件',
  'settings.storageSpace.category.temporaryOutputs': '临时命令输出',
  'settings.storageSpace.category.diagnosticLogs': '诊断日志',
  'settings.storageSpace.category.applicationData': '其他应用数据',
  'settings.webSearch.engine.title': '搜索引擎',
  'settings.webSearch.engine.experimental': '实验性',
  'settings.webSearch.engine.parallelFree.name': 'Parallel Free',
  'settings.webSearch.engine.parallelFree.description': '面向 AI 的免费搜索 API，无需 Key。',
  'settings.webSearch.engine.duckDuckGo.name': 'DuckDuckGo',
  'settings.webSearch.engine.duckDuckGo.description': '免费网页搜索，依赖非官方 HTML 接口。',
  'settings.webSearch.engine.searxng.name': 'SearXNG',
  'settings.webSearch.engine.searxng.description': '连接你自行部署的开源聚合搜索服务。',
  'settings.webSearch.engine.baiduQianfan.name': '百度千帆',
  'settings.webSearch.engine.baiduQianfan.description':
    '中文检索质量更稳定，需要配置百度千帆 API Key。',
  'settings.webSearch.engine.serper.name': 'Serper',
  'settings.webSearch.engine.serper.description': 'Google 搜索结果，需要配置 Serper API Key。',
  'settings.webSearch.engine.jinaSearch.name': 'Jina Search',
  'settings.webSearch.engine.jinaSearch.description':
    '面向大模型的搜索结果与正文摘要，注册后可使用免费额度。',
  'settings.webSearch.engine.tavily.name': 'Tavily',
  'settings.webSearch.engine.tavily.description':
    '面向 AI Agent 的搜索 API，注册后可使用免费额度。',
  'settings.webSearch.engine.freeHint':
    '免费服务可能受到共享限流影响；重度使用建议切换到需要 API Key 的搜索服务。',
  'settings.webSearch.apiKey.label': 'API Key',
  'settings.webSearch.apiKey.placeholder': '请输入 API Key',
  'settings.webSearch.apiKey.savedPlaceholder': '已保存，留空则继续使用',
  'settings.webSearch.apiKey.savedDescription': '新输入会替换已保存的 Key。',
  'settings.webSearch.apiKey.obtain': '获取 API Key',
  'settings.webSearch.searxng.title': 'SearXNG 服务',
  'settings.webSearch.searxng.urlLabel': '服务地址',
  'settings.webSearch.searxng.urlPlaceholder': 'https://search.example.com',
  'settings.webSearch.actions.save': '保存',
  'settings.webSearch.actions.saving': '正在保存...',
  'settings.webSearch.actions.test': '测试连接',
  'settings.webSearch.actions.testing': '正在测试...',
  'settings.webSearch.validation.apiKeyRequired': '请输入 API Key。',
  'settings.webSearch.validation.searxngUrlRequired': '请输入 SearXNG 服务地址。',
  'settings.webSearch.status.saved': '网络搜索设置已保存。',
  'settings.webSearch.status.connectionOk': '连接成功，耗时 {tookMs} ms。',
  'settings.webRead.render.title': '网页解析',
  'settings.webRead.render.label': 'Linnya 默认',
  'settings.webRead.reader.title': '第三方网页解析',
  'settings.webRead.reader.metaso.name': '秘塔网页解析',
  'settings.webRead.reader.metaso.description': '可以把网页解析交给秘塔处理。',
  'settings.webRead.reader.jina.name': 'Jina 网页解析',
  'settings.webRead.reader.jina.description': '可以把网页解析交给 Jina 处理。',
  'settings.webRead.credential.title': 'API 凭证',
  'settings.webRead.apiKey.label': 'API Key',
  'settings.webRead.apiKey.placeholder': '请输入 API Key',
  'settings.webRead.apiKey.availablePlaceholder': '已有可用凭证，留空则继续使用',
  'settings.webRead.apiKey.savedDescription':
    'Key 已通过系统安全存储加密；新输入会替换当前服务的 Key。',
  'settings.webRead.apiKey.registryDescription': '当前服务已有可用的本机凭证。',
  'settings.webRead.apiKey.obtain': '获取 API Key',
  'settings.webRead.actions.save': '保存',
  'settings.webRead.actions.saving': '正在保存...',
  'settings.webRead.actions.test': '测试连接',
  'settings.webRead.actions.testing': '正在测试...',
  'settings.webRead.validation.apiKeyRequired': '请输入 API Key。',
  'settings.webRead.status.saved': '网页解析设置已保存。',
  'settings.webRead.status.connectionOk': '连接成功，耗时 {tookMs} ms。',
  'settings.appearance.theme.title': '主题',
  'settings.appearance.theme.label': '选择主题',
  'settings.appearance.theme.light': '浅色',
  'settings.appearance.theme.moonBlue': '月白蓝',
  'settings.appearance.theme.dark': '深色',
  'settings.appearance.language.title': '语言',
  'settings.appearance.language.label': '选择语言',
  'settings.appearance.language.selectTitle': '选择语言',
  'settings.appearance.language.description': '切换 Linnya 的界面语言。',
  'settings.appearance.language.zhCN': '简体中文',
  'settings.appearance.language.enUS': 'English',
  'settings.appearance.font.title': '字体',
  'settings.appearance.font.label': '选择字体',
  'settings.appearance.font.selectTitle': '选择字体',
  'settings.appearance.font.description': '字体切换功能即将推出',
  'settings.appearance.font.systemDefault': '系统默认',
  'settings.appearance.font.pingfang': '苹方',
  'settings.appearance.font.sourceHan': '思源黑体',
  'settings.conversation.title': '对话',
  'settings.conversation.automaticTitle.label': '自动生成对话标题',
  'settings.conversation.automaticTitle.description':
    '新对话首次发送后，用对话标题辅助模型生成标题。',
  'settings.modelGroups.system': '系统模型',
  'settings.modelGroups.provider': '模型供应商',
  'settings.modelGroups.custom': '自定义模型',
  'settings.modelCapability.chat': '对话',
  'settings.modelCapability.imageInput': '支持视觉识别',
  'settings.addModel.imageInput.description':
    '声明该模型能够理解图片。关闭后仍可使用图片生成工具。',
  'settings.addModel.quick.title': '选择模型供应商',
  'settings.addModel.quick.description': '选择常用供应商，或从其他供应商中选择。',
  'settings.addModel.quick.other': '其他供应商',
  'settings.addModel.quick.otherPlaceholder': '选择其他供应商',
  'settings.addModel.quick.otherSelectTitle': '选择其他供应商',
  'settings.addModel.quick.otherEmpty': '暂无可用的其他供应商。',
  'settings.addModel.quick.customApi': '自定义 API',
  'settings.addModel.quick.back': '返回供应商选择',
  'settings.protocol.auto': '自动检测',
  'settings.protocol.googleGenerativeAi': 'Google Generative AI',
  'settings.modelConfig.selection.title': '模型选择',
  'settings.modelConfig.primary.label': '主模型',
  'settings.modelConfig.primary.placeholder': '请选择主模型',
  'settings.modelConfig.primary.selectTitle': '选择主模型',
  'settings.modelConfig.primary.description': '用于回答、推理和生成主要内容',
  'settings.modelConfig.auxiliary.title': '辅助模型',
  'settings.modelConfig.auxiliary.placeholder': '请选择辅助模型',
  'settings.modelConfig.auxiliary.selectTitle': '选择辅助模型',
  'settings.modelConfig.auxiliary.default.primaryModel': '使用主模型',
  'settings.modelConfig.auxiliary.documentSpecificHint':
    '文档专用 AI 功能在各个插件或文档设置里进行配置。',
  'settings.modelConfig.other.title': '其他模型',
  'settings.modelConfig.auxiliary.purposes.autocomplete.label': '自动补全',
  'settings.modelConfig.auxiliary.purposes.autocomplete.description':
    '用于编辑器输入时的即时续写建议；默认模型由辅助用途注册表指定。',
  'settings.modelConfig.auxiliary.purposes.translation.label': '翻译',
  'settings.modelConfig.auxiliary.purposes.translation.description':
    '用于文本和音频转录翻译；默认模型由辅助用途注册表指定。',
  'settings.modelConfig.auxiliary.purposes.audioSummary.label': '音频摘要',
  'settings.modelConfig.auxiliary.purposes.audioSummary.description':
    '用于从音频转录生成纪要；选择“使用主模型”时会随主模型变化。',
  'settings.modelConfig.auxiliary.purposes.writing.label': 'AI 写作',
  'settings.modelConfig.auxiliary.purposes.writing.description':
    '用于编辑器内生成正文；选择“使用主模型”时会随主模型变化。',
  'settings.modelConfig.auxiliary.purposes.annotation.label': '批注',
  'settings.modelConfig.auxiliary.purposes.annotation.description':
    '用于根据批注生成后续内容；选择“使用主模型”时会随主模型变化。',
  'settings.modelConfig.auxiliary.purposes.review.label': '审阅',
  'settings.modelConfig.auxiliary.purposes.review.description':
    '用于文档审阅和建议生成；选择“使用主模型”时会随主模型变化。',
  'settings.modelConfig.auxiliary.purposes.conversationTitle.label': '对话标题',
  'settings.modelConfig.auxiliary.purposes.conversationTitle.description':
    '用于新对话首次发送后自动生成标题；默认模型由辅助用途注册表指定。',
  'settings.modelConfig.auxiliary.purposes.knowledgeGraphExtraction.label': '知识图谱抽取',
  'settings.modelConfig.auxiliary.purposes.knowledgeGraphExtraction.description':
    '用于新上传文档的图谱抽取快照；默认模型由辅助用途注册表指定。',
  'settings.modelConfig.imageGeneration.label': '图片生成模型',
  'settings.modelConfig.imageGeneration.placeholder': '请选择图片生成模型',
  'settings.modelConfig.imageGeneration.selectTitle': '选择图片生成模型',
  'settings.modelConfig.imageGeneration.description': '用于根据文本描述生成图片',
  'settings.modelConfig.embedding.label': '知识库嵌入模型',
  'settings.modelConfig.embedding.placeholder': '请选择知识库嵌入模型',
  'settings.modelConfig.embedding.selectTitle': '选择知识库嵌入模型',
  'settings.modelConfig.embedding.description':
    '用于新文档向量化与语义检索。已建索引的知识库会继续按索引出身模型检索。',
  'settings.modelConfig.embedding.changeConfirm.title': '切换知识库嵌入模型',
  'settings.modelConfig.embedding.changeConfirm.message':
    '当前已有 {count} 个知识库使用其它嵌入模型建立索引。切换后，这些知识库需要清空并重新导入后才能继续搜索。受影响：{names}',
  'settings.modelConfig.embedding.changeConfirm.confirm': '继续切换',
  'settings.modelConfig.embedding.changeConfirm.cancel': '取消',
  'settings.modelConfig.rerank.label': '知识库重排模型',
  'settings.modelConfig.rerank.placeholder': '请选择知识库重排模型',
  'settings.modelConfig.rerank.selectTitle': '选择知识库重排模型',
  'settings.modelConfig.rerank.description': '用于知识库搜索结果重排序。',
  'settings.modelConfig.pdfOcr.label': 'PDF OCR 模型',
  'settings.modelConfig.pdfOcr.placeholder': '请选择 PDF OCR 模型',
  'settings.modelConfig.pdfOcr.selectTitle': '选择 PDF OCR 模型',
  'settings.modelConfig.pdfOcr.description': '用于扫描页和复杂版面 PDF 的 OCR 解析。',
  'settings.modelConfig.imageVision.label': '图片视觉模型',
  'settings.modelConfig.imageVision.placeholder': '请选择图片视觉模型',
  'settings.modelConfig.imageVision.selectTitle': '选择图片视觉模型',
  'settings.modelConfig.imageVision.description': '用于图片文件识别与描述。',
  'settings.modelConfig.transcription.label': '语音识别模型',
  'settings.modelConfig.transcription.placeholder': '请选择语音识别模型',
  'settings.modelConfig.transcription.selectTitle': '选择语音识别模型',
  'settings.modelConfig.transcription.description': '用于将音频转换为文字',
  'settings.modelConfig.error.fetchFailed': '获取模型列表失败',
  'settings.modelConfig.error.deleteFailed': '删除模型失败',
  'settings.modelConfig.error.updateFailed': '更新模型失败',
  'settings.addModel.provider.title': '模型供应商',
  'settings.addModel.provider.label': '模型供应商',
  'settings.addModel.provider.description':
    '选择模型供应商；下方只显示当前接入方式需要填写的内容。',
  'settings.addModel.provider.selectTitle': '选择模型供应商',
  'settings.addModel.provider.customOption': '自定义模型供应商',
  'settings.addModel.connection.label': '接入方案',
  'settings.addModel.connection.description':
    '同一供应商的不同方案使用各自的地址、凭据和额度，互不覆盖。',
  'settings.addModel.connection.placeholder': '请选择接入方案',
  'settings.addModel.connection.selectTitle': '选择接入方案',
  'settings.addModel.account.label': '账号',
  'settings.addModel.account.description': '将在浏览器中完成登录，Linnya 不会读取或保存账号密码。',
  'settings.addModel.account.loading': '正在检查登录状态...',
  'settings.addModel.account.connect': '使用 {provider} 登录',
  'settings.addModel.account.connecting': '等待浏览器授权...',
  'settings.addModel.account.connected': '已连接 {provider}',
  'settings.addModel.account.disconnect': '退出登录',
  'settings.addModel.modelName.label': '模型名称',
  'settings.addModel.api.modelName.placeholder': '例如：deepseek-chat',
  'settings.addModel.api.modelName.description': '模型的原始名称，用于 API 调用。',
  'settings.addModel.displayName.label': '自定义名称（选填）',
  'settings.addModel.displayName.placeholder': '默认使用模型名称',
  'settings.addModel.displayName.description': '在应用中显示的自定义名称，留空则使用模型名称。',
  'settings.addModel.apiKey.label': 'API Key',
  'settings.addModel.apiKey.providerDescription':
    '连接后自动启用最多三个近期模型（稳定版优先）；其他模型可在“模型管理”中按需启用。',
  'settings.addModel.apiKey.obtain': '获取此接入方式的 API Key',
  'settings.addModel.apiKey.placeholder': '请输入 API Key',
  'settings.addModel.apiKey.optionalReuseDescription':
    '首次配置必填；相同 API 地址和格式已有凭据时可留空复用。',
  'settings.addModel.apiUrl.label': 'API 地址',
  'settings.addModel.apiUrl.placeholder': '例如：https://api.openai.com/v1',
  'settings.addModel.apiUrl.descriptionLine1':
    '填写到版本号路径即可（如 /v1），不要包含 /chat/completions 或 /responses。',
  'settings.addModel.apiUrl.descriptionLine2':
    '按照服务文档选择 API 格式；大多数标注 OpenAI 兼容的服务使用 Chat Completions。',
  'settings.addModel.compatibility.label': 'API 格式',
  'settings.addModel.compatibility.selectTitle': '选择兼容格式',
  'settings.addModel.compatibility.description':
    '按照自定义 API 的接口文档选择；具体 SDK 路由由 Linnya 内部处理。',
  'settings.addModel.compatibility.openaiCompatible': 'OpenAI 兼容',
  'settings.addModel.compatibility.openaiResponses': 'OpenAI Responses',
  'settings.addModel.compatibility.anthropicCompatible': 'Anthropic 兼容',
  'settings.addModel.submit.add': '添加',
  'settings.addModel.submit.adding': '添加中...',
  'settings.addModel.submit.success': '添加成功',
  'settings.addModel.error.apiUrlInvalid': '请输入有效的 API 地址。',
  'settings.addModel.ollama.url.label': '本地 URL',
  'settings.addModel.ollama.url.description': 'Ollama 服务的监听地址，请确保 Ollama 服务正在运行。',
  'settings.addModel.ollama.model.placeholder': '请选择模型',
  'settings.addModel.ollama.model.selectTitle': '选择 Ollama 模型',
  'settings.addModel.ollama.refreshTitle': '刷新模型列表',
  'settings.addModel.discover.button': '获取可用模型',
  'settings.addModel.discover.fetching': '获取中...',
  'settings.addModel.discover.empty': '未找到可用模型',
  'settings.addModel.discover.success': '已获取 {count} 个模型',
  'settings.addModel.customProvider.label': '模型供应商',
  'settings.addModel.customProvider.placeholder': '例如：linnya.com',
  'settings.addModel.customProvider.description': '该模型归属的供应商分组，默认自动根据 API 地址提取。',
  'settings.addModel.discoveredModels.title': '已发现模型（共 {count} 个）',
  'settings.addModel.discoveredModels.enableAll': '全部启用',
  'settings.modelPicker.refreshModels': '更新模型列表',
  'settings.modelPicker.customProviders': '自定义模型供应商',
  'settings.addModel.ollama.model.description': '获取已安装的 Ollama 模型，仅支持添加对话模型。',
  'settings.addModel.ollama.loading': '正在加载...',
  'settings.addModel.ollama.empty': '请先刷新或检查 URL',
  'settings.addModel.ollama.urlRequired': '请输入 Ollama 服务 URL。',
  'settings.addModel.ollama.noModels':
    'Ollama 服务连接成功，但未找到任何已下载的模型。\n请确认您已使用 `ollama pull <model_name>` 下载模型。',
  'settings.addModel.ollama.connectionFailed':
    '无法连接到指定的 Ollama 服务地址，\n请检查服务是否正在运行且 URL 正确。',
  'settings.addModel.ollama.connectionTarget': '\n目标: ({target})。',
  'settings.addModel.ollama.timeout': '连接 Ollama 服务超时。\n请检查服务是否正在运行且网络通畅。',
  'settings.addModel.ollama.statusFailed':
    '无法从 Ollama 服务获取模型列表。\n请检查 Ollama 服务状态和日志。',
  'settings.addModel.ollama.statusCode': ' (状态码: {statusCode})  ',
  'settings.addModel.ollama.unknownRefreshError': '获取 Ollama 模型列表时发生未知错误。',
  'settings.addModel.error.unknown': '发生未知错误',
  'settings.addModel.error.modelNameRequired': '模型名称不能为空。',
  'settings.addModel.error.apiKeyRequired': 'API Key 不能为空。',
  'settings.addModel.error.providerRequired': '请选择模型供应商。',
  'settings.addModel.error.ollamaModelRequired': '请选择一个模型名称。',
  'settings.modelCapacity.contextWindow.label': '上下文窗口',
  'settings.modelCapacity.contextWindow.placeholder': '例如：128000',
  'settings.modelCapacity.contextWindow.description':
    '模型一次请求可使用的最大 token 容量，请按当前模型供应商和模型版本填写。',
  'settings.modelCapacity.maxOutput.label': '最大输出',
  'settings.modelCapacity.maxOutput.placeholder': '例如：16384',
  'settings.modelCapacity.maxOutput.description':
    '模型单次响应允许生成的最大 token 数，包含模型供应商计入输出的推理 token。',
  'settings.modelCapacity.validation.positiveIntegers': '上下文窗口和最大输出必须是正整数。',
  'settings.modelDetails.title': '模型详情',
  'settings.modelDetails.displayName.label': '自定义名称',
  'settings.modelDetails.displayName.placeholder': '请输入自定义名称（必填）',
  'settings.modelDetails.modelName.label': '模型名称',
  'settings.modelDetails.modelName.placeholder': '例如：gpt-4o',
  'settings.modelDetails.apiKey.label': 'API Key',
  'settings.modelDetails.apiAddress.label': 'API 地址',
  'settings.modelDetails.apiAddress.placeholder': '例如：https://api.example.com/v1',
  'settings.modelDetails.protocol.label': 'API 协议',
  'settings.modelDetails.protocol.selectTitle': '选择 API 协议',
  'settings.modelDetails.delete': '删除模型',
  'settings.modelDetails.save': '保存并关闭',
  'settings.modelDetails.saving': '保存中...',
  'settings.modelDetails.confirmDelete': '确定要删除模型“{modelName}”吗？此操作无法撤销。',
  'settings.modelDetails.deleteFailed': '删除模型失败',
  'settings.modelDetails.displayNameRequired': '自定义名称不能为空。',
  'settings.modelDetails.modelNameRequired': '模型名称不能为空。',
  'settings.modelDetails.apiAddressRequired': 'API 地址不能为空。',
  'settings.modelDetails.inferenceRouteMissing': '该模型缺少正式推理路由，请删除后重新添加。',
  'settings.modelDetails.updateFailed': '更新模型失败',
  'settings.about.release.title': '测试版 v{version}',
  'settings.about.release.note.pluginStore':
    '新增插件商店能力，支持插件列表、详情页、远程安装、卸载和自动更新检查。',
  'settings.about.release.note.mindmapRuntime':
    '完善 Mindmap 官方插件运行时发布链路，支持磁盘加载、远程 artifact 分阶段安装、迁移、失败回滚和 R2 上传校验。',
  'settings.about.release.note.pluginState':
    '优化插件状态与能力注册，插件启用状态改为数据库持久化，并按文件格式归属路由创建工具。',
  'settings.about.release.note.pluginStoreUi':
    '改进插件商店界面，补齐展示元数据、状态标签、缺失插件详情和发布说明折叠。',
  'settings.about.release.note.layoutFixes':
    '修复页面滚动、对话滚动控件、Slides 分隔线和部分布局外壳样式问题。',
  'settings.about.release.note.defaultWorkspaceProtection':
    '加强默认工作区项目保护，避免关键项目被误操作。',
  'settings.about.release.note.pluginDocs': '更新插件运行时、发布流程和插件化规划文档。',
  'settings.about.contact.title': '联系我们',
  'settings.about.contact.intro': '产品目前仍处于内测阶段，功能和体验会持续优化中。',
  'settings.about.contact.feedbackGuidance':
    '使用过程中遇到任何 Bug、卡顿、崩溃或建议，欢迎随时反馈；如果方便，请附上复现步骤、截图/录屏与系统版本，便于我们快速定位问题。',
  'settings.about.contact.emailLabel': '反馈邮箱',
  'settings.about.contact.websiteLabel': '官方网站',
  'settings.about.contact.tutorialLabel': '教程',
  'settings.about.contact.labelSeparator': '：',
} as const satisfies Readonly<Record<SettingsMessageKey, string>>;

export const SETTINGS_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'settings',
  catalogs: {
    'zh-CN': SETTINGS_MESSAGE_FALLBACKS,
    'en-US': {
      'settings.modal.title': 'Settings',
      'settings.modal.close': 'Close settings',
      'settings.groups.general': 'General',
      'settings.groups.models': 'Models',
      'settings.groups.documentTypes': 'Documents & plugins',
      'settings.tabs.appearance': 'Appearance',
      'settings.tabs.conversation': 'Conversation',
      'settings.tabs.modelConfig': 'Model configuration',
      'settings.tabs.modelManagement': 'Model management',
      'settings.tabs.addModel': 'Add model',
      'settings.modelPicker.description':
        'Choose which Providers and models appear beside the conversation input.',
      'settings.modelPicker.loading': 'Loading model visibility...',
      'settings.modelPicker.failure': 'Model visibility could not be loaded.',
      'settings.modelPicker.empty': 'No configured Provider or custom chat model is available yet.',
      'settings.modelPicker.sourceSearch': 'Search Providers',
      'settings.modelPicker.modelSearch': 'Search models',
      'settings.modelPicker.customModels': 'Custom models',
      'settings.modelPicker.credentialUnavailable':
        'The credential is unavailable. Delete it and add the Provider again.',
      'settings.modelPicker.credentialReason.missing':
        'The local credential was not found. Delete it and add the Provider again.',
      'settings.modelPicker.credentialReason.temporarilyUnavailable':
        'The system secure storage is temporarily unavailable. Try again later, or delete and add the Provider again.',
      'settings.modelPicker.credentialReason.invalidated':
        'The system secure storage cannot decrypt this credential (the macOS Keychain may have been reset). Delete it and add the Provider again.',
      'settings.modelPicker.credentialReason.malformedCiphertext':
        'The credential ciphertext is invalid. Delete it and add the Provider again.',
      'settings.modelPicker.credentialReason.unknown':
        'The system secure storage returned an unknown error. Delete it and add the Provider again.',
      'settings.modelPicker.removeProvider': 'Delete Provider',
      'settings.modelPicker.removeProvider.confirm':
        'This will delete the Provider configuration, credential, and activated models. You can add the Provider again afterward. Continue?',
      'settings.modelPicker.removeProvider.failed': 'Provider deletion failed. Try again later.',
      'settings.modelPicker.runtimeUnavailable': 'Currently unavailable',
      'settings.modelPicker.imageGeneration': 'Image generation',
      'settings.tabs.about': 'About',
      'settings.tabs.webSearch': 'Web search',
      'settings.tabs.commandPermission': 'Command permissions',
      'settings.tabs.storageSpace': 'Storage',
      'settings.commandPermission.title': 'Command permissions',
      'settings.commandPermission.loading': 'Loading command permissions...',
      'settings.commandPermission.unavailable': 'Command permission settings are unavailable.',
      'settings.commandPermission.status.saved':
        'Command permissions were updated and will apply to the next run.',
      'settings.commandPermission.status.revisionConflict':
        'These settings changed in another page. The latest settings are shown; select the permission again.',
      'settings.commandPermission.status.writeFailed':
        'The update failed. The previous settings were not changed. Try again.',
      'settings.commandPermission.status.saveFailed':
        'Command permission settings could not be updated.',
      'settings.commandPermission.confirmExpansion.standard.title': 'Enable standard permissions',
      'settings.commandPermission.confirmExpansion.standard.message':
        'Linnya will be able to run ordinary commands, access the internet, and create or edit files within allowed locations without asking for each action.\n\nLinnya will stop common high-risk commands for your approval, but it cannot identify every script or external tool behavior.\n\nThis includes, but is not limited to:',
      'settings.commandPermission.confirmExpansion.standard.files.title': 'Files and folders',
      'settings.commandPermission.confirmExpansion.standard.files.scope':
        'Read files and create or modify files within allowed locations',
      'settings.commandPermission.confirmExpansion.standard.files.riskyOperations':
        'Common upload, delete, cut, or move operations will require approval',
      'settings.commandPermission.confirmExpansion.standard.commands.title': 'Terminal commands',
      'settings.commandPermission.confirmExpansion.standard.commands.run':
        'Run commands, invoke software, and change some settings',
      'settings.commandPermission.confirmExpansion.standard.commands.network':
        'Access the internet, download files, and send data',
      'settings.commandPermission.confirmExpansion.standard.risk':
        'This may still cause sensitive data loss, disclosure, prompt injection, or other risks.',
      'settings.commandPermission.confirmExpansion.fullAccess.title': 'Enable full access',
      'settings.commandPermission.confirmExpansion.fullAccess.message':
        'Without asking for your permission, Linnya will be able to run any command on this computer, access the internet, and create or edit files.\n\nThis includes, but is not limited to:',
      'settings.commandPermission.confirmExpansion.fullAccess.files.title': 'Files and folders',
      'settings.commandPermission.confirmExpansion.fullAccess.files.operations':
        'Read, create, modify, upload, or delete files',
      'settings.commandPermission.confirmExpansion.fullAccess.commands.title': 'Terminal commands',
      'settings.commandPermission.confirmExpansion.fullAccess.commands.run':
        'Run commands, install software, and change system settings',
      'settings.commandPermission.confirmExpansion.fullAccess.commands.network':
        'Access the internet, download files, and send data',
      'settings.commandPermission.confirmExpansion.fullAccess.risk':
        'This can cause sensitive data loss, disclosure, prompt injection, or other risks.',
      'settings.commandPermission.confirmExpansion.internalData.title':
        'Allow access to Linnya internal data',
      'settings.commandPermission.confirmExpansion.internalData.message':
        "Commands will be able to read Linnya's local database and other internal data. Enable this only when you trust the current task.",
      'settings.commandPermission.confirmExpansion.confirm': 'Accept risk and enable',
      'settings.commandPermission.confirmExpansion.cancel': 'Cancel',
      'settings.commandPermission.level.title': 'Permission level',
      'settings.commandPermission.level.readOnly': 'Read only',
      'settings.commandPermission.level.readOnlyDescription':
        'Read access is allowed by default; other operations require approval.',
      'settings.commandPermission.level.standard': 'Standard',
      'settings.commandPermission.level.standardDescription':
        'Commands matching fixed high-risk rules require approval.',
      'settings.commandPermission.level.fullAccess': 'Full access',
      'settings.commandPermission.level.fullAccessDescription':
        'Automatically allow all commands, with substantially greater risk.',
      'settings.commandPermission.internalData.title': 'Linnya internal data',
      'settings.commandPermission.internalData.label':
        'Allow commands to access Linnya internal data',
      'settings.storageSpace.title': 'Storage',
      'settings.storageSpace.loading': 'Reading storage usage...',
      'settings.storageSpace.unavailable':
        'Storage usage is temporarily unavailable. Try again later.',
      'settings.storageSpace.empty': 'No conversation work files.',
      'settings.storageSpace.total': 'Total usage',
      'settings.storageSpace.categories': 'Usage by category',
      'settings.storageSpace.conversations': 'Conversation work files',
      'settings.storageSpace.unnamedConversation': 'Untitled conversation',
      'settings.storageSpace.measuredAt': 'Measured at',
      'settings.storageSpace.actions.refresh': 'Refresh',
      'settings.storageSpace.actions.refreshing': 'Refreshing...',
      'settings.storageSpace.actions.clear': 'Clear',
      'settings.storageSpace.actions.clearing': 'Deleting...',
      'settings.storageSpace.confirm.title': 'Clear conversation work files',
      'settings.storageSpace.confirm.message':
        'This permanently deletes the local work files for this conversation and cannot be undone. Chat history and Workspace files are kept.',
      'settings.storageSpace.confirm.confirm': 'Clear files',
      'settings.storageSpace.confirm.cancel': 'Cancel',
      'settings.storageSpace.status.notCreated': 'Not created',
      'settings.storageSpace.status.previousFilesUnavailable': 'Local work files cleared',
      'settings.storageSpace.status.available': 'Available',
      'settings.storageSpace.status.unavailable': 'Temporarily unavailable',
      'settings.storageSpace.valueUnavailable': 'Unavailable',
      'settings.storageSpace.failure.notFound': 'The conversation does not exist or was deleted.',
      'settings.storageSpace.failure.deletionInProgress': 'This conversation is being deleted.',
      'settings.storageSpace.failure.clearFailed': 'Cleanup failed. Try again later.',
      'settings.storageSpace.category.conversationWorkFiles': 'Conversation work files',
      'settings.storageSpace.category.workspace': 'Workspace files',
      'settings.storageSpace.category.attachments': 'Attachments',
      'settings.storageSpace.category.temporaryOutputs': 'Temporary command output',
      'settings.storageSpace.category.diagnosticLogs': 'Diagnostic logs',
      'settings.storageSpace.category.applicationData': 'Other application data',
      'settings.webSearch.engine.title': 'Search engine',
      'settings.webSearch.engine.experimental': 'Experimental',
      'settings.webSearch.engine.parallelFree.name': 'Parallel Free',
      'settings.webSearch.engine.parallelFree.description':
        'A free search API designed for AI, with no key required.',
      'settings.webSearch.engine.duckDuckGo.name': 'DuckDuckGo',
      'settings.webSearch.engine.duckDuckGo.description':
        'Free web search through an unofficial HTML endpoint.',
      'settings.webSearch.engine.searxng.name': 'SearXNG',
      'settings.webSearch.engine.searxng.description':
        'Connect to your self-hosted open-source metasearch service.',
      'settings.webSearch.engine.baiduQianfan.name': 'Baidu Qianfan',
      'settings.webSearch.engine.baiduQianfan.description':
        'Stronger Chinese search using your Baidu Qianfan API key.',
      'settings.webSearch.engine.serper.name': 'Serper',
      'settings.webSearch.engine.serper.description':
        'Google search results using your Serper API key.',
      'settings.webSearch.engine.jinaSearch.name': 'Jina Search',
      'settings.webSearch.engine.jinaSearch.description':
        'LLM-oriented search results and page summaries with a free allowance after signup.',
      'settings.webSearch.engine.tavily.name': 'Tavily',
      'settings.webSearch.engine.tavily.description':
        'A search API for AI agents with a free allowance after signup.',
      'settings.webSearch.engine.freeHint':
        'Free services may share rate limits. For heavier use, switch to a search service that uses an API key.',
      'settings.webSearch.apiKey.label': 'API key',
      'settings.webSearch.apiKey.placeholder': 'Enter API key',
      'settings.webSearch.apiKey.savedPlaceholder': 'Saved; leave blank to keep using it',
      'settings.webSearch.apiKey.savedDescription': 'Entering a new value replaces the saved key.',
      'settings.webSearch.apiKey.obtain': 'Get API key',
      'settings.webSearch.searxng.title': 'SearXNG service',
      'settings.webSearch.searxng.urlLabel': 'Service URL',
      'settings.webSearch.searxng.urlPlaceholder': 'https://search.example.com',
      'settings.webSearch.actions.save': 'Save',
      'settings.webSearch.actions.saving': 'Saving...',
      'settings.webSearch.actions.test': 'Test connection',
      'settings.webSearch.actions.testing': 'Testing...',
      'settings.webSearch.validation.apiKeyRequired': 'Enter an API key.',
      'settings.webSearch.validation.searxngUrlRequired': 'Enter the SearXNG service URL.',
      'settings.webSearch.status.saved': 'Web search settings saved.',
      'settings.webSearch.status.connectionOk': 'Connected in {tookMs} ms.',
      'settings.webRead.render.title': 'Web page parsing',
      'settings.webRead.render.label': 'Linnya default',
      'settings.webRead.reader.title': 'Third-party page parsing',
      'settings.webRead.reader.metaso.name': 'Metaso page parsing',
      'settings.webRead.reader.metaso.description': 'Let Metaso handle page parsing.',
      'settings.webRead.reader.jina.name': 'Jina page parsing',
      'settings.webRead.reader.jina.description': 'Let Jina handle page parsing.',
      'settings.webRead.credential.title': 'API credentials',
      'settings.webRead.apiKey.label': 'API key',
      'settings.webRead.apiKey.placeholder': 'Enter API key',
      'settings.webRead.apiKey.availablePlaceholder':
        'A credential is available; leave blank to keep using it',
      'settings.webRead.apiKey.savedDescription':
        "The key is encrypted by system secure storage. A new value replaces this service's key.",
      'settings.webRead.apiKey.registryDescription':
        'An on-device credential is available for this service.',
      'settings.webRead.apiKey.obtain': 'Get API key',
      'settings.webRead.actions.save': 'Save',
      'settings.webRead.actions.saving': 'Saving...',
      'settings.webRead.actions.test': 'Test connection',
      'settings.webRead.actions.testing': 'Testing...',
      'settings.webRead.validation.apiKeyRequired': 'Enter an API key.',
      'settings.webRead.status.saved': 'Web page parsing settings saved.',
      'settings.webRead.status.connectionOk': 'Connected in {tookMs} ms.',
      'settings.appearance.theme.title': 'Theme',
      'settings.appearance.theme.label': 'Theme',
      'settings.appearance.theme.light': 'Light',
      'settings.appearance.theme.moonBlue': 'Moon blue',
      'settings.appearance.theme.dark': 'Dark',
      'settings.appearance.language.title': 'Language',
      'settings.appearance.language.label': 'Language',
      'settings.appearance.language.selectTitle': 'Choose language',
      'settings.appearance.language.description': 'Change the Linnya interface language.',
      'settings.appearance.language.zhCN': '简体中文',
      'settings.appearance.language.enUS': 'English',
      'settings.appearance.font.title': 'Font',
      'settings.appearance.font.label': 'Font',
      'settings.appearance.font.selectTitle': 'Choose font',
      'settings.appearance.font.description': 'Font switching is coming soon.',
      'settings.appearance.font.systemDefault': 'System default',
      'settings.appearance.font.pingfang': 'PingFang',
      'settings.appearance.font.sourceHan': 'Source Han Sans',
      'settings.conversation.title': 'Conversation',
      'settings.conversation.automaticTitle.label': 'Automatically generate conversation titles',
      'settings.conversation.automaticTitle.description':
        'After the first message in a new conversation, generate a title with the conversation title auxiliary model.',
      'settings.modelGroups.system': 'System models',
      'settings.modelGroups.provider': 'Model providers',
      'settings.modelGroups.custom': 'Custom models',
      'settings.modelCapability.chat': 'Chat',
      'settings.modelCapability.imageInput': 'Supports vision',
      'settings.addModel.imageInput.description':
        'Declares that this model understands images. Image generation remains available when disabled.',
      'settings.addModel.quick.title': 'Choose a model provider',
      'settings.addModel.quick.description':
        'Choose a popular provider, or browse other providers.',
      'settings.addModel.quick.other': 'Other providers',
      'settings.addModel.quick.otherPlaceholder': 'Choose another provider',
      'settings.addModel.quick.otherSelectTitle': 'Choose another provider',
      'settings.addModel.quick.otherEmpty': 'No other providers are currently available.',
      'settings.addModel.quick.customApi': 'Custom API',
      'settings.addModel.quick.back': 'Back to provider choices',
      'settings.protocol.auto': 'Auto detect',
      'settings.protocol.googleGenerativeAi': 'Google Generative AI',
      'settings.modelConfig.selection.title': 'Model selection',
      'settings.modelConfig.primary.label': 'Primary model',
      'settings.modelConfig.primary.placeholder': 'Choose primary model',
      'settings.modelConfig.primary.selectTitle': 'Choose primary model',
      'settings.modelConfig.primary.description':
        'Used for answers, reasoning, and main content generation.',
      'settings.modelConfig.auxiliary.title': 'Auxiliary models',
      'settings.modelConfig.auxiliary.placeholder': 'Choose auxiliary model',
      'settings.modelConfig.auxiliary.selectTitle': 'Choose auxiliary model',
      'settings.modelConfig.auxiliary.default.primaryModel': 'Use primary model',
      'settings.modelConfig.auxiliary.documentSpecificHint':
        'Configure document-specific AI features in each plugin or document settings.',
      'settings.modelConfig.other.title': 'Other models',
      'settings.modelConfig.auxiliary.purposes.autocomplete.label': 'Autocomplete',
      'settings.modelConfig.auxiliary.purposes.autocomplete.description':
        'Used for instant editor continuation suggestions. The default model is specified by the auxiliary purpose registry.',
      'settings.modelConfig.auxiliary.purposes.translation.label': 'Translation',
      'settings.modelConfig.auxiliary.purposes.translation.description':
        'Used for text and audio transcript translation. The default model is specified by the auxiliary purpose registry.',
      'settings.modelConfig.auxiliary.purposes.audioSummary.label': 'Audio summary',
      'settings.modelConfig.auxiliary.purposes.audioSummary.description':
        'Used to summarize audio transcripts. "Use primary model" follows the current primary model.',
      'settings.modelConfig.auxiliary.purposes.writing.label': 'AI writing',
      'settings.modelConfig.auxiliary.purposes.writing.description':
        'Used for in-editor content generation. "Use primary model" follows the current primary model.',
      'settings.modelConfig.auxiliary.purposes.annotation.label': 'Annotation',
      'settings.modelConfig.auxiliary.purposes.annotation.description':
        'Used to generate follow-up content from annotations. "Use primary model" follows the current primary model.',
      'settings.modelConfig.auxiliary.purposes.review.label': 'Review',
      'settings.modelConfig.auxiliary.purposes.review.description':
        'Used for document review and suggestion generation. "Use primary model" follows the current primary model.',
      'settings.modelConfig.auxiliary.purposes.conversationTitle.label': 'Conversation title',
      'settings.modelConfig.auxiliary.purposes.conversationTitle.description':
        'Used to generate a title after the first message in a new conversation. The default model is specified by the auxiliary purpose registry.',
      'settings.modelConfig.auxiliary.purposes.knowledgeGraphExtraction.label':
        'Knowledge graph extraction',
      'settings.modelConfig.auxiliary.purposes.knowledgeGraphExtraction.description':
        'Captured for graph extraction on newly uploaded documents. The default model is specified by the auxiliary purpose registry.',
      'settings.modelConfig.imageGeneration.label': 'Image generation model',
      'settings.modelConfig.imageGeneration.placeholder': 'Choose image generation model',
      'settings.modelConfig.imageGeneration.selectTitle': 'Choose image generation model',
      'settings.modelConfig.imageGeneration.description':
        'Used to generate images from text prompts.',
      'settings.modelConfig.embedding.label': 'Knowledge base embedding model',
      'settings.modelConfig.embedding.placeholder': 'Choose knowledge base embedding model',
      'settings.modelConfig.embedding.selectTitle': 'Choose knowledge base embedding model',
      'settings.modelConfig.embedding.description':
        'Used to vectorize new documents and run semantic search. Existing indexes keep using the embedding model they were built with.',
      'settings.modelConfig.embedding.changeConfirm.title': 'Change knowledge base embedding model',
      'settings.modelConfig.embedding.changeConfirm.message':
        '{count} knowledge base(s) already have indexes built with another embedding model. After switching, they must be cleared and re-imported before search can continue. Affected: {names}',
      'settings.modelConfig.embedding.changeConfirm.confirm': 'Continue',
      'settings.modelConfig.embedding.changeConfirm.cancel': 'Cancel',
      'settings.modelConfig.rerank.label': 'Knowledge base rerank model',
      'settings.modelConfig.rerank.placeholder': 'Choose knowledge base rerank model',
      'settings.modelConfig.rerank.selectTitle': 'Choose knowledge base rerank model',
      'settings.modelConfig.rerank.description': 'Used to rerank knowledge base search results.',
      'settings.modelConfig.pdfOcr.label': 'PDF OCR model',
      'settings.modelConfig.pdfOcr.placeholder': 'Choose PDF OCR model',
      'settings.modelConfig.pdfOcr.selectTitle': 'Choose PDF OCR model',
      'settings.modelConfig.pdfOcr.description':
        'Used to parse scanned pages and complex-layout PDFs.',
      'settings.modelConfig.imageVision.label': 'Image vision model',
      'settings.modelConfig.imageVision.placeholder': 'Choose image vision model',
      'settings.modelConfig.imageVision.selectTitle': 'Choose image vision model',
      'settings.modelConfig.imageVision.description': 'Used to recognize and describe image files.',
      'settings.modelConfig.transcription.label': 'Speech recognition model',
      'settings.modelConfig.transcription.placeholder': 'Choose speech recognition model',
      'settings.modelConfig.transcription.selectTitle': 'Choose speech recognition model',
      'settings.modelConfig.transcription.description': 'Used to convert audio into text.',
      'settings.modelConfig.error.fetchFailed': 'Failed to fetch model list',
      'settings.modelConfig.error.deleteFailed': 'Failed to delete model',
      'settings.modelConfig.error.updateFailed': 'Failed to update model',
      'settings.addModel.provider.title': 'Provider',
      'settings.addModel.provider.label': 'Provider',
      'settings.addModel.provider.description':
        'Choose a Provider. Only the fields required for that connection are shown below.',
      'settings.addModel.provider.selectTitle': 'Choose a Provider',
      'settings.addModel.provider.customOption': 'Custom Provider',
      'settings.addModel.connection.label': 'Connection',
      'settings.addModel.connection.description':
        'Each connection uses its own endpoint, credentials, and quota.',
      'settings.addModel.connection.placeholder': 'Choose a connection',
      'settings.addModel.connection.selectTitle': 'Choose a connection',
      'settings.addModel.account.label': 'Account',
      'settings.addModel.account.description':
        'Sign in through your browser. Linnya never reads or stores your account password.',
      'settings.addModel.account.loading': 'Checking sign-in status...',
      'settings.addModel.account.connect': 'Sign in with {provider}',
      'settings.addModel.account.connecting': 'Waiting for browser authorization...',
      'settings.addModel.account.connected': 'Connected to {provider}',
      'settings.addModel.account.disconnect': 'Sign out',
      'settings.addModel.modelName.label': 'Model name',
      'settings.addModel.api.modelName.placeholder': 'Example: deepseek-chat',
      'settings.addModel.api.modelName.description': 'The original model name used for API calls.',
      'settings.addModel.displayName.label': 'Display name (optional)',
      'settings.addModel.displayName.placeholder': 'Use model name by default',
      'settings.addModel.displayName.description':
        'Custom name shown in the app. Leave blank to use the model name.',
      'settings.addModel.apiKey.label': 'API key',
      'settings.addModel.apiKey.providerDescription':
        'Connects up to three recent models, preferring stable releases. Enable others in Model Management.',
      'settings.addModel.apiKey.obtain': 'Get an API key for this connection',
      'settings.addModel.apiKey.placeholder': 'Enter API key',
      'settings.addModel.apiKey.optionalReuseDescription':
        'Required for the first setup; leave blank to reuse an existing credential for the same API URL and format.',
      'settings.addModel.apiUrl.label': 'API URL',
      'settings.addModel.apiUrl.placeholder': 'Example: https://api.openai.com/v1',
      'settings.addModel.apiUrl.descriptionLine1':
        'Enter the version root path only, such as /v1. Do not include /chat/completions or /responses.',
      'settings.addModel.apiUrl.descriptionLine2':
        'Choose the API format documented by the service. Most OpenAI-compatible services use Chat Completions.',
      'settings.addModel.compatibility.label': 'API format',
      'settings.addModel.compatibility.selectTitle': 'Choose a compatible format',
      'settings.addModel.compatibility.description':
        'Choose the format documented by the custom API. Linnya owns the internal SDK routing.',
      'settings.addModel.compatibility.openaiCompatible': 'OpenAI compatible',
      'settings.addModel.compatibility.openaiResponses': 'OpenAI Responses',
      'settings.addModel.compatibility.anthropicCompatible': 'Anthropic compatible',
      'settings.addModel.submit.add': 'Add',
      'settings.addModel.submit.adding': 'Adding...',
      'settings.addModel.submit.success': 'Added',
      'settings.addModel.error.apiUrlInvalid': 'Enter a valid API URL.',
      'settings.addModel.ollama.url.label': 'Local URL',
      'settings.addModel.ollama.url.description':
        'The Ollama service address. Make sure Ollama is running.',
      'settings.addModel.ollama.model.placeholder': 'Choose a model',
      'settings.addModel.ollama.model.selectTitle': 'Choose Ollama model',
      'settings.addModel.ollama.refreshTitle': 'Refresh model list',
      'settings.addModel.discover.button': 'Fetch available models',
      'settings.addModel.discover.fetching': 'Fetching...',
      'settings.addModel.discover.empty': 'No available models found',
      'settings.addModel.discover.success': 'Fetched {count} models',
      'settings.addModel.customProvider.label': 'Model Provider',
      'settings.addModel.customProvider.placeholder': 'e.g. linnya.com',
      'settings.addModel.customProvider.description': 'Provider group for the models, extracted from URL by default.',
      'settings.addModel.discoveredModels.title': 'Discovered Models ({count})',
      'settings.addModel.discoveredModels.enableAll': 'Enable all',
      'settings.modelPicker.refreshModels': 'Update model list',
      'settings.modelPicker.customProviders': 'Custom Providers',
      'settings.addModel.ollama.model.description':
        'Fetch installed Ollama models. Only chat models can be added.',
      'settings.addModel.ollama.loading': 'Loading...',
      'settings.addModel.ollama.empty': 'Refresh first or check the URL',
      'settings.addModel.ollama.urlRequired': 'Enter the Ollama service URL.',
      'settings.addModel.ollama.noModels':
        'Connected to Ollama, but no downloaded models were found.\nMake sure you have downloaded one with `ollama pull <model_name>`.',
      'settings.addModel.ollama.connectionFailed':
        'Could not connect to the specified Ollama service address.\nCheck that the service is running and the URL is correct.',
      'settings.addModel.ollama.connectionTarget': '\nTarget: ({target}).',
      'settings.addModel.ollama.timeout':
        'Connection to the Ollama service timed out.\nCheck that the service is running and the network is reachable.',
      'settings.addModel.ollama.statusFailed':
        'Could not fetch the model list from Ollama.\nCheck the Ollama service status and logs.',
      'settings.addModel.ollama.statusCode': ' (status code: {statusCode})  ',
      'settings.addModel.ollama.unknownRefreshError':
        'An unknown error occurred while fetching the Ollama model list.',
      'settings.addModel.error.unknown': 'An unknown error occurred',
      'settings.addModel.error.modelNameRequired': 'Model name is required.',
      'settings.addModel.error.apiKeyRequired': 'API key is required.',
      'settings.addModel.error.providerRequired': 'Choose a Provider.',
      'settings.addModel.error.ollamaModelRequired': 'Choose a model name.',
      'settings.modelCapacity.contextWindow.label': 'Context window',
      'settings.modelCapacity.contextWindow.placeholder': 'Example: 128000',
      'settings.modelCapacity.contextWindow.description':
        'Maximum token capacity available to one request. Use the limit for the current provider and model version.',
      'settings.modelCapacity.maxOutput.label': 'Max output',
      'settings.modelCapacity.maxOutput.placeholder': 'Example: 16384',
      'settings.modelCapacity.maxOutput.description':
        'Maximum tokens the model may generate in one response, including reasoning tokens counted as output by the provider.',
      'settings.modelCapacity.validation.positiveIntegers':
        'Context window and max output must be positive integers.',
      'settings.modelDetails.title': 'Model details',
      'settings.modelDetails.displayName.label': 'Display name',
      'settings.modelDetails.displayName.placeholder': 'Enter display name (required)',
      'settings.modelDetails.modelName.label': 'Model name',
      'settings.modelDetails.modelName.placeholder': 'Example: gpt-4o',
      'settings.modelDetails.apiKey.label': 'API key',
      'settings.modelDetails.apiAddress.label': 'API address',
      'settings.modelDetails.apiAddress.placeholder': 'Example: https://api.example.com/v1',
      'settings.modelDetails.protocol.label': 'API protocol',
      'settings.modelDetails.protocol.selectTitle': 'Choose API protocol',
      'settings.modelDetails.delete': 'Delete model',
      'settings.modelDetails.save': 'Save and close',
      'settings.modelDetails.saving': 'Saving...',
      'settings.modelDetails.confirmDelete': 'Delete model "{modelName}"? This cannot be undone.',
      'settings.modelDetails.deleteFailed': 'Failed to delete model',
      'settings.modelDetails.displayNameRequired': 'Display name is required.',
      'settings.modelDetails.modelNameRequired': 'Model name is required.',
      'settings.modelDetails.apiAddressRequired': 'API address is required.',
      'settings.modelDetails.inferenceRouteMissing':
        'This model has no explicit inference route. Delete it and add it again.',
      'settings.modelDetails.updateFailed': 'Failed to update model',
      'settings.about.release.title': 'Beta v{version}',
      'settings.about.release.note.pluginStore':
        'Added Plugin Store capabilities, including plugin lists, detail pages, remote installation, uninstall, and automatic update checks.',
      'settings.about.release.note.mindmapRuntime':
        'Improved the official Mindmap plugin runtime release pipeline with disk loading, staged remote artifact installation, migration, rollback on failure, and R2 upload verification.',
      'settings.about.release.note.pluginState':
        'Improved plugin state and capability registration. Plugin enabled state is now persisted in the database, and creation tools route by file format ownership.',
      'settings.about.release.note.pluginStoreUi':
        'Refined the Plugin Store interface with richer metadata, state badges, missing-plugin details, and collapsible release notes.',
      'settings.about.release.note.layoutFixes':
        'Fixed page scrolling, conversation scroll controls, Slides dividers, and several layout shell styles.',
      'settings.about.release.note.defaultWorkspaceProtection':
        'Strengthened default workspace project protection to prevent accidental changes to critical projects.',
      'settings.about.release.note.pluginDocs':
        'Updated plugin runtime, release workflow, and pluginization planning docs.',
      'settings.about.contact.title': 'Contact us',
      'settings.about.contact.intro':
        'The product is still in beta, and both features and experience will continue to improve.',
      'settings.about.contact.feedbackGuidance':
        'If you run into bugs, lag, crashes, or have suggestions, please send feedback anytime. Reproduction steps, screenshots or recordings, and your system version help us locate issues faster.',
      'settings.about.contact.emailLabel': 'Feedback email',
      'settings.about.contact.websiteLabel': 'Website',
      'settings.about.contact.tutorialLabel': 'Tutorials',
      'settings.about.contact.labelSeparator': ': ',
    },
  },
};
