import type { SharedComponentMessageKey } from './sharedComponentMessages';

/* Renderer UI 自带的确定性 fallback；Host resolver 只负责按当前 locale 覆盖。 */

export const SHARED_COMPONENT_MESSAGE_FALLBACKS = {
  'shared.alert.cancel': '取消',
  'shared.alert.confirm': '确定',
  'shared.alert.title': '提示',
  'shared.characterCount.label': '字数: {count}',
  'shared.color.red': '红色',
  'shared.color.crimson': '洋红',
  'shared.color.pink': '粉色',
  'shared.color.purple': '紫色',
  'shared.color.indigo': '靛蓝',
  'shared.color.blue': '蓝色',
  'shared.color.teal': '青色',
  'shared.color.mint': '薄荷',
  'shared.color.green': '绿色',
  'shared.color.lime': '青柠',
  'shared.color.yellow': '黄色',
  'shared.color.orange': '橙色',
  'shared.color.brown': '棕色',
  'shared.color.slate': '石板灰',
  'shared.color.gray': '灰色',
  'shared.colorPicker.backgroundTitle': '背景颜色',
  'shared.colorPicker.clear': '清除颜色',
  'shared.colorPicker.textTitle': '文字颜色',
  'shared.customSelect.placeholder': '请选择',
  'shared.customSelect.title': '选择选项',
  'shared.draggablePanel.title': '面板',
  'shared.modal.close': '关闭',
  'shared.modal.title': '标题',
  'shared.numberSpin.stepDown': '减少数值',
  'shared.numberSpin.stepUp': '增加数值',
  'shared.simpleDatePicker.month.1': '1 月',
  'shared.simpleDatePicker.month.2': '2 月',
  'shared.simpleDatePicker.month.3': '3 月',
  'shared.simpleDatePicker.month.4': '4 月',
  'shared.simpleDatePicker.month.5': '5 月',
  'shared.simpleDatePicker.month.6': '6 月',
  'shared.simpleDatePicker.month.7': '7 月',
  'shared.simpleDatePicker.month.8': '8 月',
  'shared.simpleDatePicker.month.9': '9 月',
  'shared.simpleDatePicker.month.10': '10 月',
  'shared.simpleDatePicker.month.11': '11 月',
  'shared.simpleDatePicker.month.12': '12 月',
  'shared.simpleDatePicker.placeholder': '选择日期',
  'shared.simpleDatePicker.weekday.monday': '一',
  'shared.simpleDatePicker.weekday.tuesday': '二',
  'shared.simpleDatePicker.weekday.wednesday': '三',
  'shared.simpleDatePicker.weekday.thursday': '四',
  'shared.simpleDatePicker.weekday.friday': '五',
  'shared.simpleDatePicker.weekday.saturday': '六',
  'shared.simpleDatePicker.weekday.sunday': '日',
  'shared.simpleDatePicker.year': '{year} 年',
  'shared.timePicker.cancel': '取消',
  'shared.timePicker.confirm': '确定',
  'shared.timePicker.placeholder': '选择时间',
  'shared.scrollToBottom.title': '滚动到底部',
  'shared.secretInput.hide': '隐藏敏感内容',
  'shared.secretInput.show': '显示敏感内容',
  'shared.segmentedTabs.ariaLabel': '分段切换',
  'shared.textInput.clear': '清除输入',
  'shared.textPopover.triggerTitle': '点击查看详情',
} as const satisfies Readonly<Record<SharedComponentMessageKey, string>>;

export const SHARED_COMPONENT_MESSAGE_CATALOGS = {
  'zh-CN': SHARED_COMPONENT_MESSAGE_FALLBACKS,
  'en-US': {
    'shared.alert.cancel': 'Cancel',
    'shared.alert.confirm': 'OK',
    'shared.alert.title': 'Notice',
    'shared.characterCount.label': 'Characters: {count}',
    'shared.color.red': 'Red',
    'shared.color.crimson': 'Crimson',
    'shared.color.pink': 'Pink',
    'shared.color.purple': 'Purple',
    'shared.color.indigo': 'Indigo',
    'shared.color.blue': 'Blue',
    'shared.color.teal': 'Teal',
    'shared.color.mint': 'Mint',
    'shared.color.green': 'Green',
    'shared.color.lime': 'Lime',
    'shared.color.yellow': 'Yellow',
    'shared.color.orange': 'Orange',
    'shared.color.brown': 'Brown',
    'shared.color.slate': 'Slate',
    'shared.color.gray': 'Gray',
    'shared.colorPicker.backgroundTitle': 'Background color',
    'shared.colorPicker.clear': 'Clear color',
    'shared.colorPicker.textTitle': 'Text color',
    'shared.customSelect.placeholder': 'Choose',
    'shared.customSelect.title': 'Choose an option',
    'shared.draggablePanel.title': 'Panel',
    'shared.modal.close': 'Close',
    'shared.modal.title': 'Title',
    'shared.numberSpin.stepDown': 'Decrease value',
    'shared.numberSpin.stepUp': 'Increase value',
    'shared.simpleDatePicker.month.1': 'Jan',
    'shared.simpleDatePicker.month.2': 'Feb',
    'shared.simpleDatePicker.month.3': 'Mar',
    'shared.simpleDatePicker.month.4': 'Apr',
    'shared.simpleDatePicker.month.5': 'May',
    'shared.simpleDatePicker.month.6': 'Jun',
    'shared.simpleDatePicker.month.7': 'Jul',
    'shared.simpleDatePicker.month.8': 'Aug',
    'shared.simpleDatePicker.month.9': 'Sep',
    'shared.simpleDatePicker.month.10': 'Oct',
    'shared.simpleDatePicker.month.11': 'Nov',
    'shared.simpleDatePicker.month.12': 'Dec',
    'shared.simpleDatePicker.placeholder': 'Choose date',
    'shared.simpleDatePicker.weekday.monday': 'Mon',
    'shared.simpleDatePicker.weekday.tuesday': 'Tue',
    'shared.simpleDatePicker.weekday.wednesday': 'Wed',
    'shared.simpleDatePicker.weekday.thursday': 'Thu',
    'shared.simpleDatePicker.weekday.friday': 'Fri',
    'shared.simpleDatePicker.weekday.saturday': 'Sat',
    'shared.simpleDatePicker.weekday.sunday': 'Sun',
    'shared.simpleDatePicker.year': '{year}',
    'shared.timePicker.cancel': 'Cancel',
    'shared.timePicker.confirm': 'OK',
    'shared.timePicker.placeholder': 'Choose time',
    'shared.scrollToBottom.title': 'Scroll to bottom',
    'shared.secretInput.hide': 'Hide secret',
    'shared.secretInput.show': 'Show secret',
    'shared.segmentedTabs.ariaLabel': 'Segmented tabs',
    'shared.textInput.clear': 'Clear input',
    'shared.textPopover.triggerTitle': 'Click for details',
  } satisfies Readonly<Record<SharedComponentMessageKey, string>>,
} as const;
