// Auto-generated by scripts/codegen/generate-layout-dts.ts.
// DO NOT EDIT BY HAND — regenerate with `npm run codegen-first:dts`.
//
// Sources:
//   - packages/plugins/slides/src/shared/flexComposeContract.ts
//   - packages/plugins/slides/src/shared/shapeGeometry/definitions/shapeGeometry.ts
//   - packages/plugins/slides/src/shared/svgGraphic/definitions/svgGraphic.ts
//   - packages/plugins/slides/src/shared/deckSpec/slideSize.ts
//   - packages/plugins/slides/src/backend/sandbox/layoutPrimitives.ts
//   - packages/plugins/slides/src/backend/sandbox/pptComposeProfile.ts (sandbox bindings)
//
// Consumers:
//   - References reading: AI loads via `references/layoutPrimitives.d.ts`
//   - Sandbox typecheck:  pptComposeProfile.typecheck.ts feeds this file to
//                         the TypeScript compiler API for codegen-source mode.

// ─── Layout types (extracted from flexComposeContract.ts) ───────────────────

interface AbsolutePositionBox {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface BrushArtworkArcMark {
  readonly type: 'arc';
  readonly center: BrushArtworkPosition;
  /** 相对元素短边的百分比。 */
  readonly radius: number;
  readonly startAngle: number;
  readonly endAngle: number;
}

type BrushArtworkBrush =
  | 'pen'
  | 'rotring'
  | '2B'
  | 'HB'
  | '2H'
  | 'cpencil'
  | 'pastel'
  | 'crayon'
  | 'charcoal'
  | 'spray'
  | 'marker';

interface BrushArtworkEllipseMark {
  readonly type: 'ellipse';
  readonly center: BrushArtworkPosition;
  readonly radiusX: number;
  readonly radiusY: number;
  readonly irregularity?: number;
}

type BrushArtworkField =
  | 'hand'
  | 'curved'
  | 'zigzag'
  | 'waves'
  | 'seabed'
  | 'spiral'
  | 'columns';

type BrushArtworkFill =
  | BrushArtworkWatercolorFill
  | BrushArtworkWashFill
  | BrushArtworkMassFill;

interface BrushArtworkFlowLineMark {
  readonly type: 'flowLine';
  readonly from: BrushArtworkPosition;
  /** 相对元素短边的百分比。 */
  readonly length: number;
  readonly direction: number;
}

interface BrushArtworkHatch {
  readonly brush: BrushArtworkBrush;
  readonly color: string;
  /** 相对元素短边的百分比。 */
  readonly weight?: number;
  /** 相对元素短边的百分比。 */
  readonly spacing?: number;
  readonly angle?: number;
  readonly randomness?: number;
  readonly continuous?: boolean;
  readonly gradient?: number;
}

/**
 * Agent 可持久化的作者意图。运行时、像素尺寸和图片 ownership 不进入 deck.js。
 * 普通 JavaScript 循环可以构造 marks；Worker 只消费已经求值的数据。
 */
interface BrushArtworkIntent {
  readonly seed: number;
  /** 当前上游不保留 alpha，因此首版必须显式给出最终不透明底色。 */
  readonly backgroundColor: string;
  readonly quality?: BrushArtworkQuality;
  readonly layers: readonly BrushArtworkLayer[];
}

interface BrushArtworkLayer {
  readonly stroke?: BrushArtworkStroke;
  readonly fill?: BrushArtworkFill;
  readonly hatch?: BrushArtworkHatch;
  readonly field?: BrushArtworkField;
  readonly marks: readonly BrushArtworkMark[];
}

interface BrushArtworkLineMark {
  readonly type: 'line';
  readonly from: BrushArtworkPosition;
  readonly to: BrushArtworkPosition;
}

type BrushArtworkMark =
  | BrushArtworkLineMark
  | BrushArtworkSplineMark
  | BrushArtworkArcMark
  | BrushArtworkRectMark
  | BrushArtworkEllipseMark
  | BrushArtworkPolygonMark
  | BrushArtworkFlowLineMark;

interface BrushArtworkMassFill {
  readonly kind: 'mass';
  readonly brush: BrushArtworkBrush;
  readonly color: string;
  readonly precision?: number;
  readonly strength?: number;
  readonly gradient?: number;
  readonly outline?: boolean;
}

/** 元素局部坐标，x/y 均使用 0–100；第三项是可选笔压。 */
type BrushArtworkPoint = readonly [x: number, y: number, pressure?: number];

interface BrushArtworkPolygonMark {
  readonly type: 'polygon';
  readonly points: readonly BrushArtworkPoint[];
}

type BrushArtworkPosition = readonly [x: number, y: number];

type BrushArtworkQuality = 'draft' | 'standard' | 'high';

interface BrushArtworkRectMark {
  readonly type: 'rect';
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

interface BrushArtworkSourceRef extends BrushArtworkIntent {
  readonly kind: 'brush_artwork';
}

interface BrushArtworkSplineMark {
  readonly type: 'spline';
  readonly points: readonly BrushArtworkPoint[];
  readonly curvature?: number;
}

interface BrushArtworkStroke {
  readonly brush: BrushArtworkBrush;
  readonly color: string;
  /** 相对元素短边的百分比。 */
  readonly weight?: number;
}

interface BrushArtworkWashFill {
  readonly kind: 'wash';
  readonly color: string;
  readonly opacity?: number;
}

interface BrushArtworkWatercolorFill {
  readonly kind: 'watercolor';
  readonly color: string;
  /** p5.brush 原生 1–255 opacity。 */
  readonly opacity?: number;
  readonly bleed?: number;
  readonly bleedDirection?: 'in' | 'out';
  readonly bleedAngle?: number;
  readonly texture?: number;
  readonly border?: number;
  readonly scatter?: boolean;
}

interface ContainerDecoration {
  backgroundColor?: string;
  border?: LayoutBorderInput;
  borderRadius?: number;
  opacity?: number;
}

interface CustomSlideLayout {
  readonly width: number;
  readonly height: number;
  readonly unit: 'in';
}

interface EdgeInsets {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}

interface FlexComposeInput {
  title: string;
  layout?: SlideLayout;
  theme?: LayoutThemeInput;
  slides: LayoutSlideNode[];
}

interface FlexProps {
  /** 正数 N 表示 grow=N、shrink=1、basis=0；无 flex 的显式主轴尺寸不收缩。 */
  flex?: number;
  width?: number | string;
  height?: number | string;
  /** width 的 PPT 风格别名。 */
  w?: number | string;
  /** height 的 PPT 风格别名。 */
  h?: number | string;
  minWidth?: number;
  minHeight?: number;
  maxWidth?: number;
  maxHeight?: number;
  margin?: number | EdgeInsets;
  marginTop?: number;
  marginBottom?: number;
  marginLeft?: number;
  marginRight?: number;
  position?: 'absolute' | AbsolutePositionBox;
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
  /** left 的 PPT 风格别名；出现坐标字段时自动使用绝对定位。 */
  x?: number;
  /** top 的 PPT 风格别名；出现坐标字段时自动使用绝对定位。 */
  y?: number;
}

interface LayoutBorderInput {
  color: string;
  width: number;
  dash?: 'solid' | 'dash' | 'dot';
}

/** 受控声明式 Brush 绘制；运行时仍编译成普通 Image 节点。 */
interface LayoutBrushArtworkConfig
  extends Omit<LayoutImageConfig, 'src'>, BrushArtworkIntent {}

interface LayoutChartConfig extends FlexProps {
  preset?: LayoutChartPresetName;
  chartType?: LayoutChartType;
  categories?: LayoutDisplayValue[];
  series?: LayoutChartSeriesInput[];
  /** @deprecated 使用 chartType、categories 与 series。 */
  chartData?: LayoutChartDataLike;
  showDataLabels?: boolean;
  dataLabelFormat?: string;
  legendPosition?: LayoutChartLegendPosition;
  chartStyle?: LayoutChartStyle;
}

/** @deprecated 使用 chartType、categories 与 series。 */
interface LayoutChartDataLike {
  chartType?: LayoutChartType;
  categories?: LayoutDisplayValue[];
  labels?: LayoutDisplayValue[];
  xLabels?: LayoutDisplayValue[];
  xAxisLabels?: LayoutDisplayValue[];
  series?: LayoutChartSeriesInput[];
  datasets?: LayoutChartSeriesInput[];
}

type LayoutChartLegendPosition = 'top' | 'bottom' | 'left' | 'right' | 'none';

interface LayoutChartNode extends LayoutChartConfig, LayoutSourceMetadata {
  readonly _type: 'Chart';
}

type LayoutChartPresetName =
  | 'clean-column'
  | 'stacked-column'
  | 'horizontal-bar'
  | 'stacked-bar'
  | 'smooth-line'
  | 'straight-line'
  | 'area'
  | 'pie'
  | 'doughnut'
  | 'radar'
  | 'radar-filled'
  | 'scatter';

interface LayoutChartSeriesInput {
  name: string;
  values: number[];
  labels?: LayoutDisplayValue[];
}

/**
 * 图表的跨引擎颜色语义。
 *
 * 这里只暴露前端预览和 PPTX 都能表达的稳定字段；不要把 ECharts
 * option 或 PptxGenJS 的原始配置直接放进 deck.js。
 */
interface LayoutChartStyle {
  /** 类目轴和数值轴标签的共同兜底颜色。 */
  axisLabelColor?: string;
  /** 类目轴标签颜色，未提供时回退到 axisLabelColor。 */
  categoryAxisLabelColor?: string;
  /** 数值轴标签颜色，未提供时回退到 axisLabelColor。 */
  valueAxisLabelColor?: string;
  /** 数据标签颜色。 */
  dataLabelColor?: string;
  /** 类目网格线和数值网格线的共同颜色。 */
  gridlineColor?: string;
}

type LayoutChartType =
  | 'bar'
  | 'line'
  | 'pie'
  | 'doughnut'
  | 'scatter'
  | 'area'
  | 'radar';

type LayoutContainerNode = LayoutSlideNode | LayoutViewNode;

type LayoutDisplayValue = string | number | boolean;

interface LayoutFormulaConfig extends FlexProps {
  /** 受控 LaTeX profile；不支持的命令会直接报错。 */
  latex: string;
  /** PowerPoint 原生公式字号，单位 pt。 */
  fontSize?: number;
  /** #RRGGBB。 */
  color?: string;
  align?: 'left' | 'center' | 'right';
  altText?: string;
}

interface LayoutFormulaNode extends LayoutFormulaConfig, LayoutSourceMetadata {
  readonly _type: 'Formula';
}

interface LayoutFormulaTextRun {
  formula: string | {
    latex: string;
    altText?: string;
  };
  style?: LayoutTextStyleInput;
}

type LayoutGradient = LayoutLinearGradient | LayoutRadialGradient;

interface LayoutGradientStop {
  color: string;
  position: number;
  /** 0 表示透明，1 表示不透明。 */
  opacity?: number;
}

/** @deprecated 使用 LayoutViewNode + flexDirection: 'row'。 */
type LayoutHStackNode = LayoutViewNode;

interface LayoutImageConfig extends FlexProps {
  src?: LayoutImageSourceInput;
  alt?: string;
  fitMode?: 'cover' | 'contain' | 'crop';
  maskShape?: 'rect' | 'circle';
  rounding?: boolean;
  /** 0 表示不透明，1 表示完全透明。 */
  transparency?: number;
  shadow?: LayoutImageVisualShadowInput;
  rotate?: number;
  flipH?: boolean;
  flipV?: boolean;
}

interface LayoutImageNode extends LayoutImageConfig, LayoutSourceMetadata {
  readonly _type: 'Image';
}

type LayoutImageSourceInput = LayoutImageSourceRef | string;

type LayoutImageSourceRef =
  | { kind: 'external_url'; url: string }
  | { kind: 'data_uri'; dataUri: string }
  | { kind: 'local_path'; path: string }
  | { kind: 'generated_asset'; assetId: string }
  | BrushArtworkSourceRef;

interface LayoutImageVisualShadowInput {
  color?: string;
  blur?: number;
  angle?: number;
  distance?: number;
  opacity?: number;
}

type LayoutLeafNode =
  | LayoutTextNode
  | LayoutShapeNode
  | LayoutChartNode
  | LayoutTableNode
  | LayoutImageNode
  | LayoutSvgGraphicNode
  | LayoutFormulaNode
  | LayoutSpacerNode;

interface LayoutLinearGradient {
  type: 'linear';
  angle: number;
  stops: [LayoutGradientStop, LayoutGradientStop, ...LayoutGradientStop[]];
  rotateWithShape?: boolean;
}

type LayoutNode = LayoutContainerNode | LayoutLeafNode;

interface LayoutPlainTextRun {
  text: string;
  style?: LayoutTextStyleInput;
}

interface LayoutRadialGradient {
  type: 'radial';
  stops: [LayoutGradientStop, LayoutGradientStop, ...LayoutGradientStop[]];
  center?: { x: number; y: number };
  radius?: { x: number; y: number };
  rotateWithShape?: boolean;
}

interface LayoutShapeConfig extends FlexProps {
  geometry?: ShapeGeometrySpec;
  fill?: LayoutShapeFillInput;
  border?: LayoutShapeStroke;
  borderRadius?: number;
  opacity?: number;
  rotate?: number;
  content?: string | LayoutPlainTextRun[];
}

type LayoutShapeFillInput =
  | string
  | {
      color: string;
      /** 0 表示不透明，100 表示完全透明。 */
      transparency?: number;
    }
  | LayoutGradient;

interface LayoutShapeNode extends LayoutShapeConfig, LayoutSourceMetadata {
  readonly _type: 'Shape';
}

type LayoutShapeStroke =
  | {
      color: string;
      width: number;
      dash?: 'solid' | 'dash' | 'dot';
      paint?: never;
    }
  | {
      paint: LayoutLinearGradient;
      width: number;
      dash?: 'solid' | 'dash' | 'dot';
      color?: never;
    };

type LayoutSlideBackground =
  | string
  | { color: string; image?: never; gradient?: never }
  | { image: LayoutImageSourceInput; color?: never; gradient?: never }
  | { gradient: LayoutGradient; color?: never; image?: never };

interface LayoutSlideConfig extends FlexProps, ContainerDecoration {
  background?: LayoutSlideBackground;
  notes?: string;
}

interface LayoutSlideNode extends LayoutSlideConfig, LayoutSourceMetadata {
  readonly _type: 'Slide';
  readonly children: readonly LayoutNode[];
}

interface LayoutSourceMetadata {
  readonly _sourceSpan?: {
    startLine: number;
    endLine: number;
  };
}

interface LayoutSpacerConfig extends FlexProps {}

interface LayoutSpacerNode extends LayoutSpacerConfig, LayoutSourceMetadata {
  readonly _type: 'Spacer';
}

interface LayoutSvgGraphicConfig extends FlexProps {
  source?: LayoutSvgGraphicSourceInput;
  fit?: SvgGraphicFit;
  opacity?: number;
  rotate?: number;
  /** decorative 不为 true 时必须提供非空替代文本。 */
  altText?: string;
  decorative?: boolean;
}

interface LayoutSvgGraphicNode extends LayoutSvgGraphicConfig, LayoutSourceMetadata {
  readonly _type: 'SvgGraphic';
}

type LayoutSvgGraphicSourceInput = SvgGraphicAuthoringSource | string;

interface LayoutTableBorderInput {
  color: string;
  /** 边框粗细，单位为 pt。 */
  width: number;
}

interface LayoutTableCellInput {
  text: LayoutDisplayValue;
  style?: LayoutTextStyleInput;
  fill?: string;
  colspan?: number;
  rowspan?: number;
}

type LayoutTableCellValue = LayoutDisplayValue | LayoutTableCellInput;

interface LayoutTableConfig extends FlexProps {
  headers?: LayoutTableCellValue[];
  rows?: LayoutTableCellValue[][];
  /** 整张表四边及内部网格线的统一描边。 */
  border?: LayoutTableBorderInput;
  /** @deprecated 使用 headers 与 rows。 */
  tableData?: LayoutTableDataLike;
}

/** @deprecated 使用 headers 与 rows。 */
interface LayoutTableDataLike {
  headers?: LayoutTableCellValue[];
  rows?: LayoutTableCellValue[][];
  body?: LayoutTableCellValue[][];
  data?: LayoutTableCellValue[][];
}

interface LayoutTableNode extends LayoutTableConfig, LayoutSourceMetadata {
  readonly _type: 'Table';
}

type LayoutTextAlign = 'left' | 'center' | 'right';

/**
 * Text 的横向约束决定换行语义：Flex 流中的 Text 或显式 width/maxWidth/左右边界
 * 使用固定盒宽并自动换行；绝对定位且没有横向约束时，盒宽跟随内容，只响应显式换行符。
 */
interface LayoutTextConfig extends FlexProps {
  content?: string | LayoutTextRun[];
  fontSize?: number;
  fontWeight?: 'bold' | 'normal' | number;
  fontStyle?: 'italic' | 'normal';
  textDecoration?: 'underline' | 'none';
  color?: string;
  fontFamily?: string;
  textAlign?: LayoutTextAlign;
  verticalAlign?: LayoutVerticalAlign;
  /** 行高倍数；富文本 run 的精确行距使用 style.lineSpacing。 */
  lineHeight?: number;
  /** 字间距，单位为 pt。 */
  letterSpacing?: number;
  backgroundColor?: string;
  border?: LayoutBorderInput;
  /** @deprecated 使用 fontWeight: 'bold'。 */
  bold?: boolean;
  /** @deprecated 使用 fontStyle: 'italic'。 */
  italic?: boolean;
  /** @deprecated 使用 textDecoration: 'underline'。 */
  underline?: boolean;
  /** @deprecated 使用 textAlign。 */
  align?: LayoutTextAlign;
  /** @deprecated 使用 verticalAlign。 */
  valign?: LayoutVerticalAlign;
  /** @deprecated 使用 lineHeight。 */
  lineSpacing?: number;
}

type LayoutTextLineSpacingInput =
  | { kind: 'multiple'; value: number }
  | { kind: 'exactPt'; value: number };

interface LayoutTextNode extends LayoutTextConfig, LayoutSourceMetadata {
  readonly _type: 'Text';
}

type LayoutTextRun = LayoutPlainTextRun | LayoutFormulaTextRun;

interface LayoutTextStyleInput {
  fontSize?: number;
  fontFamily?: string;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  color?: string;
  align?: LayoutTextAlign;
  valign?: LayoutVerticalAlign;
  lineSpacing?: LayoutTextLineSpacingInput;
  /** 字间距，单位为 pt。 */
  letterSpacing?: number;
}

interface LayoutThemeInput {
  colors?: Record<string, string>;
  fonts?: {
    major: string;
    minor: string;
  };
  chart?: {
    palette: [string, ...string[]];
  };
}

/** @deprecated 使用 LayoutViewNode + flexDirection: 'column'。 */
type LayoutVStackNode = LayoutViewNode;

type LayoutVerticalAlign = 'top' | 'middle' | 'bottom';

interface LayoutViewConfig extends FlexProps, ContainerDecoration {
  flexDirection?: 'column' | 'row';
  padding?: number | EdgeInsets;
  gap?: number;
  alignItems?: 'flex-start' | 'center' | 'flex-end' | 'stretch';
  justifyContent?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around';
}

interface LayoutViewNode extends LayoutViewConfig, LayoutSourceMetadata {
  readonly _type: 'View';
  readonly children: readonly LayoutNode[];
}

interface ParallelogramGeometrySpec {
  readonly type: 'parallelogram';
  /** 倾斜量相对 shape 宽度的比例，0..0.5。 */
  readonly slant: number;
  readonly direction?: 'left' | 'right';
}

interface PathGeometrySpec {
  readonly type: 'path';
  readonly viewBox: ShapeViewBox;
  readonly commands: readonly ShapePathCommand[];
}

interface PolygonGeometrySpec {
  readonly type: 'polygon';
  /** shape local normalized coordinate，x/y 均为 0..1。 */
  readonly points: readonly ShapePoint[];
}

interface PresetShapeGeometrySpec {
  readonly type: 'preset';
  readonly name: PresetShapeName;
}

/**
 * Slides 形状几何合同。
 *
 * 坐标始终属于 shape local space，不包含 slide 绝对位置；Paint、文字和 transform
 * 由 Shape element 在更高一层组合，不能进入本合同。
 */
/**
 * 内置形状名。
 *
 * 这里写成自足的字面量联合，而不是 `typeof PRESET_SHAPE_NAMES[number]`：
 * 本文件会被 `scripts/codegen/generate-layout-dts.ts` 抽取成 deck.js 的 ambient d.ts，
 * 而抽取器只搬运类型声明、不搬运值声明。派生自 const 的写法会在生成物里留下
 * 悬空的 `typeof PRESET_SHAPE_NAMES`，让 sandbox typecheck 失效。
 */
type PresetShapeName =
  | 'rect'
  | 'roundRect'
  | 'ellipse'
  | 'triangle'
  | 'rightTriangle'
  | 'diamond'
  | 'pentagon'
  | 'hexagon'
  | 'star5'
  | 'rightArrow'
  | 'line'
  | 'callout'
  | 'parallelogram'
  | 'trapezoid'
  | 'nonIsoscelesTrapezoid'
  | 'chevron';

interface RegularPolygonGeometrySpec {
  readonly type: 'regularPolygon';
  readonly sides: number;
  /** degree；默认 -90，让首个顶点朝上。 */
  readonly rotation?: number;
}

interface RenderSlideSizeInches extends SlideSizeInches {
  readonly unit: 'in';
}

interface ResolvedPathShapeGeometry {
  readonly type: 'path';
  readonly viewBox: ShapeViewBox;
  readonly commands: readonly ShapePathCommand[];
  readonly closed: boolean;
}

interface ResolvedPresetShapeGeometry {
  readonly type: 'preset';
  readonly name: PresetShapeName;
}

/** compiler、RenderModel 与 renderer 共同消费的规范化几何。 */
type ResolvedShapeGeometry =
  | ResolvedPresetShapeGeometry
  | ResolvedPathShapeGeometry;

/** deck.js / DeckSpec 使用的语义几何。字符串是 preset 的简写。 */
type ShapeGeometrySpec =
  | PresetShapeName
  | PresetShapeGeometrySpec
  | RegularPolygonGeometrySpec
  | TrapezoidGeometrySpec
  | ParallelogramGeometrySpec
  | PolygonGeometrySpec
  | PathGeometrySpec;

type ShapePathCommand =
  | { readonly type: 'moveTo'; readonly x: number; readonly y: number }
  | { readonly type: 'lineTo'; readonly x: number; readonly y: number }
  | {
      readonly type: 'quadraticTo';
      readonly x1: number;
      readonly y1: number;
      readonly x: number;
      readonly y: number;
    }
  | {
      readonly type: 'cubicTo';
      readonly x1: number;
      readonly y1: number;
      readonly x2: number;
      readonly y2: number;
      readonly x: number;
      readonly y: number;
    }
  | { readonly type: 'close' };

interface ShapePoint {
  readonly x: number;
  readonly y: number;
}

interface ShapeViewBox {
  readonly width: number;
  readonly height: number;
}

type SlideLayout = SlideLayoutPreset | CustomSlideLayout;

type SlideLayoutNormalizationResult =
  | { readonly value: SlideLayout }
  | { readonly error: string };

type SlideLayoutPreset = '16x9' | '16x10' | '4x3';

interface SlideSizeBoxInches {
  readonly w: number;
  readonly h: number;
}

interface SlideSizeEmu {
  readonly cx: number;
  readonly cy: number;
}

interface SlideSizeInches {
  readonly width: number;
  readonly height: number;
}

type SvgGraphicAccessibility =
  | { readonly altText: string; readonly decorative?: false }
  | { readonly decorative: true; readonly altText?: never };

/** Agent 首期只可写 inline SVG，或引用当前会话/本地工作区中的 SVG 文件。 */
type SvgGraphicAuthoringSource =
  | { readonly kind: 'inline_svg'; readonly svg: string }
  | { readonly kind: 'local_path'; readonly path: string }
  | { readonly kind: 'conversation_file'; readonly locator: string };

/** admission 与 ownership 完成后进入 DeckSpec 的原子 SVG Graphic 事实。 */
type SvgGraphicElementSpec = SvgGraphicAccessibility & {
  readonly asset: SvgGraphicOwnedAssetRef;
  readonly fit: SvgGraphicFit;
  /** 0 表示透明，1 表示不透明。 */
  readonly opacity?: number;
  readonly rotate?: number;
};

type SvgGraphicFit = 'contain' | 'stretch';

/** ownership 完成后的 canonical 引用；DeckSpec 不长期保存任意源路径或 SVG XML。 */
interface SvgGraphicOwnedAssetRef {
  readonly kind: 'owned_svg';
  readonly assetId: string;
  readonly contentHash: string;
  readonly byteLength: number;
  readonly viewBox: SvgGraphicViewBox;
}

/** 单次编译/渲染读取到的授权内容；不会写回 canonical DeckSpec。 */
interface SvgGraphicResolvedAsset extends SvgGraphicOwnedAssetRef {
  readonly canonicalSvg: string;
}

/** SVG Graphic 在 authoring、ownership 与渲染链之间共享的稳定合同。 */
interface SvgGraphicViewBox {
  readonly width: number;
  readonly height: number;
}

interface TrapezoidGeometrySpec {
  readonly type: 'trapezoid';
  /** 顶边左端相对 shape 宽度的缩进，0..1。 */
  readonly topLeftInset: number;
  /** 顶边右端相对 shape 宽度的缩进，0..1。 */
  readonly topRightInset: number;
}

declare global {
  // ── Sandbox factory functions ──

  /**
   * Create a deterministic opaque p5.brush image from declarative layers and marks.
   * `backgroundColor` is required and must match the complete region behind the image.
   */
  function createBrushArtwork(config: LayoutBrushArtworkConfig): LayoutImageNode;

  /**
   * Create a chart leaf node. Pass a preset name string (e.g. "clean-column",
   * "doughnut"), a config object, or nothing and configure properties later.
   */
  function createChart(): LayoutChartNode;
  function createChart(preset: LayoutChartPresetName): LayoutChartNode;
  function createChart(config: LayoutChartConfig): LayoutChartNode;

  /**
   * Create an editable native PowerPoint math formula from the supported
   * LaTeX profile. The preview uses the sibling SVG projection.
   */
  function createFormula(): LayoutFormulaNode;
  function createFormula(latex: string): LayoutFormulaNode;
  function createFormula(config: LayoutFormulaConfig): LayoutFormulaNode;

  /**
   * Create a generic flex container (replaces VStack/HStack). Configure
   * `flexDirection`, `padding`, `gap`, etc. either via the optional config
   * object or by direct property assignment after creation.
   *
   * The returned node carries an `add(...children)` method that accepts a
   * mix of single nodes, arrays of nodes, and `null` / `undefined` (skipped).
   */
  function createFrame(config?: LayoutViewConfig): LayoutViewNode & {
      add(...children: Array<LayoutNode | LayoutNode[] | null | undefined>): LayoutViewNode;
  };

  /**
   * Create an image leaf node. Pass an image source (string URL / data URI /
   * absolute local path / formal source object) or a config object containing
   * `src` plus any visual options (`fitMode`, `maskShape`, `shadow`, ...).
   */
  function createImage(): LayoutImageNode;
  function createImage(src: LayoutImageSourceInput): LayoutImageNode;
  function createImage(config: LayoutImageConfig): LayoutImageNode;

  /**
   * Create a shape leaf node. `fill` accepts a color or linear/radial gradient;
   * `border.paint` accepts a linear gradient (radial stroke is intentionally unsupported).
   * Configure `geometry`, `fill`, `border`, `borderRadius`, `opacity`,
   * `rotate`, `content` etc. through the optional
   * config object or by direct property assignment.
   */
  function createShape(config?: LayoutShapeConfig): LayoutShapeNode;

  /**
   * Create a Slide root container. Each call produces one slide; assemble
   * the slide tree with the `add(...children)` method, then pass the array
   * of slides to `compose({ slides: [...] })`.
   *
   * Configure background / notes either via the optional
   * config object or by direct property assignment after creation.
   */
  function createSlide(config?: LayoutSlideConfig): LayoutSlideNode & {
      add(...children: Array<LayoutNode | LayoutNode[] | null | undefined>): LayoutSlideNode;
  };

  /**
   * Create a flex Spacer (zero visual output). Use `flex: N` to claim a
   * proportional share of remaining space inside a flex container.
   */
  function createSpacer(config?: LayoutSpacerConfig): LayoutSpacerNode;

  /**
   * Create a text-free SVG graphic. Pass inline SVG text, a formal SVG source,
   * or a config object. Use createText() for all presentation text.
   */
  function createSvgGraphic(): LayoutSvgGraphicNode;
  function createSvgGraphic(source: LayoutSvgGraphicSourceInput): LayoutSvgGraphicNode;
  function createSvgGraphic(config: LayoutSvgGraphicConfig): LayoutSvgGraphicNode;

  /**
   * Create a table leaf node. Provide `headers` + `rows` at the top level,
   * Cell entries can be display values or `LayoutTableCellInput` objects
   * with per-cell styling and row/column spans.
   */
  function createTable(config?: LayoutTableConfig): LayoutTableNode;

  /**
   * Create a text leaf node. Pass a plain string (newlines preserved),
   * a `LayoutTextRun[]` array for rich text, a config object, or nothing
   * and configure properties later.
   */
  function createText(): LayoutTextNode;
  function createText(content: string): LayoutTextNode;
  function createText(content: number | boolean): LayoutTextNode;
  function createText(content: LayoutTextRun[]): LayoutTextNode;
  function createText(config: LayoutTextConfig): LayoutTextNode;



  // ── Sandbox-injected globals ──

  /**
   * Names of all registered chart presets. Pass any entry as the first
   * argument to `createChart()` (e.g. `createChart("clean-column")`).
   */
  const CHART_PRESETS: readonly LayoutChartPresetName[];

  /**
   * Existing-deck design anchors. Always defined, even when the deck has no
   * matching theme values (sandbox then provides an empty skeleton),
   * so `DECK_DESIGN.palette.accent1 ?? "#000"` is always safe.
   */
  const DECK_DESIGN: {
    palette: {
      accent1?: string;
      accent2?: string;
      accent3?: string;
      background?: string;
      text?: string;
      muted?: string;
    };
    fonts: { major?: string; minor?: string };
  };

  /** Sandbox 16:9 reference height in inches (5.625); prefer flex/percent for other layouts. */
  const SLIDE_H: number;

  /** Sandbox 16:9 reference width in inches (10); prefer flex/percent for other layouts. */
  const SLIDE_W: number;

  /**
   * Submit the assembled deck to the host. Must be called exactly once at
   * the end of the script. After calling `compose(...)` the script body
   * should return — anything that throws afterwards is recoverable but
   * surfaces as a warning.
   */
  function compose(input: FlexComposeInput): void;

  /**
   * Sandbox-provided logging sink. Messages are captured by the runner
   * and returned as sandbox logs; only log/warn/error are available.
   */
  const console: {
    log(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
  };
}

export {};
