import type { MessageCatalogContribution } from '@app/localization';
import type { WorkspaceMessageKey } from './workspaceMessages';

export const WORKSPACE_MESSAGE_FALLBACKS = {
  'workspace.sidebar.state.loadingProjects': '正在加载...',
  'workspace.sidebar.state.error': '加载项目失败',
  'workspace.sidebar.section.projects': '项目',
  'workspace.sidebar.section.recentChats': '最近对话',
  'workspace.sidebar.section.projectFiles': '项目文件',
  'workspace.sidebar.project.empty': '还没有任何项目',
  'workspace.sidebar.project.createFirst': '创建第一个项目',
  'workspace.sidebar.project.fallbackName': '项目',
  'workspace.sidebar.project.currentFallbackName': '当前项目',
  'workspace.sidebar.projectFiles.fallbackName': '项目文件',
  'workspace.sidebar.project.open': '打开项目',
  'workspace.sidebar.project.moreOptions': '更多选项',
  'workspace.sidebar.project.menu.overview': '项目概览',
  'workspace.sidebar.project.menu.edit': '编辑项目信息',
  'workspace.sidebar.project.menu.delete': '删除项目',
  'workspace.sidebar.project.delete.title': '删除项目',
  'workspace.sidebar.project.delete.confirm': '永久删除',
  'workspace.sidebar.project.delete.cancel': '取消',
  'workspace.sidebar.project.delete.messageWithoutName': '删除后不可恢复，确定要删除这个项目吗？',
  'workspace.sidebar.project.delete.messageWithName': '确定要删除项目「{projectName}」吗？\n删除后不可恢复。',
  'workspace.sidebar.projectSetup.eyebrow': 'AI 项目初始化',
  'workspace.sidebar.projectSetup.title': '正在为你搭建项目结构',
  'workspace.sidebar.projectSetup.badge': '规划中',
  'workspace.sidebar.projectSetup.subtitle': '在右侧与 AI 简短对话，确认项目背景与目标。完成后点击「完成并生成文档」，这里会自动出现问题定义、议题树和工作计划。',
  'workspace.sidebar.projectUnavailable': '当前项目不可用，请返回项目列表重新打开。',
  'workspace.sidebar.fileTree.newFolder': '新建文件夹',
  'workspace.sidebar.fileTree.newFile': '新建',
  'workspace.sidebar.fileTree.newBadge': '新建',
  'workspace.sidebar.fileTree.moreOptions': '更多选项',
  'workspace.sidebar.fileTree.searchEmpty': '没有匹配的文件',
  'workspace.sidebar.fileTree.emptyTitle': '开始创作',
  'workspace.sidebar.fileTree.emptyBadge': '新项目',
  'workspace.sidebar.fileTree.emptySubtitle': '这个项目还没有任何内容，先创建一个文档、思维导图、表格或演示文稿。',
  'workspace.sidebar.fileTree.aiInit': 'AI 项目初始化',
  'workspace.sidebar.fileTree.currentProject': '当前项目',
  'workspace.sidebar.fileTree.loading': '加载文件中...',
  'workspace.sidebar.fileTree.menu.editInfo': '编辑信息',
  'workspace.sidebar.fileTree.menu.batchExport': '批量导出',
  'workspace.sidebar.fileTree.menu.exportMarkdown': '导出为 Markdown',
  'workspace.sidebar.fileTree.batchExportComplete': '批量导出完成：已导出 {count} 个 Markdown 文件。',
  'workspace.sidebar.fileTree.loadFailed': '加载项目文件失败，请稍后重试。',
  'workspace.sidebar.node.fallbackName': '节点',
  'workspace.sidebar.node.untitledDocument': '未命名文档',
  'workspace.sidebar.node.untitledFolder': '未命名文件夹',
  'workspace.sidebar.node.imagePreview': '图片预览',
  'workspace.sidebar.node.attachment': '附件',
  'workspace.sidebar.node.imageLoadFailed': '图片加载失败',
  'workspace.sidebar.node.imagePreviewPathMissing': '这个图片资源没有可预览的本地路径',
  'workspace.sidebar.node.selectProjectFirst': '请先选择一个项目',
  'workspace.sidebar.node.readAttachmentFailed': '读取附件失败',
  'workspace.sidebar.node.openFailed': '打开{documentName}失败',
  'workspace.sidebar.node.createFileFailed': '创建文件失败',
  'workspace.sidebar.node.createFolderFailed': '创建文件夹失败',
  'workspace.sidebar.node.unregisteredCreateType': '未注册的新建文档类型: {type}',
  'workspace.sidebar.node.pluginDisabled': '“{documentType}” 插件已禁用',
  'workspace.sidebar.node.unavailable.disabled': '“{documentType}” 由 {pluginName} 插件支持；当前插件已停用，启用后可打开。',
  'workspace.sidebar.node.unavailable.missing': '“{documentType}” 由 {pluginName} 插件支持；安装后可打开。',
  'workspace.sidebar.node.unavailable.loadFailed': '“{documentType}” 由 {pluginName} 插件支持；插件已启用，但前端入口加载失败。',
  'workspace.sidebar.node.unavailable.unknown': '暂不支持打开这种文件类型：{nodeType}',
  'workspace.sidebar.node.unavailable.fallback': '当前文件类型暂不可打开',
  'workspace.sidebar.node.moveIntoDescendantBlocked': '不能将文件夹移动到自己的子文件夹中',
  'workspace.sidebar.node.moveFailed': '移动失败',
  'workspace.sidebar.node.transferFailed': '移动到项目失败',
  'workspace.sidebar.node.transferSaveFailed': '当前文档未能保存，已取消移动',
  'workspace.sidebar.node.transferSuccess': '“{nodeName}”已移动到项目“{projectName}”',
  'workspace.sidebar.node.parentNotFound': '目标文件夹不存在或已被删除',
  'workspace.sidebar.node.parentNotFolder': '只能移动到文件夹中',
  'workspace.sidebar.node.parentProjectMismatch': '不能把节点移动到另一个项目的文件夹中',
  'workspace.sidebar.node.moveCycle': '不能把文件夹移动到自身或其子文件夹中',
  'workspace.sidebar.node.transferSameProject': '节点已经属于这个项目',
  'workspace.sidebar.node.subtreeProjectMismatch': '文件夹层级数据异常，无法安全移动',
  'workspace.sidebar.node.nameConflict': '同一位置已存在名为“{nodeName}”的文件或文件夹',
  'workspace.sidebar.node.notFound': '这个项目不存在或已被删除',
  'workspace.sidebar.node.missingProject': '这个节点缺少所属项目，无法执行此操作',
  'workspace.sidebar.node.duplicateFolderUnsupported': '暂不支持复制文件夹',
  'workspace.sidebar.node.documentTypeUnavailable': '当前无法处理这种文件类型：{documentType}',
  'workspace.sidebar.node.sourceDocumentMissing': '源文档不存在，无法复制',
  'workspace.sidebar.node.addToKnowledgeBaseEditorUnavailable': '编辑器实例不可用，无法添加到知识库',
  'workspace.sidebar.node.addToKnowledgeBaseSuccess': '已将「{fileName}」加入上传队列，正在解析入库',
  'workspace.sidebar.node.addToKnowledgeBaseFailed': '添加失败',
  'workspace.sidebar.node.context.copyRelativePath': '复制相对路径',
  'workspace.sidebar.node.context.refresh': '刷新',
  'workspace.sidebar.node.context.showInFolder': '在 Finder 中显示',
  'workspace.sidebar.node.context.preview': '预览 / 读取',
  'workspace.sidebar.node.context.addToKnowledgeBase': '添加到知识库',
  'workspace.sidebar.node.context.duplicate': '创建副本',
  'workspace.sidebar.node.context.rename': '重命名',
  'workspace.sidebar.node.context.delete': '删除',
  'workspace.sidebar.node.context.newFile': '新建文件',
  'workspace.sidebar.node.context.newFolder': '新建文件夹',
  'workspace.sidebar.node.context.moveToProject': '移动到项目',
  'workspace.sidebar.node.context.noOtherProjects': '没有其他可移动到的项目',
  'workspace.sidebar.node.noCopyContent': '没有可复制的内容',
  'workspace.sidebar.node.createFileUnsupported': '当前不支持新建文件',
  'workspace.sidebar.node.showInFolderUnsupported': '当前环境不支持在 Finder 中显示',
  'workspace.sidebar.node.showInFolderFailed': '在 Finder 中显示失败',
  'workspace.sidebar.node.actionUnsupported': '这个节点不支持该操作',
  'workspace.sidebar.node.createFolderUnsupported': '当前不支持新建文件夹',
  'workspace.sidebar.node.duplicated': '"{nodeName}" 已复制',
  'workspace.sidebar.node.duplicateFailed': '复制失败',
  'workspace.sidebar.node.batchDuplicateSuccess': '成功创建 {count} 个副本',
  'workspace.sidebar.node.batchDuplicatePartial': '成功创建 {successCount} 个副本，失败 {failCount} 个',
  'workspace.sidebar.node.batchDuplicateFailed': '批量创建副本失败',
  'workspace.sidebar.node.addToKnowledgeBaseUnsupported': '当前不支持添加到知识库',
  'workspace.sidebar.node.relativePathCopied': '相对路径已复制',
  'workspace.sidebar.node.operationFailed': '{nodeName}操作失败',
  'workspace.sidebar.node.batchDeleteTitle': '批量删除确认',
  'workspace.sidebar.node.batchDeleteMessage': '确定要删除选中的 {count} 个项目吗？',
  'workspace.sidebar.node.deleteTitle': '删除确认',
  'workspace.sidebar.node.deleteMessage': '确定要删除 "{nodeName}" 吗？',
  'workspace.sidebar.node.deleteConfirm': '删除',
  'workspace.sidebar.node.deleteCancel': '取消',
  'workspace.sidebar.node.batchDeleteSuccess': '成功删除 {count} 个项目',
  'workspace.sidebar.node.batchDeletePartial': '成功删除 {successCount} 个，失败 {failCount} 个',
  'workspace.sidebar.node.batchDeleteFailed': '批量删除失败',
  'workspace.sidebar.node.deleted': '"{nodeName}" 已删除',
  'workspace.sidebar.node.deleteFailed': '删除失败',
  'workspace.sidebar.node.renameEmpty': '名称不能为空',
  'workspace.sidebar.node.renameFailed': '重命名失败',
  'workspace.sidebar.node.unknownError': '未知错误',
  'workspace.fileManager.markdown.openFailed': '打开文档失败',
  'workspace.fileManager.markdown.untitledDocument': '未命名文档',
  'workspace.fileManager.markdown.editorUnavailable': '保存失败：编辑器不可用',
  'workspace.fileManager.markdown.documentIdMissing': '保存失败：文档 ID 丢失',
  'workspace.fileManager.markdown.saved': '已保存',
  'workspace.fileManager.save.unknownError': '未知错误',
  'workspace.fileManager.save.failed': '保存失败',
  'workspace.fileManager.save.exception': '保存出错',
  'workspace.project.modal.createTitle': '创建新项目',
  'workspace.project.modal.editTitle': '编辑项目信息',
  'workspace.project.modal.nameLabel': '项目名称',
  'workspace.project.modal.namePlaceholder': '请输入项目名称',
  'workspace.project.modal.descriptionLabel': '项目描述',
  'workspace.project.modal.descriptionPlaceholder': '描述项目背景信息、目标和预期结果等；Linnya 可以更深入地理解你的项目',
  'workspace.project.modal.knowledgeBaseLabel': '关联知识库',
  'workspace.project.modal.knowledgeBasePlaceholder': '选择知识库...',
  'workspace.project.modal.knowledgeBaseSelectTitle': '选择要关联的知识库',
  'workspace.project.modal.aiCreate': 'AI 辅助创建',
  'workspace.project.modal.cancel': '取消',
  'workspace.project.modal.save': '保存',
  'workspace.project.modal.saving': '保存中...',
  'workspace.project.modal.create': '创建项目',
  'workspace.project.modal.creating': '创建中...',
  'workspace.project.modal.defaultProjectName': '我的新项目',
  'workspace.project.modal.nameRequired': '项目名称不能为空',
  'workspace.project.modal.nameTooLong': '项目名称不能超过100个字符',
  'workspace.project.operation.linkKnowledgeBaseFailed': '关联知识库失败',
  'workspace.project.operation.linkKnowledgeBaseIpcFailed': '关联知识库失败：IPC 调用异常，请查看日志',
  'workspace.project.operation.unknownError': '未知错误',
  'workspace.project.operation.duplicateName': '项目名称 "{projectName}" 已存在，请换一个名称',
  'workspace.project.operation.projectNotFound': '这个项目不存在或已被删除',
  'workspace.project.operation.defaultProjectDeleteBlocked': '默认项目不能删除',
  'workspace.project.operation.created': '项目 "{projectName}" 已创建',
  'workspace.project.operation.createFailed': '创建项目失败',
  'workspace.project.operation.updated': '项目信息已更新',
  'workspace.project.operation.updateFailed': '更新失败',
  'workspace.project.operation.deleted': '项目已删除',
  'workspace.project.operation.deleteFailed': '删除失败',
  'workspace.project.operation.createdWithAiPlanning': '项目 "{projectName}" 已创建，开始 AI 辅助规划',
  'workspace.project.operation.selectProjectFirst': '请先选择一个项目',
  'workspace.project.operation.currentProject': '当前项目',
  'workspace.project.operation.aiPlanningStarted': '开始 AI 辅助规划项目 "{projectName}"',
  'workspace.project.operation.aiInitFailed': '初始化失败',
  'workspace.projectOverview.title': '项目概览',
  'workspace.projectOverview.loading': '统计中',
  'workspace.projectOverview.untitledProject': '未命名项目',
  'workspace.projectOverview.loadFailed': '文件统计加载失败',
  'workspace.projectOverview.stats.pages': '页面',
  'workspace.projectOverview.stats.pagesHint': '包含文档、思维导图、表格与演示文稿',
  'workspace.projectOverview.stats.folders': '文件夹',
  'workspace.projectOverview.stats.characters': '字符数',
  'workspace.todo.create.title': '创建待办',
  'workspace.todo.create.close': '关闭',
  'workspace.todo.create.titlePlaceholder': '输入任务名称...',
  'workspace.todo.create.tagPlaceholder': '添加标签...',
  'workspace.todo.create.priority': '优先级',
  'workspace.todo.create.date': '日期',
  'workspace.todo.create.time': '时间',
  'workspace.todo.create.datePlaceholder': '选择日期',
  'workspace.todo.create.timePlaceholder': '选择时间',
  'workspace.todo.create.cancel': '取消',
  'workspace.todo.create.add': '添加',
  'workspace.todo.priority.low': '低',
  'workspace.todo.priority.medium': '中',
  'workspace.todo.priority.high': '高',
  'workspace.todo.item.delete': '删除任务',
  'workspace.todo.date.today': '今天',
  'workspace.todo.date.tomorrow': '明天',
  'workspace.todo.section.schedule': '日程',
  'workspace.todo.section.todo': '待办',
  'workspace.todo.section.completed': '已完成',
  'workspace.todo.section.overdue': '过期任务',
  'workspace.todo.section.future': '远期任务',
  'workspace.todo.empty': '暂无任务',
  'workspace.export.modal.title.txt': '导出为 TXT',
  'workspace.export.modal.title.markdown': '导出为 Markdown',
  'workspace.export.modal.title.pdf': '导出为 PDF',
  'workspace.export.modal.title.docx': '导出为 Word',
  'workspace.export.modal.title.settings': '导出设置',
  'workspace.export.modal.invalidType': '无效的导出类型',
  'workspace.export.modal.cancel': '取消',
  'workspace.export.modal.export': '导出',
  'workspace.export.modal.txtSettingsUnavailable': '导出失败：无法访问 TXT 导出设置。',
  'workspace.export.modal.markdownSettingsUnavailable': '导出失败：无法访问 Markdown 导出设置。',
  'workspace.export.modal.editorUnavailable': '导出失败：编辑器实例不可用。',
  'workspace.export.modal.invalidTypeAlert': '无效的导出类型！',
  'workspace.export.service.editorNotReady': '导出失败：编辑器未准备好。',
  'workspace.export.service.markdownEditorNotReady': '导出 Markdown 失败：编辑器未准备好。',
  'workspace.export.service.markdownTxtEditorNotReady': '导出 Markdown TXT 失败：编辑器未准备好。',
  'workspace.export.service.pdfEditorNotReady': '导出 PDF 失败：编辑器未准备好。',
  'workspace.export.service.exportUnavailable': '导出功能不可用，请检查应用程序设置。',
  'workspace.export.service.pdfUnavailable': '导出 PDF 功能不可用，请检查应用程序设置。',
  'workspace.export.service.wordUnavailable': '导出为 Word 功能尚未实现。',
  'workspace.export.service.pdfTitle': '导出文档',
  'workspace.export.dialog.exportButton': '导出',
  'workspace.export.dialog.title.txt': '导出为 TXT',
  'workspace.export.dialog.title.markdown': '导出为 Markdown',
  'workspace.export.dialog.title.pdf': '导出为 PDF',
  'workspace.export.dialog.filter.txt': '文本文件',
  'workspace.export.dialog.filter.markdown': 'Markdown 文件',
  'workspace.export.dialog.filter.pdf': 'PDF 文件',
  'workspace.export.defaultFileName': '未命名文档',
  'workspace.export.markdownSerializer.bibliographyTitle': '参考文献',
  'workspace.export.markdownSerializer.imageAlt': '图片',
  'workspace.export.markdownSerializer.imageDescription': '[图片：{alt}]',
  'workspace.export.markdownSerializer.imageDescriptionWithWidth': '[图片：{alt}，宽度{width}px]',
  'workspace.export.markdownSerializer.imageDescriptionWithHeight': '[图片：{alt}，高度{height}px]',
  'workspace.export.markdownSerializer.imageDescriptionWithSize': '[图片：{alt}，宽度{width}px，高度{height}px]',
  'workspace.export.markdownSerializer.audioFile': '音频文件',
  'workspace.export.markdownSerializer.emptyAudioBlock': '空音频块',
  'workspace.export.docx.placeholder': '该导出功能正在开发中，敬请期待！',
  'workspace.export.pdf.pageSize': '纸张大小',
  'workspace.export.pdf.pageSizeTitle': '选择纸张大小',
  'workspace.export.pdf.orientation': '页面方向',
  'workspace.export.pdf.orientationPortrait': '纵向',
  'workspace.export.pdf.orientationLandscape': '横向',
  'workspace.export.pdf.margins': '页面边距（cm）',
  'workspace.export.pdf.marginTop': '上',
  'workspace.export.pdf.marginBottom': '下',
  'workspace.export.pdf.marginLeft': '左',
  'workspace.export.pdf.marginRight': '右',
  'workspace.export.txt.format': '导出格式',
  'workspace.export.txt.plain': '纯文本 (.txt)',
  'workspace.export.txt.markdownTxt': 'Markdown 语法文本 (.txt)',
  'workspace.export.txt.markdownTxtDescription': '保留 Markdown 语法的纯文本文件，便于在任何文本编辑器中查看。',
  'workspace.export.batch.title': '批量导出为 Markdown',
  'workspace.export.batch.options': '导出选项',
  'workspace.export.batch.escapeSpecialChars': '转义特殊字符',
  'workspace.export.batch.escapeSpecialCharsDescription': '转义 Markdown 特殊字符（如 *、_、#、[]、() 等），确保显示正确。',
  'workspace.export.batch.lineBreakStyle': '换行风格',
  'workspace.export.batch.lineBreakStandard': '标准',
  'workspace.export.batch.lineBreakNewline': '\\n换行',
  'workspace.export.batch.scopeTip': '将导出整个项目内的所有 Markdown 文档；其他文档类型会被自动跳过。',
  'workspace.export.batch.currentProject': '当前项目：{projectName}',
  'workspace.export.batch.cancel': '取消',
  'workspace.export.batch.export': '导出',
  'workspace.export.batch.apiUnavailable': '批量导出不可用：electronAPI 未就绪。',
  'workspace.export.batch.schemaUnavailable': '批量导出失败：编辑器 schema 不可用（请先打开任意文档）。',
  'workspace.export.batch.noDocuments': '当前项目下没有可导出的 Markdown 文档。',
  'workspace.export.batch.chooseDirectory': '选择导出目录',
  'workspace.export.batch.openDirectoryFailed': '打开目录选择对话框失败。',
  'workspace.export.batch.directorySelectionCanceled': '已取消选择导出目录。',
  'workspace.export.batch.readDocumentFailed': '读取文档失败：{documentName}',
  'workspace.export.batch.writeFailed': '批量写入文件失败。',
  'workspace.projectKb.title': '管理关联的知识库',
  'workspace.projectKb.subtitle': '为保证 AI 的回答质量，请选择与当前项目相关的知识库。',
  'workspace.projectKb.linkedTitle': '已关联知识库',
  'workspace.projectKb.availableTitle': '可关联的知识库',
  'workspace.projectKb.count': '{count} 个',
  'workspace.projectKb.loadingLinks': '正在加载关联关系…',
  'workspace.projectKb.emptyLinked': '暂未关联任何知识库',
  'workspace.projectKb.loadingKnowledgeBases': '正在加载知识库列表…',
  'workspace.projectKb.emptyAvailable': '暂无可关联的知识库',
  'workspace.projectKb.unlinkTitle': '解除关联',
  'workspace.projectKb.unlink': '解除',
  'workspace.projectKb.linkTitle': '关联到当前项目',
  'workspace.projectKb.link': '关联',
  'workspace.projectKb.save': '保存',
  'workspace.projectKb.saving': '保存中…',
  'workspace.projectKb.untitledProject': '未命名项目',
  'workspace.projectKb.loadFailed': '加载项目关联的知识库失败',
  'workspace.projectKb.updateFailed': '更新项目关联的知识库失败',
  'workspace.projectKb.updated': '项目关联的知识库已更新',
  'workspace.projectKb.saveFailed': '保存项目关联知识库失败',
} as const satisfies Readonly<Record<WorkspaceMessageKey, string>>;

export const WORKSPACE_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'workspace',
  catalogs: {
    'zh-CN': WORKSPACE_MESSAGE_FALLBACKS,
    'en-US': {
      'workspace.sidebar.state.loadingProjects': 'Loading...',
      'workspace.sidebar.state.error': 'Failed to load projects',
      'workspace.sidebar.section.projects': 'Projects',
      'workspace.sidebar.section.recentChats': 'Recent chats',
      'workspace.sidebar.section.projectFiles': 'Project files',
      'workspace.sidebar.project.empty': 'No projects yet',
      'workspace.sidebar.project.createFirst': 'Create first project',
      'workspace.sidebar.project.fallbackName': 'Project',
      'workspace.sidebar.project.currentFallbackName': 'Current project',
      'workspace.sidebar.projectFiles.fallbackName': 'Project files',
      'workspace.sidebar.project.open': 'Open project',
      'workspace.sidebar.project.moreOptions': 'More options',
      'workspace.sidebar.project.menu.overview': 'Project overview',
      'workspace.sidebar.project.menu.edit': 'Edit project info',
      'workspace.sidebar.project.menu.delete': 'Delete project',
      'workspace.sidebar.project.delete.title': 'Delete project',
      'workspace.sidebar.project.delete.confirm': 'Delete forever',
      'workspace.sidebar.project.delete.cancel': 'Cancel',
      'workspace.sidebar.project.delete.messageWithoutName': 'This cannot be undone. Delete this project?',
      'workspace.sidebar.project.delete.messageWithName': 'Delete project "{projectName}"?\nThis cannot be undone.',
      'workspace.sidebar.projectSetup.eyebrow': 'AI project setup',
      'workspace.sidebar.projectSetup.title': 'Building your project structure',
      'workspace.sidebar.projectSetup.badge': 'Planning',
      'workspace.sidebar.projectSetup.subtitle': 'Have a short conversation with AI on the right to confirm the project background and goals. After you finish and generate documents, problem definitions, topic trees, and work plans will appear here automatically.',
      'workspace.sidebar.projectUnavailable': 'The current project is unavailable. Return to the project list and open it again.',
      'workspace.sidebar.fileTree.newFolder': 'New folder',
      'workspace.sidebar.fileTree.newFile': 'New',
      'workspace.sidebar.fileTree.newBadge': 'New',
      'workspace.sidebar.fileTree.moreOptions': 'More options',
      'workspace.sidebar.fileTree.searchEmpty': 'No matching files',
      'workspace.sidebar.fileTree.emptyTitle': 'Start creating',
      'workspace.sidebar.fileTree.emptyBadge': 'New project',
      'workspace.sidebar.fileTree.emptySubtitle': 'This project is empty. Create a document, mind map, spreadsheet, or presentation to begin.',
      'workspace.sidebar.fileTree.aiInit': 'AI project setup',
      'workspace.sidebar.fileTree.currentProject': 'Current project',
      'workspace.sidebar.fileTree.loading': 'Loading files...',
      'workspace.sidebar.fileTree.menu.editInfo': 'Edit info',
      'workspace.sidebar.fileTree.menu.batchExport': 'Batch export',
      'workspace.sidebar.fileTree.menu.exportMarkdown': 'Export as Markdown',
      'workspace.sidebar.fileTree.batchExportComplete': 'Batch export complete: exported {count} Markdown files.',
      'workspace.sidebar.fileTree.loadFailed': 'Failed to load project files. Please try again.',
      'workspace.sidebar.node.fallbackName': 'Node',
      'workspace.sidebar.node.untitledDocument': 'Untitled document',
      'workspace.sidebar.node.untitledFolder': 'Untitled folder',
      'workspace.sidebar.node.imagePreview': 'Image preview',
      'workspace.sidebar.node.attachment': 'Attachment',
      'workspace.sidebar.node.imageLoadFailed': 'Failed to load image',
      'workspace.sidebar.node.imagePreviewPathMissing': 'This image resource has no local path to preview.',
      'workspace.sidebar.node.selectProjectFirst': 'Choose a project first',
      'workspace.sidebar.node.readAttachmentFailed': 'Failed to read attachment',
      'workspace.sidebar.node.openFailed': 'Failed to open {documentName}',
      'workspace.sidebar.node.createFileFailed': 'Failed to create file',
      'workspace.sidebar.node.createFolderFailed': 'Failed to create folder',
      'workspace.sidebar.node.unregisteredCreateType': 'Unregistered create document type: {type}',
      'workspace.sidebar.node.pluginDisabled': 'The "{documentType}" plugin is disabled',
      'workspace.sidebar.node.unavailable.disabled': '"{documentType}" is supported by the {pluginName} plugin. The plugin is disabled; enable it to open this file.',
      'workspace.sidebar.node.unavailable.missing': '"{documentType}" is supported by the {pluginName} plugin. Install it to open this file.',
      'workspace.sidebar.node.unavailable.loadFailed': '"{documentType}" is supported by the {pluginName} plugin. The plugin is enabled, but its renderer entry failed to load.',
      'workspace.sidebar.node.unavailable.unknown': 'This file type is not supported yet: {nodeType}',
      'workspace.sidebar.node.unavailable.fallback': 'This file type cannot be opened right now',
      'workspace.sidebar.node.moveIntoDescendantBlocked': 'Cannot move a folder into its own child folder',
      'workspace.sidebar.node.moveFailed': 'Move failed',
      'workspace.sidebar.node.transferFailed': 'Failed to move to project',
      'workspace.sidebar.node.transferSaveFailed': 'The current document could not be saved, so the move was cancelled',
      'workspace.sidebar.node.transferSuccess': '“{nodeName}” moved to project “{projectName}”',
      'workspace.sidebar.node.parentNotFound': 'The destination folder does not exist or was deleted',
      'workspace.sidebar.node.parentNotFolder': 'Items can only be moved into folders',
      'workspace.sidebar.node.parentProjectMismatch': 'An item cannot be moved into a folder in another project',
      'workspace.sidebar.node.moveCycle': 'A folder cannot be moved into itself or one of its child folders',
      'workspace.sidebar.node.transferSameProject': 'This item already belongs to that project',
      'workspace.sidebar.node.subtreeProjectMismatch': 'The folder hierarchy is inconsistent, so it cannot be moved safely',
      'workspace.sidebar.node.nameConflict': 'An item named "{nodeName}" already exists in this folder',
      'workspace.sidebar.node.notFound': 'This item does not exist or has been deleted',
      'workspace.sidebar.node.missingProject': 'This item has no project, so the operation cannot be completed',
      'workspace.sidebar.node.duplicateFolderUnsupported': 'Duplicating folders is not supported yet',
      'workspace.sidebar.node.documentTypeUnavailable': 'This file type cannot be handled right now: {documentType}',
      'workspace.sidebar.node.sourceDocumentMissing': 'The source document does not exist, so it cannot be duplicated',
      'workspace.sidebar.node.addToKnowledgeBaseEditorUnavailable': 'The editor instance is unavailable, so this cannot be added to the knowledge base',
      'workspace.sidebar.node.addToKnowledgeBaseSuccess': '"{fileName}" was added to the upload queue and is being parsed',
      'workspace.sidebar.node.addToKnowledgeBaseFailed': 'Add failed',
      'workspace.sidebar.node.context.copyRelativePath': 'Copy relative path',
      'workspace.sidebar.node.context.refresh': 'Refresh',
      'workspace.sidebar.node.context.showInFolder': 'Show in Finder',
      'workspace.sidebar.node.context.preview': 'Preview / read',
      'workspace.sidebar.node.context.addToKnowledgeBase': 'Add to knowledge base',
      'workspace.sidebar.node.context.duplicate': 'Duplicate',
      'workspace.sidebar.node.context.rename': 'Rename',
      'workspace.sidebar.node.context.delete': 'Delete',
      'workspace.sidebar.node.context.newFile': 'New file',
      'workspace.sidebar.node.context.newFolder': 'New folder',
      'workspace.sidebar.node.context.moveToProject': 'Move to project',
      'workspace.sidebar.node.context.noOtherProjects': 'There are no other projects to move this item to',
      'workspace.sidebar.node.noCopyContent': 'Nothing to copy',
      'workspace.sidebar.node.createFileUnsupported': 'Creating files is not supported here',
      'workspace.sidebar.node.showInFolderUnsupported': 'Show in Finder is not supported in this environment',
      'workspace.sidebar.node.showInFolderFailed': 'Failed to show in Finder',
      'workspace.sidebar.node.actionUnsupported': 'This node does not support that action',
      'workspace.sidebar.node.createFolderUnsupported': 'Creating folders is not supported here',
      'workspace.sidebar.node.duplicated': '"{nodeName}" duplicated',
      'workspace.sidebar.node.duplicateFailed': 'Duplicate failed',
      'workspace.sidebar.node.batchDuplicateSuccess': 'Created {count} copies',
      'workspace.sidebar.node.batchDuplicatePartial': 'Created {successCount} copies, {failCount} failed',
      'workspace.sidebar.node.batchDuplicateFailed': 'Batch duplicate failed',
      'workspace.sidebar.node.addToKnowledgeBaseUnsupported': 'Adding to the knowledge base is not supported here',
      'workspace.sidebar.node.relativePathCopied': 'Relative path copied',
      'workspace.sidebar.node.operationFailed': '{nodeName} operation failed',
      'workspace.sidebar.node.batchDeleteTitle': 'Confirm batch delete',
      'workspace.sidebar.node.batchDeleteMessage': 'Delete the selected {count} items?',
      'workspace.sidebar.node.deleteTitle': 'Confirm delete',
      'workspace.sidebar.node.deleteMessage': 'Delete "{nodeName}"?',
      'workspace.sidebar.node.deleteConfirm': 'Delete',
      'workspace.sidebar.node.deleteCancel': 'Cancel',
      'workspace.sidebar.node.batchDeleteSuccess': 'Deleted {count} items',
      'workspace.sidebar.node.batchDeletePartial': 'Deleted {successCount}, failed {failCount}',
      'workspace.sidebar.node.batchDeleteFailed': 'Batch delete failed',
      'workspace.sidebar.node.deleted': '"{nodeName}" deleted',
      'workspace.sidebar.node.deleteFailed': 'Delete failed',
      'workspace.sidebar.node.renameEmpty': 'Name is required',
      'workspace.sidebar.node.renameFailed': 'Rename failed',
      'workspace.sidebar.node.unknownError': 'Unknown error',
      'workspace.fileManager.markdown.openFailed': 'Failed to open document',
      'workspace.fileManager.markdown.untitledDocument': 'Untitled document',
      'workspace.fileManager.markdown.editorUnavailable': 'Save failed: the editor is unavailable',
      'workspace.fileManager.markdown.documentIdMissing': 'Save failed: document ID is missing',
      'workspace.fileManager.markdown.saved': 'Saved',
      'workspace.fileManager.save.unknownError': 'Unknown error',
      'workspace.fileManager.save.failed': 'Save failed',
      'workspace.fileManager.save.exception': 'Save error',
      'workspace.project.modal.createTitle': 'Create project',
      'workspace.project.modal.editTitle': 'Edit project info',
      'workspace.project.modal.nameLabel': 'Project name',
      'workspace.project.modal.namePlaceholder': 'Enter project name',
      'workspace.project.modal.descriptionLabel': 'Project description',
      'workspace.project.modal.descriptionPlaceholder': 'Describe the project background, goals, and expected results so Linnya can understand it better.',
      'workspace.project.modal.knowledgeBaseLabel': 'Linked knowledge bases',
      'workspace.project.modal.knowledgeBasePlaceholder': 'Choose knowledge base...',
      'workspace.project.modal.knowledgeBaseSelectTitle': 'Choose knowledge base to link',
      'workspace.project.modal.aiCreate': 'Create with AI',
      'workspace.project.modal.cancel': 'Cancel',
      'workspace.project.modal.save': 'Save',
      'workspace.project.modal.saving': 'Saving...',
      'workspace.project.modal.create': 'Create project',
      'workspace.project.modal.creating': 'Creating...',
      'workspace.project.modal.defaultProjectName': 'My new project',
      'workspace.project.modal.nameRequired': 'Project name is required',
      'workspace.project.modal.nameTooLong': 'Project name cannot exceed 100 characters',
      'workspace.project.operation.linkKnowledgeBaseFailed': 'Failed to link knowledge base',
      'workspace.project.operation.linkKnowledgeBaseIpcFailed': 'Failed to link knowledge base: IPC call failed. Check logs for details.',
      'workspace.project.operation.unknownError': 'Unknown error',
      'workspace.project.operation.duplicateName': 'Project name "{projectName}" already exists. Choose another name.',
      'workspace.project.operation.projectNotFound': 'This project does not exist or has been deleted',
      'workspace.project.operation.defaultProjectDeleteBlocked': 'The default project cannot be deleted',
      'workspace.project.operation.created': 'Project "{projectName}" created',
      'workspace.project.operation.createFailed': 'Failed to create project',
      'workspace.project.operation.updated': 'Project info updated',
      'workspace.project.operation.updateFailed': 'Update failed',
      'workspace.project.operation.deleted': 'Project deleted',
      'workspace.project.operation.deleteFailed': 'Delete failed',
      'workspace.project.operation.createdWithAiPlanning': 'Project "{projectName}" created. Starting AI planning.',
      'workspace.project.operation.selectProjectFirst': 'Choose a project first',
      'workspace.project.operation.currentProject': 'Current project',
      'workspace.project.operation.aiPlanningStarted': 'Starting AI planning for project "{projectName}"',
      'workspace.project.operation.aiInitFailed': 'Initialization failed',
      'workspace.projectOverview.title': 'Project overview',
      'workspace.projectOverview.loading': 'Calculating',
      'workspace.projectOverview.untitledProject': 'Untitled project',
      'workspace.projectOverview.loadFailed': 'Failed to load file statistics',
      'workspace.projectOverview.stats.pages': 'Pages',
      'workspace.projectOverview.stats.pagesHint': 'Includes documents, mind maps, spreadsheets, and presentations',
      'workspace.projectOverview.stats.folders': 'Folders',
      'workspace.projectOverview.stats.characters': 'Characters',
      'workspace.todo.create.title': 'Create task',
      'workspace.todo.create.close': 'Close',
      'workspace.todo.create.titlePlaceholder': 'Enter task name...',
      'workspace.todo.create.tagPlaceholder': 'Add tag...',
      'workspace.todo.create.priority': 'Priority',
      'workspace.todo.create.date': 'Date',
      'workspace.todo.create.time': 'Time',
      'workspace.todo.create.datePlaceholder': 'Choose date',
      'workspace.todo.create.timePlaceholder': 'Choose time',
      'workspace.todo.create.cancel': 'Cancel',
      'workspace.todo.create.add': 'Add',
      'workspace.todo.priority.low': 'Low',
      'workspace.todo.priority.medium': 'Medium',
      'workspace.todo.priority.high': 'High',
      'workspace.todo.item.delete': 'Delete task',
      'workspace.todo.date.today': 'Today',
      'workspace.todo.date.tomorrow': 'Tomorrow',
      'workspace.todo.section.schedule': 'Schedule',
      'workspace.todo.section.todo': 'To do',
      'workspace.todo.section.completed': 'Completed',
      'workspace.todo.section.overdue': 'Overdue',
      'workspace.todo.section.future': 'Upcoming',
      'workspace.todo.empty': 'No tasks',
      'workspace.export.modal.title.txt': 'Export as TXT',
      'workspace.export.modal.title.markdown': 'Export as Markdown',
      'workspace.export.modal.title.pdf': 'Export as PDF',
      'workspace.export.modal.title.docx': 'Export as Word',
      'workspace.export.modal.title.settings': 'Export settings',
      'workspace.export.modal.invalidType': 'Invalid export type',
      'workspace.export.modal.cancel': 'Cancel',
      'workspace.export.modal.export': 'Export',
      'workspace.export.modal.txtSettingsUnavailable': 'Export failed: TXT export settings are unavailable.',
      'workspace.export.modal.markdownSettingsUnavailable': 'Export failed: Markdown export settings are unavailable.',
      'workspace.export.modal.editorUnavailable': 'Export failed: the editor instance is unavailable.',
      'workspace.export.modal.invalidTypeAlert': 'Invalid export type.',
      'workspace.export.service.editorNotReady': 'Export failed: the editor is not ready.',
      'workspace.export.service.markdownEditorNotReady': 'Markdown export failed: the editor is not ready.',
      'workspace.export.service.markdownTxtEditorNotReady': 'Markdown TXT export failed: the editor is not ready.',
      'workspace.export.service.pdfEditorNotReady': 'PDF export failed: the editor is not ready.',
      'workspace.export.service.exportUnavailable': 'Export is unavailable. Check the application settings.',
      'workspace.export.service.pdfUnavailable': 'PDF export is unavailable. Check the application settings.',
      'workspace.export.service.wordUnavailable': 'Export as Word is not implemented yet.',
      'workspace.export.service.pdfTitle': 'Exported document',
      'workspace.export.dialog.exportButton': 'Export',
      'workspace.export.dialog.title.txt': 'Export as TXT',
      'workspace.export.dialog.title.markdown': 'Export as Markdown',
      'workspace.export.dialog.title.pdf': 'Export as PDF',
      'workspace.export.dialog.filter.txt': 'Text Files',
      'workspace.export.dialog.filter.markdown': 'Markdown Files',
      'workspace.export.dialog.filter.pdf': 'PDF Files',
      'workspace.export.defaultFileName': 'Untitled document',
      'workspace.export.markdownSerializer.bibliographyTitle': 'References',
      'workspace.export.markdownSerializer.imageAlt': 'Image',
      'workspace.export.markdownSerializer.imageDescription': '[Image: {alt}]',
      'workspace.export.markdownSerializer.imageDescriptionWithWidth': '[Image: {alt}, width {width}px]',
      'workspace.export.markdownSerializer.imageDescriptionWithHeight': '[Image: {alt}, height {height}px]',
      'workspace.export.markdownSerializer.imageDescriptionWithSize': '[Image: {alt}, width {width}px, height {height}px]',
      'workspace.export.markdownSerializer.audioFile': 'Audio file',
      'workspace.export.markdownSerializer.emptyAudioBlock': 'Empty audio block',
      'workspace.export.docx.placeholder': 'This export feature is still in development.',
      'workspace.export.pdf.pageSize': 'Page size',
      'workspace.export.pdf.pageSizeTitle': 'Choose page size',
      'workspace.export.pdf.orientation': 'Orientation',
      'workspace.export.pdf.orientationPortrait': 'Portrait',
      'workspace.export.pdf.orientationLandscape': 'Landscape',
      'workspace.export.pdf.margins': 'Page margins (cm)',
      'workspace.export.pdf.marginTop': 'Top',
      'workspace.export.pdf.marginBottom': 'Bottom',
      'workspace.export.pdf.marginLeft': 'Left',
      'workspace.export.pdf.marginRight': 'Right',
      'workspace.export.txt.format': 'Export format',
      'workspace.export.txt.plain': 'Plain text (.txt)',
      'workspace.export.txt.markdownTxt': 'Markdown syntax text (.txt)',
      'workspace.export.txt.markdownTxtDescription': 'A plain text file that keeps Markdown syntax, easy to view in any text editor.',
      'workspace.export.batch.title': 'Batch export as Markdown',
      'workspace.export.batch.options': 'Export options',
      'workspace.export.batch.escapeSpecialChars': 'Escape special characters',
      'workspace.export.batch.escapeSpecialCharsDescription': 'Escape Markdown special characters such as *, _, #, [], and () to keep the output displaying correctly.',
      'workspace.export.batch.lineBreakStyle': 'Line break style',
      'workspace.export.batch.lineBreakStandard': 'Standard',
      'workspace.export.batch.lineBreakNewline': '\\n line break',
      'workspace.export.batch.scopeTip': 'Exports all Markdown documents in the project. Other document types are skipped automatically.',
      'workspace.export.batch.currentProject': 'Current project: {projectName}',
      'workspace.export.batch.cancel': 'Cancel',
      'workspace.export.batch.export': 'Export',
      'workspace.export.batch.apiUnavailable': 'Batch export is unavailable: electronAPI is not ready.',
      'workspace.export.batch.schemaUnavailable': 'Batch export failed: editor schema is unavailable. Open any document first.',
      'workspace.export.batch.noDocuments': 'This project has no Markdown documents to export.',
      'workspace.export.batch.chooseDirectory': 'Choose export folder',
      'workspace.export.batch.openDirectoryFailed': 'Failed to open the folder picker.',
      'workspace.export.batch.directorySelectionCanceled': 'Export folder selection canceled.',
      'workspace.export.batch.readDocumentFailed': 'Failed to read document: {documentName}',
      'workspace.export.batch.writeFailed': 'Failed to write exported files.',
      'workspace.projectKb.title': 'Manage linked knowledge bases',
      'workspace.projectKb.subtitle': 'Choose knowledge bases related to the current project to improve AI answer quality.',
      'workspace.projectKb.linkedTitle': 'Linked knowledge bases',
      'workspace.projectKb.availableTitle': 'Available knowledge bases',
      'workspace.projectKb.count': '{count}',
      'workspace.projectKb.loadingLinks': 'Loading linked knowledge bases...',
      'workspace.projectKb.emptyLinked': 'No linked knowledge bases yet',
      'workspace.projectKb.loadingKnowledgeBases': 'Loading knowledge bases...',
      'workspace.projectKb.emptyAvailable': 'No knowledge bases available to link',
      'workspace.projectKb.unlinkTitle': 'Unlink',
      'workspace.projectKb.unlink': 'Unlink',
      'workspace.projectKb.linkTitle': 'Link to current project',
      'workspace.projectKb.link': 'Link',
      'workspace.projectKb.save': 'Save',
      'workspace.projectKb.saving': 'Saving...',
      'workspace.projectKb.untitledProject': 'Untitled project',
      'workspace.projectKb.loadFailed': 'Failed to load linked knowledge bases',
      'workspace.projectKb.updateFailed': 'Failed to update linked knowledge bases',
      'workspace.projectKb.updated': 'Linked knowledge bases updated',
      'workspace.projectKb.saveFailed': 'Failed to save linked knowledge bases',
    },
  },
};
