/**
 * Phase 5 过渡门面：Scene Graph / Flex compose 的纯 DSL 契约已下沉到
 * `@plugin/slides/shared`，方便 sandbox profile、工具管线和未来包内 engine 共用
 * 同一份形状守卫。Flex 编译器实现仍暂留 host，后续随 5BA/5BC 迁包。
 */

export {
  isContainerNode,
  isFlexComposeInput,
  isLeafNode,
} from '@plugin/slides/shared';
export type {
  AbsolutePositionBox,
  ContainerDecoration,
  EdgeInsets,
  FlexComposeInput,
  FlexProps,
  LayoutBorderInput,
  LayoutChartConfig,
  LayoutChartDataLike,
  LayoutChartLegendPosition,
  LayoutChartNode,
  LayoutChartStyle,
  LayoutChartPresetName,
  LayoutChartSeriesInput,
  LayoutChartType,
  LayoutContainerNode,
  LayoutDisplayValue,
  LayoutGradient,
  LayoutGradientStop,
  LayoutHStackNode,
  LayoutImageConfig,
  LayoutImageNode,
  LayoutFormulaConfig,
  LayoutFormulaNode,
  LayoutImageSourceInput,
  LayoutImageSourceRef,
  LayoutImageVisualShadowInput,
  LayoutLinearGradient,
  LayoutLeafNode,
  LayoutNode,
  LayoutRadialGradient,
  LayoutShapeConfig,
  LayoutShapeFillInput,
  LayoutShapeNode,
  LayoutShapeStroke,
  LayoutSvgGraphicConfig,
  LayoutSvgGraphicNode,
  LayoutSvgGraphicSourceInput,
  LayoutSlideBackground,
  LayoutSlideConfig,
  LayoutSlideNode,
  LayoutSourceMetadata,
  LayoutSpacerConfig,
  LayoutSpacerNode,
  LayoutTableCellInput,
  LayoutTableBorderInput,
  LayoutTableCellValue,
  LayoutTableConfig,
  LayoutTableDataLike,
  LayoutTableNode,
  LayoutTextAlign,
  LayoutTextConfig,
  LayoutTextLineSpacingInput,
  LayoutTextNode,
  LayoutTextRun,
  LayoutPlainTextRun,
  LayoutFormulaTextRun,
  LayoutTextStyleInput,
  LayoutThemeInput,
  LayoutVerticalAlign,
  LayoutViewConfig,
  LayoutViewNode,
  LayoutVStackNode,
} from '@plugin/slides/shared';
