import type { MessageCatalogContribution } from '@app/localization';
import type { PluginStoreMessageKey } from './pluginStoreMessages';

export const PLUGIN_STORE_MESSAGE_FALLBACKS = {
  'pluginStore.title': '插件',
  'pluginStore.subtitle': '安装、启停和管理本机可用的 Linnya 插件。',
  'pluginStore.tabs.ariaLabel': '插件范围',
  'pluginStore.tabs.installed': '已有插件',
  'pluginStore.tabs.market': '插件市场',
  'pluginStore.headerMeta.installed': '共 {count} 个已有插件',
  'pluginStore.headerMeta.market': '共 {count} 个可安装插件',
  'pluginStore.back': '插件',
  'pluginStore.loading.list': '正在加载插件列表',
  'pluginStore.loading.detail': '正在加载插件详情',
  'pluginStore.empty.installed': '暂无已安装的插件',
  'pluginStore.empty.market': '暂无可安装插件',
  'pluginStore.empty.installFromMarket': '去插件市场安装吧',
  'pluginStore.list.ariaLabel': '插件列表',
  'pluginStore.card.viewDetail': '查看 {pluginName} 详情',
  'pluginStore.pluginIcon.ariaLabel': '{pluginName} 图标',
  'pluginStore.toggle.ariaLabel': '{pluginName} 启用状态',
  'pluginStore.action.install': '安装',
  'pluginStore.action.uninstall': '卸载',
  'pluginStore.section.introduction': '介绍',
  'pluginStore.section.skills': '技能',
  'pluginStore.section.skill': '技能',
  'pluginStore.section.agents': '智能体',
  'pluginStore.section.agent': '智能体',
  'pluginStore.section.releaseNotes': '版本更新',
  'pluginStore.section.infoManagement': '插件信息与管理',
  'pluginStore.release.expandAll': '展开全部',
  'pluginStore.release.collapse': '收起',
  'pluginStore.fact.version': '版本',
  'pluginStore.fact.developer': '开发者',
  'pluginStore.fact.size': '大小',
  'pluginStore.fact.homepage': '主页',
  'pluginStore.fact.open': '打开',
  'pluginStore.state.enabled': '已启用',
  'pluginStore.state.disabled': '已停用',
  'pluginStore.state.missing': '未安装',
  'pluginStore.reason.required': '核心能力不可禁用',
  'pluginStore.reason.notInstalled': '插件未安装',
  'pluginStore.error.listRefreshFailed': '插件列表刷新失败，请稍后重试。',
  'pluginStore.error.toggleFailed': '插件启停失败，请稍后重试。',
  'pluginStore.error.installFailed': '插件安装失败，请稍后重试。',
  'pluginStore.error.updateFailed': '插件更新失败，请稍后重试。',
  'pluginStore.error.updateCheckFailed': '插件更新检查失败，请稍后重试。',
  'pluginStore.error.uninstallFailed': '插件卸载失败，请稍后重试。',
  'pluginStore.error.detailReadFailed': '插件详情读取失败，请稍后重试。',
  'pluginStore.error.detailReadFallback': '插件详情读取失败',
  'pluginStore.error.homepageOpenFailed': '打开主页失败，请稍后重试。',
  'pluginStore.error.unknown': '未知错误',
  'pluginStore.runtimeError.pluginStateResponseInvalid': '插件状态返回值不是对象',
  'pluginStore.runtimeError.pluginStateReadFailed': '插件状态读取失败',
  'pluginStore.runtimeError.pluginStateSchemaInvalid': '插件状态结构不符合约定',
  'pluginStore.runtimeError.pluginStoreListResponseInvalid': '插件商店列表返回值不是对象',
  'pluginStore.runtimeError.pluginStoreListReadFailed': '插件商店列表读取失败',
  'pluginStore.runtimeError.pluginStoreListSchemaInvalid': '插件商店列表结构不符合约定',
  'pluginStore.runtimeError.pluginStoreDetailUnavailable': '插件详情不可用：{pluginId}',
  'pluginStore.runtimeError.pluginStoreDetailResponseInvalid': '插件详情返回值不是对象',
  'pluginStore.runtimeError.pluginStoreDetailReadFailed': '插件详情读取失败',
  'pluginStore.runtimeError.pluginStoreDetailSchemaInvalid': '插件详情结构不符合约定',
  'pluginStore.runtimeError.pluginRemoteInstallResponseInvalid': '插件远程安装返回值不是对象',
  'pluginStore.runtimeError.pluginRemoteInstallFailed': '插件远程安装失败',
  'pluginStore.runtimeError.pluginRemoteInstallSchemaInvalid': '插件远程安装结果结构不符合约定',
  'pluginStore.runtimeError.pluginRemoteUpdateCheckResponseInvalid': '插件远程更新检查返回值不是对象',
  'pluginStore.runtimeError.pluginRemoteUpdateCheckFailed': '插件远程更新检查失败',
  'pluginStore.runtimeError.pluginRemoteUpdateCheckSchemaInvalid': '插件远程更新检查结果结构不符合约定',
  'pluginStore.runtimeError.pluginDiagnosticsResponseInvalid': '插件诊断返回值不是对象',
  'pluginStore.runtimeError.pluginDiagnosticsReadFailed': '插件诊断读取失败',
  'pluginStore.runtimeError.pluginDiagnosticsSchemaInvalid': '插件诊断结构不符合约定',
  'pluginStore.runtimeError.pluginMutationResponseInvalid': '插件操作返回值不是对象',
  'pluginStore.runtimeError.pluginMutationFailed': '插件操作失败',
  'pluginStore.runtimeError.pluginRemoteUpdateCheckUnsupported': '当前环境不支持插件远程更新检查',
  'pluginStore.runtimeError.pluginRemoteInstallUnsupported': '当前环境不支持插件远程安装',
  'pluginStore.runtimeError.pluginUninstallUnsupported': '当前环境不支持插件卸载',
  'pluginStore.runtimeError.pluginToggleUnsupported': '当前环境不支持插件启停',
  'pluginStore.toast.enabled': '{pluginName} 已启用',
  'pluginStore.toast.disabled': '{pluginName} 已停用',
  'pluginStore.toast.installed': '{pluginName} 已安装，重启后完全生效',
  'pluginStore.toast.updated': '{pluginName} 已更新，重启后完全生效',
  'pluginStore.toast.current': '{pluginName} 已是最新版本',
  'pluginStore.toast.incompatible': '{pluginName} 与当前应用版本不兼容',
  'pluginStore.toast.uninstalled': '{pluginName} 已卸载，重启后完全移除',
  'pluginStore.confirm.uninstall': '卸载 {pluginName}？插件会从本机移除，但不会删除已有文档数据。',
} as const satisfies Readonly<Record<PluginStoreMessageKey, string>>;

export const PLUGIN_STORE_MESSAGE_CATALOG: MessageCatalogContribution = {
  owner: 'plugin-store',
  catalogs: {
    'zh-CN': PLUGIN_STORE_MESSAGE_FALLBACKS,
    'en-US': {
      'pluginStore.title': 'Plugins',
      'pluginStore.subtitle': 'Install, enable, disable, and manage the Linnya plugins available on this device.',
      'pluginStore.tabs.ariaLabel': 'Plugin scope',
      'pluginStore.tabs.installed': 'Installed',
      'pluginStore.tabs.market': 'Marketplace',
      'pluginStore.headerMeta.installed': '{count} installed plugins',
      'pluginStore.headerMeta.market': '{count} installable plugins',
      'pluginStore.back': 'Plugins',
      'pluginStore.loading.list': 'Loading plugin list',
      'pluginStore.loading.detail': 'Loading plugin details',
      'pluginStore.empty.installed': 'No installed plugins yet',
      'pluginStore.empty.market': 'No installable plugins available',
      'pluginStore.empty.installFromMarket': 'Browse the plugin marketplace',
      'pluginStore.list.ariaLabel': 'Plugin list',
      'pluginStore.card.viewDetail': 'View details for {pluginName}',
      'pluginStore.pluginIcon.ariaLabel': '{pluginName} icon',
      'pluginStore.toggle.ariaLabel': '{pluginName} enabled state',
      'pluginStore.action.install': 'Install',
      'pluginStore.action.uninstall': 'Uninstall',
      'pluginStore.section.introduction': 'Introduction',
      'pluginStore.section.skills': 'Skills',
      'pluginStore.section.skill': 'Skill',
      'pluginStore.section.agents': 'Agents',
      'pluginStore.section.agent': 'Agent',
      'pluginStore.section.releaseNotes': 'Release notes',
      'pluginStore.section.infoManagement': 'Plugin info and management',
      'pluginStore.release.expandAll': 'Expand all',
      'pluginStore.release.collapse': 'Collapse',
      'pluginStore.fact.version': 'Version',
      'pluginStore.fact.developer': 'Developer',
      'pluginStore.fact.size': 'Size',
      'pluginStore.fact.homepage': 'Homepage',
      'pluginStore.fact.open': 'Open',
      'pluginStore.state.enabled': 'Enabled',
      'pluginStore.state.disabled': 'Disabled',
      'pluginStore.state.missing': 'Not installed',
      'pluginStore.reason.required': 'Core capability cannot be disabled',
      'pluginStore.reason.notInstalled': 'Plugin is not installed',
      'pluginStore.error.listRefreshFailed': 'Failed to refresh plugin list. Please try again.',
      'pluginStore.error.toggleFailed': 'Failed to change plugin state. Please try again.',
      'pluginStore.error.installFailed': 'Failed to install plugin. Please try again.',
      'pluginStore.error.updateFailed': 'Failed to update plugin. Please try again.',
      'pluginStore.error.updateCheckFailed': 'Failed to check plugin updates. Please try again.',
      'pluginStore.error.uninstallFailed': 'Failed to uninstall plugin. Please try again.',
      'pluginStore.error.detailReadFailed': 'Failed to read plugin details. Please try again.',
      'pluginStore.error.detailReadFallback': 'Failed to read plugin details',
      'pluginStore.error.homepageOpenFailed': 'Failed to open homepage. Please try again.',
      'pluginStore.error.unknown': 'Unknown error',
      'pluginStore.runtimeError.pluginStateResponseInvalid': 'Plugin state response is not an object',
      'pluginStore.runtimeError.pluginStateReadFailed': 'Failed to read plugin state',
      'pluginStore.runtimeError.pluginStateSchemaInvalid': 'Plugin state data does not match the expected structure',
      'pluginStore.runtimeError.pluginStoreListResponseInvalid': 'Plugin marketplace response is not an object',
      'pluginStore.runtimeError.pluginStoreListReadFailed': 'Failed to read plugin marketplace list',
      'pluginStore.runtimeError.pluginStoreListSchemaInvalid': 'Plugin marketplace list does not match the expected structure',
      'pluginStore.runtimeError.pluginStoreDetailUnavailable': 'Plugin details are unavailable: {pluginId}',
      'pluginStore.runtimeError.pluginStoreDetailResponseInvalid': 'Plugin details response is not an object',
      'pluginStore.runtimeError.pluginStoreDetailReadFailed': 'Failed to read plugin details',
      'pluginStore.runtimeError.pluginStoreDetailSchemaInvalid': 'Plugin details do not match the expected structure',
      'pluginStore.runtimeError.pluginRemoteInstallResponseInvalid': 'Remote plugin install response is not an object',
      'pluginStore.runtimeError.pluginRemoteInstallFailed': 'Remote plugin install failed',
      'pluginStore.runtimeError.pluginRemoteInstallSchemaInvalid': 'Remote plugin install result does not match the expected structure',
      'pluginStore.runtimeError.pluginRemoteUpdateCheckResponseInvalid': 'Remote plugin update check response is not an object',
      'pluginStore.runtimeError.pluginRemoteUpdateCheckFailed': 'Remote plugin update check failed',
      'pluginStore.runtimeError.pluginRemoteUpdateCheckSchemaInvalid': 'Remote plugin update check result does not match the expected structure',
      'pluginStore.runtimeError.pluginDiagnosticsResponseInvalid': 'Plugin diagnostics response is not an object',
      'pluginStore.runtimeError.pluginDiagnosticsReadFailed': 'Failed to read plugin diagnostics',
      'pluginStore.runtimeError.pluginDiagnosticsSchemaInvalid': 'Plugin diagnostics do not match the expected structure',
      'pluginStore.runtimeError.pluginMutationResponseInvalid': 'Plugin operation response is not an object',
      'pluginStore.runtimeError.pluginMutationFailed': 'Plugin operation failed',
      'pluginStore.runtimeError.pluginRemoteUpdateCheckUnsupported': 'This environment does not support remote plugin update checks',
      'pluginStore.runtimeError.pluginRemoteInstallUnsupported': 'This environment does not support remote plugin installation',
      'pluginStore.runtimeError.pluginUninstallUnsupported': 'This environment does not support plugin uninstall',
      'pluginStore.runtimeError.pluginToggleUnsupported': 'This environment does not support enabling or disabling plugins',
      'pluginStore.toast.enabled': '{pluginName} enabled',
      'pluginStore.toast.disabled': '{pluginName} disabled',
      'pluginStore.toast.installed': '{pluginName} installed. Restart Linnya for it to fully take effect.',
      'pluginStore.toast.updated': '{pluginName} updated. Restart Linnya for it to fully take effect.',
      'pluginStore.toast.current': '{pluginName} is already up to date',
      'pluginStore.toast.incompatible': '{pluginName} is incompatible with the current app version',
      'pluginStore.toast.uninstalled': '{pluginName} uninstalled. Restart Linnya to remove it completely.',
      'pluginStore.confirm.uninstall': 'Uninstall {pluginName}? The plugin will be removed from this device, but existing document data will not be deleted.',
    },
  },
};
