/**
 * 渲染协议类型 re-export
 *
 * 从 @plugin/slides/shared/renderModel 导入前后端共享的渲染模型定义。
 * slides 域内其他模块统一从此处导入渲染类型。
 */

export type {
  PresentationRenderModel,
  RenderSlideSize,
  RenderCapabilities,
  SlideRenderModel,
  SlideBackgroundModel,
  SlideBackgroundGradientModel,
  SlideDiagnosticsSummary,
  SlideReferencePreview,
  EditableOperation,
  EditableTarget,
  RenderNodeKind,
  RenderBox,
  RenderNodeBase,
  RenderSourceSpan,
  RenderNode,
  TextRenderNode,
  RenderParagraph,
  RenderTextRun,
  RenderFormulaRun,
  RenderInlineRun,
  RenderBullet,
  ShapeRenderNode,
  SvgGraphicRenderNode,
  MathFormulaRenderNode,
  ImageRenderNode,
  RenderAssetRef,
  TableRenderNode,
  RenderTableCell,
  RenderTableCellBorders,
  ChartRenderNode,
  ChartPptxHints,
  RenderChartType,
  RenderChartSeries,
  RenderChartAxes,
  RenderChartAxis,
  RenderChartLegend,
  RenderChartDataLabels,
  RenderChartGridlines,
  RenderChartLabelStyle,
  GroupRenderNode,
  TablePptxHints,
  RenderFill,
  RenderSolidFill,
  RenderNoneFill,
  RenderGradientFill,
  RenderStroke,
  RenderShadow,
  RenderPadding,
} from '@plugin/slides/shared/renderModel';
