/**
 * emit — assemble the final `.d.ts` text from extracted types,
 * ambient factory signatures, and ambient globals.
 *
 * Output structure
 * ────────────────
 * 1. Header banner (machine-generated marker + source file references).
 * 2. External dependency stubs (`type X = unknown;`) for any imported
 *    name that is **not** redefined in `moduleScopeTypes` — these keep
 *    the d.ts self-contained for sandbox typecheck.
 * 3. Module-scope types (interfaces / type aliases / extracted helpers)
 *    in alphabetical order.
 * 4. A single `declare global { ... }` block holding the sandbox-injected
 *    factories and globals (also in alphabetical order). Inside the
 *    block we use `function` / `const` (no `declare` keyword), which is
 *    the canonical TypeScript form.
 * 5. `export {};` to convert the file into a module so `declare global`
 *    is well-formed.
 *
 * Determinism guarantees
 * ──────────────────────
 * - All ordering is by ASCII compare (see `sort.ts`).
 * - Caller is responsible for de-duping symbols *before* calling emit.
 * - Output uses LF newlines and ends with exactly one trailing newline.
 * - No timestamps, no machine-specific paths in the body (the header is
 *   the only place stable bookkeeping lives).
 */

import type { ExtractedTypeSymbol, ExternalDependency } from './extractTypes.js';
import ts from 'typescript';
import { compareAscii } from './sort.js';

export interface EmitLayoutDtsOptions {
  /** Types that live at module scope (interfaces / type aliases / helper functions). */
  moduleScopeTypes: ExtractedTypeSymbol[];
  /** Factory function signatures (createSlide, createFrame, ...). */
  ambientFactories: ExtractedTypeSymbol[];
  /** Sandbox-injected globals (SLIDE_W, DECK_DESIGN, compose, ...). */
  ambientGlobals: ExtractedTypeSymbol[];
  /** External names that were imported but not re-extracted; emitted as
   *  `type X = unknown;` stubs unless already defined in moduleScopeTypes. */
  externalDependencies: ExternalDependency[];
  /** Free-form banner text inserted at the top of the file. */
  header: string;
}

interface ExternalStub {
  name: string;
  indexedAccessKeys: string[];
}

/**
 * Constants the CLI driver passes into `emit`. Lifted into the emitter
 * module so `__tests__/emit.test.ts` can pin the canonical header
 * without depending on the driver.
 */
export const EMIT_OPTIONS_FOR_GENERATOR = Object.freeze({
  headerLines: Object.freeze([
    '// Auto-generated by scripts/codegen/generate-layout-dts.ts.',
    '// DO NOT EDIT BY HAND — regenerate with `npm run codegen-first:dts`.',
    '//',
    '// Sources:',
    '//   - packages/plugins/slides/src/shared/flexComposeContract.ts',
    '//   - packages/plugins/slides/src/shared/shapeGeometry/definitions/shapeGeometry.ts',
    '//   - packages/plugins/slides/src/shared/svgGraphic/definitions/svgGraphic.ts',
    '//   - packages/plugins/slides/src/shared/deckSpec/slideSize.ts',
    '//   - packages/plugins/slides/src/backend/sandbox/layoutPrimitives.ts',
    '//   - packages/plugins/slides/src/backend/sandbox/pptComposeProfile.ts (sandbox bindings)',
    '//',
    '// Consumers:',
    '//   - References reading: AI loads via `references/layoutPrimitives.d.ts`',
    '//   - Sandbox typecheck:  pptComposeProfile.typecheck.ts feeds this file to',
    '//                         the TypeScript compiler API for codegen-source mode.',
  ] as readonly string[]),
});

export function emitLayoutDts(options: EmitLayoutDtsOptions): string {
  const moduleScopeNames = new Set(options.moduleScopeTypes.map((t) => t.name));

  const stubs = collectExternalStubs(
    options.externalDependencies,
    moduleScopeNames,
    options.moduleScopeTypes,
    options.ambientFactories,
    options.ambientGlobals,
  );

  const moduleScope = [...options.moduleScopeTypes].sort((a, b) =>
    compareAscii(a.name, b.name),
  );
  const factories = [...options.ambientFactories].sort((a, b) =>
    compareAscii(a.name, b.name),
  );
  const globals = [...options.ambientGlobals].sort((a, b) =>
    compareAscii(a.name, b.name),
  );

  const sections: string[] = [];

  sections.push(options.header.trimEnd());

  if (stubs.length > 0) {
    sections.push(
      [
        '// ─── External dependency stubs (replaced with `unknown` for sandbox isolation) ──',
        ...stubs.map(renderExternalStub),
      ].join('\n'),
    );
  }

  if (moduleScope.length > 0) {
    sections.push(
      [
        '// ─── Layout types (extracted from flexComposeContract.ts) ───────────────────',
        ...moduleScope.map((sym) => sym.text),
      ].join('\n\n'),
    );
  }

  const innerLines: string[] = [];
  if (factories.length > 0) {
    innerLines.push('  // ── Sandbox factory functions ──');
    for (const f of factories) {
      innerLines.push(indentBlock(f.text, '  '));
    }
  }
  if (globals.length > 0) {
    if (innerLines.length > 0) innerLines.push('');
    innerLines.push('  // ── Sandbox-injected globals ──');
    for (const g of globals) {
      innerLines.push(indentBlock(g.text, '  '));
    }
  }
  sections.push(['declare global {', innerLines.join('\n\n'), '}'].join('\n'));

  sections.push('export {};');

  // Join with blank lines; force LF; end with exactly one trailing newline.
  return sections.join('\n\n').replace(/\r\n/g, '\n') + '\n';
}

// ─── internal helpers ──────────────────────────────────────────────────

/**
 * Pick external names that need a `type X = unknown;` stub.
 *
 * An external name is stubbed only when:
 *   1. it is NOT redefined locally in `moduleScopeTypes`, AND
 *   2. it is actually referenced (as a whole-word identifier) by at
 *      least one of the emitted bodies (module-scope types, factory
 *      signatures, or ambient globals).
 *
 * Without rule 2 we would emit a stub for every value-import (e.g.
 * `isRecord`), even though function bodies are dropped during extraction
 * and the name never appears in the d.ts output. Stubbing them clutters
 * the file and, for value imports, gives a misleading impression that
 * the AI can call them inside the sandbox.
 */
function collectExternalStubs(
  deps: ExternalDependency[],
  moduleScopeNames: Set<string>,
  moduleScope: ExtractedTypeSymbol[],
  ambientFactories: ExtractedTypeSymbol[],
  ambientGlobals: ExtractedTypeSymbol[],
): ExternalStub[] {
  const corpus =
    moduleScope.map((s) => s.text).join('\n') +
    '\n' +
    ambientFactories.map((s) => s.text).join('\n') +
    '\n' +
    ambientGlobals.map((s) => s.text).join('\n');

  const indexedAccessKeys = collectIndexedAccessKeys(corpus);
  const out = new Map<string, Set<string>>();
  for (const dep of deps) {
    for (const name of dep.importedNames) {
      if (moduleScopeNames.has(name)) continue;
      if (!isReferenced(name, corpus)) continue;
      out.set(name, indexedAccessKeys.get(name) ?? new Set<string>());
    }
  }
  return [...out.entries()]
    .sort(([a], [b]) => compareAscii(a, b))
    .map(([name, keys]) => ({
      name,
      indexedAccessKeys: [...keys].sort(compareAscii),
    }));
}

function collectIndexedAccessKeys(corpus: string): Map<string, Set<string>> {
  const sourceFile = ts.createSourceFile(
    'layout-dts-corpus.ts',
    corpus,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ false,
    ts.ScriptKind.TS,
  );
  const out = new Map<string, Set<string>>();

  function visit(node: ts.Node): void {
    if (ts.isIndexedAccessTypeNode(node)) {
      const owner = readIdentifierTypeName(node.objectType);
      const key = readLiteralIndexKey(node.indexType);
      if (owner && key) {
        const keys = out.get(owner) ?? new Set<string>();
        keys.add(key);
        out.set(owner, keys);
      }
    }
    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return out;
}

function readIdentifierTypeName(node: ts.TypeNode): string | null {
  return ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName)
    ? node.typeName.text
    : null;
}

function readLiteralIndexKey(node: ts.TypeNode): string | null {
  if (!ts.isLiteralTypeNode(node)) return null;
  const literal = node.literal;
  if (ts.isStringLiteral(literal)) return literal.text;
  if (ts.isNumericLiteral(literal)) return literal.text;
  return null;
}

function renderExternalStub(stub: ExternalStub): string {
  if (stub.indexedAccessKeys.length === 0) {
    return `type ${stub.name} = unknown;`;
  }
  return [
    `type ${stub.name} = {`,
    ...stub.indexedAccessKeys.map((key) => `  ${JSON.stringify(key)}: unknown;`),
    '};',
  ].join('\n');
}

function isReferenced(name: string, corpus: string): boolean {
  if (name.length === 0) return false;
  const re = new RegExp(`(?<![\\w$])${escapeRegExp(name)}(?![\\w$])`);
  return re.test(corpus);
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function indentBlock(text: string, prefix: string): string {
  return text
    .split('\n')
    .map((line) => (line.length === 0 ? line : prefix + line))
    .join('\n');
}
